#!/usr/bin/awk -f
# Generated by UnifyWeaver v0.0.3
# Target: AWK
# Generated: 2025-11-27 12:19:40
# Predicate: person/1
# Input format: tsv

BEGIN {
    FS = "	"
    facts["alice"] = 1
    facts["bob"] = 1
    facts["charlie"] = 1
}
{
    key = $1
    if (key in facts && !(key in seen)) {
        seen[key] = 1
        print $0
    }
}
