:- module(test_typr_target, [run_all_tests/0]).

:- use_module(library(plunit)).
:- use_module('../src/unifyweaver/targets/type_declarations').
:- use_module('../src/unifyweaver/targets/typr_target').
:- use_module('../src/unifyweaver/core/target_registry').
:- use_module('../src/unifyweaver/core/recursive_compiler').

run_all_tests :-
    run_tests([typr_target]).

setup_typr_test :-
    clear_type_declarations.

cleanup_typr_test :-
    clear_type_declarations,
    retractall(user:edge(_, _)),
    retractall(user:tc(_, _)),
    retractall(user:simple_fact(_)),
    retractall(user:lower_name(_, _)),
    retractall(user:classify_name(_, _)),
    retractall(user:inferred_lower(_, _)),
    retractall(user:classify_name_guarded(_, _)),
    retractall(user:guarded_name(_, _)),
    retractall(user:mid_guard(_, _)),
    retractall(user:multi_guard_chain(_, _)),
    retractall(user:multi_clause_chain(_, _)),
    retractall(user:comparison_guard_chain(_, _)),
    retractall(user:comparison_clause_chain(_, _)),
    retractall(user:fanout_chain(_, _)),
    retractall(user:fanout_clause_chain(_, _)),
    retractall(user:split_recombine_chain(_, _)),
    retractall(user:split_recombine_clause_chain(_, _)),
    retractall(user:alternative_assign_chain(_, _)),
    retractall(user:alternative_assign_clause_chain(_, _)),
    retractall(user:sort_rows(_, _)),
    retractall(user:filter_rows(_, _)),
    retractall(user:group_rows(_, _)),
    retractall(user:numeric_input(_)).

:- begin_tests(typr_target, [
    setup(setup_typr_test),
    cleanup(cleanup_typr_test)
]).

test(explicit_mode_emits_declared_scalar_annotations) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let tc_all <- fn(start: char): [#N, char]")),
    once(sub_string(Code, _, _, _, "let tc_check <- fn(start: char, target: char): bool")).

test(infer_mode_omits_scalar_parameter_annotations) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(infer)], Code)),
    \+ sub_string(Code, _, _, _, "start: char"),
    once(sub_string(Code, _, _, _, "let tc_all <- fn(start)")).

test(explicit_any_is_preserved_in_infer_mode) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, any)),
    assertz(type_declarations:uw_type(edge/2, 2, any)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(infer)], Code)),
    once(sub_string(Code, _, _, _, "start: Any")),
    once(sub_string(Code, _, _, _, "target: Any")).

test(per_predicate_typed_mode_overrides_call_option) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    assertz(type_declarations:uw_typed_mode(tc/2, off)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    \+ sub_string(Code, _, _, _, ": char"),
    \+ sub_string(Code, _, _, _, ": [#N, char]").

test(target_registry_registers_typr_family) :-
    clear_type_declarations,
    target_exists(typr),
    target_family(typr, r).

test(target_registry_dispatches_typr) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_to_target(typr, tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "Generated by UnifyWeaver TypR Target")).

test(generic_predicates_receive_typed_signature) :-
    clear_type_declarations,
    assertz(user:simple_fact(hello)),
    assertz(type_declarations:uw_type(simple_fact/1, 1, atom)),
    once(compile_predicate_to_typr(simple_fact/1, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let simple_fact <- fn(arg1: char): bool")),
    once(sub_string(Code, _, _, _, "identical(arg1, \"hello\")")),
    generated_typr_is_valid(Code, exit(0)).

test(recursive_compiler_supports_typr_non_recursive_path) :-
    clear_type_declarations,
    assertz(user:simple_fact(hello)),
    assertz(type_declarations:uw_type(simple_fact/1, 1, atom)),
    once(recursive_compiler:compile_recursive(simple_fact/1, [target(typr), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let simple_fact <- fn(arg1: char): bool")),
    generated_typr_is_valid(Code, exit(0)).

test(generic_body_predicates_reuse_r_backend) :-
    clear_type_declarations,
    assertz(user:(lower_name(Name, Lower) :- string_lower(Name, Lower))),
    assertz(type_declarations:uw_type(lower_name/2, 1, atom)),
    assertz(type_declarations:uw_type(lower_name/2, 2, atom)),
    assertz(type_declarations:uw_return_type(lower_name/2, atom)),
    once(compile_predicate_to_typr(lower_name/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let lower_name <- fn(arg1: char, arg2: char): char")),
    once(sub_string(Code, _, _, _, "tolower(arg1)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(generic_multi_clause_predicates_reuse_r_backend) :-
    clear_type_declarations,
    assertz(user:(classify_name(short, Lower) :- string_lower('HI', Lower))),
    assertz(user:(classify_name(long, Lower) :- string_lower('BYE', Lower))),
    assertz(type_declarations:uw_type(classify_name/2, 1, atom)),
    assertz(type_declarations:uw_type(classify_name/2, 2, atom)),
    once(compile_predicate_to_typr(classify_name/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let classify_name <- fn(arg1: char, arg2: char): char")),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "tolower(\"HI\")")),
    once(sub_string(Code, _, _, _, "tolower(\"BYE\")")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(generic_body_predicates_infer_return_type_without_declaration) :-
    clear_type_declarations,
    assertz(user:(inferred_lower(Name, Lower) :- string_lower(Name, Lower), true)),
    assertz(type_declarations:uw_type(inferred_lower/2, 1, atom)),
    assertz(type_declarations:uw_type(inferred_lower/2, 2, atom)),
    once(compile_predicate_to_typr(inferred_lower/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let inferred_lower <- fn(arg1: char, arg2: char): char")),
    generated_typr_is_valid(Code, exit(0)).

test(generic_multi_clause_predicates_infer_guarded_return_type) :-
    clear_type_declarations,
    assertz(user:(classify_name_guarded(short, Lower) :- string_lower('HI', Lower), true)),
    assertz(user:(classify_name_guarded(long, Lower) :- string_lower('BYE', Lower), true)),
    assertz(type_declarations:uw_type(classify_name_guarded/2, 1, atom)),
    assertz(type_declarations:uw_type(classify_name_guarded/2, 2, atom)),
    once(compile_predicate_to_typr(classify_name_guarded/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let classify_name_guarded <- fn(arg1: char, arg2: char): char")),
    generated_typr_is_valid(Code, exit(0)).

test(type_diagnostics_report_defaults_to_empty_for_native_typr_lowering) :-
    clear_type_declarations,
    assertz(user:(lower_name(Name, Lower) :- string_lower(Name, Lower))),
    assertz(type_declarations:uw_type(lower_name/2, 1, atom)),
    assertz(type_declarations:uw_type(lower_name/2, 2, atom)),
    once(compile_predicate_to_typr(lower_name/2, [typed_mode(explicit), type_diagnostics_report(Report)], _Code)),
    assertion(Report == []).

test(guard_bindings_expand_native_clause_conditions) :-
    clear_type_declarations,
    assertz(user:(guarded_name(Name, Lower) :- is_character(Name), string_lower(Name, Lower))),
    assertz(type_declarations:uw_type(guarded_name/2, 1, atom)),
    assertz(type_declarations:uw_type(guarded_name/2, 2, atom)),
    once(compile_predicate_to_typr(guarded_name/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "is.character(arg1)")),
    once(sub_string(Code, _, _, _, "tolower(arg1)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(sequential_guards_after_output_lower_natively) :-
    clear_type_declarations,
    assertz(user:(mid_guard(Name, Len) :- string_lower(Name, Lower), is_character(Lower), string_length(Lower, Len))),
    assertz(type_declarations:uw_type(mid_guard/2, 1, atom)),
    assertz(type_declarations:uw_type(mid_guard/2, 2, integer)),
    once(compile_predicate_to_typr(mid_guard/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "tolower(arg1)")),
    once(sub_string(Code, _, _, _, "is.character(v3)")),
    once(sub_string(Code, _, _, _, "nchar(v3)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(multi_decision_guard_chains_use_let_for_new_intermediates) :-
    clear_type_declarations,
    assertz(user:(multi_guard_chain(Name, Out) :- string_lower(Name, Lower), is_character(Lower), string_length(Lower, Len), is_numeric(Len), string_upper(Lower, Upper), is_character(Upper), string_concat(Upper, '!', Out))),
    assertz(type_declarations:uw_type(multi_guard_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(multi_guard_chain/2, 2, atom)),
    once(compile_predicate_to_typr(multi_guard_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let v3 <- @{ tolower(arg1) }@;")),
    once(sub_string(Code, _, _, _, "let v4 <- if (@{ is.character(v3) }@)")),
    once(sub_string(Code, _, _, _, "let v5 <- if (@{ is.numeric(v4) }@)")),
    once(sub_string(Code, _, _, _, "arg2 <- if (@{ is.character(v5) }@)")),
    \+ sub_string(Code, _, _, _, "local({"),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(multi_clause_decision_chains_stay_native_in_branch_bodies) :-
    clear_type_declarations,
    assertz(user:(multi_clause_chain(short, Out) :- string_lower('HI', Lower), is_character(Lower), string_length(Lower, Len), is_numeric(Len), string_upper(Lower, Out))),
    assertz(user:(multi_clause_chain(long, Out) :- string_lower('BYE', Lower), is_character(Lower), string_length(Lower, Len), is_numeric(Len), string_upper(Lower, Out))),
    assertz(type_declarations:uw_type(multi_clause_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(multi_clause_chain/2, 2, atom)),
    once(compile_predicate_to_typr(multi_clause_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "let v2 <- @{ tolower(\"HI\") }@;")),
    once(sub_string(Code, _, _, _, "let v3 <- if (@{ is.character(v2) }@)")),
    \+ sub_string(Code, _, _, _, "local({"),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(comparison_guard_chains_lower_natively) :-
    clear_type_declarations,
    assertz(user:(comparison_guard_chain(Name, Out) :- string_lower(Name, Lower), string_length(Lower, Len), >(Len, 1), string_upper(Lower, Upper), string_length(Upper, UpperLen), <(UpperLen, 10), string_concat(Upper, '!', Out))),
    assertz(type_declarations:uw_type(comparison_guard_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(comparison_guard_chain/2, 2, atom)),
    once(compile_predicate_to_typr(comparison_guard_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let v4 <- @{ nchar(v3) }@;")),
    once(sub_string(Code, _, _, _, "if (@{ v4 > 1 }@)")),
    once(sub_string(Code, _, _, _, "let v6 <- @{ nchar(v5) }@;")),
    once(sub_string(Code, _, _, _, "if (@{ v6 < 10 }@)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(comparison_guard_branch_bodies_stay_native) :-
    clear_type_declarations,
    assertz(user:(comparison_clause_chain(short, Out) :- string_lower('HI', Lower), string_length(Lower, Len), >(Len, 1), string_upper(Lower, Out))),
    assertz(user:(comparison_clause_chain(long, Out) :- string_lower('BYE', Lower), string_length(Lower, Len), >(Len, 2), string_upper(Lower, Out))),
    assertz(type_declarations:uw_type(comparison_clause_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(comparison_clause_chain/2, 2, atom)),
    once(compile_predicate_to_typr(comparison_clause_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "let v3 <- @{ nchar(v2) }@;")),
    once(sub_string(Code, _, _, _, "if (@{ v3 > 1 }@)")),
    \+ sub_string(Code, _, _, _, "local({"),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(fanout_chains_reuse_one_intermediate_across_multiple_later_outputs) :-
    clear_type_declarations,
    assertz(user:(fanout_chain(Name, Out) :- string_lower(Name, Lower), string_length(Lower, Len), >(Len, 1), string_upper(Lower, Upper), string_concat(Lower, '?', Tagged), string_length(Tagged, TaggedLen), <(TaggedLen, 20), string_concat(Upper, Tagged, Out))),
    assertz(type_declarations:uw_type(fanout_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(fanout_chain/2, 2, atom)),
    once(compile_predicate_to_typr(fanout_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let v3 <- @{ tolower(arg1) }@;")),
    once(sub_string(Code, _, _, _, "let v5 <- if (@{ v4 > 1 }@)")),
    once(sub_string(Code, _, _, _, "let v6 <- @{ paste0(v3, \"?\") }@;")),
    once(sub_string(Code, _, _, _, "arg2 <- if (@{ v7 < 20 }@)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(fanout_branch_bodies_stay_native) :-
    clear_type_declarations,
    assertz(user:(fanout_clause_chain(short, Out) :- string_lower('HI', Lower), string_length(Lower, Len), >(Len, 1), string_upper(Lower, Upper), string_concat(Lower, '?', Tagged), string_concat(Upper, Tagged, Out))),
    assertz(user:(fanout_clause_chain(long, Out) :- string_lower('BYE', Lower), string_length(Lower, Len), >(Len, 2), string_upper(Lower, Upper), string_concat(Lower, '?', Tagged), string_concat(Upper, Tagged, Out))),
    assertz(type_declarations:uw_type(fanout_clause_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(fanout_clause_chain/2, 2, atom)),
    once(compile_predicate_to_typr(fanout_clause_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "let v4 <- if (@{ v3 > 1 }@)")),
    once(sub_string(Code, _, _, _, "let v5 <- @{ paste0(v2, \"?\") }@;")),
    once(sub_string(Code, _, _, _, "let arg2 <- @{ paste0(v4, v5) }@;")),
    \+ sub_string(Code, _, _, _, "local({"),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(split_recombine_chains_stay_native) :-
    clear_type_declarations,
    assertz(user:(split_recombine_chain(Name, Out) :- string_lower(Name, Lower), string_length(Lower, LowerLen), >(LowerLen, 1), string_upper(Lower, Upper), string_length(Upper, UpperLen), <(UpperLen, 10), string_concat(Lower, '?', Tagged), string_length(Tagged, TaggedLen), <(TaggedLen, 20), string_concat(Upper, Tagged, Out))),
    assertz(type_declarations:uw_type(split_recombine_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(split_recombine_chain/2, 2, atom)),
    once(compile_predicate_to_typr(split_recombine_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let v5 <- if (@{ v4 > 1 }@)")),
    once(sub_string(Code, _, _, _, "let v7 <- if (@{ v6 < 10 }@)")),
    once(sub_string(Code, _, _, _, "arg2 <- if (@{ v8 < 20 }@)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(split_recombine_branch_bodies_stay_native) :-
    clear_type_declarations,
    assertz(user:(split_recombine_clause_chain(short, Out) :- string_lower('HI', Lower), string_length(Lower, LowerLen), >(LowerLen, 1), string_upper(Lower, Upper), string_length(Upper, UpperLen), <(UpperLen, 10), string_concat(Lower, '?', Tagged), string_length(Tagged, TaggedLen), <(TaggedLen, 20), string_concat(Upper, Tagged, Out))),
    assertz(user:(split_recombine_clause_chain(long, Out) :- string_lower('BYE', Lower), string_length(Lower, LowerLen), >(LowerLen, 2), string_upper(Lower, Upper), string_length(Upper, UpperLen), <(UpperLen, 10), string_concat(Lower, '?', Tagged), string_length(Tagged, TaggedLen), <(TaggedLen, 20), string_concat(Upper, Tagged, Out))),
    assertz(type_declarations:uw_type(split_recombine_clause_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(split_recombine_clause_chain/2, 2, atom)),
    once(compile_predicate_to_typr(split_recombine_clause_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "let v4 <- if (@{ v3 > 1 }@)")),
    once(sub_string(Code, _, _, _, "let v6 <- if (@{ v5 < 10 }@)")),
    once(sub_string(Code, _, _, _, "arg2 <- if (@{ v7 < 20 }@)")),
    \+ sub_string(Code, _, _, _, "local({"),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(disjunction_alternative_assignments_lower_natively) :-
    clear_type_declarations,
    assertz(user:(alternative_assign_chain(Name, Out) :- string_lower(Name, Lower), string_length(Lower, Len), ((>(Len, 3), string_upper(Lower, Upper), string_concat(Upper, '!', Mid)); (=<(Len, 3), string_concat(Lower, '?', Mid))), string_concat(Mid, '#', Out))),
    assertz(type_declarations:uw_type(alternative_assign_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(alternative_assign_chain/2, 2, atom)),
    once(compile_predicate_to_typr(alternative_assign_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let v5 <- if (@{ v4 > 3 }@)")),
    once(sub_string(Code, _, _, _, "let v6 <- @{ paste0(v5, \"!\") }@;")),
    once(sub_string(Code, _, _, _, "else if (@{ v4 <= 3 }@)")),
    once(sub_string(Code, _, _, _, "arg2 <- @{ paste0(v5, \"#\") }@;")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(disjunction_alternative_assignments_stay_native_in_branch_bodies) :-
    clear_type_declarations,
    assertz(user:(alternative_assign_clause_chain(short, Out) :- string_lower('Hello', Lower), string_length(Lower, Len), ((>(Len, 3), string_upper(Lower, Upper), string_concat(Upper, '!', Mid)); (=<(Len, 3), string_concat(Lower, '?', Mid))), string_concat(Mid, '#', Out))),
    assertz(user:(alternative_assign_clause_chain(tiny, Out) :- string_lower('Yo', Lower), string_length(Lower, Len), ((>(Len, 3), string_upper(Lower, Upper), string_concat(Upper, '!', Mid)); (=<(Len, 3), string_concat(Lower, '?', Mid))), string_concat(Mid, '#', Out))),
    assertz(type_declarations:uw_type(alternative_assign_clause_chain/2, 1, atom)),
    assertz(type_declarations:uw_type(alternative_assign_clause_chain/2, 2, atom)),
    once(compile_predicate_to_typr(alternative_assign_clause_chain/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "let v4 <- if (@{ v3 > 3 }@)")),
    once(sub_string(Code, _, _, _, "let v5 <- @{ paste0(v4, \"!\") }@;")),
    once(sub_string(Code, _, _, _, "let arg2 <- @{ paste0(v4, \"#\") }@;")),
    \+ sub_string(Code, _, _, _, "local({"),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(guard_only_predicates_infer_boolean_return_type) :-
    clear_type_declarations,
    assertz(user:(numeric_input(Value) :- is_numeric(Value))),
    once(compile_predicate_to_typr(numeric_input/1, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let numeric_input <- fn(arg1): bool")),
    once(sub_string(Code, _, _, _, "is.numeric(arg1)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(dataframe_sort_predicates_lower_natively) :-
    clear_type_declarations,
    assertz(user:(sort_rows(Input, Output) :- sort_by(Input, name, Output))),
    once(compile_predicate_to_typr(sort_rows/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "order(arg1[[\"name\"]])")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(dataframe_filter_predicates_lower_natively) :-
    clear_type_declarations,
    assertz(user:(filter_rows(Input, Output) :- filter(Input, score > 10, Output))),
    once(compile_predicate_to_typr(filter_rows/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "subset(arg1, (score > 10))")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(dataframe_group_predicates_lower_natively) :-
    clear_type_declarations,
    assertz(user:(group_rows(Input, Output) :- group_by(Input, category, Output))),
    once(compile_predicate_to_typr(group_rows/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "aggregate(. ~ \"category\", data=arg1, FUN=list)")),
    \+ sub_string(Code, _, _, _, "(function("),
    generated_typr_is_valid(Code, exit(0)).

test(transitive_closure_template_is_valid_typr) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "while (length(queue) > 0)")),
    generated_typr_is_valid(Code, exit(0)).

test(transitive_closure_seeds_known_base_facts) :-
    clear_type_declarations,
    assertz(user:edge(a, b)),
    assertz(user:edge(b, c)),
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "_seed_edge_1 <- add_edge(\"a\", \"b\");")),
    once(sub_string(Code, _, _, _, "_seed_edge_2 <- add_edge(\"b\", \"c\");")).

:- end_tests(typr_target).
