:- module(test_typr_target, [run_all_tests/0]).

:- use_module(library(plunit)).
:- use_module('../src/unifyweaver/targets/type_declarations').
:- use_module('../src/unifyweaver/targets/typr_target').
:- use_module('../src/unifyweaver/core/target_registry').
:- use_module('../src/unifyweaver/core/recursive_compiler').

run_all_tests :-
    run_tests([typr_target]).

setup_typr_test :-
    clear_type_declarations.

cleanup_typr_test :-
    clear_type_declarations,
    retractall(user:edge(_, _)),
    retractall(user:tc(_, _)),
    retractall(user:simple_fact(_)),
    retractall(user:lower_name(_, _)),
    retractall(user:classify_name(_, _)).

:- begin_tests(typr_target, [
    setup(setup_typr_test),
    cleanup(cleanup_typr_test)
]).

test(explicit_mode_emits_declared_scalar_annotations) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let tc_all <- fn(start: char): [#N, char]")),
    once(sub_string(Code, _, _, _, "let tc_check <- fn(start: char, target: char): bool")).

test(infer_mode_omits_scalar_parameter_annotations) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(infer)], Code)),
    \+ sub_string(Code, _, _, _, "start: char"),
    once(sub_string(Code, _, _, _, "let tc_all <- fn(start)")).

test(explicit_any_is_preserved_in_infer_mode) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, any)),
    assertz(type_declarations:uw_type(edge/2, 2, any)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(infer)], Code)),
    once(sub_string(Code, _, _, _, "start: Any")),
    once(sub_string(Code, _, _, _, "target: Any")).

test(per_predicate_typed_mode_overrides_call_option) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    assertz(type_declarations:uw_typed_mode(tc/2, off)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    \+ sub_string(Code, _, _, _, ": char"),
    \+ sub_string(Code, _, _, _, ": [#N, char]").

test(target_registry_registers_typr_family) :-
    clear_type_declarations,
    target_exists(typr),
    target_family(typr, r).

test(target_registry_dispatches_typr) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_to_target(typr, tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "Generated by UnifyWeaver TypR Target")).

test(generic_predicates_receive_typed_signature) :-
    clear_type_declarations,
    assertz(user:simple_fact(hello)),
    assertz(type_declarations:uw_type(simple_fact/1, 1, atom)),
    once(compile_predicate_to_typr(simple_fact/1, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let simple_fact <- fn(arg1: char): bool")),
    once(sub_string(Code, _, _, _, "identical(arg1, \"hello\")")),
    generated_typr_is_valid(Code, exit(0)).

test(recursive_compiler_supports_typr_non_recursive_path) :-
    clear_type_declarations,
    assertz(user:simple_fact(hello)),
    assertz(type_declarations:uw_type(simple_fact/1, 1, atom)),
    once(recursive_compiler:compile_recursive(simple_fact/1, [target(typr), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let simple_fact <- fn(arg1: char): bool")),
    generated_typr_is_valid(Code, exit(0)).

test(generic_body_predicates_reuse_r_backend) :-
    clear_type_declarations,
    assertz(user:(lower_name(Name, Lower) :- string_lower(Name, Lower))),
    assertz(type_declarations:uw_type(lower_name/2, 1, atom)),
    assertz(type_declarations:uw_type(lower_name/2, 2, atom)),
    once(compile_predicate_to_typr(lower_name/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "let lower_name <- fn(arg1: char, arg2: char): Any")),
    once(sub_string(Code, _, _, _, "tolower(arg1)")),
    generated_typr_is_valid(Code, exit(0)).

test(generic_multi_clause_predicates_reuse_r_backend) :-
    clear_type_declarations,
    assertz(user:(classify_name(short, Lower) :- string_lower('HI', Lower))),
    assertz(user:(classify_name(long, Lower) :- string_lower('BYE', Lower))),
    assertz(type_declarations:uw_type(classify_name/2, 1, atom)),
    assertz(type_declarations:uw_type(classify_name/2, 2, atom)),
    once(compile_predicate_to_typr(classify_name/2, [typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "else if")),
    once(sub_string(Code, _, _, _, "tolower(\"HI\")")),
    once(sub_string(Code, _, _, _, "tolower(\"BYE\")")),
    generated_typr_is_valid(Code, exit(0)).

test(transitive_closure_template_is_valid_typr) :-
    clear_type_declarations,
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "while (length(queue) > 0)")),
    generated_typr_is_valid(Code, exit(0)).

test(transitive_closure_seeds_known_base_facts) :-
    clear_type_declarations,
    assertz(user:edge(a, b)),
    assertz(user:edge(b, c)),
    assertz(type_declarations:uw_type(edge/2, 1, atom)),
    assertz(type_declarations:uw_type(edge/2, 2, atom)),
    once(compile_predicate_to_typr(tc/2, [base_pred(edge), typed_mode(explicit)], Code)),
    once(sub_string(Code, _, _, _, "_seed_edge_1 <- add_edge(\"a\", \"b\");")),
    once(sub_string(Code, _, _, _, "_seed_edge_2 <- add_edge(\"b\", \"c\");")).

:- end_tests(typr_target).
