:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% direct_multi_call_recursion.pl - Direct recursive code generation for multi-call patterns
% Generates actual recursive bash functions with memoization instead of fold-based approach
%
% Strategy: For predicates like fibonacci with 2+ independent recursive calls,
% generate bash functions that directly call themselves recursively with memoization.

:- module(direct_multi_call_recursion, [
    compile_direct_multi_call/3,    % +Pred/Arity, +Options, -Code
    can_compile_direct_multi_call/1, % +Pred/Arity
    extract_body_components/5,      % +Body, +Pred, -Computations, -RecCalls, -Aggregation (shared)
    test_direct_multi_call/0        % Test predicate
]).

:- use_module(library(lists)).
:- use_module('pattern_matchers').

%% compile_direct_multicall_pattern/5 is multifile - targets register their own clauses.
%% compile_direct_multicall_pattern(+Target, +PredStr, +BaseClauses, +RecClause, -Code)
:- multifile compile_direct_multicall_pattern/5.

%% get_recursive_call_count(+Pred/Arity, -MaxCount)
%  Count max recursive calls per clause for a predicate
get_recursive_call_count(Pred/Arity, MaxCount) :-
    functor(Head, Pred, Arity),
    findall(Count,
        (user:clause(Head, Body),
         contains_call_to(Body, Pred),
         count_recursive_calls(Body, Pred, Count)),
        Counts),
    (Counts = [] -> MaxCount = 0 ; max_list(Counts, MaxCount)).

%% get_multi_call_info(+Pred/Arity, -Info)
%  Gather multi-call analysis info. Only Count is currently used.
get_multi_call_info(Pred/Arity, multi_call(Count, true, true, true)) :-
    get_recursive_call_count(Pred/Arity, Count).

%% can_compile_direct_multi_call(+Pred/Arity)
%  Check if predicate can be compiled as direct multi-call recursion
can_compile_direct_multi_call(Pred/Arity) :-
    Arity =:= 2,
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    % Must have at least one recursive clause with 2+ calls
    member(clause(_, RecBody), Clauses),
    contains_call_to(RecBody, Pred),
    count_recursive_calls(RecBody, Pred, Count),
    Count >= 2.

%% compile_direct_multi_call(+Pred/Arity, +Options, -BashCode)
%  Compile multi-call predicate to direct recursive bash with memoization
%  Options: List of Key=Value pairs (e.g., [unique=true, ordered=false])
compile_direct_multi_call(Pred/Arity, Options, BashCode) :-
    format('  Compiling direct multi-call recursion: ~w/~w~n', [Pred, Arity]),

    % Get multi-call info
    get_multi_call_info(Pred/Arity, multi_call(Count, _IsLinear, _HasDistinct, _IsPrecomp)),
    format('  Recursive calls: ~w~n', [Count]),

    % Currently only support arity 2 (input, output)
    (   Arity =:= 2 ->
        compile_direct_binary_recursion(Pred, Options, BashCode)
    ;   format('  ERROR: Direct multi-call only supports arity 2 currently~n', []),
        fail
    ).

%% compile_direct_binary_recursion(+Pred, +Options, -Code)
%  Compile arity-2 predicate with direct recursion
compile_direct_binary_recursion(Pred, Options, Code) :-
    atom_string(Pred, PredStr),
    
    % Determine target
    (   member(target(Target), Options) -> true
    ;   Target = bash
    ),
    format('  Target: ~w~n', [Target]),

    % Get clauses
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),

    % Separate base and recursive cases
    partition(is_recursive_clause(Pred), Clauses, [RecClause|_], BaseClauses),

    % Delegate to multifile
    (   compile_direct_multicall_pattern(Target, PredStr, BaseClauses, RecClause, Code) ->
        true
    ;   format('Error: No direct multicall recursion support for target ~w~n', [Target]),
        fail
    ).

%% ============================================
%% BASH CODE GENERATORS (registered as multifile)
%% ============================================

compile_direct_multicall_pattern(bash, PredStr, BaseClauses, RecClause, BashCode) :-
    generate_direct_binary_bash(PredStr, BaseClauses, RecClause, BashCode).

%% generate_direct_binary_bash(+PredStr, +BaseClauses, +RecClause, -BashCode)
generate_direct_binary_bash(PredStr, BaseClauses, RecClause, BashCode) :-
    % Extract base cases
    extract_base_cases(BaseClauses, PredStr, BaseCasesCode),

    % Extract recursive case structure
    atom_string(Pred, PredStr),
    extract_recursive_case(RecClause, Pred, PredStr, RecursiveCaseCode),

    % Generate bash code
    format(string(BashCode), '#!/bin/bash
# ~w - direct recursive with memoization (multi-call pattern)
# Generated by direct_multi_call_recursion compiler

declare -gA ~w_memo
declare -ga _split_result

# Split a Prolog-style list "[a,b,[c,d],e]" into top-level elements,
# respecting nested brackets. Result is placed in $_split_result.
_split_list() {
    local s="$1"
    s="${s#[}"
    s="${s%]}"
    _split_result=()
    if [[ -z "$s" ]]; then return 0; fi
    local depth=0 start=0 i=0 len=${#s}
    while [[ $i -lt $len ]]; do
        local c="${s:$i:1}"
        case "$c" in
            "[") depth=$((depth + 1)) ;;
            "]") depth=$((depth - 1)) ;;
            ",")
                if [[ $depth -eq 0 ]]; then
                    _split_result+=("${s:$start:$((i - start))}")
                    start=$((i + 1))
                fi
                ;;
        esac
        i=$((i + 1))
    done
    _split_result+=("${s:$start}")
}

~w() {
    local input="$1"
    local expected="$2"

    # Check memo
    if [[ -n "${~w_memo[$input]}" ]]; then
        local cached="${~w_memo[$input]}"
        if [[ -z "$expected" ]]; then
            echo "$input:$cached"
            return 0
        elif [[ "$cached" == "$expected" ]]; then
            echo "$input:$expected"
            return 0
        else
            return 1
        fi
    fi

~w
~w

    # Should not reach here
    return 1
}

# Stream wrapper
~w_stream() {
    ~w "$@"
}
', [PredStr, PredStr, PredStr, PredStr, PredStr, BaseCasesCode, RecursiveCaseCode, PredStr, PredStr]).

%% is_recursive_clause(+Pred, +Clause)
is_recursive_clause(Pred, clause(_Head, Body)) :-
    contains_call_to(Body, Pred).

%% extract_base_cases(+BaseClauses, +PredStr, -BashCode)
%  Extract base case conditions and values
extract_base_cases(BaseClauses, PredStr, BashCode) :-
    findall(BaseCode, (
        member(clause(Head, _Body), BaseClauses),
        Head =.. [_Pred, BaseInput, BaseOutput],
        base_case_match(BaseInput, MatchTest),
        format(string(BaseCode), '    # Base case: ~w -> ~w
    if ~w; then
        local result="~w"
        ~w_memo["$input"]="$result"
        if [[ -z "$expected" ]]; then
            echo "$input:$result"
            return 0
        elif [[ "$result" == "$expected" ]]; then
            echo "$input:$expected"
            return 0
        else
            return 1
        fi
    fi', [BaseInput, BaseOutput, MatchTest, BaseOutput, PredStr])
    ), BaseCodes),
    atomic_list_concat(BaseCodes, '\n', BashCode).

%% base_case_match(+BaseInput, -BashTest)
%  Build a bash conditional expression that matches the base-case input.
%  Numbers and atoms become string-equality tests; variables match anything.
base_case_match(BaseInput, MatchTest) :-
    (   var(BaseInput)
    ->  MatchTest = '[[ -n "$input" ]]'
    ;   format(string(MatchTest), '[[ "$input" == "~w" ]]', [BaseInput])
    ).

%% extract_recursive_case(+RecClause, +Pred, +PredStr, -BashCode)
%  Extract recursive case: argument computations, recursive calls, aggregation
extract_recursive_case(clause(Head, Body), Pred, PredStr, BashCode) :-
    % Parse the body structure
    Head =.. [_Pred, InputPattern, _OutputVar],

    % Extract the body components
    extract_body_components(Body, Pred, Computations, RecCalls, Aggregation),

    % Generate bash for each part
    generate_pattern_decomposition_bash(InputPattern, DecompCode),
    generate_computations_bash(Computations, ComputationsCode),
    generate_recursive_calls_bash(RecCalls, PredStr, RecCallsCode),
    generate_aggregation_bash(Aggregation, AggregationCode),

    % Combine into recursive case code
    format(string(BashCode), '    # Recursive case
~w
~w
~w
~w

    # Memoize result
    ~w_memo["$input"]="$result"

    if [[ -z "$expected" ]]; then
        echo "$input:$result"
        return 0
    elif [[ "$result" == "$expected" ]]; then
        echo "$input:$expected"
        return 0
    else
        return 1
    fi', [DecompCode, ComputationsCode, RecCallsCode, AggregationCode, PredStr]).

%% generate_pattern_decomposition_bash(+InputPattern, -BashCode)
%  If the head input is a list pattern like [V, L, R], emit bash that
%  splits $input into elements and binds each variable element to a
%  bash variable matching the Prolog variable's gensym name.
%  For variable inputs (e.g., fib(N, F)), emit nothing — $input is the value.
generate_pattern_decomposition_bash(InputPattern, BashCode) :-
    (   var(InputPattern)
    ->  BashCode = ''
    ;   is_list(InputPattern)
    ->  generate_list_decomposition(InputPattern, BashCode)
    ;   BashCode = ''
    ).

generate_list_decomposition(Elements, BashCode) :-
    length(Elements, N),
    findall(BindCode, (
        nth0(I, Elements, El),
        var(El),
        var_to_bash_name(El, ElName),
        format(string(BindCode), '    local ~w="${_split_result[~w]}"', [ElName, I])
    ), BindCodes),
    atomic_list_concat(BindCodes, '\n', BindAll),
    format(string(BashCode), '    # Decompose input as ~w-element list pattern
    _split_list "$input"
    if [[ ${#_split_result[@]} -ne ~w ]]; then
        return 1
    fi
~w', [N, N, BindAll]).

%% extract_body_components(+Body, +Pred, -Computations, -RecCalls, -Aggregation)
%  Parse body into: argument computations, recursive calls, result aggregation
%  The aggregation is the `_ is _` goal whose expression references output
%  variables from recursive calls (e.g., F is F1 + F2 where F1, F2 are
%  bound by fib(N1, F1), fib(N2, F2)).
extract_body_components(Body, Pred, Computations, RecCalls, Aggregation) :-
    extract_goals_ordered(Body, Goals),
    % First identify recursive calls
    partition(is_recursive_call(Pred), Goals, RecCalls, NonRecGoals),
    % Separate is-goals from conditions/guards
    partition(is_computation, NonRecGoals, IsGoals, _Conditions),
    % Among is-goals, find the aggregation: the one whose expression
    % references an output variable from a recursive call (by identity).
    % NOTE: We check directly against RecCalls rather than using findall,
    % because findall copies variables and breaks identity (==) checks.
    (   select(AggGoal, IsGoals, CompGoals),
        AggGoal = (_ is AggExpr),
        term_variables(AggExpr, ExprVars),
        member(EV, ExprVars),
        member(Call, RecCalls),
        Call =.. [_|CallArgs],
        last(CallArgs, OutVar),
        EV == OutVar
    ->  Aggregation = AggGoal,
        Computations = CompGoals
    ;   Computations = IsGoals,
        Aggregation = true
    ).

is_computation(_ is _).

is_recursive_call(Pred, Goal) :-
    compound(Goal),
    functor(Goal, Pred, _).

%% extract_goals_ordered(+Body, -Goals)
%  Extract goals in order from conjunction
extract_goals_ordered((A, B), Goals) :- !,
    extract_goals_ordered(A, GoalsA),
    extract_goals_ordered(B, GoalsB),
    append(GoalsA, GoalsB, Goals).
extract_goals_ordered(Goal, [Goal]).

%% generate_computations_bash(+Computations, -BashCode)
%  Generate bash for argument computations (e.g., N1 is N-1, N2 is N-2)
generate_computations_bash(Computations, BashCode) :-
    findall(Code, (
        member(Var is Expr, Computations),
        translate_computation(Var, Expr, Code)
    ), Codes),
    atomic_list_concat(Codes, '\n', BashCode).

translate_computation(Var, Expr, Code) :-
    translate_expr_to_bash(Expr, BashExpr),
    var_to_bash_name(Var, VarLower),
    format(string(Code), '    local ~w=~w', [VarLower, BashExpr]).

%% var_to_bash_name(+Var, -BashName)
%  Convert a Prolog variable to a bash variable name
var_to_bash_name(Var, BashName) :-
    (   var(Var) ->
        % Variable - get its name and lowercase it
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, BashName)
    ;   atom(Var) ->
        % Already an atom - just lowercase it
        downcase_atom(Var, BashName)
    ;   % Other type - convert to atom and lowercase
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, BashName)
    ).

translate_expr_to_bash(N - 1, '$(($input - 1))') :- var(N), !.
translate_expr_to_bash(N - 2, '$(($input - 2))') :- var(N), !.
translate_expr_to_bash(N - 3, '$(($input - 3))') :- var(N), !.
translate_expr_to_bash(N - K, BashExpr) :- var(N), integer(K), !,
    format(string(BashExpr), '$(($input - ~w))', [K]).
% SWI-Prolog stores N-K as N+(-K) in clause database, so handle N+K too
translate_expr_to_bash(N + K, BashExpr) :- var(N), integer(K), K < 0, !,
    AbsK is abs(K),
    format(string(BashExpr), '$(($input - ~w))', [AbsK]).
translate_expr_to_bash(N + K, BashExpr) :- var(N), integer(K), !,
    format(string(BashExpr), '$(($input + ~w))', [K]).
translate_expr_to_bash(Expr, '$(($input))') :- var(Expr), !.

%% generate_recursive_calls_bash(+RecCalls, +PredStr, -BashCode)
%  Generate bash for recursive calls with result extraction
generate_recursive_calls_bash(RecCalls, PredStr, BashCode) :-
    findall(Code, (
        member(RecCall, RecCalls),
        RecCall =.. [_Pred, ArgVar, ResultVar],
        var_to_bash_name(ArgVar, ArgLower),
        var_to_bash_name(ResultVar, ResLower),
        format(string(Code), '    local ~w=$(~w "$~w" | cut -d: -f2)', [ResLower, PredStr, ArgLower])
    ), Codes),
    atomic_list_concat(Codes, '\n', BashCode).

%% generate_aggregation_bash(+Aggregation, -BashCode)
%  Generate bash for result aggregation (e.g., F is F1 + F2, S is V + LS + RS)
generate_aggregation_bash(_Result is Expr, BashCode) :-
    translate_arith_to_bash(Expr, Inner),
    format(string(BashCode), '    local result=$((~w))', [Inner]).

%% translate_arith_to_bash(+Expr, -BashExpr)
%  Recursively translate an arithmetic expression to bash $((...)) syntax.
%  Variables become $name, integers become themselves, and binary operators
%  are emitted infix. Recurses into sub-expressions so left-associative chains
%  like V+LS+RS = (V+LS)+RS expand correctly.
translate_arith_to_bash(Expr, BashExpr) :-
    var(Expr), !,
    var_to_bash_name(Expr, Name),
    format(string(BashExpr), '$~w', [Name]).
translate_arith_to_bash(N, BashExpr) :-
    integer(N), !,
    format(string(BashExpr), '~w', [N]).
translate_arith_to_bash(A + B, BashExpr) :- !,
    translate_arith_to_bash(A, AStr),
    translate_arith_to_bash(B, BStr),
    format(string(BashExpr), '~w + ~w', [AStr, BStr]).
translate_arith_to_bash(A - B, BashExpr) :- !,
    translate_arith_to_bash(A, AStr),
    translate_arith_to_bash(B, BStr),
    format(string(BashExpr), '~w - ~w', [AStr, BStr]).
translate_arith_to_bash(A * B, BashExpr) :- !,
    translate_arith_to_bash(A, AStr),
    translate_arith_to_bash(B, BStr),
    format(string(BashExpr), '~w * ~w', [AStr, BStr]).
translate_arith_to_bash(A / B, BashExpr) :- !,
    translate_arith_to_bash(A, AStr),
    translate_arith_to_bash(B, BStr),
    format(string(BashExpr), '~w / ~w', [AStr, BStr]).

%% Test predicate
test_direct_multi_call :-
    format('~n=== Testing Direct Multi-Call Compilation ===~n', []),

    % Setup output directory
    (   exists_directory('output/advanced') -> true
    ;   make_directory('output/advanced')
    ),

    % Clear test predicates
    catch(abolish(test_dfib/2), _, true),

    % Define fibonacci
    assertz(user:test_dfib(0, 0)),
    assertz(user:test_dfib(1, 1)),
    assertz(user:(test_dfib(N, F) :-
        N > 1,
        N1 is N - 1,
        N2 is N - 2,
        test_dfib(N1, F1),
        test_dfib(N2, F2),
        F is F1 + F2
    )),

    % Test 1: Detection
    writeln('Test 1: Detect fibonacci as direct multi-call'),
    (   can_compile_direct_multi_call(test_dfib/2) ->
        writeln('  ✓ PASS - fibonacci detected')
    ;   writeln('  ✗ FAIL - should detect fibonacci')
    ),

    % Test 2: Bash compilation
    writeln('Test 2: Compile fibonacci to bash'),
    (   compile_direct_multi_call(test_dfib/2, [target(bash)], BashCode) ->
        write_output_file('output/advanced/fib_direct.sh', BashCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.sh (bash)')
    ;   writeln('  ✗ FAIL - bash compilation failed')
    ),

    % Test 3: R compilation
    writeln('Test 3: Compile fibonacci to R'),
    (   compile_direct_multi_call(test_dfib/2, [target(r)], RCode) ->
        write_output_file('output/advanced/fib_direct.R', RCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.R (r)')
    ;   writeln('  ✗ FAIL - R compilation failed')
    ),

    % Test 4: Lua compilation
    writeln('Test 4: Compile fibonacci to Lua'),
    (   compile_direct_multi_call(test_dfib/2, [target(lua)], LuaCode) ->
        write_output_file('output/advanced/fib_direct.lua', LuaCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.lua (lua)')
    ;   writeln('  ✗ FAIL - Lua compilation failed')
    ),

    % Test 5: C compilation
    writeln('Test 5: Compile fibonacci to C'),
    (   compile_direct_multi_call(test_dfib/2, [target(c)], CCode) ->
        write_output_file('output/advanced/fib_direct.c', CCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.c (c)')
    ;   writeln('  ✗ FAIL - C compilation failed')
    ),

    % Test 6: Haskell compilation
    writeln('Test 6: Compile fibonacci to Haskell'),
    (   compile_direct_multi_call(test_dfib/2, [target(haskell)], HsCode) ->
        write_output_file('output/advanced/fib_direct.hs', HsCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.hs (haskell)')
    ;   writeln('  ✗ FAIL - Haskell compilation failed')
    ),

    % Test 7: Java compilation
    writeln('Test 7: Compile fibonacci to Java'),
    (   compile_direct_multi_call(test_dfib/2, [target(java)], JavaCode) ->
        write_java_file('output/advanced', JavaCode)
    ;   writeln('  ✗ FAIL - Java compilation failed')
    ),

    % Test 8: Elixir compilation
    writeln('Test 8: Compile fibonacci to Elixir'),
    (   compile_direct_multi_call(test_dfib/2, [target(elixir)], ExCode) ->
        write_output_file('output/advanced/fib_direct.exs', ExCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.exs (elixir)')
    ;   writeln('  ✗ FAIL - Elixir compilation failed')
    ),

    % Test 9: F# compilation
    writeln('Test 9: Compile fibonacci to F#'),
    (   compile_direct_multi_call(test_dfib/2, [target(fsharp)], FsCode) ->
        write_output_file('output/advanced/fib_direct.fs', FsCode),
        writeln('  ✓ Compiled to output/advanced/fib_direct.fs (fsharp)')
    ;   writeln('  ✗ FAIL - F# compilation failed')
    ),

    % Additional targets
    (   compile_direct_multi_call(test_dfib/2, [target(ruby)], RubyCode) ->
        write_output_file('output/advanced/fib_direct.rb', RubyCode),
        writeln('  ✓ Compiled fib_direct.rb (ruby)')
    ;   writeln('  ⊘ ruby fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(perl)], PerlCode) ->
        write_output_file('output/advanced/fib_direct.pl', PerlCode),
        writeln('  ✓ Compiled fib_direct.pl (perl)')
    ;   writeln('  ⊘ perl fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(jython)], PyCode) ->
        write_output_file('output/advanced/fib_direct.jy.py', PyCode),
        writeln('  ✓ Compiled fib_direct.jy.py (python)')
    ;   writeln('  ⊘ python fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(typescript)], TsCode) ->
        write_output_file('output/advanced/fib_direct.ts', TsCode),
        writeln('  ✓ Compiled fib_direct.ts (typescript)')
    ;   writeln('  ⊘ typescript fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(cpp)], CppCode) ->
        write_output_file('output/advanced/fib_direct.cpp', CppCode),
        writeln('  ✓ Compiled fib_direct.cpp (cpp)')
    ;   writeln('  ⊘ cpp fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(kotlin)], KtCode) ->
        write_output_file('output/advanced/fib_direct.kt', KtCode),
        writeln('  ✓ Compiled fib_direct.kt (kotlin)')
    ;   writeln('  ⊘ kotlin fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(scala)], ScCode) ->
        write_output_file('output/advanced/fib_direct.scala', ScCode),
        writeln('  ✓ Compiled fib_direct.scala (scala)')
    ;   writeln('  ⊘ scala fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(rust)], RsCode) ->
        write_output_file('output/advanced/fib_direct.rs', RsCode),
        writeln('  ✓ Compiled fib_direct.rs (rust)')
    ;   writeln('  ⊘ rust fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(go)], GoCode) ->
        write_output_file('output/advanced/fib_direct.go', GoCode),
        writeln('  ✓ Compiled fib_direct.go (go)')
    ;   writeln('  ⊘ go fib_direct skipped')
    ),
    (   compile_direct_multi_call(test_dfib/2, [target(clojure)], CljCode) ->
        write_output_file('output/advanced/fib_direct.clj', CljCode),
        writeln('  ✓ Compiled fib_direct.clj (clojure)')
    ;   writeln('  ⊘ clojure fib_direct skipped')
    ),

    format('~n=== Tests Complete ===~n', []).

%% Helper to write output files
write_output_file(Path, Content) :-
    open(Path, write, Stream),
    write(Stream, Content),
    close(Stream).

%% Write Java file using class name from generated code
write_java_file(Dir, Code) :-
    (   sub_string(Code, B, _, _, "public class "),
        B1 is B + 13,
        sub_string(Code, B1, _, _, Rest),
        sub_string(Rest, SpacePos, 1, _, " "),
        sub_string(Rest, 0, SpacePos, _, ClassName)
    ->  atomic_list_concat([Dir, '/', ClassName, '.java'], FilePath),
        open(FilePath, write, Stream),
        write(Stream, Code),
        close(Stream),
        format('  ✓ Compiled to ~w (java)~n', [FilePath])
    ;   writeln('  ✗ FAIL - could not extract Java class name from generated code')
    ).
