:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% direct_multi_call_recursion.pl - Direct recursive code generation for multi-call patterns
% Generates actual recursive bash functions with memoization instead of fold-based approach
%
% Strategy: For predicates like fibonacci with 2+ independent recursive calls,
% generate bash functions that directly call themselves recursively with memoization.

:- module(direct_multi_call_recursion, [
    compile_direct_multi_call/3,    % +Pred/Arity, +Options, -BashCode
    can_compile_direct_multi_call/1 % +Pred/Arity
]).

:- use_module(library(lists)).
:- use_module('pattern_matchers').

%% can_compile_direct_multi_call(+Pred/Arity)
%  Check if predicate can be compiled as direct multi-call recursion
can_compile_direct_multi_call(Pred/Arity) :-
    % Must be linear recursive streamable (includes multi-call check)
    is_linear_recursive_streamable(Pred/Arity),
    % Must have 2+ recursive calls
    get_recursive_call_count(Pred/Arity, Count),
    Count >= 2.

%% compile_direct_multi_call(+Pred/Arity, +Options, -BashCode)
%  Compile multi-call predicate to direct recursive bash with memoization
%  Options: List of Key=Value pairs (e.g., [unique=true, ordered=false])
compile_direct_multi_call(Pred/Arity, Options, BashCode) :-
    format('  Compiling direct multi-call recursion: ~w/~w~n', [Pred, Arity]),

    % Get multi-call info
    get_multi_call_info(Pred/Arity, multi_call(Count, _IsLinear, _HasDistinct, _IsPrecomp)),
    format('  Recursive calls: ~w~n', [Count]),

    % Currently only support arity 2 (input, output)
    (   Arity =:= 2 ->
        compile_direct_binary_recursion(Pred, Options, BashCode)
    ;   format('  ERROR: Direct multi-call only supports arity 2 currently~n', []),
        fail
    ).

%% compile_direct_binary_recursion(+Pred, +Options, -Code)
%  Compile arity-2 predicate with direct recursion
compile_direct_binary_recursion(Pred, Options, Code) :-
    atom_string(Pred, PredStr),
    
    % Determine target
    (   member(target(Target), Options) -> true
    ;   Target = bash
    ),
    format('  Target: ~w~n', [Target]),

    % Get clauses
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),

    % Separate base and recursive cases
    partition(is_recursive_clause(Pred), Clauses, [RecClause|_], BaseClauses),

    (   Target == r ->
        generate_direct_binary_r(PredStr, BaseClauses, RecClause, Code)
    ;   Target == bash ->
        generate_direct_binary_bash(PredStr, BaseClauses, RecClause, Code)
    ;   format('Error: Unsupported target ~w for direct multicall recursion~n', [Target]),
        fail
    ).

%% generate_direct_binary_r(+PredStr, +BaseClauses, +RecClause, -RCode)
generate_direct_binary_r(PredStr, BaseClauses, RecClause, RCode) :-
    % Extract base cases for R
    extract_base_cases_r(BaseClauses, BaseCasesCode),

    % Extract recursive case structure
    RecClause = clause(RecHead, RecBody),
    RecHead =.. [Pred, _InputVar, _OutputVar],
    extract_body_components(RecBody, Pred, Computations, RecCalls, Aggregation),

    % Generate R code for each part
    generate_computations_r(Computations, ComputationsCode),
    generate_recursive_calls_r(RecCalls, PredStr, RecCallsCode),
    generate_aggregation_r(Aggregation, AggregationCode),

    % Assemble
    format(string(RCode),
'#!/usr/bin/env Rscript
# ~w - direct recursive with memoization (multi-call pattern, R)
# Generated by direct_multi_call_recursion compiler

~w_memo <- new.env(hash=TRUE, parent=emptyenv())

~w <- function(input) {
    # Check memo
    key <- as.character(input)
    if (!is.null(~w_memo[[key]])) return(~w_memo[[key]])

~w

    # Computations
~w

    # Recursive calls
~w

    # Aggregate
~w

    # Memoize
    ~w_memo[[key]] <<- result
    return(result)
}

# Run when script executed directly
if (!interactive()) {
    args <- commandArgs(TRUE)
    if (length(args) >= 1) cat(~w(as.integer(args[1])), "\\n")
}
', [PredStr, PredStr, PredStr, PredStr, PredStr,
    BaseCasesCode, ComputationsCode, RecCallsCode, AggregationCode,
    PredStr, PredStr]).

%% extract_base_cases_r(+BaseClauses, -RCode)
extract_base_cases_r(BaseClauses, RCode) :-
    findall(BaseCode, (
        member(clause(Head, _Body), BaseClauses),
        Head =.. [_Pred, BaseInput, BaseOutput],
        format(string(BaseCode),
'    # Base case: ~w -> ~w
    if (input == ~w) { ~w_memo[[key]] <<- ~w; return(~w) }',
            [BaseInput, BaseOutput, BaseInput, '_direct', BaseOutput, BaseOutput])
    ), BaseCodes),
    atomic_list_concat(BaseCodes, '\n', RCode).

%% generate_computations_r(+Computations, -RCode)
generate_computations_r(Computations, RCode) :-
    findall(Code, (
        member(Var is Expr, Computations),
        var_to_r_name(Var, VarName),
        translate_expr_to_r(Expr, RExpr),
        format(string(Code), '    ~w <- ~w', [VarName, RExpr])
    ), Codes),
    atomic_list_concat(Codes, '\n', RCode).

%% generate_recursive_calls_r(+RecCalls, +PredStr, -RCode)
generate_recursive_calls_r(RecCalls, PredStr, RCode) :-
    findall(Code, (
        member(RecCall, RecCalls),
        RecCall =.. [_Pred, ArgVar, ResultVar],
        var_to_r_name(ArgVar, ArgName),
        var_to_r_name(ResultVar, ResName),
        format(string(Code), '    ~w <- ~w(~w)', [ResName, PredStr, ArgName])
    ), Codes),
    atomic_list_concat(Codes, '\n', RCode).

%% generate_aggregation_r(+Aggregation, -RCode)
generate_aggregation_r(_Result is Expr, RCode) :-
    translate_aggregation_expr_r(Expr, RExpr),
    format(string(RCode), '    result <- ~w', [RExpr]).

translate_aggregation_expr_r(A + B, RExpr) :-
    var_to_r_name(A, AName),
    var_to_r_name(B, BName),
    format(string(RExpr), '~w + ~w', [AName, BName]).
translate_aggregation_expr_r(A + B + C, RExpr) :-
    var_to_r_name(A, AName),
    var_to_r_name(B, BName),
    var_to_r_name(C, CName),
    format(string(RExpr), '~w + ~w + ~w', [AName, BName, CName]).
translate_aggregation_expr_r(A * B, RExpr) :-
    var_to_r_name(A, AName),
    var_to_r_name(B, BName),
    format(string(RExpr), '~w * ~w', [AName, BName]).

%% var_to_r_name(+Var, -RName)
var_to_r_name(Var, RName) :-
    (   var(Var) ->
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, RName)
    ;   atom(Var) ->
        downcase_atom(Var, RName)
    ;   term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, RName)
    ).

%% translate_expr_to_r(+Expr, -RExpr)
translate_expr_to_r(N - K, RExpr) :- var(N), integer(K), !,
    format(string(RExpr), 'input - ~w', [K]).
translate_expr_to_r(N + K, RExpr) :- var(N), integer(K), !,
    format(string(RExpr), 'input + ~w', [K]).
translate_expr_to_r(Expr, 'input') :- var(Expr), !.

%% generate_direct_binary_bash(+PredStr, +BaseClauses, +RecClause, -BashCode)
generate_direct_binary_bash(PredStr, BaseClauses, RecClause, BashCode) :-
    % Extract base cases
    extract_base_cases(BaseClauses, PredStr, BaseCasesCode),

    % Extract recursive case structure
    extract_recursive_case(RecClause, Pred, PredStr, RecursiveCaseCode),

    % Generate bash code
    format(string(BashCode), '#!/bin/bash
# ~w - direct recursive with memoization (multi-call pattern)
# Generated by direct_multi_call_recursion compiler

declare -gA ~w_memo

~w() {
    local input="$1"
    local expected="$2"

    # Check memo
    if [[ -n "${~w_memo[$input]}" ]]; then
        local cached="${~w_memo[$input]}"
        if [[ -z "$expected" ]]; then
            echo "$input:$cached"
            return 0
        elif [[ "$cached" == "$expected" ]]; then
            echo "$input:$expected"
            return 0
        else
            return 1
        fi
    fi

~w
~w

    # Should not reach here
    return 1
}

# Stream wrapper
~w_stream() {
    ~w "$@"
}
', [PredStr, PredStr, PredStr, PredStr, PredStr, BaseCasesCode, RecursiveCaseCode, PredStr, PredStr]).

%% is_recursive_clause(+Pred, +Clause)
is_recursive_clause(Pred, clause(_Head, Body)) :-
    contains_call_to(Body, Pred).

%% extract_base_cases(+BaseClauses, +PredStr, -BashCode)
%  Extract base case conditions and values
extract_base_cases(BaseClauses, PredStr, BashCode) :-
    findall(BaseCode, (
        member(clause(Head, _Body), BaseClauses),
        Head =.. [_Pred, BaseInput, BaseOutput],
        format(string(BaseCode), '    # Base case: ~w -> ~w
    if [[ "$input" -eq ~w ]]; then
        local result="~w"
        ~w_memo["$input"]="$result"
        if [[ -z "$expected" ]]; then
            echo "$input:$result"
            return 0
        elif [[ "$result" == "$expected" ]]; then
            echo "$input:$expected"
            return 0
        else
            return 1
        fi
    fi', [BaseInput, BaseOutput, BaseInput, BaseOutput, PredStr])
    ), BaseCodes),
    atomic_list_concat(BaseCodes, '\n', BashCode).

%% extract_recursive_case(+RecClause, +Pred, +PredStr, -BashCode)
%  Extract recursive case: argument computations, recursive calls, aggregation
extract_recursive_case(clause(Head, Body), Pred, PredStr, BashCode) :-
    % Parse the body structure
    Head =.. [_Pred, _InputVar, _OutputVar],

    % Extract the body components
    extract_body_components(Body, Pred, Computations, RecCalls, Aggregation),

    % Generate bash for each part
    generate_computations_bash(Computations, ComputationsCode),
    generate_recursive_calls_bash(RecCalls, PredStr, RecCallsCode),
    generate_aggregation_bash(Aggregation, AggregationCode),

    % Combine into recursive case code
    format(string(BashCode), '    # Recursive case
~w
~w
~w

    # Memoize result
    ~w_memo["$input"]="$result"

    if [[ -z "$expected" ]]; then
        echo "$input:$result"
        return 0
    elif [[ "$result" == "$expected" ]]; then
        echo "$input:$expected"
        return 0
    else
        return 1
    fi', [ComputationsCode, RecCallsCode, AggregationCode, PredStr]).

%% extract_body_components(+Body, +Pred, -Computations, -RecCalls, -Aggregation)
%  Parse body into: argument computations, recursive calls, result aggregation
extract_body_components(Body, Pred, Computations, RecCalls, Aggregation) :-
    extract_goals_ordered(Body, Goals),
    partition(is_computation, Goals, Computations, Rest1),
    partition(is_recursive_call(Pred), Rest1, RecCalls, Rest2),
    (   Rest2 = [Aggregation|_] -> true ; Aggregation = true).

is_computation(_ is _).

is_recursive_call(Pred, Goal) :-
    compound(Goal),
    functor(Goal, Pred, _).

%% extract_goals_ordered(+Body, -Goals)
%  Extract goals in order from conjunction
extract_goals_ordered((A, B), Goals) :- !,
    extract_goals_ordered(A, GoalsA),
    extract_goals_ordered(B, GoalsB),
    append(GoalsA, GoalsB, Goals).
extract_goals_ordered(Goal, [Goal]).

%% generate_computations_bash(+Computations, -BashCode)
%  Generate bash for argument computations (e.g., N1 is N-1, N2 is N-2)
generate_computations_bash(Computations, BashCode) :-
    findall(Code, (
        member(Var is Expr, Computations),
        translate_computation(Var, Expr, Code)
    ), Codes),
    atomic_list_concat(Codes, '\n', BashCode).

translate_computation(Var, Expr, Code) :-
    translate_expr_to_bash(Expr, BashExpr),
    var_to_bash_name(Var, VarLower),
    format(string(Code), '    local ~w=~w', [VarLower, BashExpr]).

%% var_to_bash_name(+Var, -BashName)
%  Convert a Prolog variable to a bash variable name
var_to_bash_name(Var, BashName) :-
    (   var(Var) ->
        % Variable - get its name and lowercase it
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, BashName)
    ;   atom(Var) ->
        % Already an atom - just lowercase it
        downcase_atom(Var, BashName)
    ;   % Other type - convert to atom and lowercase
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, BashName)
    ).

translate_expr_to_bash(N - 1, '$(($input - 1))') :- var(N), !.
translate_expr_to_bash(N - 2, '$(($input - 2))') :- var(N), !.
translate_expr_to_bash(N - 3, '$(($input - 3))') :- var(N), !.
translate_expr_to_bash(N - K, BashExpr) :- var(N), integer(K), !,
    format(string(BashExpr), '$(($input - ~w))', [K]).
translate_expr_to_bash(Expr, '$(($input))') :- var(Expr), !.

%% generate_recursive_calls_bash(+RecCalls, +PredStr, -BashCode)
%  Generate bash for recursive calls with result extraction
generate_recursive_calls_bash(RecCalls, PredStr, BashCode) :-
    findall(Code, (
        member(RecCall, RecCalls),
        RecCall =.. [_Pred, ArgVar, ResultVar],
        var_to_bash_name(ArgVar, ArgLower),
        var_to_bash_name(ResultVar, ResLower),
        format(string(Code), '    local ~w=$(~w "$~w" | cut -d: -f2)', [ResLower, PredStr, ArgLower])
    ), Codes),
    atomic_list_concat(Codes, '\n', BashCode).

%% generate_aggregation_bash(+Aggregation, -BashCode)
%  Generate bash for result aggregation (e.g., F is F1 + F2)
generate_aggregation_bash(_Result is Expr, BashCode) :-
    translate_aggregation_expr(Expr, BashExpr),
    format(string(BashCode), '    local result=~w', [BashExpr]).

translate_aggregation_expr(A + B, BashExpr) :-
    var_to_bash_name(A, ALower),
    var_to_bash_name(B, BLower),
    format(string(BashExpr), '$(($~w + $~w))', [ALower, BLower]).

translate_aggregation_expr(A + B + C, BashExpr) :-
    var_to_bash_name(A, ALower),
    var_to_bash_name(B, BLower),
    var_to_bash_name(C, CLower),
    format(string(BashExpr), '$(($~w + $~w + $~w))', [ALower, BLower, CLower]).

%% Test predicate
test_direct_multi_call :-
    format('~n=== Testing Direct Multi-Call Compilation ===~n', []),

    % Test fibonacci
    (   can_compile_direct_multi_call(fib/2) ->
        format('✓ fib/2 can use direct multi-call~n', [])
    ;   format('✗ fib/2 cannot use direct multi-call~n', [])
    ),

    format('~n=== Tests Complete ===~n', []).
