#!/usr/bin/env bash
# Regenerate the (gitignored) cumulative scored set used for replay (--replay-pairs) and dedup
# (--dedup-against). It is the UNION of every round's committed scored set; duplicate pairs collapse
# downstream (dedup keys by sorted (a,b)). Kept out of git because it is 100% derived — run this after a
# fresh clone or after adding a new round's mu_pairs_scored_<round>.tsv.
cd "$(dirname "$0")"
ROUNDS=(mu_pairs_scored_eng.tsv mu_pairs_scored_enwiki.tsv mu_pairs_scored_mathfields.tsv
        mu_pairs_scored_alggeom.tsv mu_pairs_scored_boundary.tsv mu_pairs_scored_stats.tsv
        mu_pairs_scored_sysinfo.tsv)
{ echo "# cumulative scored set (regenerated by make_cumulative.sh) = union of all round scored sets"
  grep -hv '^#' "${ROUNDS[@]}"; } > mu_pairs_scored_cumulative.tsv
# "prior" = the pre-mathfields baseline (eng + enwiki), used as the mathfields round's replay baseline.
{ echo "# prior cumulative (regenerated) = mu_pairs_scored_eng.tsv + mu_pairs_scored_enwiki.tsv"
  grep -hv '^#' mu_pairs_scored_eng.tsv mu_pairs_scored_enwiki.tsv; } > mu_pairs_scored_prior.tsv
echo "cumulative: $(grep -vc '^#' mu_pairs_scored_cumulative.tsv) rows ; prior: $(grep -vc '^#' mu_pairs_scored_prior.tsv) rows"
