%% agent_loop_module.pl - Prolog generator for UnifyWeaver Agent Loop
%%
%% This module defines agent backends and tools declaratively,
%% then generates Python code from the specifications.

:- module(agent_loop_module, [
    generate_all/0,
    generate_backend/1,
    generate_tools/0,
    agent_backend/2,
    tool_spec/2
]).

%% =============================================================================
%% Agent Backend Definitions
%% =============================================================================

%% agent_backend(Name, Properties)
%% Defines an agent backend with its configuration

agent_backend(coro, [
    type(cli),
    command("claude"),
    args(["--verbose"]),
    description("Coro-code CLI backend using single-task mode"),
    context_format(conversation_history),
    output_parser(coro_parser),
    supports_streaming(false)
]).

agent_backend(claude_api, [
    type(api),
    endpoint("https://api.anthropic.com/v1/messages"),
    model("claude-sonnet-4-20250514"),
    auth_env("ANTHROPIC_API_KEY"),
    auth_header("x-api-key"),
    description("Anthropic Claude API backend"),
    context_format(messages_array),
    supports_tools(true),
    supports_streaming(true)
]).

agent_backend(openai, [
    type(api),
    endpoint("https://api.openai.com/v1/chat/completions"),
    model("gpt-4o"),
    auth_env("OPENAI_API_KEY"),
    auth_header("Authorization"),
    auth_prefix("Bearer "),
    description("OpenAI API backend"),
    context_format(messages_array),
    supports_tools(true),
    supports_streaming(true)
]).

agent_backend(ollama, [
    type(api),
    endpoint("http://localhost:11434/api/chat"),
    model("llama3"),
    description("Ollama local API backend"),
    context_format(messages_array),
    auth_required(false),
    supports_streaming(true)
]).

%% =============================================================================
%% Tool Definitions
%% =============================================================================

%% tool_spec(Name, Properties)
%% Defines a tool that agents can use

tool_spec(bash, [
    description("Execute a bash command"),
    parameters([
        param(command, string, required, "The command to execute")
    ]),
    confirmation_required(true),
    timeout(120)
]).

tool_spec(read, [
    description("Read a file"),
    parameters([
        param(path, string, required, "Path to file")
    ]),
    confirmation_required(false)
]).

tool_spec(write, [
    description("Write content to a file"),
    parameters([
        param(path, string, required, "Path to file"),
        param(content, string, required, "Content to write")
    ]),
    confirmation_required(true)
]).

tool_spec(edit, [
    description("Edit a file with search/replace"),
    parameters([
        param(path, string, required, "Path to file"),
        param(old_string, string, required, "Text to find"),
        param(new_string, string, required, "Replacement text")
    ]),
    confirmation_required(true)
]).

%% =============================================================================
%% Loop Configuration
%% =============================================================================

loop_config([
    max_context_tokens(100000),
    max_messages(50),
    trim_strategy(oldest_first),
    display_tokens(true),
    display_tool_calls(true),
    confirm_destructive_tools(true)
]).

%% =============================================================================
%% Code Generation
%% =============================================================================

%% Generate all files
generate_all :-
    write('Generating agent loop files...'), nl,
    generate_backends_init,
    forall(agent_backend(Name, _), generate_backend(Name)),
    generate_tools,
    generate_readme,
    write('Done.'), nl.

%% Generate __init__.py for backends (to stubs directory)
generate_backends_init :-
    open('generated/stubs/__init__.py', write, Stream),
    write(Stream, '# Auto-generated by agent_loop_module.pl\n'),
    write(Stream, 'from .base import AgentBackend, AgentResponse, ToolCall\n'),
    findall(Name, agent_backend(Name, _), Backends),
    generate_backend_imports(Stream, Backends),
    write(Stream, '\n__all__ = ['),
    write(Stream, '\'AgentBackend\', \'AgentResponse\', \'ToolCall\''),
    generate_all_exports(Stream, Backends),
    write(Stream, ']\n'),
    close(Stream),
    format('  Generated backends/__init__.py~n', []).

generate_backend_imports(_, []).
generate_backend_imports(Stream, [Name|Rest]) :-
    backend_class_name(Name, ClassName),
    backend_file_name(Name, FileName),
    format(Stream, 'from .~w import ~w~n', [FileName, ClassName]),
    generate_backend_imports(Stream, Rest).

generate_all_exports(_, []).
generate_all_exports(Stream, [Name|Rest]) :-
    backend_class_name(Name, ClassName),
    format(Stream, ', \'~w\'', [ClassName]),
    generate_all_exports(Stream, Rest).

%% Generate a backend Python file (to stubs directory)
generate_backend(Name) :-
    agent_backend(Name, Props),
    backend_file_name(Name, FileName),
    atom_concat('generated/stubs/', FileName, Path1),
    atom_concat(Path1, '.py', Path),
    open(Path, write, Stream),
    generate_backend_code(Stream, Name, Props),
    close(Stream),
    format('  Generated stubs/~w.py~n', [FileName]).

generate_backend_code(Stream, Name, Props) :-
    backend_class_name(Name, ClassName),
    member(type(Type), Props),
    member(description(Desc), Props),
    format(Stream, '"""~w"""~n~n', [Desc]),
    (Type = cli ->
        generate_cli_backend(Stream, ClassName, Props)
    ;
        generate_api_backend(Stream, ClassName, Props)
    ).

generate_cli_backend(Stream, ClassName, Props) :-
    member(command(Cmd), Props),
    format(Stream, 'import subprocess~n', []),
    format(Stream, 'from .base import AgentBackend, AgentResponse~n~n', []),
    format(Stream, 'class ~w(AgentBackend):~n', [ClassName]),
    format(Stream, '    """CLI backend using ~w command."""~n~n', [Cmd]),
    format(Stream, '    def __init__(self, command: str = "~w"):~n', [Cmd]),
    format(Stream, '        self.command = command~n~n', []),
    format(Stream, '    def send_message(self, message: str, context: list[dict]) -> AgentResponse:~n', []),
    format(Stream, '        # Implementation in coro.py~n', []),
    format(Stream, '        raise NotImplementedError("See coro.py for full implementation")~n', []).

generate_api_backend(Stream, ClassName, Props) :-
    member(endpoint(Endpoint), Props),
    member(model(Model), Props),
    format(Stream, 'import os~n', []),
    format(Stream, 'import requests~n', []),
    format(Stream, 'from .base import AgentBackend, AgentResponse~n~n', []),
    format(Stream, 'class ~w(AgentBackend):~n', [ClassName]),
    format(Stream, '    """API backend for ~w"""~n~n', [Endpoint]),
    format(Stream, '    ENDPOINT = "~w"~n', [Endpoint]),
    format(Stream, '    DEFAULT_MODEL = "~w"~n~n', [Model]),
    format(Stream, '    def __init__(self, api_key: str = None, model: str = None):~n', []),
    (member(auth_env(EnvVar), Props) ->
        format(Stream, '        self.api_key = api_key or os.environ.get("~w")~n', [EnvVar])
    ;
        format(Stream, '        self.api_key = api_key~n', [])
    ),
    format(Stream, '        self.model = model or self.DEFAULT_MODEL~n~n', []),
    format(Stream, '    def send_message(self, message: str, context: list[dict]) -> AgentResponse:~n', []),
    format(Stream, '        # Implementation varies by API~n', []),
    format(Stream, '        raise NotImplementedError("Implement for specific API")~n', []).

%% Generate tools.py (to stubs directory)
generate_tools :-
    open('generated/stubs/tools_generated.py', write, Stream),
    write(Stream, '"""Auto-generated tool definitions from Prolog specs."""\n\n'),
    write(Stream, 'TOOL_SPECS = {\n'),
    findall(Name, tool_spec(Name, _), Tools),
    generate_tool_specs(Stream, Tools),
    write(Stream, '}\n\n'),
    write(Stream, 'DESTRUCTIVE_TOOLS = {\n'),
    generate_destructive_list(Stream, Tools),
    write(Stream, '}\n'),
    close(Stream),
    format('  Generated tools_generated.py~n', []).

generate_tool_specs(_, []).
generate_tool_specs(Stream, [Name|Rest]) :-
    tool_spec(Name, Props),
    member(description(Desc), Props),
    member(parameters(Params), Props),
    format(Stream, '    "~w": {~n', [Name]),
    format(Stream, '        "description": "~w",~n', [Desc]),
    format(Stream, '        "parameters": [~n', []),
    generate_params(Stream, Params),
    format(Stream, '        ]~n', []),
    format(Stream, '    },~n', []),
    generate_tool_specs(Stream, Rest).

generate_params(_, []).
generate_params(Stream, [param(Name, Type, Required, Desc)|Rest]) :-
    format(Stream, '            {"name": "~w", "type": "~w", "required": ~w, "description": "~w"},~n',
           [Name, Type, Required, Desc]),
    generate_params(Stream, Rest).

generate_destructive_list(_, []).
generate_destructive_list(Stream, [Name|Rest]) :-
    tool_spec(Name, Props),
    (member(confirmation_required(true), Props) ->
        format(Stream, '    "~w",~n', [Name])
    ;
        true
    ),
    generate_destructive_list(Stream, Rest).

%% Generate README (to stubs directory)
generate_readme :-
    open('generated/stubs/README.md', write, Stream),
    write(Stream, '# UnifyWeaver Agent Loop - Generated Code\n\n'),
    write(Stream, 'This code was generated by `agent_loop_module.pl`.\n\n'),
    write(Stream, '## Backends\n\n'),
    forall(agent_backend(Name, Props), (
        member(description(Desc), Props),
        format(Stream, '- **~w**: ~w~n', [Name, Desc])
    )),
    write(Stream, '\n## Tools\n\n'),
    forall(tool_spec(Name, Props), (
        member(description(Desc), Props),
        format(Stream, '- **~w**: ~w~n', [Name, Desc])
    )),
    write(Stream, '\n## Usage\n\n'),
    write(Stream, '```bash\n'),
    write(Stream, 'python3 agent_loop.py              # interactive\n'),
    write(Stream, 'python3 agent_loop.py "prompt"     # single prompt\n'),
    write(Stream, 'python3 agent_loop.py -b claude    # use Claude API\n'),
    write(Stream, '```\n'),
    close(Stream),
    format('  Generated README.md~n', []).

%% Helper predicates
backend_class_name(Name, ClassName) :-
    atom_codes(Name, Codes),
    to_camel_case(Codes, CamelCodes),
    atom_codes('Backend', BackendCodes),
    append(CamelCodes, BackendCodes, ClassCodes),
    atom_codes(ClassName, ClassCodes).

backend_file_name(Name, FileName) :-
    atom_codes(Name, Codes),
    to_snake_case(Codes, SnakeCodes),
    atom_codes(FileName, SnakeCodes).

to_camel_case([], []).
to_camel_case([C|Rest], [Upper|CamelRest]) :-
    C >= 0'a, C =< 0'z,
    Upper is C - 32,
    to_camel_case_rest(Rest, CamelRest).
to_camel_case([C|Rest], [C|CamelRest]) :-
    to_camel_case_rest(Rest, CamelRest).

to_camel_case_rest([], []).
to_camel_case_rest([0'_|Rest], CamelRest) :-
    to_camel_case(Rest, CamelRest).
to_camel_case_rest([C|Rest], [C|CamelRest]) :-
    C \= 0'_,
    to_camel_case_rest(Rest, CamelRest).

to_snake_case([], []).
to_snake_case([C|Rest], [Lower|SnakeRest]) :-
    C >= 0'A, C =< 0'Z,
    Lower is C + 32,
    to_snake_case(Rest, SnakeRest).
to_snake_case([C|Rest], [C|SnakeRest]) :-
    to_snake_case(Rest, SnakeRest).

%% Query helpers for introspection
list_backends :-
    write('Available backends:'), nl,
    forall(agent_backend(Name, Props), (
        member(description(Desc), Props),
        format('  ~w: ~w~n', [Name, Desc])
    )).

list_tools :-
    write('Available tools:'), nl,
    forall(tool_spec(Name, Props), (
        member(description(Desc), Props),
        format('  ~w: ~w~n', [Name, Desc])
    )).
