import type { Meta, StoryObj } from "@storybook/react";
import React, { useState, useCallback } from "react";

// Animated Box Component for demonstrating animations
interface AnimatedBoxProps {
  animation: string;
  label: string;
}

const AnimatedBox: React.FC<AnimatedBoxProps> = ({ animation, label }) => {
  const [key, setKey] = useState(0);

  const replay = useCallback(() => {
    setKey((prev) => prev + 1);
  }, []);

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "0.5rem",
      }}
    >
      <div
        key={key}
        className={`animate-${animation}`}
        style={{
          width: "80px",
          height: "80px",
          background: "var(--color-primary)",
          borderRadius: "var(--border-radius-md)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "white",
          fontSize: "0.75rem",
          fontWeight: 600,
        }}
      >
        {label}
      </div>
      <button
        onClick={replay}
        style={{
          padding: "0.25rem 0.5rem",
          fontSize: "0.75rem",
          border: "1px solid var(--color-border)",
          borderRadius: "var(--border-radius-sm)",
          background: "var(--color-surface)",
          cursor: "pointer",
        }}
      >
        Replay
      </button>
    </div>
  );
};

// Animation Gallery Component
const AnimationGallery: React.FC = () => {
  const animations = [
    { name: "fade_in", label: "Fade In" },
    { name: "fade_in_up", label: "Fade Up" },
    { name: "scale_in", label: "Scale In" },
    { name: "pulse", label: "Pulse" },
  ];

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
        gap: "2rem",
        padding: "1rem",
      }}
    >
      {animations.map(({ name, label }) => (
        <AnimatedBox key={name} animation={name} label={label} />
      ))}
    </div>
  );
};

const meta: Meta<typeof AnimationGallery> = {
  title: "Animations/Gallery",
  component: AnimationGallery,
  tags: ["autodocs"],
  parameters: {
    docs: {
      description: {
        component: `
Animation presets generated by UnifyWeaver for entry, exit, and attention effects.

**Generated from:** \`generate_preset_css/2\` in \`animation_presets.pl\`

\`\`\`prolog
% Generate CSS for all presets
?- generate_all_presets_css(CSS).

% Generate useAnimation hook
?- generate_preset_hook(Hook).
\`\`\`

### Available Presets

**Entry Animations:**
- fade_in, fade_in_up, fade_in_down, fade_in_left, fade_in_right
- slide_in_up, slide_in_down, slide_in_left, slide_in_right
- scale_in, scale_in_center, zoom_in, bounce_in
- flip_in_x, flip_in_y

**Exit Animations:**
- fade_out, fade_out_up, fade_out_down
- scale_out, zoom_out

**Attention Animations:**
- pulse, bounce, shake, wiggle, flash, heartbeat, jello

**Chart Animations:**
- chart_draw, bar_grow, pie_reveal, data_point_pop, tooltip_appear
        `,
      },
    },
  },
};

export default meta;
type Story = StoryObj<typeof AnimationGallery>;

export const Default: Story = {};

export const SingleAnimation: Story = {
  render: () => <AnimatedBox animation="fade_in_up" label="Fade Up" />,
  parameters: {
    docs: {
      description: {
        story: "Individual animation demonstration with replay button.",
      },
    },
  },
};
