:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2026 John William Creighton (@s243a)
%
% pe_number.pl - canonical number spelling for the v0.5 surface:
% CPython float-repr semantics, in Prolog.
%
% ============================================================
% WHY THIS EXISTS
% ============================================================
% The sealed bundles spell numbers with Python's `repr`, because
% process_cards.py's _render_val does.  The third-consumer report
% flagged the resulting assumption honestly:
%
%   "Number spelling relies on SWI ~w agreeing with Python repr — true
%    for every float in the golden corpus, but scientific-notation
%    floats could diverge and no golden row exercises them."
%
% Golden v4 added `scientific-notation-number` (margin(t=1e-05)), and
% the divergence is real.  Measured, SWI ~w versus Python repr:
%
%   value      Python repr             SWI ~w
%   1e-05      1e-05                   1.0e-5      mantissa + padding
%   1.5e-07    1.5e-07                 1.5e-7      exponent padding
%   1e16       1e+16                   1.0e+16     mantissa
%   1e15       1000000000000000.0      1.0e+15     DIFFERENT THRESHOLD
%   0.85       0.85                    0.85        agree
%   2.5e-10    2.5e-10                 2.5e-10     agree
%
% Three distinct divergences, of which the third is not a formatting
% tweak: SWI switches to exponential notation earlier on the large
% side than CPython does.  So this module implements CPython's rule
% rather than post-patching SWI's output shape.
%
% ============================================================
% THE RULE (CPython float_repr -> format_float_short, mode 0)
% ============================================================
% Take the shortest round-tripping decimal digits D and the decimal
% point position `decpt` (value = 0.D * 10^decpt, i.e. the point falls
% after `decpt` digits).  Then:
%
%   decpt <= -4  or  decpt > 16   ->  exponential
%   otherwise                     ->  fixed
%
% Exponential: d0 ["." d1..] "e" sign exp2, where exp = decpt - 1 and
% the exponent is zero-padded to at least two digits.
% Fixed: the usual placement, always with at least one fractional
% digit (CPython appends ".0" to an otherwise-integral result).
%
% SWI's own ~w already produces shortest round-tripping digits, so
% those are parsed out of it rather than recomputed; only the
% *presentation* rule is reimplemented.
%
% INTEGERS PASS THROUGH.  Python's _render_val uses str() for ints, so
% `margin(t=1)` spells `1`, not `1.0` — and the golden row
% `int-spelled-number` pins exactly that.  Only floats are reformatted.
%
% ============================================================
% TESTED RANGE, AND FAIL-CLOSED OUTSIDE IT
% ============================================================
% test_pe_number.pl checks this against a corpus of values whose
% expected spellings were generated by real Python and pasted in as
% fixtures — so the claim is measured, not asserted.  Non-finite
% floats (inf, nan) have no v0.5 surface spelling and are REFUSED:
% process_cards.py raises on them too ("cannot render non-finite
% process value"), and inventing a spelling here would put bytes on
% the surface that the sealed renderer would never produce.

:- module(pe_number, [
    pe_number_atom/2        % +Number, -Atom
]).

:- use_module(library(lists)).

%% pe_number_atom(+Number, -Atom)
%  The v0.5 surface spelling of Number.
pe_number_atom(N, A) :-
    integer(N),
    !,
    atom_number(A, N).
pe_number_atom(N, A) :-
    float(N),
    !,
    (   is_finite_float(N)
    ->  float_repr(N, A)
    ;   throw(error(pe_number(non_finite(N)), _))
    ).
pe_number_atom(N, _) :-
    throw(error(pe_number(not_a_number(N)), _)).

is_finite_float(N) :-
    N =:= N,                       % nan =\= nan
    N < inf,
    N > -inf.

%% float_repr(+Float, -Atom)
float_repr(F, Atom) :-
    (   F < 0.0
    ->  Sign = '-', Abs is -F
    ;   Sign = '', Abs = F
    ),
    shortest_digits(Abs, Digits, Decpt),
    (   Digits == "0"
    ->  Body = '0.0'
    ;   string_length(Digits, N),
        (   ( Decpt =< -4 ; Decpt > 16 )
        ->  exponential_form(Digits, N, Decpt, Body)
        ;   fixed_form(Digits, N, Decpt, Body)
        )
    ),
    atom_concat(Sign, Body, Atom).

%% shortest_digits(+AbsFloat, -Digits, -Decpt)
%  Digits is the shortest round-tripping digit string with leading and
%  trailing zeros removed; Decpt is the decimal point position (value =
%  0.Digits * 10^Decpt).  Parsed out of SWI's own shortest-roundtrip
%  rendering rather than recomputed.
shortest_digits(F, Digits, Decpt) :-
    format(atom(S), '~w', [F]),
    atom_string(S, Str),
    split_exponent(Str, MantStr, Exp),
    split_point(MantStr, IntPart, FracPart),
    string_concat(IntPart, FracPart, RawDigits),
    string_length(IntPart, IntLen),
    Decpt0 is IntLen + Exp,
    strip_leading_zeros(RawDigits, Stripped, Removed),
    Decpt1 is Decpt0 - Removed,
    strip_trailing_zeros(Stripped, Digits0),
    (   Digits0 == ""
    ->  Digits = "0", Decpt = 1
    ;   Digits = Digits0, Decpt = Decpt1
    ).

split_exponent(Str, Mant, Exp) :-
    (   ( sub_string(Str, B, 1, _, "e") ; sub_string(Str, B, 1, _, "E") )
    ->  sub_string(Str, 0, B, _, Mant),
        After is B + 1,
        sub_string(Str, After, _, 0, ExpStr),
        number_string(Exp, ExpStr)
    ;   Mant = Str, Exp = 0
    ).

split_point(Mant, IntPart, FracPart) :-
    (   sub_string(Mant, B, 1, _, ".")
    ->  sub_string(Mant, 0, B, _, IntPart),
        After is B + 1,
        sub_string(Mant, After, _, 0, FracPart)
    ;   IntPart = Mant, FracPart = ""
    ).

strip_leading_zeros(S, Out, Removed) :-
    (   sub_string(S, 0, 1, _, "0"),
        string_length(S, L),
        L > 1
    ->  sub_string(S, 1, _, 0, Rest),
        strip_leading_zeros(Rest, Out, R0),
        Removed is R0 + 1
    ;   Out = S, Removed = 0
    ).

strip_trailing_zeros(S, Out) :-
    string_length(S, L),
    (   L > 0,
        Last is L - 1,
        sub_string(S, Last, 1, 0, "0")
    ->  sub_string(S, 0, Last, _, Rest),
        strip_trailing_zeros(Rest, Out)
    ;   Out = S
    ).

%% exponential_form(+Digits, +NDigits, +Decpt, -Atom)
%  d0 ["." rest] "e" sign exp, exponent zero-padded to two places.
exponential_form(Digits, N, Decpt, Atom) :-
    sub_string(Digits, 0, 1, _, First),
    (   N > 1
    ->  sub_string(Digits, 1, _, 0, Rest),
        format(atom(Mant), '~w.~w', [First, Rest])
    ;   Mant = First
    ),
    Exp is Decpt - 1,
    (   Exp < 0
    ->  ESign = '-', EAbs is -Exp
    ;   ESign = '+', EAbs = Exp
    ),
    format(atom(EStr), '~|~`0t~d~2+', [EAbs]),
    format(atom(Atom), '~we~w~w', [Mant, ESign, EStr]).

%% fixed_form(+Digits, +NDigits, +Decpt, -Atom)
fixed_form(Digits, _N, Decpt, Atom) :-
    Decpt =< 0,
    !,
    Pad is -Decpt,
    zeros(Pad, Z),
    format(atom(Atom), '0.~w~w', [Z, Digits]).
fixed_form(Digits, N, Decpt, Atom) :-
    Decpt >= N,
    !,
    Pad is Decpt - N,
    zeros(Pad, Z),
    format(atom(Atom), '~w~w.0', [Digits, Z]).
fixed_form(Digits, _N, Decpt, Atom) :-
    sub_string(Digits, 0, Decpt, _, Left),
    sub_string(Digits, Decpt, _, 0, Right),
    format(atom(Atom), '~w.~w', [Left, Right]).

zeros(N, Z) :-
    length(L, N),
    maplist(=('0'), L),
    atomic_list_concat(L, Z).
