:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
%
% test_pe_number.pl - pe_number.pl against CPython repr.
%
% Run from this directory:
%   swipl -g run_tests -t halt test_pe_number.pl
%
% Every expected value below was produced by REAL PYTHON (repr of the
% float) and pasted in as a fixture, so this is a measurement against
% the spelling the sealed bundles actually use, not an assertion about
% what it ought to be.  The corpus deliberately includes the shapes
% where SWI's own ~w disagrees with Python: mantissa .0 in exponential
% form, exponent zero-padding, and the different fixed/exponential
% threshold on the large side.

:- use_module(pe_number).
:- use_module(library(plunit)).

%% py(+Float, -PythonRepr): fixtures generated by CPython.
py(0.85, '0.85').
py(0.02, '0.02').
py(0.03, '0.03').
py(0.6, '0.6').
py(-0.5, '-0.5').
py(1e-05, '1e-05').
py(1.5e-07, '1.5e-07').
py(0.0001, '0.0001').
py(1e+16, '1e+16').
py(1000000000000000.0, '1000000000000000.0').
py(123456.789, '123456.789').
py(1e+100, '1e+100').
py(2.5e-10, '2.5e-10').
py(1.0, '1.0').
py(100.0, '100.0').
py(0.1, '0.1').
py(0.0, '0.0').
py(-0.0, '-0.0').
py(3.14159265358979, '3.14159265358979').
py(1e-300, '1e-300').
py(9.87e+22, '9.87e+22').
py(-1e-05, '-1e-05').
py(0.5, '0.5').
py(0.0001, '0.0001').
py(1e+17, '1e+17').
py(1.2345678901234568e+16, '1.2345678901234568e+16').
py(-352334.4703336753, '-352334.4703336753').
py(-698301.6521509961, '-698301.6521509961').
py(301868.9460797075, '301868.9460797075').
py(-855127.4266649145, '-855127.4266649145').
py(71764.00861337851, '71764.00861337851').
py(-268622.1661748289, '-268622.1661748289').
py(-884002.1504505863, '-884002.1504505863').
py(14871.466378840501, '14871.466378840501').
py(-925008.6831160302, '-925008.6831160302').
py(-132708.6326752283, '-132708.6326752283').
py(-860289.1528507621, '-860289.1528507621').
py(-818573.9733122699, '-818573.9733122699').
py(424519.18914251396, '424519.18914251396').
py(1.2380196114964559e-06, '1.2380196114964559e-06').
py(630625.915731737, '630625.915731737').
py(947708.9424570056, '947708.9424570056').
py(5.855414226403867e-12, '5.855414226403867e-12').
py(9.7625510559292e-12, '9.7625510559292e-12').
py(5.566648979370926e-09, '5.566648979370926e-09').
py(2.8960928633167626e-09, '2.8960928633167626e-09').
py(540685.8855321425, '540685.8855321425').
py(308481824.1019344, '308481824.1019344').
py(180726.37992393746, '180726.37992393746').
py(5.712043914117922e-07, '5.712043914117922e-07').

:- begin_tests(python_repr_parity).

test(matches_python_repr, [forall(py(V, Expected))]) :-
    pe_number_atom(V, Got),
    (   Got == Expected
    ->  true
    ;   format(user_error, "~q: expected ~q got ~q~n", [V, Expected, Got]),
        fail
    ).

% The three shapes where SWI's ~w diverges, called out by name so a
% regression names itself.
test(exponential_mantissa_has_no_dot_zero) :-
    pe_number_atom(1.0e-5, A), A == '1e-05'.

test(exponent_is_zero_padded_to_two_digits) :-
    pe_number_atom(1.5e-7, A), A == '1.5e-07'.

test(large_side_threshold_matches_python) :-
    pe_number_atom(1.0e15, A), A == '1000000000000000.0',   % fixed, not exponential
    pe_number_atom(1.0e16, B), B == '1e+16'.                % exponential

% Integers pass through as integers: process_cards uses str() for
% non-floats, which the int-spelled-number golden row pins.
test(integers_pass_through) :-
    pe_number_atom(1, A), A == '1',
    pe_number_atom(10, B), B == '10',
    pe_number_atom(-3, C), C == '-3'.

% Non-finite floats are REFUSED: process_cards raises on them too, and
% inventing a spelling would put bytes on the surface the sealed
% renderer would never produce.
test(infinity_refused, error(pe_number(non_finite(_)))) :-
    X is inf,
    pe_number_atom(X, _).

test(nan_refused, error(pe_number(non_finite(_)))) :-
    X is nan,
    pe_number_atom(X, _).

test(non_number_refused, error(pe_number(not_a_number(_)))) :-
    pe_number_atom(foo, _).

:- end_tests(python_repr_parity).
