#!/bin/bash
# test_generated_scripts.sh - Ad-hoc test script for integration test outputs
#
# NOTE: This is a TEMPORARY ad-hoc test script
#
# Purpose:
#   Tests the bash scripts generated by examples/integration_test.pl
#   (products.sh, orders.sh, analyze_orders.sh, top_products.sh)
#
# Future Work:
#   A proper generated test runner should be created using the test runner
#   generation infrastructure (src/unifyweaver/core/advanced/test_runner_generator.pl)
#   as demonstrated in the advanced recursion tests.
#
# See Also:
#   - src/unifyweaver/core/advanced/test_runner_generator.pl
#   - Advanced recursion test generation workflow
#
# Usage:
#   1. Run integration test first to generate scripts:
#      KEEP_TEST_DATA=true swipl -l init.pl -g main -t halt examples/integration_test.pl
#
#   2. Run this script to test the generated outputs:
#      bash test_generated_scripts.sh
#
# Generated Scripts Location: test_output/

echo "=== Testing Generated UnifyWeaver Scripts ==="
echo
echo "NOTE: This is an ad-hoc test script."
echo "      Future versions will use test_runner_generator.pl"
echo

echo "1. CSV Source (Products):"
source test_output/products.sh && products
echo

echo "2. JSON Source (Orders):"
bash test_output/orders.sh
echo

echo "3. Python ETL Pipeline (Orders → Analysis):"
bash test_output/orders.sh | bash test_output/analyze_orders.sh
echo

echo "4. SQLite Query (Top Products):"
bash test_output/top_products.sh
echo

echo "✅ All scripts tested successfully!"
