:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% build_diff.pl -- compile resolver.pl into a WAM-C diff project (no smoke wrappers).
:- use_module('../../../src/unifyweaver/targets/wam_c_target',
              [write_wam_c_project/3]).
:- use_module(library(filesex),
              [make_directory_path/1, directory_file_path/3, copy_file/2]).

load_into_user(File, Preds) :-
    setup_call_cleanup(open(File, read, S), load_terms(S, [], Acc), close(S)),
    sort(Acc, Preds).

load_terms(S, Acc, Preds) :-
    read_term(S, T, []),
    (   T == end_of_file
    ->  Preds = Acc
    ;   T = (:- _)
    ->  load_terms(S, Acc, Preds)
    ;   pred_of_term(T, PA),
        assertz(user:T),
        load_terms(S, [PA|Acc], Preds)
    ).

pred_of_term((Head :- _), P/A) :- !, functor(Head, P, A).
pred_of_term(Head, P/A) :- functor(Head, P, A).

qualify_user(P/A, user:P/A).

% C++ include_stdlib([predsort]) compiles a general predsort/3 that uses
% call/N. WAM-C INSTR_CALL does not dispatch call/N, so a general stdlib
% copy would fail closed. resolver.pl only predsorts through cmp_ver/3
% (Debian versions); compile that specialized merge-sort instead.
predsort_helpers([
    predsort/3,
    wam_c_predsort/4,
    wam_c_sort2/4,
    wam_c_predmerge/3,
    wam_c_predmerge_ord/6
]).

assert_wam_c_predsort :-
    (   current_predicate(user:wam_c_predsort/4)
    ->  true
    ;   assertz((user:predsort(cmp_ver, L, S) :-
            length(L, N), wam_c_predsort(N, L, _, S))),
        assertz((user:wam_c_predsort(2, [X1, X2|T], T, R) :- !,
            cmp_ver(O, X1, X2), wam_c_sort2(O, X1, X2, R))),
        assertz((user:wam_c_predsort(1, [X|T], T, [X]) :- !)),
        assertz((user:wam_c_predsort(0, T, T, []) :- !)),
        assertz((user:wam_c_predsort(N, L1, L3, R) :-
            N1 is N // 2, N2 is N - N1,
            wam_c_predsort(N1, L1, L2, R1),
            wam_c_predsort(N2, L2, L3, R2),
            wam_c_predmerge(R1, R2, R))),
        assertz((user:wam_c_sort2(<, A, B, [A, B]))),
        assertz((user:wam_c_sort2(=, A, _, [A]))),
        assertz((user:wam_c_sort2(>, A, B, [B, A]))),
        assertz((user:wam_c_predmerge([], R, R) :- !)),
        assertz((user:wam_c_predmerge(R, [], R) :- !)),
        assertz((user:wam_c_predmerge([H1|T1], [H2|T2], R) :-
            cmp_ver(O, H1, H2),
            wam_c_predmerge_ord(O, H1, H2, T1, T2, R))),
        assertz((user:wam_c_predmerge_ord(<, H1, H2, T1, T2, [H1|R]) :-
            wam_c_predmerge(T1, [H2|T2], R))),
        assertz((user:wam_c_predmerge_ord(=, H1, _, T1, T2, [H1|R]) :-
            wam_c_predmerge(T1, T2, R))),
        assertz((user:wam_c_predmerge_ord(>, H1, H2, T1, T2, [H2|R]) :-
            wam_c_predmerge([H1|T1], T2, R)))
    ).

c_copy_runtime_header(Dir) :-
    module_property(wam_c_target, file(TargetFile)),
    file_directory_name(TargetFile, TargetsDir),
    directory_file_path(TargetsDir, 'wam_c_runtime/wam_runtime.h', HdrSrc),
    directory_file_path(Dir, 'wam_runtime.h', HdrDst),
    copy_file(HdrSrc, HdrDst).

write_setup_inc(Preds, OutDir) :-
    directory_file_path(OutDir, 'setup_all.inc', Path),
    setup_call_cleanup(
        open(Path, write, S),
        (   format(S, '/* Generated by build_diff.pl -- do not edit. */~n', []),
            forall(member(_:N/A, Preds),
                   format(S, 'void setup_~w_~w(WamState* state);~n', [N, A])),
            format(S, 'void setup_detected_wam_c_kernels(WamState* state);~n', []),
            format(S, 'void setup_lowered_wam_c_helpers(WamState* state);~n~n', []),
            format(S, 'static void setup_all_predicates(WamState *state) {~n', []),
            forall(member(_:N/A, Preds),
                   format(S, '    setup_~w_~w(state);~n', [N, A])),
            format(S, '    setup_detected_wam_c_kernels(state);~n', []),
            format(S, '    setup_lowered_wam_c_helpers(state);~n', []),
            format(S, '}~n', [])
        ),
        close(S)
    ).

main :-
    current_prolog_flag(argv, Argv),
    (   Argv = [Src0, Out0|_]
    ->  Src = Src0, OutDir = Out0
    ;   Argv = [Out0|_]
    ->  Src = '../resolver.pl',
        (Out0 == '.' -> OutDir = 'diff/generated' ; OutDir = Out0)
    ;   Src = '../resolver.pl',
        OutDir = 'diff/generated'
    ),
    make_directory_path(OutDir),
    load_into_user(Src, Preds0),
    assert_wam_c_predsort,
    predsort_helpers(Hs),
    append(Preds0, Hs, Preds1),
    maplist(qualify_user, Preds1, Preds),
    length(Preds, N),
    format('build_diff.pl: compiling ~w predicates from ~w~n', [N, Src]),
    write_wam_c_project(Preds,
        [no_kernels(true),
         lowered_helpers(false)],
        OutDir),
    c_copy_runtime_header(OutDir),
    write_setup_inc(Preds, OutDir),
    format('build_diff.pl: wrote WAM C diff project under ~w/~n', [OutDir]).
