// Generated by UnifyWeaver WAM-to-Rust transpilation
// Date: 2026-09-03 18:54:21

use std::fmt;
use std::ops::Deref;
use std::sync::Arc;

/// Shared argument spine: the sub-arguments of a compound term, or the
/// elements of a list — plus an offset, so that the TAIL of a list is the same
/// allocation viewed one element further along.
///
/// STRUCTURAL SHARING (see docs/WAM_RUST_STATUS.md). Terms in this runtime are
/// immutable — a variable binding lives in `WamState::bindings` keyed by the
/// variable's name, never inside the term cell — so two terms may share one
/// spine with no aliasing hazard: nothing can mutate a spine another snapshot
/// observes, and the trail restores bindings, not cells. Sharing therefore
/// needs no trail cooperation at all.
///
/// Two costs collapse because of it:
///
///  * `Value::clone` is O(1) for lists and compounds instead of a deep copy,
///    so a choice point costs O(live registers), not O(term size) — a register
///    holding the whole catalog is no longer copied per choice point.
///  * `tail()` is O(1), so walking an N-element list is O(N) instead of
///    allocating (and retaining) an N-element copy per step. That second one
///    is what the resolver's `[H|T]` recursion over the catalog does at every
///    level.
///
/// `Arc` rather than `Rc` because `WamState` must stay `Send`: the T7
/// parallel-aggregate substrate forks a machine per Rayon worker and the
/// static assertion in state.rs pins `Send` (an `Rc` inside `Value` would put
/// non-`Send` data in `regs`/`heap`/`trail`/`bindings` and break it).
///
/// `Deref<Target = [Value]>` means every read (`len`, `iter`, indexing,
/// slicing, `split_first`, `to_vec`) works on the visible window as if it were
/// a plain slice; only construction and cons go through the methods below.
#[derive(Clone, Debug)]
pub struct Args {
    spine: Arc<Vec<Value>>,
    off: usize,
}

impl Args {
    /// Take ownership of a freshly built vector as a new spine.
    #[inline]
    pub fn from_vec(items: Vec<Value>) -> Args {
        Args { spine: Arc::new(items), off: 0 }
    }

    /// The empty spine.
    #[inline]
    pub fn empty() -> Args {
        Args::from_vec(Vec::new())
    }

    /// This spine minus its first element — O(1), sharing the allocation.
    /// Panics-free: an empty spine yields an empty spine.
    #[inline]
    pub fn tail(&self) -> Args {
        let off = if self.off < self.spine.len() { self.off + 1 } else { self.off };
        Args { spine: Arc::clone(&self.spine), off }
    }

    /// This spine with `head` prepended. The visible window starts at `off`, so
    /// a slot before it may belong to another view of the same allocation and
    /// can never be written; prepending therefore copies.
    #[inline]
    pub fn cons(&self, head: Value) -> Args {
        let mut items = Vec::with_capacity(self.len() + 1);
        items.push(head);
        items.extend_from_slice(self);
        Args::from_vec(items)
    }

    /// Are these the SAME view of the same allocation? Used to detect "nothing
    /// changed" without comparing contents; `false` is always safe.
    #[inline]
    pub fn same_ref(a: &Args, b: &Args) -> bool {
        a.off == b.off && Arc::ptr_eq(&a.spine, &b.spine)
    }
}

impl Deref for Args {
    type Target = [Value];
    #[inline]
    fn deref(&self) -> &[Value] {
        &self.spine[self.off..]
    }
}

impl From<Vec<Value>> for Args {
    #[inline]
    fn from(items: Vec<Value>) -> Args {
        Args::from_vec(items)
    }
}

impl PartialEq for Args {
    #[inline]
    fn eq(&self, other: &Args) -> bool {
        Self::same_ref(self, other) || **self == **other
    }
}

/// Universal value type for the WAM runtime.
/// Mirrors the Prolog term universe used by wam_runtime.pl.
#[derive(Clone, Debug)]
pub enum Value {
    /// Atomic symbol (Prolog atom)
    Atom(String),
    /// Integer value
    Integer(i64),
    /// Floating point value
    Float(f64),
    /// Compound term: functor name + shared sub-argument spine
    Str(String, Args),
    /// List value (Prolog list), shared spine
    List(Args),
    /// Heap reference (from put_structure/put_list)
    Ref(usize),
    /// Unbound variable (e.g., _V5, _H3)
    Unbound(String),
    /// Boolean value
    Bool(bool),
    /// Uninitialized register slot -- zero-cost sentinel for the register file.
    /// Never appears in Prolog terms; only used internally by WamState.
    Uninit,
}

impl Value {
    /// First-argument index key for T9 fact tables: a type-tagged canonical
    /// string for an atomic value (atom / integer / float), or None for
    /// compound / list / unbound / ref values (which can only match via a full
    /// scan). The same function keys both the stored rows and the query arg, so
    /// a bound atomic first argument selects exactly the matching index bucket.
    pub fn fact_index_key(&self) -> Option<String> {
        match self {
            Value::Atom(s) => Some(format!("a:{}", s)),
            Value::Integer(n) => Some(format!("i:{}", n)),
            Value::Float(f) => Some(format!("f:{}", f)),
            _ => None,
        }
    }

    /// Check if this value is an unbound WAM variable.
    /// Corresponds to is_unbound_var/1 in wam_runtime.pl.
    pub fn is_unbound(&self) -> bool {
        matches!(self, Value::Unbound(_))
    }

    /// Check if this value is a number (integer or float).
    pub fn is_number(&self) -> bool {
        matches!(self, Value::Integer(_) | Value::Float(_))
    }

    /// Check if this value is a compound term.
    pub fn is_compound(&self) -> bool {
        matches!(self, Value::Str(_, _))
    }

    /// Check if this value is a list.
    pub fn is_list(&self) -> bool {
        matches!(self, Value::List(_))
    }

    /// Extract integer value, panicking if not an integer.
    pub fn as_int(&self) -> i64 {
        match self {
            Value::Integer(n) => *n,
            _ => panic!("Expected integer, got {:?}", self),
        }
    }

    /// Extract float value, coercing integers.
    pub fn as_float(&self) -> f64 {
        match self {
            Value::Float(f) => *f,
            Value::Integer(n) => *n as f64,
            _ => panic!("Expected number, got {:?}", self),
        }
    }

    /// Extract atom string, panicking if not an atom.
    pub fn as_atom(&self) -> &str {
        match self {
            Value::Atom(s) => s,
            _ => panic!("Expected atom, got {:?}", self),
        }
    }

    /// Decompose a compound term (=../2 equivalent).
    /// Returns (functor, args) or None for non-compound values.
    pub fn univ(&self) -> Option<(&str, &[Value])> {
        match self {
            Value::Str(f, args) => Some((f, args)),
            _ => None,
        }
    }

    /// Construct a compound term from functor and args.
    pub fn make_str(functor: &str, args: Vec<Value>) -> Value {
        Value::Str(functor.to_string(), Args::from_vec(args))
    }

    /// Construct a list from an owned `Vec` (structural-sharing constructor).
    /// `Value::List` itself takes the shared `Args` spine; this is the
    /// convenience form for the many sites that build a fresh vector.
    #[inline]
    pub fn list(items: Vec<Value>) -> Value {
        Value::List(Args::from_vec(items))
    }

    /// Construct a compound term from an owned functor `String` and an owned
    /// `Vec` of arguments (structural-sharing constructor).
    #[inline]
    pub fn strv(functor: String, args: Vec<Value>) -> Value {
        Value::Str(functor, Args::from_vec(args))
    }


    /// Create a new unbound variable with the given name.
    pub fn new_unbound(name: &str) -> Value {
        Value::Unbound(name.to_string())
    }
}

impl PartialEq for Value {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Value::Atom(a), Value::Atom(b)) => a == b,
            (Value::Integer(a), Value::Integer(b)) => a == b,
            (Value::Float(a), Value::Float(b)) => a == b,
            (Value::Bool(a), Value::Bool(b)) => a == b,
            (Value::Str(f1, a1), Value::Str(f2, a2)) => f1 == f2 && a1 == a2,
            (Value::List(a), Value::List(b)) => a == b,
            (Value::Ref(a), Value::Ref(b)) => a == b,
            (Value::Unbound(a), Value::Unbound(b)) => a == b,
            (Value::Uninit, Value::Uninit) => true,
            _ => false,
        }
    }
}

impl fmt::Display for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Value::Atom(s) => write!(f, "{}", s),
            Value::Integer(n) => write!(f, "{}", n),
            Value::Float(n) => write!(f, "{}", n),
            Value::Bool(b) => write!(f, "{}", b),
            Value::Str(func, args) => {
                write!(f, "{}(", func)?;
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 { write!(f, ", ")?; }
                    write!(f, "{}", arg)?;
                }
                write!(f, ")")
            }
            Value::List(items) => {
                write!(f, "[")?;
                for (i, item) in items.iter().enumerate() {
                    if i > 0 { write!(f, ", ")?; }
                    write!(f, "{}", item)?;
                }
                write!(f, "]")
            }
            Value::Ref(addr) => write!(f, "ref({})", addr),
            Value::Unbound(name) => write!(f, "{}", name),
            Value::Uninit => write!(f, "_uninit_"),
        }
    }
}
