% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (s243a)
%
% c_target.pl - C Target for UnifyWeaver
% Generates C programs for record/field processing
% Uses cJSON for JSON handling

:- encoding(utf8).

:- module(c_target, [
    compile_predicate_to_c/3,     % +Predicate, +Options, -CCode
    compile_c_pipeline/3,         % +Predicates, +Options, -CCode
    compile_facts_to_c/3,         % +Pred, +Arity, -CCode  -- NEW
    generate_makefile/2,          % +Options, -MakefileContent
    generate_cmake/2,             % +Options, -CMakeContent
    write_c_program/2,            % +CCode, +FilePath
    init_c_target/0,              % Initialize C target
    test_c_pipeline_mode/0        % Test pipeline mode
]).

:- use_module(library(lists)).

% Binding system integration
:- use_module('../core/binding_registry').

% Track required includes
:- dynamic required_c_include/1.

%% init_c_target
init_c_target :-
    retractall(required_c_include(_)).

%% clear_c_includes
clear_c_includes :-
    retractall(required_c_include(_)).

%% collect_c_include(+Include)
collect_c_include(Include) :-
    (   required_c_include(Include)
    ->  true
    ;   assertz(required_c_include(Include))
    ).

%% get_c_includes(-Includes)
get_c_includes(Includes) :-
    findall(I, required_c_include(I), Includes).

%% format_c_includes(+Includes, -FormattedStr)
format_c_includes([], "").
format_c_includes(Includes, FormattedStr) :-
    Includes \= [],
    sort(Includes, UniqueIncludes),
    findall(Formatted,
        (   member(Include, UniqueIncludes),
            format(string(Formatted), "#include ~w~n", [Include])
        ),
        FormattedList),
    atomic_list_concat(FormattedList, '', FormattedStr).

%% ============================================
%% PUBLIC API
%% ============================================

%% compile_predicate_to_c(+Predicate, +Options, -CCode)
compile_predicate_to_c(PredIndicator, Options, CCode) :-
    (   PredIndicator = _Module:Pred/Arity
    ->  true
    ;   PredIndicator = Pred/Arity
    ),
    format('=== Compiling ~w/~w to C ===~n', [Pred, Arity]),

    clear_c_includes,

    % Check mode
    (   option(generator_mode(true), Options)
    ->  format('  Mode: Generator (callback iterator)~n'),
        compile_generator_mode_c(Pred, Arity, Options, CCode)
    ;   option(pipeline_input(true), Options)
    ->  format('  Mode: Pipeline (streaming JSONL)~n'),
        compile_pipeline_mode_c(Pred, Arity, Options, CCode)
    ;   format('  Mode: Simple predicate~n'),
        compile_simple_mode_c(Pred, Arity, Options, CCode)
    ).

%% ============================================
%% COMPILE FACTS TO C
%% ============================================

compile_facts_to_c(Pred, Arity, CCode) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredCap),
    functor(Head, Pred, Arity),
    
    findall(Args, (clause(Head, true), Head =.. [_|Args]), AllFacts),
    length(AllFacts, NumFacts),
    
    (   AllFacts == []
    ->  FactEntries = "    /* No facts defined */"
    ;   findall(Entry, (
            member(Args, AllFacts),
            format_c_fact_entry(Args, Entry)
        ), Entries),
        atomic_list_concat(Entries, ',\n', FactEntries)
    ),
    
    format(string(CCode),
'/* Generated by UnifyWeaver C Target - Facts Export */
/* Predicate: ~w/~w */

#include <stdio.h>
#include <string.h>

#define NUM_~w_FACTS ~w
#define ~w_ARITY ~w

/* Facts array: ~w(arg1, arg2, ...) */
static const char* ~w_facts[NUM_~w_FACTS][~w_ARITY] = {
~w
};

/* Get all facts */
void ~w_get_all(void (*callback)(const char**, int)) {
    for (int i = 0; i < NUM_~w_FACTS; i++) {
        callback(~w_facts[i], ~w_ARITY);
    }
}

/* Check if fact exists */
int ~w_contains(const char** args) {
    for (int i = 0; i < NUM_~w_FACTS; i++) {
        int match = 1;
        for (int j = 0; j < ~w_ARITY; j++) {
            if (strcmp(~w_facts[i][j], args[j]) != 0) {
                match = 0;
                break;
            }
        }
        if (match) return 1;
    }
    return 0;
}

/* Print fact helper */
static void print_fact(const char** fact, int arity) {
    for (int i = 0; i < arity; i++) {
        printf(\"%s\", fact[i]);
        if (i < arity - 1) printf(\":\");
    }
    printf(\"\\n\");
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    ~w_get_all(print_fact);
    return 0;
}
', [PredStr, Arity, PredCap, NumFacts, PredCap, Arity, PredStr, PredStr, 
    PredCap, PredCap, FactEntries, PredStr, PredCap, PredStr, PredCap, 
    PredStr, PredCap, PredCap, PredStr, PredStr]).

format_c_fact_entry(Args, Entry) :-
    findall(Formatted, (
        member(Arg, Args),
        format(string(Formatted), '"~w"', [Arg])
    ), FormattedArgs),
    atomic_list_concat(FormattedArgs, ', ', ArgsStr),
    format(string(Entry), '    { ~w }', [ArgsStr]).

%% ============================================
%% GENERATOR MODE (Callback-based iterator)
%% ============================================

compile_generator_mode_c(Pred, Arity, _Options, CCode) :-
    collect_c_include('<stdio.h>'),
    collect_c_include('<stdlib.h>'),
    collect_c_include('<string.h>'),
    collect_c_include('"cJSON.h"'),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  GeneratorBody = "    /* No clauses - yield input unchanged */\n    callback(record, user_data);\n    return 1;"
    ;   generate_generator_body_c(Clauses, GeneratorBody)
    ),
    
    get_c_includes(IncludeList),
    format_c_includes(IncludeList, IncludesStr),
    
    format(string(CCode),
"/* Generated by UnifyWeaver C Target - Generator Mode */
/* Predicate: ~w/~w */
/* Uses callback-based iteration pattern */

~w

typedef void (*record_callback)(cJSON* record, void* user_data);

/**
 * Generator: processes record and calls callback for each result.
 * @param record Input JSON record
 * @param callback Function to call for each generated result
 * @param user_data User data passed to callback
 * @return Number of results generated
 */
int generate_~w(cJSON* record, record_callback callback, void* user_data) {
~w
}

/**
 * Process all records from JSONL stdin.
 */
void run_generator(record_callback callback, void* user_data) {
    char line[65536];
    
    while (fgets(line, sizeof(line), stdin)) {
        size_t len = strlen(line);
        if (len > 0 && line[len-1] == '\\n') line[len-1] = '\\0';
        if (strlen(line) == 0) continue;
        
        cJSON* record = cJSON_Parse(line);
        if (!record) {
            fprintf(stderr, \"JSON parse error\\n\");
            continue;
        }
        
        generate_~w(record, callback, user_data);
        cJSON_Delete(record);
    }
}

void print_result(cJSON* record, void* user_data) {
    (void)user_data;
    char* json_str = cJSON_PrintUnformatted(record);
    if (json_str) {
        printf(\"%s\\n\", json_str);
        free(json_str);
    }
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    run_generator(print_result, NULL);
    return 0;
}
", [Pred, Arity, IncludesStr, Pred, GeneratorBody, Pred]).

%% generate_generator_body_c(+Clauses, -Code)
generate_generator_body_c(Clauses, Code) :-
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_c(Name, Clauses)
    ->  partition(is_recursive_clause_c(Name), Clauses, RecClauses, BaseClauses),
        compile_generator_recursive_c(Name, BaseClauses, RecClauses, Code)
    ;   Code = "    /* Non-recursive: yield once */\n    callback(record, user_data);\n    return 1;"
    ).

compile_generator_recursive_c(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_c(BaseHead, BaseCondition)
    ;   BaseCondition = "0"
    ),
    
    format(string(Code),
"    /* Recursive generator: ~w */
    cJSON* current = cJSON_Duplicate(record, 1);
    int count = 0;
    int max_iterations = 10000;
    
    for (int i = 0; i < max_iterations; i++) {
        callback(current, user_data);
        count++;
        
        /* Check base case */
        if (~w) {
            cJSON_Delete(current);
            return count;
        }
        
        /* TODO: Transform for next iteration */
    }
    
    fprintf(stderr, \"Warning: Max iterations exceeded for ~w\\n\");
    cJSON_Delete(current);
    return count;", [Name, BaseCondition, Name]).

%% ============================================
%% PIPELINE MODE
%% ============================================

compile_pipeline_mode_c(Pred, Arity, _Options, CCode) :-
    collect_c_include('<stdio.h>'),
    collect_c_include('<stdlib.h>'),
    collect_c_include('<string.h>'),
    collect_c_include('"cJSON.h"'),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  ProcessBody = "    /* No clauses - pass through */\n    return record;"
    ;   generate_pipeline_process_c(Clauses, ProcessBody)
    ),
    
    get_c_includes(IncludeList),
    format_c_includes(IncludeList, IncludesStr),
    
    format(string(CCode),
"/* Generated by UnifyWeaver C Target - Pipeline Mode */
/* Predicate: ~w/~w */

~w

/**
 * Process a single record.
 * @param record Input JSON (takes ownership)
 * @return Processed record or NULL to filter out
 */
cJSON* process(cJSON* record) {
~w
}

/**
 * Run the pipeline: read JSONL from stdin, process, write to stdout.
 */
void run_pipeline(void) {
    char line[65536];
    
    while (fgets(line, sizeof(line), stdin)) {
        size_t len = strlen(line);
        if (len > 0 && line[len-1] == '\\n') line[len-1] = '\\0';
        if (strlen(line) == 0) continue;
        
        cJSON* record = cJSON_Parse(line);
        if (!record) {
            fprintf(stderr, \"JSON parse error: %%s\\n\", cJSON_GetErrorPtr());
            continue;
        }
        
        cJSON* result = process(record);
        if (result) {
            char* json_str = cJSON_PrintUnformatted(result);
            if (json_str) {
                printf(\"%%s\\n\", json_str);
                free(json_str);
            }
            if (result != record) cJSON_Delete(result);
        }
        cJSON_Delete(record);
    }
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    run_pipeline();
    return 0;
}
", [Pred, Arity, IncludesStr, ProcessBody]).

%% generate_pipeline_process_c(+Clauses, -Code)
generate_pipeline_process_c([], "    return record;").
generate_pipeline_process_c(Clauses, Code) :-
    Clauses \= [],
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_c(Name, Clauses)
    ->  partition(is_recursive_clause_c(Name), Clauses, RecClauses, BaseClauses),
        (   is_tail_recursive_c(Name, RecClauses)
        ->  compile_tail_recursive_c(Name, BaseClauses, RecClauses, Code)
        ;   compile_general_recursive_c(Name, BaseClauses, RecClauses, Code)
        )
    ;   findall(ClauseCode, 
            (member((H, B), Clauses), translate_clause_c(H, B, ClauseCode)),
            ClauseCodes),
        atomic_list_concat(ClauseCodes, '\n', Code)
    ).

%% ============================================
%% RECURSION DETECTION
%% ============================================

is_recursive_predicate_c(Name, Clauses) :-
    member((_, Body), Clauses),
    contains_recursive_call_c(Body, Name).

is_recursive_clause_c(Name, (_, Body)) :-
    contains_recursive_call_c(Body, Name).

is_tail_recursive_c(Name, RecClauses) :-
    member((_, Body), RecClauses),
    get_last_goal_c(Body, LastGoal),
    functor(LastGoal, Name, _).

get_last_goal_c((_, B), LastGoal) :- !, get_last_goal_c(B, LastGoal).
get_last_goal_c(Goal, Goal).

contains_recursive_call_c(Body, Name) :-
    extract_goal_c(Body, Goal),
    functor(Goal, Name, _),
    !.

extract_goal_c(Goal, Goal) :-
    compound(Goal),
    \+ Goal = (_,_),
    \+ Goal = (_;_).
extract_goal_c((A, _), Goal) :- extract_goal_c(A, Goal).
extract_goal_c((_, B), Goal) :- extract_goal_c(B, Goal).

%% ============================================
%% TAIL RECURSION (→ while loop)
%% ============================================

compile_tail_recursive_c(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_c(BaseHead, BaseCondition)
    ;   BaseCondition = "0"
    ),
    
    format(string(Code),
"    /* Tail-recursive predicate: ~w - optimized to while loop */
    cJSON* current = cJSON_Duplicate(record, 1);
    int max_iterations = 10000;
    
    for (int i = 0; i < max_iterations; i++) {
        /* Base case check */
        if (~w) {
            return current;
        }
        
        /* Recursive step: transform current */
        /* TODO: Apply transformation */
    }
    
    fprintf(stderr, \"Warning: Max iterations exceeded for ~w\\n\");
    return current;", [Name, BaseCondition, Name]).

%% ============================================
%% GENERAL RECURSION (→ explicit stack)
%% ============================================

compile_general_recursive_c(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_c(BaseHead, BaseCondition)
    ;   BaseCondition = "0"
    ),
    
    format(string(Code),
"    /* General recursive predicate: ~w - using explicit stack */
    #define MAX_STACK 1000
    cJSON* stack[MAX_STACK];
    int stack_top = 0;
    
    stack[stack_top++] = cJSON_Duplicate(record, 1);
    cJSON* result = NULL;
    
    while (stack_top > 0) {
        cJSON* current = stack[--stack_top];
        
        /* Base case */
        if (~w) {
            result = current;
            break;
        }
        
        /* Push recursive case onto stack */
        /* TODO: Compute next value and push */
        cJSON_Delete(current);
    }
    
    /* Cleanup stack */
    while (stack_top > 0) {
        cJSON_Delete(stack[--stack_top]);
    }
    
    return result ? result : cJSON_Duplicate(record, 1);", [Name, BaseCondition]).

%% ============================================
%% CLAUSE TRANSLATION
%% ============================================

translate_clause_c(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    generate_input_extraction_c(Args, InputCode),
    (   Body == true
    ->  BodyCode = "    /* Fact - no conditions */"
    ;   translate_body_c(Body, BodyCode)
    ),
    format(string(Code), "~w\n~w\n    return record;", [InputCode, BodyCode]).

generate_input_extraction_c(Args, Code) :-
    findall(Line, (
        nth0(I, Args, Arg),
        (   var(Arg)
        ->  format(string(Line), "    cJSON* arg~w = cJSON_GetObjectItem(record, \"arg~w\");", [I, I])
        ;   format(string(Line), "    /* arg~w = ~w (constant) */", [I, Arg])
        )
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

%% ============================================
%% BODY TRANSLATION
%% ============================================

translate_body_c((Goal, Rest), Code) :-
    !,
    translate_goal_c(Goal, Code1),
    translate_body_c(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_body_c(Goal, Code) :-
    translate_goal_c(Goal, Code).

translate_goal_c(>(X, Y), Code) :-
    !, expr_to_c(X, CX), expr_to_c(Y, CY),
    format(string(Code), "    if (!(~w > ~w)) return NULL;", [CX, CY]).

translate_goal_c(<(X, Y), Code) :-
    !, expr_to_c(X, CX), expr_to_c(Y, CY),
    format(string(Code), "    if (!(~w < ~w)) return NULL;", [CX, CY]).

translate_goal_c(>=(X, Y), Code) :-
    !, expr_to_c(X, CX), expr_to_c(Y, CY),
    format(string(Code), "    if (!(~w >= ~w)) return NULL;", [CX, CY]).

translate_goal_c(=<(X, Y), Code) :-
    !, expr_to_c(X, CX), expr_to_c(Y, CY),
    format(string(Code), "    if (!(~w <= ~w)) return NULL;", [CX, CY]).

translate_goal_c(=:=(X, Y), Code) :-
    !, expr_to_c(X, CX), expr_to_c(Y, CY),
    format(string(Code), "    if (~w != ~w) return NULL;", [CX, CY]).

translate_goal_c(true, "    /* true */") :- !.

translate_goal_c(Goal, Code) :-
    format(string(Code), "    /* TODO: ~w */", [Goal]).

%% ============================================
%% HELPER PREDICATES
%% ============================================

generate_base_condition_c(Head, Condition) :-
    Head =.. [_|Args],
    (   Args = [Arg|_],
        (   number(Arg)
        ->  format(string(Condition), 
                "cJSON_GetObjectItem(current, \"arg0\") && cJSON_GetObjectItem(current, \"arg0\")->valueint == ~w", [Arg])
        ;   atom(Arg)
        ->  format(string(Condition),
                "cJSON_GetObjectItem(current, \"arg0\") && strcmp(cJSON_GetObjectItem(current, \"arg0\")->valuestring, \"~w\") == 0", [Arg])
        ;   Condition = "0"
        )
    ;   Condition = "0"
    ).

expr_to_c(Expr, CExpr) :-
    (   number(Expr)
    ->  format(atom(CExpr), "~w", [Expr])
    ;   var(Expr)
    ->  format(atom(CExpr), "var_~p", [Expr])
    ;   Expr = X + Y
    ->  expr_to_c(X, CX), expr_to_c(Y, CY),
        format(atom(CExpr), "(~w + ~w)", [CX, CY])
    ;   Expr = X - Y
    ->  expr_to_c(X, CX), expr_to_c(Y, CY),
        format(atom(CExpr), "(~w - ~w)", [CX, CY])
    ;   Expr = X * Y
    ->  expr_to_c(X, CX), expr_to_c(Y, CY),
        format(atom(CExpr), "(~w * ~w)", [CX, CY])
    ;   Expr = X / Y
    ->  expr_to_c(X, CX), expr_to_c(Y, CY),
        format(atom(CExpr), "(~w / ~w)", [CX, CY])
    ;   format(atom(CExpr), "~w", [Expr])
    ).

%% ============================================
%% SIMPLE MODE
%% ============================================

compile_simple_mode_c(Pred, Arity, _Options, CCode) :-
    collect_c_include('<stdio.h>'),
    
    get_c_includes(IncludeList),
    format_c_includes(IncludeList, IncludesStr),
    
    format(string(CCode),
"/* Generated by UnifyWeaver C Target */
/* Predicate: ~w/~w */

~w

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    printf(\"Hello from ~w\\n\");
    return 0;
}
", [Pred, Arity, IncludesStr, Pred]).

%% ============================================
%% BUILD SYSTEM GENERATION
%% ============================================

generate_makefile(Options, MakefileContent) :-
    option(program_name(ProgName), Options, 'pipeline'),
    option(source_file(SourceFile), Options, 'pipeline.c'),
    
    format(string(MakefileContent),
"# Generated by UnifyWeaver C Target
CC = gcc
CFLAGS = -Wall -Wextra -O2 -std=c11
LDFLAGS = -lcjson

TARGET = ~w
SOURCES = ~w cJSON.c

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SOURCES)
\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

clean:
\trm -f $(TARGET)
", [ProgName, SourceFile]).

generate_cmake(Options, CMakeContent) :-
    option(project_name(ProjName), Options, 'UnifyWeaverPipeline'),
    option(source_file(SourceFile), Options, 'pipeline.c'),
    
    format(string(CMakeContent),
"# Generated by UnifyWeaver C Target
cmake_minimum_required(VERSION 3.10)
project(~w C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

add_executable(pipeline ~w cJSON.c)
target_link_libraries(pipeline cjson)
", [ProjName, SourceFile]).

%% ============================================
%% UTILITY PREDICATES
%% ============================================

write_c_program(CCode, FilePath) :-
    open(FilePath, write, Stream),
    write(Stream, CCode),
    close(Stream),
    format('Written C program to: ~w~n', [FilePath]).

compile_c_pipeline(_Steps, _Options, Code) :-
    Code = "/* Multi-step C pipeline - use compile_predicate_to_c for now */".

option(Option, Options, _Default) :-
    member(Option, Options), !.
option(Option, _Options, Default) :-
    Option =.. [_, Default].

%% ============================================
%% TESTS
%% ============================================

test_c_pipeline_mode :-
    format('~n=== Testing C Pipeline Mode ===~n~n'),
    
    format('Test 1: Basic pipeline generation~n'),
    compile_predicate_to_c(test_pred/2, [pipeline_input(true)], Code1),
    (   sub_atom(Code1, _, _, _, 'run_pipeline')
    ->  format('  [PASS] Generated pipeline code~n')
    ;   format('  [FAIL] Missing pipeline code~n')
    ),
    
    format('~nTest 2: cJSON usage~n'),
    (   sub_atom(Code1, _, _, _, 'cJSON')
    ->  format('  [PASS] Uses cJSON~n')
    ;   format('  [FAIL] Missing cJSON~n')
    ),
    
    format('~nTest 3: Generator mode~n'),
    compile_predicate_to_c(test_gen/2, [generator_mode(true)], Code2),
    (   sub_atom(Code2, _, _, _, 'callback')
    ->  format('  [PASS] Uses callback pattern~n')
    ;   format('  [FAIL] Missing callback~n')
    ),
    
    format('~nTest 4: Makefile generation~n'),
    generate_makefile([program_name('test_prog')], Makefile),
    (   sub_atom(Makefile, _, _, _, 'gcc')
    ->  format('  [PASS] Generated Makefile~n')
    ;   format('  [FAIL] Invalid Makefile~n')
    ),
    
    format('~nTest 5: CMake generation~n'),
    generate_cmake([project_name('TestProject')], CMake),
    (   sub_atom(CMake, _, _, _, 'cmake_minimum_required')
    ->  format('  [PASS] Generated CMakeLists.txt~n')
    ;   format('  [FAIL] Invalid CMakeLists.txt~n')
    ),
    
    format('~n=== C Pipeline Mode Tests Complete ===~n').

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(c, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_c(StepOp, CStepExpr),
    (   Arity =:= 3 ->
        format(string(Code),
'/* Generated by UnifyWeaver C Target - Tail Recursion (multifile dispatch) */
/* Predicate: ~w/~w */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int ~w(const int* items, int count) {
    int acc = 0;
    for (int i = 0; i < count; i++) {
        int item = items[i];
        acc = ~w;
    }
    return acc;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) {
        int items[1024], count = 0;
        char* token = strtok(argv[1], ",");
        while (token && count < 1024) {
            items[count++] = atoi(token);
            token = strtok(NULL, ",");
        }
        printf("%d\\n", ~w(items, count));
    }
    return 0;
}
', [PredStr, Arity, PredStr, CStepExpr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'/* Generated by UnifyWeaver C Target - Tail Recursion (binary, multifile dispatch) */
/* Predicate: ~w/~w */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int ~w(const char* items[], int count) {
    int result = 0;
    for (int i = 0; i < count; i++) { result++; }
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) {
        int count = 0;
        char* token = strtok(argv[1], ",");
        while (token) { count++; token = strtok(NULL, ","); }
        printf("%d\\n", count);
    }
    return 0;
}
', [PredStr, Arity, PredStr])
    ;   fail
    ).

step_op_to_c(arithmetic(Expr), CExpr) :- tail_expr_to_c(Expr, CExpr).
step_op_to_c(unknown, 'acc + 1').

tail_expr_to_c(_ + Const, CExpr) :- integer(Const), !, format(atom(CExpr), 'acc + ~w', [Const]).
tail_expr_to_c(_ + _, 'acc + item') :- !.
tail_expr_to_c(_ - _, 'acc - item') :- !.
tail_expr_to_c(_ * _, 'acc * item') :- !.
tail_expr_to_c(_, 'acc + 1').

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(c, PredStr, Arity, BaseClauses, _RecClauses, MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_c(PredStr, BaseClauses, MemoEnabled, Code)
    ;   linear_generic_c(PredStr, Arity, MemoEnabled, Code)
    ).

linear_fold_c(PredStr, BaseClauses, MemoEnabled, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    (   MemoEnabled = true ->
        MemoDecl = "#define MAX_MEMO 10000\nstatic int memo[MAX_MEMO];\nstatic int memo_valid[MAX_MEMO];",
        format(string(MemoCheck), '    if (n >= 0 && n < MAX_MEMO && memo_valid[n]) return memo[n];', []),
        format(string(MemoStore), '    if (n >= 0 && n < MAX_MEMO) { memo[n] = result; memo_valid[n] = 1; }', [])
    ;   MemoDecl = "/* Memoization disabled */",
        MemoCheck = '',
        MemoStore = ''
    ),
    % Extract fold
    atom_string(Pred, PredStr),
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
    partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRec, _),
    (   ActualRec = [clause(RHead, RBody)|_] ->
        RHead =.. [_, InputVar, _],
        linear_recursion:find_recursive_call(RBody, RecCall),
        RecCall =.. [_, _, AccVar],
        linear_recursion:find_last_is_expression(RBody, _ is FoldExpr),
        translate_fold_expr_c(FoldExpr, InputVar, AccVar, COp)
    ;   COp = "current * result"
    ),
    (   InputType = numeric ->
        format(string(Code),
'/* Generated by UnifyWeaver C Target - Linear Recursion (numeric, multifile dispatch) */
/* Predicate: ~w/2 */

#include <stdio.h>
#include <stdlib.h>

~w

int ~w(int n) {
~w
    if (n == ~w) return ~w;
    int result = ~w;
    for (int current = n; current >= 1; current--) {
        result = ~w;
    }
~w
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) printf("%d\\n", ~w(atoi(argv[1])));
    return 0;
}
', [PredStr, MemoDecl, PredStr, MemoCheck, BaseInput, BaseOutput, BaseOutput, COp, MemoStore, PredStr])
    ;   InputType = list ->
        % Re-extract fold with head variable for list patterns
        (   ActualRec = [clause(LRHead, LRBody)|_] ->
            linear_recursion:find_last_is_expression(LRBody, _ is LFoldExpr),
            linear_recursion:find_recursive_call(LRBody, LRecCall),
            LRecCall =.. [_, _, LAccVar],
            LRHead =.. [_, [LHeadVar|_], _],
            translate_list_fold_c(LFoldExpr, LHeadVar, LAccVar, ListCOp)
        ;   ListCOp = "result + current"
        ),
        format(string(Code),
'/* Generated by UnifyWeaver C Target - Linear Recursion (list, multifile dispatch) */
/* Predicate: ~w/2 */

#include <stdio.h>
#include <stdlib.h>

~w

int ~w(const int* lst, int len) {
    if (len == 0) return ~w;
    int result = ~w;
    for (int i = 0; i < len; i++) {
        int current = lst[i];
        result = ~w;
    }
    return result;
}

int main(int argc, char* argv[]) {
    /* Usage with list input */
    return 0;
}
', [PredStr, '/* List pattern — no memoization */', PredStr, BaseOutput, BaseOutput, ListCOp])
    ;   linear_generic_c(PredStr, 2, MemoEnabled, Code)
    ).

linear_generic_c(PredStr, Arity, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        format(string(Code),
'/* Generated by UnifyWeaver C Target - Linear Recursion (generic, multifile dispatch) */
/* Predicate: ~w/~w */

#include <stdio.h>
#include <stdlib.h>

#define MAX_MEMO 10000
static int memo[MAX_MEMO];
static int memo_valid[MAX_MEMO];

int ~w(int n) {
    if (n >= 0 && n < MAX_MEMO && memo_valid[n]) return memo[n];
    int result;
    if (n <= 0) result = 0;
    else if (n == 1) result = 1;
    else result = ~w(n - 1) + n;
    if (n >= 0 && n < MAX_MEMO) { memo[n] = result; memo_valid[n] = 1; }
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) printf("%d\\n", ~w(atoi(argv[1])));
    return 0;
}
', [PredStr, Arity, PredStr, PredStr, PredStr])
    ;   format(string(Code),
'/* Generated by UnifyWeaver C Target - Linear Recursion (generic, multifile dispatch) */
/* Predicate: ~w/~w */

#include <stdio.h>
#include <stdlib.h>

int ~w(int n) {
    int result;
    if (n <= 0) result = 0;
    else if (n == 1) result = 1;
    else result = ~w(n - 1) + n;
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) printf("%d\\n", ~w(atoi(argv[1])));
    return 0;
}
', [PredStr, Arity, PredStr, PredStr, PredStr])
    ).

translate_fold_expr_c(A * B, IV, AV, E) :- translate_c_term(A, IV, AV, AT), translate_c_term(B, IV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_fold_expr_c(A + B, IV, AV, E) :- translate_c_term(A, IV, AV, AT), translate_c_term(B, IV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_fold_expr_c(A - B, IV, AV, E) :- translate_c_term(A, IV, AV, AT), translate_c_term(B, IV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_fold_expr_c(T, IV, AV, E) :- translate_c_term(T, IV, AV, E).

translate_c_term(T, IV, _, 'current') :- T == IV, !.
translate_c_term(T, _, AV, 'result') :- T == AV, !.
translate_c_term(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_c_term(A, _, _, S) :- format(string(S), '~w', [A]).

%% translate_list_fold_c(+PrologExpr, +HeadVar, +AccVar, -CExpr)
%  Like translate_fold_expr_c but maps HeadVar → 'current' (loop variable for list element)
%  and AccVar → 'result' (accumulator variable in for loop).
translate_list_fold_c(A * B, HV, AV, E) :- translate_list_term_c(A, HV, AV, AT), translate_list_term_c(B, HV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_list_fold_c(A + B, HV, AV, E) :- translate_list_term_c(A, HV, AV, AT), translate_list_term_c(B, HV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_list_fold_c(A - B, HV, AV, E) :- translate_list_term_c(A, HV, AV, AT), translate_list_term_c(B, HV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_list_fold_c(T, HV, AV, E) :- translate_list_term_c(T, HV, AV, E).

translate_list_term_c(T, HV, _, 'current') :- T == HV, !.
translate_list_term_c(T, _, AV, 'result') :- T == AV, !.
translate_list_term_c(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_list_term_c(A, _, _, S) :- format(string(S), '~w', [A]).

% ============================================================================
% TREE RECURSION - C target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(c, _Pattern, Pred, _Arity, _UseMemo, CCode) :-
    atom_string(Pred, PredStr),
    format(string(CCode),
'/* Generated by UnifyWeaver C Target - Tree Recursion (fibonacci, multifile dispatch) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int memo[1000];
static int memo_set[1000];

int ~w(int n) {
    if (n <= 0) return 0;
    if (n == 1) return 1;
    if (n < 1000 && memo_set[n]) return memo[n];
    int result = ~w(n - 1) + ~w(n - 2);
    if (n < 1000) { memo[n] = result; memo_set[n] = 1; }
    return result;
}

int main(int argc, char *argv[]) {
    memset(memo_set, 0, sizeof(memo_set));
    if (argc >= 2) printf("%d\\n", ~w(atoi(argv[1])));
    return 0;
}
', [PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTICALL LINEAR RECURSION - C target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(c, PredStr, BaseClauses, _RecClauses, _MemoEnabled, CCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    if (n == ~w) return ~w;', [BInput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(CCode),
'/* Generated by UnifyWeaver C Target - Multicall Linear Recursion (multifile dispatch) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int memo[1000];
static int memo_set[1000];

int ~w(int n) {
~w
    if (n < 1000 && memo_set[n]) return memo[n];
    int result = ~w(n - 1) + ~w(n - 2);
    if (n < 1000) { memo[n] = result; memo_set[n] = 1; }
    return result;
}

int main(int argc, char *argv[]) {
    memset(memo_set, 0, sizeof(memo_set));
    if (argc >= 2) printf("%d\\n", ~w(atoi(argv[1])));
    return 0;
}
', [PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% DIRECT MULTI-CALL RECURSION - C target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(c, PredStr, BaseClauses, RecClause, CCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    if (input == ~w) { memo[input] = ~w; memo_set[input] = 1; return ~w; }', [BInput, BOutput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    RecClause = clause(RecHead, RecBody),
    RecHead =.. [Pred, _IV, _OV],
    extract_body_components(RecBody, Pred, Computations, RecCalls, Aggregation),
    direct_computations_c(Computations, ComputationsCode),
    direct_recursive_calls_c(RecCalls, PredStr, RecCallsCode),
    direct_aggregation_c(Aggregation, AggCode),
    format(string(CCode),
'/* Generated by UnifyWeaver C Target - Direct Multicall Recursion (multifile dispatch) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int memo[1000];
static int memo_set[1000];

int ~w(int input) {
    if (input >= 0 && input < 1000 && memo_set[input]) return memo[input];
~w
~w
~w
~w
    if (input >= 0 && input < 1000) { memo[input] = result; memo_set[input] = 1; }
    return result;
}

int main(int argc, char *argv[]) {
    memset(memo_set, 0, sizeof(memo_set));
    if (argc >= 2) printf("%d\\n", ~w(atoi(argv[1])));
    return 0;
}
', [PredStr, BaseCaseStr, ComputationsCode, RecCallsCode, AggCode, PredStr]).

direct_computations_c(Computations, Code) :-
    findall(Line, (
        member(Var is Expr, Computations),
        direct_var_to_c_name(Var, VarName),
        direct_translate_expr_c(Expr, CExpr),
        format(string(Line), '    int ~w = ~w;', [VarName, CExpr])
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

direct_recursive_calls_c(RecCalls, PredStr, Code) :-
    findall(Line, (
        member(RecCall, RecCalls),
        RecCall =.. [_Pred, ArgVar, ResultVar],
        direct_var_to_c_name(ArgVar, ArgName),
        direct_var_to_c_name(ResultVar, ResName),
        format(string(Line), '    int ~w = ~w(~w);', [ResName, PredStr, ArgName])
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

direct_aggregation_c(_ is Expr, Code) :-
    direct_translate_agg_expr_c(Expr, CExpr),
    format(string(Code), '    int result = ~w;', [CExpr]).

direct_translate_agg_expr_c(A + B, Expr) :-
    direct_var_to_c_name(A, AName), direct_var_to_c_name(B, BName),
    format(string(Expr), '~w + ~w', [AName, BName]).
direct_translate_agg_expr_c(A * B, Expr) :-
    direct_var_to_c_name(A, AName), direct_var_to_c_name(B, BName),
    format(string(Expr), '~w * ~w', [AName, BName]).

%% direct_var_to_c_name(+Var, -CName)
%  Convert Prolog variable to valid C identifier.
%  Internal var names like _G12345 become v12345 in C.
direct_var_to_c_name(Var, CName) :-
    (   var(Var) ->
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, LowerName),
        ensure_c_identifier(LowerName, CName)
    ;   atom(Var) ->
        downcase_atom(Var, LowerName),
        ensure_c_identifier(LowerName, CName)
    ;   term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, LowerName),
        ensure_c_identifier(LowerName, CName)
    ).

ensure_c_identifier(Name, ValidName) :-
    atom_chars(Name, [First|Rest]),
    (   (First = '_' ; char_type(First, digit)) ->
        atom_chars(ValidName, [v|Rest])
    ;   ValidName = Name
    ).

direct_translate_expr_c(N - K, Expr) :- var(N), integer(K), !,
    format(string(Expr), 'input - ~w', [K]).
direct_translate_expr_c(N + K, Expr) :- var(N), integer(K), K < 0, !,
    AbsK is abs(K), format(string(Expr), 'input - ~w', [AbsK]).
direct_translate_expr_c(N + K, Expr) :- var(N), integer(K), !,
    format(string(Expr), 'input + ~w', [K]).
direct_translate_expr_c(Expr, 'input') :- var(Expr), !.
direct_translate_expr_c(N, S) :- integer(N), !, format(string(S), '~w', [N]).
direct_translate_expr_c(A, S) :- format(string(S), '~w', [A]).

% ============================================================================
% MUTUAL RECURSION - C target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(c, Predicates, MemoEnabled, _MemoStrategy, CCode) :-
    length(Predicates, NumPreds),
    MemoSize is NumPreds * 1000,
    % Forward declarations
    findall(FwdDecl, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(FwdDecl), 'int ~w(int n);', [PredStr])
    ), FwdDecls),
    atomic_list_concat(FwdDecls, '\n', ForwardDecls),
    % Generate functions
    mutual_functions_c(Predicates, Predicates, MemoEnabled, 0, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    % Dispatch
    mutual_dispatch_c(Predicates, DispatchCode),
    format(string(CCode),
'/* Generated by UnifyWeaver C Target - Mutual Recursion (multifile dispatch) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int memo[~w];
static int memo_set[~w];

~w

~w

int main(int argc, char *argv[]) {
    memset(memo_set, 0, sizeof(memo_set));
~w
    return 0;
}
', [MemoSize, MemoSize, ForwardDecls, FunctionsCode, DispatchCode]).

mutual_functions_c([], _AllPreds, _MemoEnabled, _Idx, []).
mutual_functions_c([Pred/Arity|Rest], AllPreds, MemoEnabled, Idx, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    mutual_base_cases_c(BaseClauses, MemoEnabled, Idx, BaseParts),
    atomic_list_concat(BaseParts, '\n', BaseCode),
    mutual_rec_cases_c(RecClauses, MemoEnabled, Idx, RecParts),
    atomic_list_concat(RecParts, '\n', RecCode),
    (   MemoEnabled = true ->
        format(string(FuncCode),
'int ~w(int n) {
    int idx = ~w * 1000 + n;
    if (n >= 0 && n < 1000 && memo_set[idx]) return memo[idx];
~w
~w
    return 0;
}', [PredStr, Idx, BaseCode, RecCode])
    ;   format(string(FuncCode),
'int ~w(int n) {
~w
~w
    return 0;
}', [PredStr, BaseCode, RecCode])
    ),
    NextIdx is Idx + 1,
    mutual_functions_c(Rest, AllPreds, MemoEnabled, NextIdx, RestCodes).

mutual_base_cases_c([], _MemoEnabled, _Idx, []).
mutual_base_cases_c([clause(Head, true)|Rest], MemoEnabled, Idx, [Part|RestParts]) :-
    Head =.. [_Pred, Value],
    (   MemoEnabled = true ->
        format(string(Part),
'    if (n == ~w) { if (n >= 0 && n < 1000) { memo[~w * 1000 + n] = 1; memo_set[~w * 1000 + n] = 1; } return 1; }',
            [Value, Idx, Idx])
    ;   format(string(Part), '    if (n == ~w) return 1;', [Value])
    ),
    mutual_base_cases_c(Rest, MemoEnabled, Idx, RestParts).
mutual_base_cases_c([_|Rest], MemoEnabled, Idx, RestParts) :-
    mutual_base_cases_c(Rest, MemoEnabled, Idx, RestParts).

mutual_rec_cases_c([], _MemoEnabled, _Idx, []).
mutual_rec_cases_c([clause(_Head, Body)|Rest], MemoEnabled, Idx, [Part|RestParts]) :-
    extract_mutual_rec_info_c(Body, Guard, CalledPred, Step),
    atom_string(CalledPred, CalledStr),
    (   Guard = (N > Threshold), var(N) ->
        (   MemoEnabled = true ->
            format(string(Part),
'    if (n > ~w) {
        int result = ~w(n ~w);
        if (n >= 0 && n < 1000) { memo[~w * 1000 + n] = result; memo_set[~w * 1000 + n] = 1; }
        return result;
    }', [Threshold, CalledStr, Step, Idx, Idx])
        ;   format(string(Part),
'    if (n > ~w) return ~w(n ~w);', [Threshold, CalledStr, Step])
        )
    ;   (   MemoEnabled = true ->
            format(string(Part),
'    {
        int result = ~w(n ~w);
        if (n >= 0 && n < 1000) { memo[~w * 1000 + n] = result; memo_set[~w * 1000 + n] = 1; }
        return result;
    }', [CalledStr, Step, Idx, Idx])
        ;   format(string(Part), '    return ~w(n ~w);', [CalledStr, Step])
        )
    ),
    mutual_rec_cases_c(Rest, MemoEnabled, Idx, RestParts).
mutual_rec_cases_c([_|Rest], MemoEnabled, Idx, RestParts) :-
    mutual_rec_cases_c(Rest, MemoEnabled, Idx, RestParts).

extract_mutual_rec_info_c(Body, Guard, CalledPred, Step) :-
    extract_goals_from_body_c(Body, Goals),
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(Step), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(Step), '- ~w', [AbsK])
    ;   Step = "- 1"
    ).

extract_goals_from_body_c((A, B), Goals) :- !,
    extract_goals_from_body_c(A, GA),
    extract_goals_from_body_c(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body_c(true, []) :- !.
extract_goals_from_body_c(Goal, [Goal]).

mutual_dispatch_c(Predicates, Code) :-
    findall(DispLine, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(DispLine),
'    if (argc >= 3 && strcmp(argv[1], "~w") == 0) printf("%d\\n", ~w(atoi(argv[2])));',
            [PredStr, PredStr])
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).
