% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (s243a)
%
% cpp_target.pl - C++ Target for UnifyWeaver
% Generates modern C++ programs using nlohmann/json
% Supports streams, lambdas, and iterator patterns

:- encoding(utf8).

:- module(cpp_target, [
    compile_predicate_to_cpp/3,   % +Predicate, +Options, -CppCode
    compile_cpp_pipeline/3,       % +Predicates, +Options, -CppCode
    compile_facts_to_cpp/3,       % +Pred, +Arity, -CppCode  -- NEW
    generate_cmake_cpp/2,         % +Options, -CMakeContent
    write_cpp_program/2,          % +CppCode, +FilePath
    init_cpp_target/0,            % Initialize C++ target
    test_cpp_pipeline_mode/0      % Test pipeline mode
]).

:- use_module(library(lists)).

% Binding system integration
:- use_module('../core/binding_registry').
:- use_module('../core/clause_body_analysis').

% Track required includes
:- dynamic required_cpp_include/1.

%% init_cpp_target
init_cpp_target :-
    retractall(required_cpp_include(_)).

%% clear_cpp_includes
clear_cpp_includes :-
    retractall(required_cpp_include(_)).

%% collect_cpp_include(+Include)
collect_cpp_include(Include) :-
    (   required_cpp_include(Include)
    ->  true
    ;   assertz(required_cpp_include(Include))
    ).

%% get_cpp_includes(-Includes)
get_cpp_includes(Includes) :-
    findall(I, required_cpp_include(I), Includes).

%% format_cpp_includes(+Includes, -FormattedStr)
format_cpp_includes([], "").
format_cpp_includes(Includes, FormattedStr) :-
    Includes \= [],
    sort(Includes, UniqueIncludes),
    findall(Formatted,
        (   member(Include, UniqueIncludes),
            format(string(Formatted), "#include ~w~n", [Include])
        ),
        FormattedList),
    atomic_list_concat(FormattedList, '', FormattedStr).

%% ============================================
%% PUBLIC API
%% ============================================

compile_predicate_to_cpp(PredIndicator, Options, CppCode) :-
    (   PredIndicator = _Module:Pred/Arity
    ->  true
    ;   PredIndicator = Pred/Arity
    ),
    format('=== Compiling ~w/~w to C++ ===~n', [Pred, Arity]),

    clear_cpp_includes,

    % Check mode
    (   option(generator_mode(true), Options)
    ->  format('  Mode: Generator (iterator class)~n'),
        compile_generator_mode_cpp(Pred, Arity, Options, CppCode)
    ;   option(pipeline_input(true), Options)
    ->  format('  Mode: Pipeline (streaming JSONL)~n'),
        compile_pipeline_mode_cpp(Pred, Arity, Options, CppCode)
    ;   format('  Mode: Simple predicate~n'),
        compile_simple_mode_cpp(Pred, Arity, Options, CppCode)
    ).

%% ============================================
%% GENERATOR MODE (Iterator class)
%% ============================================

compile_generator_mode_cpp(Pred, Arity, _Options, CppCode) :-
    collect_cpp_include('<iostream>'),
    collect_cpp_include('<string>'),
    collect_cpp_include('<vector>'),
    collect_cpp_include('<optional>'),
    collect_cpp_include('<functional>'),
    collect_cpp_include('<nlohmann/json.hpp>'),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  GeneratorBody = "        // No clauses - yield input once\n        results.push_back(record);"
    ;   generate_generator_body_cpp(Clauses, GeneratorBody)
    ),
    
    get_cpp_includes(IncludeList),
    format_cpp_includes(IncludeList, IncludesStr),
    
    upcase_atom(Pred, PredUpper),
    
    format(string(CppCode),
"// Generated by UnifyWeaver C++ Target - Generator Mode
// Predicate: ~w/~w

~w

using json = nlohmann::json;

/**
 * Generator for ~w predicate.
 * Returns vector of results for each input.
 */
class ~wGenerator {
public:
    std::vector<json> process(const json& record) {
        std::vector<json> results;
~w
        return results;
    }
    
    /**
     * Process all records using a callback.
     */
    template<typename Callback>
    void processAll(std::istream& input, Callback callback) {
        std::string line;
        while (std::getline(input, line)) {
            if (line.empty()) continue;
            try {
                json record = json::parse(line);
                for (const auto& result : process(record)) {
                    callback(result);
                }
            } catch (const json::exception& e) {
                std::cerr << \"JSON parse error: \" << e.what() << std::endl;
            }
        }
    }
};

void runPipeline() {
    ~wGenerator generator;
    generator.processAll(std::cin, [](const json& result) {
        std::cout << result.dump() << std::endl;
    });
}

int main() {
    runPipeline();
    return 0;
}
", [Pred, Arity, IncludesStr, Pred, PredUpper, GeneratorBody, PredUpper]).

%% generate_generator_body_cpp(+Clauses, -Code)
generate_generator_body_cpp(Clauses, Code) :-
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_cpp(Name, Clauses)
    ->  partition(is_recursive_clause_cpp(Name), Clauses, RecClauses, BaseClauses),
        compile_generator_recursive_cpp(Name, BaseClauses, RecClauses, Code)
    ;   Code = "        // Non-recursive: yield once\n        results.push_back(record);"
    ).

compile_generator_recursive_cpp(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_cpp(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),
    
    format(string(Code),
"        // Recursive generator: ~w
        json current = record;
        constexpr int MAX_ITERATIONS = 10000;
        
        for (int i = 0; i < MAX_ITERATIONS; ++i) {
            results.push_back(current);
            
            // Check base case
            if (~w) {
                break;
            }
            
            // TODO: Transform for next iteration
        }", [Name, BaseCondition]).

%% ============================================
%% PIPELINE MODE
%% ============================================

compile_pipeline_mode_cpp(Pred, Arity, _Options, CppCode) :-
    collect_cpp_include('<iostream>'),
    collect_cpp_include('<string>'),
    collect_cpp_include('<optional>'),
    collect_cpp_include('<nlohmann/json.hpp>'),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  ProcessBody = "    // No clauses - pass through\n    return record;"
    ;   generate_pipeline_process_cpp(Clauses, ProcessBody)
    ),
    
    get_cpp_includes(IncludeList),
    format_cpp_includes(IncludeList, IncludesStr),
    
    format(string(CppCode),
"// Generated by UnifyWeaver C++ Target - Pipeline Mode
// Predicate: ~w/~w

~w

using json = nlohmann::json;

/**
 * Process a single record.
 * @return std::optional<json> - result or nullopt to filter out
 */
std::optional<json> process(const json& record) {
~w
}

/**
 * Run the pipeline: read JSONL from stdin, process, write to stdout.
 */
void runPipeline() {
    std::string line;
    
    while (std::getline(std::cin, line)) {
        if (line.empty()) continue;
        
        try {
            json record = json::parse(line);
            auto result = process(record);
            if (result) {
                std::cout << result->dump() << std::endl;
            }
        } catch (const json::exception& e) {
            std::cerr << \"JSON parse error: \" << e.what() << std::endl;
        }
    }
}

int main() {
    runPipeline();
    return 0;
}
", [Pred, Arity, IncludesStr, ProcessBody]).

%% generate_pipeline_process_cpp(+Clauses, -Code)
generate_pipeline_process_cpp([], "    return record;").
generate_pipeline_process_cpp(Clauses, Code) :-
    Clauses \= [],
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_cpp(Name, Clauses)
    ->  partition(is_recursive_clause_cpp(Name), Clauses, RecClauses, BaseClauses),
        (   is_tail_recursive_cpp(Name, RecClauses)
        ->  compile_tail_recursive_cpp(Name, BaseClauses, RecClauses, Code)
        ;   compile_general_recursive_cpp(Name, BaseClauses, RecClauses, Code)
        )
    ;   findall(ClauseCode, 
            (member((H, B), Clauses), translate_clause_cpp(H, B, ClauseCode)),
            ClauseCodes),
        atomic_list_concat(ClauseCodes, '\n', Code)
    ).

%% ============================================
%% RECURSION DETECTION
%% ============================================

is_recursive_predicate_cpp(Name, Clauses) :-
    member((_, Body), Clauses),
    contains_recursive_call_cpp(Body, Name).

is_recursive_clause_cpp(Name, (_, Body)) :-
    contains_recursive_call_cpp(Body, Name).

is_tail_recursive_cpp(Name, RecClauses) :-
    member((_, Body), RecClauses),
    get_last_goal_cpp(Body, LastGoal),
    functor(LastGoal, Name, _).

get_last_goal_cpp((_, B), LastGoal) :- !, get_last_goal_cpp(B, LastGoal).
get_last_goal_cpp(Goal, Goal).

contains_recursive_call_cpp(Body, Name) :-
    extract_goal_cpp(Body, Goal),
    functor(Goal, Name, _),
    !.

extract_goal_cpp(Goal, Goal) :-
    compound(Goal),
    \+ Goal = (_,_),
    \+ Goal = (_;_).
extract_goal_cpp((A, _), Goal) :- extract_goal_cpp(A, Goal).
extract_goal_cpp((_, B), Goal) :- extract_goal_cpp(B, Goal).

%% ============================================
%% TAIL RECURSION (→ while loop)
%% ============================================

compile_tail_recursive_cpp(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_cpp(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),
    
    format(string(Code),
"    // Tail-recursive predicate: ~w - optimized to loop
    json current = record;
    constexpr int MAX_ITERATIONS = 10000;
    
    for (int i = 0; i < MAX_ITERATIONS; ++i) {
        // Base case check
        if (~w) {
            return current;
        }
        
        // Recursive step: transform current
        // TODO: Apply transformation
    }
    
    std::cerr << \"Warning: Max iterations exceeded for ~w\" << std::endl;
    return current;", [Name, BaseCondition, Name]).

%% ============================================
%% GENERAL RECURSION (→ stack)
%% ============================================

compile_general_recursive_cpp(Name, BaseClauses, _RecClauses, Code) :-
    collect_cpp_include('<unordered_set>'),
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_cpp(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),

    format(string(Code),
"    // General recursive predicate: ~w - using explicit stack with visited set
    std::vector<json> stack;
    std::unordered_set<std::string> visited;
    stack.push_back(record);

    while (!stack.empty()) {
        json current = stack.back();
        stack.pop_back();

        // Cycle detection: check if current node already visited
        std::string visit_key = current.value(\"arg0\", \"\");
        if (visit_key.empty() && current.contains(\"arg0\") && current[\"arg0\"].is_number()) {
            visit_key = std::to_string(current[\"arg0\"].get<int>());
        }
        if (visited.count(visit_key)) {
            continue;
        }
        visited.insert(visit_key);

        // Base case
        if (~w) {
            return current;
        }

        // Push recursive case onto stack
        // TODO: Compute next value and push
    }

    return record;", [Name, BaseCondition]).

%% ============================================
%% CLAUSE TRANSLATION
%% ============================================

translate_clause_cpp(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    generate_input_extraction_cpp(Args, InputCode),
    (   Body == true
    ->  BodyCode = "    // Fact - no conditions"
    ;   translate_body_cpp(Body, BodyCode)
    ),
    format(string(Code), "~w\n~w\n    return record;", [InputCode, BodyCode]).

generate_input_extraction_cpp(Args, Code) :-
    findall(Line, (
        nth0(I, Args, Arg),
        (   var(Arg)
        ->  format(string(Line), "    auto arg~w = record.value(\"arg~w\", json{});", [I, I])
        ;   format(string(Line), "    // arg~w = ~w (constant)", [I, Arg])
        )
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

%% ============================================
%% BODY TRANSLATION
%% ============================================

translate_body_cpp((Goal, Rest), Code) :-
    !,
    translate_goal_cpp(Goal, Code1),
    translate_body_cpp(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_body_cpp(Goal, Code) :-
    translate_goal_cpp(Goal, Code).

translate_goal_cpp(>(X, Y), Code) :-
    !, expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
    format(string(Code), "    if (!(~w > ~w)) return std::nullopt;", [CX, CY]).

translate_goal_cpp(<(X, Y), Code) :-
    !, expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
    format(string(Code), "    if (!(~w < ~w)) return std::nullopt;", [CX, CY]).

translate_goal_cpp(>=(X, Y), Code) :-
    !, expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
    format(string(Code), "    if (!(~w >= ~w)) return std::nullopt;", [CX, CY]).

translate_goal_cpp(=<(X, Y), Code) :-
    !, expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
    format(string(Code), "    if (!(~w <= ~w)) return std::nullopt;", [CX, CY]).

translate_goal_cpp(=:=(X, Y), Code) :-
    !, expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
    format(string(Code), "    if (~w != ~w) return std::nullopt;", [CX, CY]).

translate_goal_cpp(true, "    // true") :- !.

translate_goal_cpp(Goal, Code) :-
    format(string(Code), "    // TODO: ~w", [Goal]).

%% ============================================
%% HELPER PREDICATES
%% ============================================

generate_base_condition_cpp(Head, Condition) :-
    Head =.. [_|Args],
    (   Args = [Arg|_],
        (   number(Arg)
        ->  format(string(Condition), "current.value(\"arg0\", 0) == ~w", [Arg])
        ;   atom(Arg)
        ->  format(string(Condition), "current.value(\"arg0\", \"\") == \"~w\"", [Arg])
        ;   Condition = "false"
        )
    ;   Condition = "false"
    ).

expr_to_cpp(Expr, CppExpr) :-
    (   number(Expr)
    ->  format(atom(CppExpr), "~w", [Expr])
    ;   var(Expr)
    ->  format(atom(CppExpr), "var_~p", [Expr])
    ;   Expr = X + Y
    ->  expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
        format(atom(CppExpr), "(~w + ~w)", [CX, CY])
    ;   Expr = X - Y
    ->  expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
        format(atom(CppExpr), "(~w - ~w)", [CX, CY])
    ;   Expr = X * Y
    ->  expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
        format(atom(CppExpr), "(~w * ~w)", [CX, CY])
    ;   Expr = X / Y
    ->  expr_to_cpp(X, CX), expr_to_cpp(Y, CY),
        format(atom(CppExpr), "(~w / ~w)", [CX, CY])
    ;   format(atom(CppExpr), "~w", [Expr])
    ).

%% ============================================
%% SIMPLE MODE
%% ============================================

% Try native clause body lowering first
compile_simple_mode_cpp(Pred, Arity, _Options, CppCode) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    Clauses \= [],
    native_cpp_clause_body(Pred/Arity, Clauses, FuncBody),
    !,
    atom_string(Pred, PredStr),
    Arity1 is Arity - 1,
    build_cpp_arg_list(Arity1, ArgList),
    format(string(CppCode),
'// Generated by UnifyWeaver C++ Target - Native Clause Lowering
// Predicate: ~w/~w

#include <iostream>
#include <string>
#include <stdexcept>

std::string ~w(~w) {
~w
}

int main() {
    std::cout << ~w(0) << std::endl;
    return 0;
}
', [PredStr, Arity, PredStr, ArgList, FuncBody, PredStr]).

% Fallback to existing stub
compile_simple_mode_cpp(Pred, Arity, _Options, CppCode) :-
    collect_cpp_include('<iostream>'),

    get_cpp_includes(IncludeList),
    format_cpp_includes(IncludeList, IncludesStr),

    format(string(CppCode),
"// Generated by UnifyWeaver C++ Target
// Predicate: ~w/~w

~w

int main() {
    std::cout << \"Hello from ~w\" << std::endl;
    return 0;
}
", [Pred, Arity, IncludesStr, Pred]).

%% ============================================
%% COMPILE FACTS TO C++
%% ============================================

compile_facts_to_cpp(Pred, Arity, CppCode) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    
    findall(Args, (clause(Head, true), Head =.. [_|Args]), AllFacts),
    
    (   AllFacts == []
    ->  FactEntries = "    // No facts defined"
    ;   findall(Entry, (
            member(Args, AllFacts),
            format_cpp_fact_entry(Args, Entry)
        ), Entries),
        atomic_list_concat(Entries, ',\n', FactEntries)
    ),
    
    format(string(CppCode),
'// Generated by UnifyWeaver C++ Target - Facts Export
// Predicate: ~w/~w

#include <iostream>
#include <string>
#include <vector>
#include <array>
#include <algorithm>

namespace ~w {

constexpr size_t ARITY = ~w;
using Fact = std::array<std::string, ARITY>;

inline const std::vector<Fact> facts = {
~w
};

inline const std::vector<Fact>& getAll() { return facts; }

template<typename... Args>
bool contains(Args&&... args) {
    Fact target = {std::forward<Args>(args)...};
    return std::find(facts.begin(), facts.end(), target) != facts.end();
}

inline void printAll() {
    for (const auto& fact : facts) {
        for (size_t i = 0; i < ARITY; ++i) {
            std::cout << fact[i];
            if (i < ARITY - 1) std::cout << \":";
        }
        std::cout << std::endl;
    }
}

} // namespace ~w

int main() {
    ~w::printAll();
    return 0;
}
', [PredStr, Arity, PredStr, Arity, FactEntries, PredStr, PredStr]).

format_cpp_fact_entry(Args, Entry) :-
    findall(Formatted, (
        member(Arg, Args),
        format(string(Formatted), '"~w"', [Arg])
    ), FormattedArgs),
    atomic_list_concat(FormattedArgs, ', ', ArgsStr),
    format(string(Entry), '    {~w}', [ArgsStr]).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_cpp_arg_list(+N, -ArgList)
build_cpp_arg_list(0, "") :- !.
build_cpp_arg_list(N, ArgList) :-
    findall(ArgDecl, (
        between(1, N, I),
        format(string(ArgDecl), 'int arg~w', [I])
    ), ArgDecls),
    atomic_list_concat(ArgDecls, ', ', ArgList).

%% native_cpp_clause_body(+PredSpec, +Clauses, -Code)

% Single clause
native_cpp_clause_body(PredSpec, [Head-Body], Code) :-
    native_cpp_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !,
    (   Condition == "true"
    ->  format(string(Code), '    return ~w;', [ClauseCode])
    ;   format(string(Code),
'    if (~w) {
        return ~w;
    }
    throw std::runtime_error("No matching clause for ~w");', [Condition, ClauseCode, PredSpec])
    ).

% Multi-clause → if/else if/else
native_cpp_clause_body(PredSpec, Clauses, Code) :-
    Clauses = [_|[_|_]],
    maplist(native_cpp_clause_pair(PredSpec), Clauses, Branches),
    Branches \= [],
    branches_to_cpp_if_chain(Branches, PredSpec, Code).

native_cpp_clause_pair(PredSpec, Head-Body, branch(Condition, ClauseCode)) :-
    native_cpp_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !.

%% native_cpp_clause(+PredSpec, +Head, +Body, -Condition, -Code)
native_cpp_clause(_PredSpec, Head, Body, Condition, Code) :-
    Head =.. [_Pred|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputHeadArgs, [OutputHeadArg], HeadArgs),
        cpp_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ;   OutputHeadArg = _,
        cpp_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ),
    normalize_goals(Body, Goals),
    (   Goals == []
    ->  cpp_resolve_value(VarMap, OutputHeadArg, Code),
        GoalConditions = []
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
            maplist(cpp_guard_condition(VarMap), GuardGoals, GoalConditions),
            (   OutputGoals == []
            ->  cpp_literal(OutputHeadArg, Code)
            ;   cpp_output_goals(OutputGoals, VarMap, Code)
            )
        ;   native_cpp_goal_sequence(Goals, VarMap, GoalConditions, Code)
        )
    ),
    append(HeadConditions, GoalConditions, AllConditions),
    combine_cpp_conditions(AllConditions, Condition).

%% cpp_head_conditions(+HeadArgs, +Index, +Arity, -Conditions)
cpp_head_conditions([], _, _, []).
cpp_head_conditions([_], _, Arity, []) :- Arity > 1, !.
cpp_head_conditions([HeadArg|Rest], Index, Arity, Conditions) :-
    (   var(HeadArg)
    ->  Conditions = RestConditions
    ;   format(string(ArgName), 'arg~w', [Index]),
        cpp_literal(HeadArg, Literal),
        format(string(Cond), '~w == ~w', [ArgName, Literal]),
        Conditions = [Cond|RestConditions]
    ),
    NextIndex is Index + 1,
    cpp_head_conditions(Rest, NextIndex, Arity, RestConditions).

%% native_cpp_goal_sequence(+Goals, +VarMap, -Conditions, -Code)
%  Uses classify_goal_sequence for advanced pattern detection.
%  Falls back to clause_guard_output_split if classification fails.
native_cpp_goal_sequence(Goals, VarMap, Conditions, Code) :-
    classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
    ClassifiedGoals \= [],
    cpp_render_classified_goals(ClassifiedGoals, VarMap, Conditions, Lines),
    Lines \= [],
    atomic_list_concat(Lines, '\n', Code),
    !.
native_cpp_goal_sequence(Goals, VarMap, Conditions, Code) :-
    clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
    maplist(cpp_guard_condition(VarMap), GuardGoals, Conditions),
    cpp_output_goals(OutputGoals, VarMap, Code).

%% cpp_render_classified_goals(+ClassifiedGoals, +VarMap, -Conditions, -Lines)
cpp_render_classified_goals([], _VarMap, [], []).
cpp_render_classified_goals([Classified], VarMap, Conds, Lines) :-
    !,
    cpp_render_classified_last(Classified, VarMap, Conds, Lines).
%% Guarded tail: output followed by guard(s)
cpp_render_classified_goals([output(Goal, _, _)|Rest], VarMap, [], Lines) :-
    Rest = [guard(_, _)|_],
    !,
    cpp_output_goal(Goal, VarMap, AssignLine, VarMap1),
    cpp_collect_trailing_guards(Rest, VarMap1, GuardGoals, _Remaining),
    maplist(cpp_guard_condition(VarMap1), GuardGoals, GuardConds),
    atomic_list_concat(GuardConds, ' && ', GuardExpr),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMap1, OutName)
    ->  true
    ;   OutName = "_"
    ),
    format(string(IfLine), '    if (~w) {', [GuardExpr]),
    format(string(RetLine), '        return ~w;', [OutName]),
    CloseLine = '    }',
    Lines = [AssignLine, IfLine, RetLine, CloseLine].
cpp_render_classified_goals([Classified|Rest], VarMap, Conds, Lines) :-
    cpp_render_classified_mid(Classified, VarMap, MidConds, MidLines, VarMap1),
    cpp_render_classified_goals(Rest, VarMap1, RestConds, RestLines),
    append(MidConds, RestConds, Conds),
    append(MidLines, RestLines, Lines).

%% cpp_render_classified_mid(+Classified, +VarMap, -Conds, -Lines, -VarMapOut)
cpp_render_classified_mid(guard(Goal, _), VarMap, [Cond], [], VarMap) :-
    cpp_guard_condition(VarMap, Goal, Cond).
cpp_render_classified_mid(output(Goal, _, _), VarMap0, [], [Line], VarMapOut) :-
    cpp_output_goal(Goal, VarMap0, Line, VarMapOut).
cpp_render_classified_mid(output_ite(If, Then, Else, _SharedVars), VarMap0, [], Lines, VarMap0) :-
    cpp_guard_condition(VarMap0, If, Cond),
    cpp_branch_value(Then, VarMap0, ThenExpr),
    cpp_branch_value(Else, VarMap0, ElseExpr),
    format(string(IfLine), '    if (~w) {', [Cond]),
    format(string(ThenLine), '        return ~w;', [ThenExpr]),
    ElseLine = '    } else {',
    format(string(ElseRetLine), '        return ~w;', [ElseExpr]),
    CloseLine = '    }',
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine, CloseLine].
cpp_render_classified_mid(passthrough(Goal), VarMap0, [], [Line], VarMapOut) :-
    cpp_output_goal(Goal, VarMap0, Line, VarMapOut).
cpp_render_classified_mid(_, VarMap, [], [], VarMap).

%% cpp_render_classified_last(+Classified, +VarMap, -Conds, -Lines)
cpp_render_classified_last(guard(Goal, _), VarMap, [Cond], []) :-
    cpp_guard_condition(VarMap, Goal, Cond).
cpp_render_classified_last(output(Goal, _, _), VarMap, [], Lines) :-
    cpp_classified_output_last(Goal, VarMap, Lines).
cpp_render_classified_last(output_ite(If, Then, Else, _), VarMap, [], Lines) :-
    cpp_guard_condition(VarMap, If, Cond),
    cpp_branch_value(Then, VarMap, ThenExpr),
    cpp_branch_value(Else, VarMap, ElseExpr),
    format(string(IfLine), '    if (~w) {', [Cond]),
    format(string(ThenLine), '        return ~w;', [ThenExpr]),
    ElseLine = '    } else {',
    format(string(ElseRetLine), '        return ~w;', [ElseExpr]),
    CloseLine = '    }',
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine, CloseLine].
cpp_render_classified_last(output_disj(Alternatives, _SharedVars), VarMap, [], Lines) :-
    cpp_disj_if_chain(Alternatives, VarMap, Lines).
cpp_render_classified_last(passthrough(Goal), VarMap, [], Lines) :-
    cpp_classified_output_last(Goal, VarMap, Lines).
cpp_render_classified_last(_, _, [], []).

%% cpp_classified_output_last(+Goal, +VarMap, -Lines)
%%  Wrap a single output goal as lines for classified rendering.
cpp_classified_output_last(Goal, VarMap, [Line]) :-
    cpp_output_goal(Goal, VarMap, AssignLine, VarMapOut),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMapOut, OutName)
    ->  format(string(Line), '~w\n    return ~w;', [AssignLine, OutName])
    ;   Line = AssignLine
    ).
cpp_classified_output_last(Goal, VarMap, [Line]) :-
    cpp_branch_value(Goal, VarMap, Expr),
    format(string(Line), '    return ~w;', [Expr]).

%% cpp_collect_trailing_guards(+ClassifiedGoals, +VarMap, -GuardGoals, -Remaining)
cpp_collect_trailing_guards([guard(Goal, _)|Rest], VarMap, [Goal|Guards], Remaining) :-
    !, cpp_collect_trailing_guards(Rest, VarMap, Guards, Remaining).
cpp_collect_trailing_guards(Remaining, _, [], Remaining).

%% cpp_disj_if_chain(+Alternatives, +VarMap, -Lines)
cpp_disj_if_chain([], _, []).
cpp_disj_if_chain([Alt], VarMap, [ElseLine, RetLine, CloseLine]) :-
    !,
    cpp_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    } else {',
    format(string(RetLine), '        return ~w;', [ValExpr]),
    CloseLine = '    }'.
cpp_disj_if_chain([Alt|Rest], VarMap, Lines) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(cpp_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = "true"
    ),
    cpp_branch_value(Alt, VarMap, ValExpr),
    format(string(IfLine), '    if (~w) {', [CondExpr]),
    format(string(RetLine), '        return ~w;', [ValExpr]),
    cpp_disj_elif_chain(Rest, VarMap, RestLines),
    append([IfLine, RetLine], RestLines, Lines).

cpp_disj_elif_chain([], _, []).
cpp_disj_elif_chain([Alt], VarMap, [ElseLine, RetLine, CloseLine]) :-
    !,
    cpp_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    } else {',
    format(string(RetLine), '        return ~w;', [ValExpr]),
    CloseLine = '    }'.
cpp_disj_elif_chain([Alt|Rest], VarMap, [ElifLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(cpp_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = "true"
    ),
    cpp_branch_value(Alt, VarMap, ValExpr),
    format(string(ElifLine), '    } else if (~w) {', [CondExpr]),
    format(string(RetLine), '        return ~w;', [ValExpr]),
    cpp_disj_elif_chain(Rest, VarMap, RestLines).

%% cpp_guard_condition(+VarMap, +Goal, -Condition)
cpp_guard_condition(VarMap, _Module:Goal, Condition) :-
    !, cpp_guard_condition(VarMap, Goal, Condition).
cpp_guard_condition(VarMap, Goal, Condition) :-
    compound(Goal),
    Goal =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    cpp_expr(Left, VarMap, CLeft),
    cpp_expr(Right, VarMap, CRight),
    cpp_op(StdOp, COp),
    format(string(Condition), '~w ~w ~w', [CLeft, COp, CRight]).

%% cpp_output_goals(+Goals, +VarMap, -Code)
cpp_output_goals([], _VarMap, '"error"') :- !.
cpp_output_goals([Goal], VarMap, Code) :-
    !, cpp_output_goal_last(Goal, VarMap, Code).
cpp_output_goals([Goal|Rest], VarMap0, Code) :-
    cpp_output_goal(Goal, VarMap0, _Line, VarMap1),
    cpp_output_goals(Rest, VarMap1, Code).

%% cpp_output_goal_last — produce the return expression
cpp_output_goal_last(_Module:Goal, VarMap, Code) :-
    !, cpp_output_goal_last(Goal, VarMap, Code).
cpp_output_goal_last(Goal, VarMap, Code) :-
    if_then_else_goal(Goal, IfGoal, ThenGoal, ElseGoal),
    !,
    cpp_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap, Code).
cpp_output_goal_last(=(Var, Expr), VarMap, Code) :-
    var(Var), !,
    cpp_expr(Expr, VarMap, Code).
cpp_output_goal_last(is(Var, Expr), VarMap, Code) :-
    var(Var), !,
    cpp_expr(Expr, VarMap, Code).

%% cpp_output_goal — produce an assignment (not used as return)
cpp_output_goal(_Module:Goal, VarMap0, Line, VarMapOut) :-
    !, cpp_output_goal(Goal, VarMap0, Line, VarMapOut).
cpp_output_goal(=(Var, Expr), VarMap0, Line, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    cpp_expr(Expr, VarMap0, CExpr),
    format(string(Line), 'int ~w = ~w;', [VarName, CExpr]).
cpp_output_goal(is(Var, Expr), VarMap0, Line, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    cpp_expr(Expr, VarMap0, CExpr),
    format(string(Line), 'int ~w = ~w;', [VarName, CExpr]).

%% cpp_if_then_else_output — generate ternary or if/else
cpp_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap, Code) :-
    flatten_cpp_if_branches(IfGoal, ThenGoal, ElseGoal, Branches, DefaultGoal),
    cpp_branches_to_ternary(Branches, DefaultGoal, VarMap, Code).

flatten_cpp_if_branches(If, Then, Else, [branch(If, Then)|RestBranches], Default) :-
    if_then_else_goal(Else, If2, Then2, Else2),
    !,
    flatten_cpp_if_branches(If2, Then2, Else2, RestBranches, Default).
flatten_cpp_if_branches(If, Then, Else, [branch(If, Then)], Else).

cpp_branches_to_ternary([branch(If, Then)], DefaultGoal, VarMap, Code) :-
    !,
    cpp_guard_condition(VarMap, If, IfCond),
    cpp_branch_value(Then, VarMap, ThenVal),
    cpp_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Code), '(~w) ? ~w : ~w', [IfCond, ThenVal, ElseVal]).
cpp_branches_to_ternary([branch(If, Then)|Rest], DefaultGoal, VarMap, Code) :-
    cpp_guard_condition(VarMap, If, IfCond),
    cpp_branch_value(Then, VarMap, ThenVal),
    cpp_branches_to_ternary(Rest, DefaultGoal, VarMap, ElseCode),
    format(string(Code), '(~w) ? ~w : ~w', [IfCond, ThenVal, ElseCode]).

%% cpp_branch_value — extract result value from a branch
cpp_branch_value(_Module:Goal, VarMap, Value) :-
    !, cpp_branch_value(Goal, VarMap, Value).
cpp_branch_value(Goal, VarMap, Value) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    cpp_guard_condition(VarMap, If, Cond),
    cpp_branch_value(Then, VarMap, ThenVal),
    cpp_branch_value(Else, VarMap, ElseVal),
    format(string(Value), '(~w) ? ~w : ~w', [Cond, ThenVal, ElseVal]).
cpp_branch_value((A, B), VarMap, Value) :-
    !,
    normalize_goals((A, B), Goals),
    last(Goals, LastGoal),
    cpp_branch_value(LastGoal, VarMap, Value).
cpp_branch_value(=(_, Expr), VarMap, Value) :-
    !, cpp_expr(Expr, VarMap, Value).
cpp_branch_value(is(_, Expr), VarMap, Value) :-
    !, cpp_expr(Expr, VarMap, Value).
cpp_branch_value(Goal, VarMap, Value) :-
    cpp_expr(Goal, VarMap, Value).

% ============================================================================
% MULTIFILE HOOKS — Register C++ renderers for shared compile_expression
% ============================================================================

clause_body_analysis:render_output_goal(cpp, Goal, VarMap, Line, VarName, VarMapOut) :-
    cpp_output_goal(Goal, VarMap, Line, VarMapOut),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMapOut, VarName)
    ->  true
    ;   VarName = "_"
    ).

clause_body_analysis:render_guard_condition(cpp, Goal, VarMap, CondStr) :-
    cpp_guard_condition(VarMap, Goal, CondStr).

clause_body_analysis:render_branch_value(cpp, Branch, VarMap, ExprStr) :-
    cpp_branch_value(Branch, VarMap, ExprStr).

clause_body_analysis:render_ite_block(cpp, Cond, ThenLines, ElseLines, Indent, _ReturnVars, Lines) :-
    format(string(IfLine), '~wif (~w) {', [Indent, Cond]),
    cpp_indent_lines(ThenLines, Indent, IndentedThen),
    format(string(CloseThen), '~w}', [Indent]),
    (   ElseLines \= []
    ->  format(string(ElseLine), '~w} else {', [Indent]),
        cpp_indent_lines(ElseLines, Indent, IndentedElse),
        format(string(CloseElse), '~w}', [Indent]),
        append([IfLine|IndentedThen], [ElseLine|IndentedElse], PreClose),
        append(PreClose, [CloseElse], Lines)
    ;   append([IfLine|IndentedThen], [CloseThen], Lines)
    ).

cpp_indent_lines([], _, []).
cpp_indent_lines([Line|Rest], Indent, [Indented|RestIndented]) :-
    format(string(Indented), '~w    ~w', [Indent, Line]),
    cpp_indent_lines(Rest, Indent, RestIndented).

%% cpp_expr — convert Prolog expression to C++ syntax
cpp_expr(Var, VarMap, CExpr) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  CExpr = Name
    ;   term_string(Var, CExpr)
    ).
cpp_expr(Expr, VarMap, CExpr) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    cpp_expr(Left, VarMap, CLeft),
    cpp_expr(Right, VarMap, CRight),
    cpp_op(StdOp, COp),
    format(string(CExpr), '(~w ~w ~w)', [CLeft, COp, CRight]).
cpp_expr(-Expr, VarMap, CExpr) :-
    !,
    cpp_expr(Expr, VarMap, Inner),
    format(string(CExpr), '(-~w)', [Inner]).
cpp_expr(abs(Expr), VarMap, CExpr) :-
    !,
    cpp_expr(Expr, VarMap, Inner),
    format(string(CExpr), 'std::abs(~w)', [Inner]).
cpp_expr(Atom, _VarMap, CExpr) :-
    atom(Atom), !,
    cpp_literal(Atom, CExpr).
cpp_expr(Number, _VarMap, CExpr) :-
    number(Number), !,
    format(string(CExpr), '~w', [Number]).
cpp_expr(String, _VarMap, CExpr) :-
    string(String), !,
    format(string(CExpr), '"~w"', [String]).

%% cpp_literal — convert Prolog value to C++ literal
cpp_literal(Value, '""') :- var(Value), !.
cpp_literal(true, 'std::string("true")') :- !.
cpp_literal(false, 'std::string("false")') :- !.
cpp_literal(Value, CppLiteral) :-
    number(Value), !,
    format(string(CppLiteral), 'std::to_string(~w)', [Value]).
cpp_literal(Value, CppLiteral) :-
    atom(Value), !,
    format(string(CppLiteral), 'std::string("~w")', [Value]).
cpp_literal(Value, CppLiteral) :-
    string(Value), !,
    format(string(CppLiteral), 'std::string("~w")', [Value]).
cpp_literal(Value, CppLiteral) :-
    term_string(Value, S),
    format(string(CppLiteral), 'std::string("~w")', [S]).

%% cpp_resolve_value — resolve variable or constant to C++ expression
cpp_resolve_value(VarMap, Var, CExpr) :-
    var(Var), !,
    lookup_var(Var, VarMap, CExpr).
cpp_resolve_value(_VarMap, Value, CExpr) :-
    cpp_literal(Value, CExpr).

%% cpp_op — map standard operator to C++ syntax
cpp_op('>', '>').
cpp_op('<', '<').
cpp_op('>=', '>=').
cpp_op('<=', '<=').
cpp_op('==', '==').
cpp_op('!=', '!=').
cpp_op('+', '+').
cpp_op('-', '-').
cpp_op('*', '*').
cpp_op('/', '/').
cpp_op('%', '%').
cpp_op('&&', '&&').
cpp_op('||', '||').

%% combine_cpp_conditions — join conditions with &&
combine_cpp_conditions([], "true") :- !.
combine_cpp_conditions([Condition], Condition) :- !.
combine_cpp_conditions(Conditions, Combined) :-
    atomic_list_concat(Conditions, ' && ', Combined).

%% branches_to_cpp_if_chain — build C++ if/else if/else chain
branches_to_cpp_if_chain(Branches, PredSpec, Code) :-
    branches_to_cpp_if_lines(Branches, PredSpec, Lines),
    atomic_list_concat(Lines, '\n', Code).

branches_to_cpp_if_lines([branch(Condition, ClauseCode)], PredSpec, [IfLine, RetLine, ElseLine, ErrLine, CloseLine]) :-
    !,
    format(string(IfLine), '    if (~w) {', [Condition]),
    format(string(RetLine), '        return ~w;', [ClauseCode]),
    ElseLine = '    } else {',
    format(string(ErrLine), '        throw std::runtime_error("No matching clause for ~w");', [PredSpec]),
    CloseLine = '    }'.
branches_to_cpp_if_lines([branch(Condition, ClauseCode)|Rest], PredSpec, [IfLine, RetLine|RestLines]) :-
    format(string(IfLine), '    if (~w) {', [Condition]),
    format(string(RetLine), '        return ~w;', [ClauseCode]),
    branches_to_cpp_elif_lines(Rest, PredSpec, RestLines).

branches_to_cpp_elif_lines([branch(Condition, ClauseCode)], PredSpec, [ElifLine, RetLine, ElseLine, ErrLine, CloseLine]) :-
    !,
    format(string(ElifLine), '    } else if (~w) {', [Condition]),
    format(string(RetLine), '        return ~w;', [ClauseCode]),
    ElseLine = '    } else {',
    format(string(ErrLine), '        throw std::runtime_error("No matching clause for ~w");', [PredSpec]),
    CloseLine = '    }'.
branches_to_cpp_elif_lines([branch(Condition, ClauseCode)|Rest], PredSpec, [ElifLine, RetLine|RestLines]) :-
    format(string(ElifLine), '    } else if (~w) {', [Condition]),
    format(string(RetLine), '        return ~w;', [ClauseCode]),
    branches_to_cpp_elif_lines(Rest, PredSpec, RestLines).

%% ============================================
%% BUILD SYSTEM GENERATION
%% ============================================

generate_cmake_cpp(Options, CMakeContent) :-
    option(project_name(ProjName), Options, 'UnifyWeaverCppPipeline'),
    option(source_file(SourceFile), Options, 'pipeline.cpp'),
    
    format(string(CMakeContent),
"# Generated by UnifyWeaver C++ Target
cmake_minimum_required(VERSION 3.14)
project(~w CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Fetch nlohmann/json
include(FetchContent)
FetchContent_Declare(
    json
    URL https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz
)
FetchContent_MakeAvailable(json)

add_executable(pipeline ~w)
target_link_libraries(pipeline PRIVATE nlohmann_json::nlohmann_json)
", [ProjName, SourceFile]).

%% ============================================
%% UTILITY PREDICATES
%% ============================================

write_cpp_program(CppCode, FilePath) :-
    open(FilePath, write, Stream),
    write(Stream, CppCode),
    close(Stream),
    format('Written C++ program to: ~w~n', [FilePath]).

compile_cpp_pipeline(_Steps, _Options, Code) :-
    Code = "// Multi-step C++ pipeline - use compile_predicate_to_cpp for now".

option(Option, Options, _Default) :-
    member(Option, Options), !.
option(Option, _Options, Default) :-
    Option =.. [_, Default].

upcase_atom(Atom, Upper) :-
    atom_codes(Atom, Codes),
    maplist(upcase_code, Codes, UpperCodes),
    atom_codes(Upper, UpperCodes).

upcase_code(C, U) :-
    (   C >= 97, C =< 122
    ->  U is C - 32
    ;   U = C
    ).

%% ============================================
%% TESTS
%% ============================================

test_cpp_pipeline_mode :-
    format('~n=== Testing C++ Pipeline Mode ===~n~n'),
    
    format('Test 1: Basic pipeline generation~n'),
    compile_predicate_to_cpp(test_pred/2, [pipeline_input(true)], Code1),
    (   sub_atom(Code1, _, _, _, 'runPipeline')
    ->  format('  [PASS] Generated pipeline code~n')
    ;   format('  [FAIL] Missing pipeline code~n')
    ),
    
    format('~nTest 2: nlohmann/json usage~n'),
    (   sub_atom(Code1, _, _, _, 'nlohmann')
    ->  format('  [PASS] Uses nlohmann/json~n')
    ;   format('  [FAIL] Missing nlohmann/json~n')
    ),
    
    format('~nTest 3: std::optional for filtering~n'),
    (   sub_atom(Code1, _, _, _, 'std::optional')
    ->  format('  [PASS] Uses std::optional~n')
    ;   format('  [FAIL] Missing std::optional~n')
    ),
    
    format('~nTest 4: Generator mode~n'),
    compile_predicate_to_cpp(test_gen/2, [generator_mode(true)], Code2),
    (   sub_atom(Code2, _, _, _, 'Generator')
    ->  format('  [PASS] Uses Generator class~n')
    ;   format('  [FAIL] Missing Generator class~n')
    ),
    
    format('~nTest 5: CMake generation with FetchContent~n'),
    generate_cmake_cpp([project_name('TestProject')], CMake),
    (   sub_atom(CMake, _, _, _, 'FetchContent')
    ->  format('  [PASS] Uses FetchContent for dependencies~n')
    ;   format('  [FAIL] Missing FetchContent~n')
    ),
    
    format('~n=== C++ Pipeline Mode Tests Complete ===~n').

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(cpp, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_cpp(StepOp, CppStepExpr),
    (   Arity =:= 3 ->
        format(string(Code),
'// Generated by UnifyWeaver C++ Target - Tail Recursion (multifile dispatch)
// Predicate: ~w/~w

#include <iostream>
#include <vector>
#include <string>
#include <sstream>

int ~w(const std::vector<int>& items) {
    int acc = 0;
    for (int item : items) {
        acc = ~w;
    }
    return acc;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) {
        std::vector<int> items;
        std::stringstream ss(argv[1]);
        std::string token;
        while (std::getline(ss, token, '','')) {
            items.push_back(std::stoi(token));
        }
        std::cout << ~w(items) << std::endl;
    }
    return 0;
}
', [PredStr, Arity, PredStr, CppStepExpr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'// Generated by UnifyWeaver C++ Target - Tail Recursion (binary, multifile dispatch)
// Predicate: ~w/~w

#include <iostream>
#include <vector>
#include <string>
#include <sstream>

template<typename T>
int ~w(const std::vector<T>& items) {
    int count = 0;
    for (const auto& item : items) { (void)item; count++; }
    return count;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) {
        std::vector<std::string> items;
        std::stringstream ss(argv[1]);
        std::string token;
        while (std::getline(ss, token, '','')) {
            items.push_back(token);
        }
        std::cout << ~w(items) << std::endl;
    }
    return 0;
}
', [PredStr, Arity, PredStr, PredStr])
    ;   fail
    ).

step_op_to_cpp(arithmetic(Expr), CppExpr) :- tail_expr_to_cpp(Expr, CppExpr).
step_op_to_cpp(unknown, 'acc + 1').

tail_expr_to_cpp(_ + Const, CppExpr) :- integer(Const), !, format(atom(CppExpr), 'acc + ~w', [Const]).
tail_expr_to_cpp(_ + _, 'acc + item') :- !.
tail_expr_to_cpp(_ - _, 'acc - item') :- !.
tail_expr_to_cpp(_ * _, 'acc * item') :- !.
tail_expr_to_cpp(_, 'acc + 1').

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(cpp, PredStr, Arity, BaseClauses, _RecClauses, MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_cpp(PredStr, BaseClauses, MemoEnabled, Code)
    ;   linear_generic_cpp(PredStr, Arity, MemoEnabled, Code)
    ).

linear_fold_cpp(PredStr, BaseClauses, MemoEnabled, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    (   MemoEnabled = true ->
        MemoDecl = "static std::unordered_map<int, int> memo;",
        format(string(MemoCheck), '    auto it = memo.find(n); if (it != memo.end()) return it->second;', []),
        format(string(MemoStore), '    memo[n] = result;', [])
    ;   MemoDecl = "// Memoization disabled",
        MemoCheck = '',
        MemoStore = ''
    ),
    % Extract fold
    atom_string(Pred, PredStr),
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
    partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRec, _),
    (   ActualRec = [clause(RHead, RBody)|_] ->
        RHead =.. [_, InputVar, _],
        linear_recursion:find_recursive_call(RBody, RecCall),
        RecCall =.. [_, _, AccVar],
        linear_recursion:find_last_is_expression(RBody, _ is FoldExpr),
        translate_fold_expr_cpp(FoldExpr, InputVar, AccVar, CppOp)
    ;   CppOp = "current * result"
    ),
    (   InputType = numeric ->
        format(string(Code),
'// Generated by UnifyWeaver C++ Target - Linear Recursion (numeric, multifile dispatch)
// Predicate: ~w/2

#include <iostream>
#include <unordered_map>

~w

int ~w(int n) {
~w
    if (n == ~w) return ~w;
    int result = ~w;
    for (int current = n; current >= 1; current--) {
        result = ~w;
    }
~w
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) std::cout << ~w(std::atoi(argv[1])) << std::endl;
    return 0;
}
', [PredStr, MemoDecl, PredStr, MemoCheck, BaseInput, BaseOutput, BaseOutput, CppOp, MemoStore, PredStr])
    ;   InputType = list ->
        % Re-extract fold with head variable for list patterns
        (   ActualRec = [clause(LRHead, LRBody)|_] ->
            linear_recursion:find_last_is_expression(LRBody, _ is LFoldExpr),
            linear_recursion:find_recursive_call(LRBody, LRecCall),
            LRecCall =.. [_, _, LAccVar],
            LRHead =.. [_, [LHeadVar|_], _],
            translate_list_fold_cpp(LFoldExpr, LHeadVar, LAccVar, ListCppOp)
        ;   ListCppOp = "result + current"
        ),
        format(string(Code),
'// Generated by UnifyWeaver C++ Target - Linear Recursion (list, multifile dispatch)
// Predicate: ~w/2

#include <iostream>
#include <vector>
#include <unordered_map>
#include <numeric>
#include <sstream>
#include <string>

~w

int ~w(const std::vector<int>& lst) {
    if (lst.empty()) return ~w;
    return std::accumulate(lst.begin(), lst.end(), ~w,
        [](int result, int current) { return ~w; });
}

int main(int argc, char* argv[]) {
    if (argc >= 2) {
        std::vector<int> items;
        std::string s(argv[1]);
        size_t pos = 0, found;
        while ((found = s.find('','', pos)) != std::string::npos) {
            items.push_back(std::stoi(s.substr(pos, found - pos)));
            pos = found + 1;
        }
        items.push_back(std::stoi(s.substr(pos)));
        std::cout << ~w(items) << std::endl;
    }
    return 0;
}
', [PredStr, '// List pattern — no memoization', PredStr, BaseOutput, BaseOutput, ListCppOp, PredStr])
    ;   linear_generic_cpp(PredStr, 2, MemoEnabled, Code)
    ).

linear_generic_cpp(PredStr, Arity, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        format(string(Code),
'// Generated by UnifyWeaver C++ Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

#include <iostream>
#include <unordered_map>

static std::unordered_map<int, int> memo;

int ~w(int n) {
    auto it = memo.find(n);
    if (it != memo.end()) return it->second;
    int result;
    if (n <= 0) result = 0;
    else if (n == 1) result = 1;
    else result = ~w(n - 1) + n;
    memo[n] = result;
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) std::cout << ~w(std::atoi(argv[1])) << std::endl;
    return 0;
}
', [PredStr, Arity, PredStr, PredStr, PredStr])
    ;   format(string(Code),
'// Generated by UnifyWeaver C++ Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

#include <iostream>

int ~w(int n) {
    int result;
    if (n <= 0) result = 0;
    else if (n == 1) result = 1;
    else result = ~w(n - 1) + n;
    return result;
}

int main(int argc, char* argv[]) {
    if (argc >= 2) std::cout << ~w(std::atoi(argv[1])) << std::endl;
    return 0;
}
', [PredStr, Arity, PredStr, PredStr, PredStr])
    ).

translate_fold_expr_cpp(A * B, IV, AV, E) :- translate_cpp_term(A, IV, AV, AT), translate_cpp_term(B, IV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_fold_expr_cpp(A + B, IV, AV, E) :- translate_cpp_term(A, IV, AV, AT), translate_cpp_term(B, IV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_fold_expr_cpp(A - B, IV, AV, E) :- translate_cpp_term(A, IV, AV, AT), translate_cpp_term(B, IV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_fold_expr_cpp(T, IV, AV, E) :- translate_cpp_term(T, IV, AV, E).

translate_cpp_term(T, IV, _, 'current') :- T == IV, !.
translate_cpp_term(T, _, AV, 'result') :- T == AV, !.
translate_cpp_term(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_cpp_term(A, _, _, S) :- format(string(S), '~w', [A]).

%% translate_list_fold_cpp(+PrologExpr, +HeadVar, +AccVar, -CppExpr)
%  Like translate_fold_expr_cpp but maps HeadVar → 'current' (lambda parameter for
%  each list element) and AccVar → 'result' (accumulator in std::accumulate lambda).
translate_list_fold_cpp(A * B, HV, AV, E) :- translate_list_term_cpp(A, HV, AV, AT), translate_list_term_cpp(B, HV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_list_fold_cpp(A + B, HV, AV, E) :- translate_list_term_cpp(A, HV, AV, AT), translate_list_term_cpp(B, HV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_list_fold_cpp(A - B, HV, AV, E) :- translate_list_term_cpp(A, HV, AV, AT), translate_list_term_cpp(B, HV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_list_fold_cpp(T, HV, AV, E) :- translate_list_term_cpp(T, HV, AV, E).

translate_list_term_cpp(T, HV, _, 'current') :- T == HV, !.
translate_list_term_cpp(T, _, AV, 'result') :- T == AV, !.
translate_list_term_cpp(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_list_term_cpp(A, _, _, S) :- format(string(S), '~w', [A]).

% ============================================================================
% TREE RECURSION - C++ target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(cpp, _Pattern, Pred, _Arity, _UseMemo, CppCode) :-
    atom_string(Pred, PredStr),
    format(string(CppCode),
'/* Generated by UnifyWeaver C++ Target - Tree Recursion (fibonacci, multifile dispatch) */
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <unordered_map>

static std::unordered_map<int, int> memo;

int ~w(int n) {
    if (n <= 0) return 0;
    if (n == 1) return 1;
    auto it = memo.find(n);
    if (it != memo.end()) return it->second;
    int result = ~w(n - 1) + ~w(n - 2);
    memo[n] = result;
    return result;
}

int main(int argc, char *argv[]) {
    if (argc >= 2) std::cout << ~w(std::atoi(argv[1])) << std::endl;
    return 0;
}
', [PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTICALL LINEAR RECURSION - C++ target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(cpp, PredStr, BaseClauses, _RecClauses, _MemoEnabled, CppCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    if (n == ~w) return ~w;', [BInput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(CppCode),
'/* Generated by UnifyWeaver C++ Target - Multicall Linear Recursion (multifile dispatch) */
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <unordered_map>

static std::unordered_map<int, int> memo;

int ~w(int n) {
~w
    auto it = memo.find(n);
    if (it != memo.end()) return it->second;
    int result = ~w(n - 1) + ~w(n - 2);
    memo[n] = result;
    return result;
}

int main(int argc, char *argv[]) {
    if (argc >= 2) std::cout << ~w(std::atoi(argv[1])) << std::endl;
    return 0;
}
', [PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% DIRECT MULTI-CALL RECURSION - C++ target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(cpp, PredStr, BaseClauses, RecClause, CppCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    if (input == ~w) { memo[input] = ~w; return ~w; }', [BInput, BOutput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    RecClause = clause(RecHead, RecBody),
    RecHead =.. [Pred, _IV, _OV],
    extract_body_components(RecBody, Pred, Computations, RecCalls, Aggregation),
    direct_computations_cpp(Computations, ComputationsCode),
    direct_recursive_calls_cpp(RecCalls, PredStr, RecCallsCode),
    direct_aggregation_cpp(Aggregation, AggCode),
    format(string(CppCode),
'/* Generated by UnifyWeaver C++ Target - Direct Multicall Recursion (multifile dispatch) */
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <unordered_map>

static std::unordered_map<int, int> memo;

int ~w(int input) {
    auto it = memo.find(input);
    if (it != memo.end()) return it->second;
~w
~w
~w
~w
    memo[input] = result;
    return result;
}

int main(int argc, char *argv[]) {
    if (argc >= 2) std::cout << ~w(std::atoi(argv[1])) << std::endl;
    return 0;
}
', [PredStr, BaseCaseStr, ComputationsCode, RecCallsCode, AggCode, PredStr]).

direct_computations_cpp(Computations, Code) :-
    findall(Line, (
        member(Var is Expr, Computations),
        direct_var_to_cpp_name(Var, VarName),
        direct_translate_expr_cpp(Expr, CppExpr),
        format(string(Line), '    int ~w = ~w;', [VarName, CppExpr])
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

direct_recursive_calls_cpp(RecCalls, PredStr, Code) :-
    findall(Line, (
        member(RecCall, RecCalls),
        RecCall =.. [_Pred, ArgVar, ResultVar],
        direct_var_to_cpp_name(ArgVar, ArgName),
        direct_var_to_cpp_name(ResultVar, ResName),
        format(string(Line), '    int ~w = ~w(~w);', [ResName, PredStr, ArgName])
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

direct_aggregation_cpp(_ is Expr, Code) :-
    direct_translate_agg_expr_cpp(Expr, CppExpr),
    format(string(Code), '    int result = ~w;', [CppExpr]).

direct_translate_agg_expr_cpp(A + B, Expr) :-
    direct_var_to_cpp_name(A, AName), direct_var_to_cpp_name(B, BName),
    format(string(Expr), '~w + ~w', [AName, BName]).
direct_translate_agg_expr_cpp(A * B, Expr) :-
    direct_var_to_cpp_name(A, AName), direct_var_to_cpp_name(B, BName),
    format(string(Expr), '~w * ~w', [AName, BName]).

%% direct_var_to_cpp_name(+Var, -CppName)
%  Convert Prolog variable to valid C++ identifier.
%  Internal var names like _G12345 become v12345 in C++.
direct_var_to_cpp_name(Var, CppName) :-
    (   var(Var) ->
        term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, LowerName),
        ensure_cpp_identifier(LowerName, CppName)
    ;   atom(Var) ->
        downcase_atom(Var, LowerName),
        ensure_cpp_identifier(LowerName, CppName)
    ;   term_string(Var, VarStr),
        atom_string(VarAtom, VarStr),
        downcase_atom(VarAtom, LowerName),
        ensure_cpp_identifier(LowerName, CppName)
    ).

ensure_cpp_identifier(Name, ValidName) :-
    atom_chars(Name, [First|Rest]),
    (   (First = '_' ; char_type(First, digit)) ->
        atom_chars(ValidName, [v|Rest])
    ;   ValidName = Name
    ).

direct_translate_expr_cpp(N - K, Expr) :- var(N), integer(K), !,
    format(string(Expr), 'input - ~w', [K]).
direct_translate_expr_cpp(N + K, Expr) :- var(N), integer(K), K < 0, !,
    AbsK is abs(K), format(string(Expr), 'input - ~w', [AbsK]).
direct_translate_expr_cpp(N + K, Expr) :- var(N), integer(K), !,
    format(string(Expr), 'input + ~w', [K]).
direct_translate_expr_cpp(Expr, 'input') :- var(Expr), !.
direct_translate_expr_cpp(N, S) :- integer(N), !, format(string(S), '~w', [N]).
direct_translate_expr_cpp(A, S) :- format(string(S), '~w', [A]).

% ============================================================================
% MUTUAL RECURSION - C++ target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(cpp, Predicates, MemoEnabled, _MemoStrategy, CppCode) :-
    % Forward declarations
    findall(FwdDecl, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(FwdDecl), 'int ~w(int n);', [PredStr])
    ), FwdDecls),
    atomic_list_concat(FwdDecls, '\n', ForwardDecls),
    % Generate functions
    mutual_functions_cpp(Predicates, Predicates, MemoEnabled, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    % Dispatch
    mutual_dispatch_cpp(Predicates, DispatchCode),
    format(string(CppCode),
'/* Generated by UnifyWeaver C++ Target - Mutual Recursion (multifile dispatch) */
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <string>
#include <unordered_map>

static std::unordered_map<std::string, int> memo;

~w

~w

int main(int argc, char *argv[]) {
~w
    return 0;
}
', [ForwardDecls, FunctionsCode, DispatchCode]).

mutual_functions_cpp([], _AllPreds, _MemoEnabled, []).
mutual_functions_cpp([Pred/Arity|Rest], AllPreds, MemoEnabled, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    mutual_base_cases_cpp(BaseClauses, PredStr, MemoEnabled, BaseParts),
    atomic_list_concat(BaseParts, '\n', BaseCode),
    mutual_rec_cases_cpp(RecClauses, PredStr, MemoEnabled, RecParts),
    atomic_list_concat(RecParts, '\n', RecCode),
    (   MemoEnabled = true ->
        format(string(FuncCode),
'int ~w(int n) {
    std::string key = "~w:" + std::to_string(n);
    auto it = memo.find(key);
    if (it != memo.end()) return it->second;
~w
~w
    return 0;
}', [PredStr, PredStr, BaseCode, RecCode])
    ;   format(string(FuncCode),
'int ~w(int n) {
~w
~w
    return 0;
}', [PredStr, BaseCode, RecCode])
    ),
    mutual_functions_cpp(Rest, AllPreds, MemoEnabled, RestCodes).

mutual_base_cases_cpp([], _PredStr, _MemoEnabled, []).
mutual_base_cases_cpp([clause(Head, true)|Rest], PredStr, MemoEnabled, [Part|RestParts]) :-
    Head =.. [_Pred, Value],
    (   MemoEnabled = true ->
        format(string(Part),
'    if (n == ~w) { memo["~w:" + std::to_string(n)] = 1; return 1; }',
            [Value, PredStr])
    ;   format(string(Part), '    if (n == ~w) return 1;', [Value])
    ),
    mutual_base_cases_cpp(Rest, PredStr, MemoEnabled, RestParts).
mutual_base_cases_cpp([_|Rest], PredStr, MemoEnabled, RestParts) :-
    mutual_base_cases_cpp(Rest, PredStr, MemoEnabled, RestParts).

mutual_rec_cases_cpp([], _PredStr, _MemoEnabled, []).
mutual_rec_cases_cpp([clause(_Head, Body)|Rest], PredStr, MemoEnabled, [Part|RestParts]) :-
    extract_mutual_rec_info_cpp(Body, Guard, CalledPred, Step),
    atom_string(CalledPred, CalledStr),
    (   Guard = (N > Threshold), var(N) ->
        (   MemoEnabled = true ->
            format(string(Part),
'    if (n > ~w) {
        int result = ~w(n ~w);
        memo["~w:" + std::to_string(n)] = result;
        return result;
    }', [Threshold, CalledStr, Step, PredStr])
        ;   format(string(Part),
'    if (n > ~w) return ~w(n ~w);', [Threshold, CalledStr, Step])
        )
    ;   (   MemoEnabled = true ->
            format(string(Part),
'    {
        int result = ~w(n ~w);
        memo["~w:" + std::to_string(n)] = result;
        return result;
    }', [CalledStr, Step, PredStr])
        ;   format(string(Part), '    return ~w(n ~w);', [CalledStr, Step])
        )
    ),
    mutual_rec_cases_cpp(Rest, PredStr, MemoEnabled, RestParts).
mutual_rec_cases_cpp([_|Rest], PredStr, MemoEnabled, RestParts) :-
    mutual_rec_cases_cpp(Rest, PredStr, MemoEnabled, RestParts).

extract_mutual_rec_info_cpp(Body, Guard, CalledPred, Step) :-
    extract_goals_from_body_cpp(Body, Goals),
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(Step), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(Step), '- ~w', [AbsK])
    ;   Step = "- 1"
    ).

extract_goals_from_body_cpp((A, B), Goals) :- !,
    extract_goals_from_body_cpp(A, GA),
    extract_goals_from_body_cpp(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body_cpp(true, []) :- !.
extract_goals_from_body_cpp(Goal, [Goal]).

mutual_dispatch_cpp(Predicates, Code) :-
    findall(DispLine, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(DispLine),
'    if (argc >= 3 && std::string(argv[1]) == "~w") std::cout << ~w(std::atoi(argv[2])) << std::endl;',
            [PredStr, PredStr])
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).
