:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2026 John William Creighton (s243a)
%
% elixir_target.pl - Elixir Target for UnifyWeaver
% Generates Elixir programs for record/field processing

:- module(elixir_target, [
    target_info/1,
    compile_predicate/3,
    compile_predicate_to_elixir/3,
    compile_facts_to_elixir/3,
    compile_rules_to_elixir/3,
    compile_mutual_recursion_elixir/3,
    write_elixir_module/2,
    init_elixir_target/0
]).

:- use_module(library(lists)).
:- use_module(library(option)).

%% ============================================
%% TARGET INFO
%% ============================================

target_info(info{
    name: "Elixir",
    family: beam,
    file_extension: ".ex",
    runtime: beam,
    features: [pattern_matching, tail_recursion, streams, actors, functional],
    recursion_patterns: [tail_recursion, linear_recursion, mutual_recursion, transitive_closure],
    compile_command: "elixirc"
}).

%% ============================================
%% INIT
%% ============================================

init_elixir_target :-
    format('[Elixir Target] Initialized~n', []).

%% ============================================
%% MAIN DISPATCH
%% ============================================

compile_predicate(PredArity, Options, Code) :-
    compile_predicate_to_elixir(PredArity, Options, Code).

compile_predicate_to_elixir(Pred/Arity, Options, ElixirCode) :-
    (   option(type(facts), Options)
    ->  compile_facts_to_elixir(Pred, Arity, ElixirCode)
    ;   option(type(mutual_recursion), Options)
    ->  compile_mutual_recursion_elixir(Pred/Arity, Options, ElixirCode)
    ;   option(generator_mode(true), Options)
    ->  compile_generator_mode_elixir(Pred, Arity, Options, ElixirCode)
    ;   option(pipeline_input(true), Options)
    ->  compile_pipeline_mode_elixir(Pred, Arity, Options, ElixirCode)
    ;   compile_simple_mode_elixir(Pred, Arity, Options, ElixirCode)
    ).

compile_rules_to_elixir(Pred/Arity, Options, Code) :-
    compile_simple_mode_elixir(Pred, Arity, Options, Code).

%% ============================================
%% FACTS COMPILATION
%% ============================================

compile_facts_to_elixir(Pred, Arity, ElixirCode) :-
    atom_string(Pred, PredStr),
    upcase_atom_first(Pred, PredCap),
    functor(Head, Pred, Arity),
    
    findall(Args, (user:clause(Head, true), Head =.. [_|Args]), AllFacts),
    
    (   AllFacts == []
    ->  FactEntries = "  @facts []"
    ;   findall(Entry, (
            member(Args, AllFacts),
            format_elixir_fact_entry(Args, Entry)
        ), Entries),
        atomic_list_concat(Entries, ',\n    ', FactList),
        format(string(FactEntries), "  @facts [\n    ~w\n  ]", [FactList])
    ),
    
    format(string(ElixirCode),
'# Generated by UnifyWeaver Elixir Target
# Facts for ~w/~w

defmodule Generated.~w do
  @moduledoc "Generated facts for ~w/~w"

~w

  @doc "Return all facts"
  def all, do: @facts

  @doc "Check if tuple is a fact"
  def member?(args), do: args in @facts

  @doc "Stream all facts lazily"
  def stream, do: Stream.map(@facts, & &1)
end
', [PredStr, Arity, PredCap, PredStr, Arity, FactEntries]).

format_elixir_fact_entry(Args, Entry) :-
    findall(Formatted, (
        member(Arg, Args),
        (   number(Arg) -> format(string(Formatted), "~w", [Arg])
        ;   atom(Arg)   -> format(string(Formatted), "\"~w\"", [Arg])
        ;   string(Arg) -> format(string(Formatted), "\"~w\"", [Arg])
        ;   format(string(Formatted), "\"~w\"", [Arg])
        )
    ), FormattedArgs),
    atomic_list_concat(FormattedArgs, ', ', ArgsStr),
    format(string(Entry), '{~w}', [ArgsStr]).

%% ============================================
%% SIMPLE MODE
%% ============================================

compile_simple_mode_elixir(Pred, Arity, _Options, ElixirCode) :-
    atom_string(Pred, PredStr),
    upcase_atom_first(Pred, PredCap),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), user:clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  FuncBody = "  def process(_), do: nil"
    ;   generate_simple_clauses_elixir(PredStr, Clauses, FuncBody)
    ),
    
    format(string(ElixirCode),
'# Generated by UnifyWeaver Elixir Target
# Predicate: ~w/~w

defmodule Generated.~w do
~w
end
', [PredStr, Arity, PredCap, FuncBody]).

generate_simple_clauses_elixir(Name, Clauses, Code) :-
    findall(ClauseCode, (
        member((Head, Body), Clauses),
        Head =.. [_|Args],
        length(Args, Arity),
        (   Arity == 0
        ->  ArgsStr = ""
        ;   findall(V, (member(A,Args), var_to_elixir(A,V)), Vars),
            atomic_list_concat(Vars, ', ', ArgsStr)
        ),
        translate_body_elixir(Body, BodyCode),
        format(string(ClauseCode), "  def ~w(~w) do\n    try do\n~w\n      {:ok, [~w]}\n    catch\n      :fail -> :fail\n    end\n  end", [Name, ArgsStr, BodyCode, ArgsStr])
    ), Codes),
    atomic_list_concat(Codes, '\n\n', Code).

%% ============================================
%% PIPELINE MODE
%% ============================================

compile_pipeline_mode_elixir(Pred, Arity, _Options, ElixirCode) :-
    atom_string(Pred, PredStr),
    upcase_atom_first(Pred, PredCap),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), user:clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  FuncBody = "    record"
    ;   generate_pipeline_clauses_elixir(Clauses, FuncBody)
    ),
    
    format(string(ElixirCode),
'# Generated by UnifyWeaver Elixir Target - Pipeline Mode
# Predicate: ~w/~w
# Requires: Jason 

defmodule Generated.~wPipeline do

  def process(record) do
~w
  end

  def run do
    IO.stream(:stdio, :line)
    |> Stream.reject(&(&1 == "\\n"))
    |> Stream.map(&String.trim/1)
    |> Stream.map(&Jason.decode!/1)
    |> Stream.map(&process/1)
    |> Stream.reject(&is_nil/1)
    |> Enum.each(&(IO.puts(Jason.encode!(&1))))
  end
end

case System.argv() do
  [] -> :ok
  ["--run"|_] -> Generated.~wPipeline.run()
  _ -> :ok
end
', [PredStr, Arity, PredCap, FuncBody, PredCap]).

generate_pipeline_clauses_elixir([], "    record").
generate_pipeline_clauses_elixir(Clauses, Code) :-
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_elixir(Name, Clauses)
    ->  partition(is_recursive_clause_elixir(Name), Clauses, RecClauses, BaseClauses),
        compile_recursive_elixir(Name, BaseClauses, RecClauses, Code)
    ;   findall(ClauseCode, (
            member((H, B), Clauses),
            translate_pipeline_clause_elixir(H, B, ClauseCode)
        ), Codes),
        atomic_list_concat(Codes, '\n\n', Code)
    ).

translate_pipeline_clause_elixir(Head, Body, Code) :-
    Head =.. [_Pred|_Args],
    % For pipeline, input is 'record' map
    (   Body == true
    ->  BodyCode = "    record"
    ;   translate_body_elixir(Body, TransBody),
        format(string(BodyCode), "    try do\n~w\n      record\n    catch\n      :fail -> nil\n    end", [TransBody])
    ),
    Code = BodyCode.

%% ============================================
%% GENERATOR MODE
%% ============================================

compile_generator_mode_elixir(Pred, Arity, Options, ElixirCode) :-
    compile_pipeline_mode_elixir(Pred, Arity, Options, PipelineCode),
    % Tweak pipeline to create generator for simplicity
    upcase_atom_first(Pred, PredCap),
    format(string(ElixirCode),
'~w
# Wrapper for Generator
defmodule Generated.~wGen do
  def generate(init_record) do
    Stream.unfold(init_record, fn record ->
      case Generated.~wPipeline.process(record) do
        nil -> nil
        next -> {next, next}
      end
    end)
  end
end
', [PipelineCode, PredCap, PredCap]).

%% ============================================
%% MUTUAL RECURSION
%% ============================================

compile_mutual_recursion_elixir(PredList, _Options, Code) :-
    format(string(Code),
'# Generated by UnifyWeaver Elixir Target
# Mutual Recursion module for ~w

defmodule Generated.MutualGroup do
  # mutually recursive defs will go here
end
', [PredList]).

%% ============================================
%% BODY TRANSLATION
%% ============================================

translate_body_elixir((Goal, Rest), Code) :-
    !,
    translate_goal_elixir(Goal, Code1),
    translate_body_elixir(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_body_elixir(Goal, Code) :-
    translate_goal_elixir(Goal, Code).

translate_goal_elixir(>(X, Y), Code) :-
    !, expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
    format(string(Code), "      if not (~w > ~w), do: throw(:fail)", [CX, CY]).

translate_goal_elixir(<(X, Y), Code) :-
    !, expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
    format(string(Code), "      if not (~w < ~w), do: throw(:fail)", [CX, CY]).

translate_goal_elixir(>=(X, Y), Code) :-
    !, expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
    format(string(Code), "      if not (~w >= ~w), do: throw(:fail)", [CX, CY]).

translate_goal_elixir(=<(X, Y), Code) :-
    !, expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
    format(string(Code), "      if not (~w <= ~w), do: throw(:fail)", [CX, CY]).

translate_goal_elixir(=:=(X, Y), Code) :-
    !, expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
    format(string(Code), "      if not (~w === ~w), do: throw(:fail)", [CX, CY]).

translate_goal_elixir(=\\=(X, Y), Code) :-
    !, expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
    format(string(Code), "      if not (~w !== ~w), do: throw(:fail)", [CX, CY]).

translate_goal_elixir(is(Var, Expr), Code) :-
    !,
    var_to_elixir(Var, EVar),
    expr_to_elixir(Expr, EExpr),
    format(string(Code), "      ~w = ~w", [EVar, EExpr]).

translate_goal_elixir(true, "      # true") :- !.

translate_goal_elixir(Goal, Code) :-
    format(string(Code), "      # TODO: translate ~w", [Goal]).

%% ============================================
%% EXPRESSIONS AND VARIABLES
%% ============================================

var_to_elixir(Var, ElixirVar) :-
    (   var(Var)
    ->  term_to_atom(Var, VarAtom),
        format(atom(ElixirVar), "v_~w", [VarAtom])
    ;   Var = '$VAR'(N)
    ->  format(atom(ElixirVar), "v_~w", [N])
    ;   atom(Var)
    ->  % lowercase the first char so Elixir treats it as a variable, not a module
        atom_string(Var, VarStr),
        string_lower(VarStr, LowerStr),
        atom_string(ElixirVar, LowerStr)
    ;   term_to_atom(Var, ElixirVar)
    ).

expr_to_elixir(Expr, ElixirExpr) :-
    (   number(Expr)
    ->  format(atom(ElixirExpr), "~w", [Expr])
    ;   var(Expr)
    ->  var_to_elixir(Expr, ElixirExpr)
    ;   Expr = '$VAR'(N)
    ->  format(atom(ElixirExpr), "v_~w", [N])
    ;   Expr = X + Y
    ->  expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
        format(atom(ElixirExpr), "(~w + ~w)", [CX, CY])
    ;   Expr = X - Y
    ->  expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
        format(atom(ElixirExpr), "(~w - ~w)", [CX, CY])
    ;   Expr = X * Y
    ->  expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
        format(atom(ElixirExpr), "(~w * ~w)", [CX, CY])
    ;   Expr = X / Y
    ->  expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
        format(atom(ElixirExpr), "div(~w, ~w)", [CX, CY])
    ;   Expr = X mod Y
    ->  expr_to_elixir(X, CX), expr_to_elixir(Y, CY),
        format(atom(ElixirExpr), "rem(~w, ~w)", [CX, CY])
    ;   atom(Expr)
    ->  format(atom(ElixirExpr), "\"~w\"", [Expr])
    ;   format(atom(ElixirExpr), "~w", [Expr])
    ).

%% ============================================
%% RECURSION UTILS
%% ============================================

is_recursive_predicate_elixir(Name, Clauses) :-
    member((_, Body), Clauses),
    contains_recursive_call_elixir(Body, Name).

is_recursive_clause_elixir(Name, (_, Body)) :-
    contains_recursive_call_elixir(Body, Name).

contains_recursive_call_elixir(Body, Name) :-
    extract_goal_elixir(Body, Goal),
    functor(Goal, Name, _),
    !.

extract_goal_elixir(Goal, Goal) :-
    compound(Goal),
    \+ Goal = (_,_),
    \+ Goal = (_;_).
extract_goal_elixir((A, _), Goal) :- extract_goal_elixir(A, Goal).
extract_goal_elixir((_, B), Goal) :- extract_goal_elixir(B, Goal).

compile_recursive_elixir(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_elixir(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),
    
    format(string(Code),
"    # Recursive predicate: ~w
    iter = fn iter_fn, current, depth ->
      if depth > 10000 do
        IO.puts(:stderr, \"Warning: Max depth for ~w\")
        current
      else
        if ~w do
          current
        else
          iter_fn.(iter_fn, current, depth + 1)
        end
      end
    end

    iter.(iter, record, 0)", [Name, Name, BaseCondition]).

generate_base_condition_elixir(Head, Condition) :-
    Head =.. [_|Args],
    (   Args = [Arg|_],
        (   number(Arg)
        ->  format(string(Condition), "Map.get(current, \"arg0\") == ~w", [Arg])
        ;   atom(Arg)
        ->  format(string(Condition), "Map.get(current, \"arg0\") == \"~w\"", [Arg])
        ;   Condition = "false"
        )
    ;   Condition = "false"
    ).

%% ============================================
%% UTILS
%% ============================================

upcase_atom_first(Atom, CapAtom) :-
    atom_chars(Atom, [H|T]),
    upcase_atom(H, HU),
    atom_chars(CapAtom, [HU|T]).

write_elixir_module(ElixirCode, FilePath) :-
    open(FilePath, write, Stream),
    write(Stream, ElixirCode),
    close(Stream),
    format('Written Elixir program to: ~w~n', [FilePath]).
