:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% fsharp_target.pl - F# Code Generation Target
% Compiles Prolog predicates to F# programs using functional idioms.

:- module(fsharp_target, [
    compile_predicate_to_fsharp/3,         % +PredIndicator, +Options, -FSharpCode
    compile_facts_to_fsharp/3,             % +Pred, +Arity, -FSharpCode  
    compile_tail_recursion_fsharp/3,       % +Pred/Arity, +Options, -FSharpCode
    compile_linear_recursion_fsharp/3,     % +Pred/Arity, +Options, -FSharpCode
    compile_mutual_recursion_fsharp/3,     % +Predicates, +Options, -FSharpCode
    write_fsharp_program/2,                % +Code, +Filename
    init_fsharp_target/0                   % Initialize target
]).

:- use_module(library(lists)).
:- use_module('../bindings/fsharp_bindings', [init_fsharp_bindings/0]).
:- use_module('../core/clause_body_analysis').

%% init_fsharp_target
init_fsharp_target :-
    init_fsharp_bindings.

%% fsharp_ensure_fsi_compatible(+Code, -CompatCode)
%  Post-process generated F# code to work with both dotnet fsi and compiled F#.
%  1. Adds `module Program` declaration if missing (fixes FS0222)
%  2. Wraps [<EntryPoint>] in #if !INTERACTIVE (fixes FS0433)
%  3. Adds #if INTERACTIVE block before entry point for fsi execution
fsharp_ensure_fsi_compatible(Code, CompatCode) :-
    atom_string(Code, CodeStr),
    % Add module declaration if missing
    (   sub_string(CodeStr, _, _, _, "module ")
    ->  Code1 = CodeStr
    ;   (   sub_string(CodeStr, Pos, 4, _, "open")
        ->  sub_string(CodeStr, 0, Pos, _, Before),
            sub_string(CodeStr, Pos, _, 0, After),
            format(string(Code1), "~wmodule Program\n\n~w", [Before, After])
        ;   Code1 = CodeStr
        )
    ),
    % Wrap [<EntryPoint>] block in #if !INTERACTIVE, add #if INTERACTIVE before it
    (   sub_string(Code1, EntryPos, 14, _, "[<EntryPoint>]")
    ->  sub_string(Code1, 0, EntryPos, _, BeforeEntry),
        sub_string(Code1, EntryPos, _, 0, EntryAndAfter),
        % Extract the body of main (lines between "let main argv =" and final "    0")
        fsharp_extract_main_body(EntryAndAfter, MainBody),
        format(string(CompatCode),
            "~w#if INTERACTIVE\nlet argv = fsi.CommandLineArgs |> Array.tail\n~w#endif\n\n#if !INTERACTIVE\n~w#endif\n",
            [BeforeEntry, MainBody, EntryAndAfter])
    ;   CompatCode = Code1
    ).

%% fsharp_extract_main_body(+EntryBlock, -Body)
%  Extract the body lines between "let main argv =" and the final "    0",
%  then de-indent by 4 spaces for use at top level in INTERACTIVE mode.
fsharp_extract_main_body(EntryBlock, Body) :-
    % Find end of "let main argv =\n"
    sub_string(EntryBlock, MainPos, _, _, "let main argv ="),
    AfterMainStart is MainPos + 16,  % length of "let main argv =\n"
    sub_string(EntryBlock, AfterMainStart, _, 0, AfterMain),
    % Find the final "    0" and extract body before it
    (   sub_string(AfterMain, ZeroPos, _, _, "    0")
    ->  sub_string(AfterMain, 0, ZeroPos, _, RawBody)
    ;   RawBody = AfterMain
    ),
    % De-indent: remove leading 4-space indent from each line
    fsharp_deindent(RawBody, Body).

fsharp_deindent(Text, Result) :-
    split_string(Text, "\n", "", Lines),
    maplist(fsharp_deindent_line, Lines, DeLines),
    atomics_to_text(DeLines, "\n", Result).

fsharp_deindent_line(Line, DeLine) :-
    (   sub_string(Line, 0, 4, _, "    ")
    ->  sub_string(Line, 4, _, 0, DeLine)
    ;   DeLine = Line
    ).

atomics_to_text([], _, "").
atomics_to_text([X], _, X).
atomics_to_text([X|Xs], Sep, Result) :-
    Xs \= [],
    atomics_to_text(Xs, Sep, Rest),
    format(string(Result), "~w~w~w", [X, Sep, Rest]).

%% compile_predicate_to_fsharp(+PredIndicator, +Options, -Code)
compile_predicate_to_fsharp(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'F# target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_fsharp(Pred, Arity, Clauses, Options, RawCode),
        fsharp_ensure_fsi_compatible(RawCode, Code)
    ).

%% compile_clauses_to_fsharp(+Pred, +Arity, +Clauses, +Options, -Code)

% Try native clause body lowering first
compile_clauses_to_fsharp(Pred, Arity, Clauses, _Options, Code) :-
    native_fsharp_clause_body(Pred/Arity, Clauses, FuncBody),
    !,
    atom_string(Pred, PredStr),
    Arity1 is Arity - 1,
    build_fsharp_arg_list(Arity1, ArgList),
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Native Clause Lowering
// Predicate: ~w/~w

open System

let ~w ~w=
~w

[<EntryPoint>]
let main argv =
    printfn "%A" (~w 0)
    0
', [PredStr, Arity, PredStr, ArgList, FuncBody, PredStr]).

% Fallback to existing compilation
compile_clauses_to_fsharp(Pred, Arity, Clauses, _Options, Code) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredUp),
    atom_string(PredUp, PredUpStr),
    
    (   forall(member(_-Body, Clauses), Body == true)
    ->  compile_facts_fsharp(PredStr, PredUpStr, Arity, Clauses, Code)
    ;   compile_rule_fsharp(PredStr, PredUpStr, Arity, Clauses, Code)
    ).

%% compile_facts_fsharp(+PredStr, +PredUpStr, +Arity, +Clauses, -Code)
compile_facts_fsharp(PredStr, PredUpStr, Arity, Clauses, Code) :-
    generate_fsharp_fields(Arity, FieldDefs),
    findall(Entry, (
        member(Head-true, Clauses),
        Head =.. [_|Args],
        generate_fsharp_fact_entry(Args, Entry)
    ), Entries),
    atomic_list_concat(Entries, '\n        ', EntriesCode),
    generate_fsharp_print_pattern(Arity, PrintPattern),
    generate_fsharp_print_args(Arity, PrintArgs),
    
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Fact Export
// Predicate: ~w/~w

open System

type ~w = {
    ~w
}

let getAll~w () =
    [
        ~w
    ]

let stream~w () =
    getAll~w () |> Seq.ofList

let contains~w target =
    getAll~w () |> List.exists ((=) target)

[<EntryPoint>]
let main argv =
    getAll~w ()
    |> List.iter (fun fact -> printfn "~w" ~w)
    0
', [PredStr, Arity, PredUpStr, FieldDefs, 
    PredUpStr, EntriesCode,
    PredUpStr, PredUpStr,
    PredUpStr, PredUpStr,
    PredUpStr, PrintPattern, PrintArgs]).

%% compile_rule_fsharp(+PredStr, +PredUpStr, +Arity, +Clauses, -Code)
compile_rule_fsharp(PredStr, _PredUpStr, Arity, _Clauses, Code) :-
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Rule Compilation
// Predicate: ~w/~w

open System
open System.IO

let processLine (line: string) =
    let parts = line.Split('':'')
    if parts.Length >= ~w then Some line
    else None

[<EntryPoint>]
let main argv =
    use reader = new StreamReader(Console.OpenStandardInput())
    
    let rec readLines () = seq {
        let line = reader.ReadLine()
        if line <> null then
            yield line
            yield! readLines ()
    }
    
    readLines ()
    |> Seq.choose processLine
    |> Seq.iter (printfn "%s")
    
    0
', [PredStr, Arity, Arity]).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_fsharp_arg_list(+N, -ArgList)
%  Generates "arg1 arg2 " (trailing space) or "" for 0 args
build_fsharp_arg_list(0, "") :- !.
build_fsharp_arg_list(N, ArgList) :-
    findall(ArgName, (
        between(1, N, I),
        format(string(ArgName), 'arg~w', [I])
    ), ArgNames),
    atomic_list_concat(ArgNames, ' ', ArgListNoTrail),
    format(string(ArgList), '~w ', [ArgListNoTrail]).

%% native_fsharp_clause_body(+PredSpec, +Clauses, -Code)

% Single clause
native_fsharp_clause_body(PredSpec, [Head-Body], Code) :-
    native_fsharp_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !,
    (   Condition == "true"
    ->  format(string(Code), '    ~w', [ClauseCode])
    ;   format(string(Code),
'    if ~w then ~w
    else failwith "No matching clause for ~w"', [Condition, ClauseCode, PredSpec])
    ).

% Multi-clause → if/elif/else
native_fsharp_clause_body(PredSpec, Clauses, Code) :-
    Clauses = [_|[_|_]],
    maplist(native_fsharp_clause_pair(PredSpec), Clauses, Branches),
    Branches \= [],
    branches_to_fsharp_if_chain(Branches, PredSpec, Code).

native_fsharp_clause_pair(PredSpec, Head-Body, branch(Condition, ClauseCode)) :-
    native_fsharp_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !.

%% native_fsharp_clause(+PredSpec, +Head, +Body, -Condition, -Code)
native_fsharp_clause(_PredSpec, Head, Body, Condition, Code) :-
    Head =.. [_Pred|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputHeadArgs, [OutputHeadArg], HeadArgs),
        fsharp_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ;   OutputHeadArg = _,
        fsharp_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ),
    normalize_goals(Body, Goals),
    (   Goals == []
    ->  fsharp_resolve_value(VarMap, OutputHeadArg, OutputExpr),
        Code = OutputExpr,
        GoalConditions = []
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
            maplist(fsharp_guard_condition(VarMap), GuardGoals, GoalConditions),
            (   OutputGoals == []
            ->  fsharp_literal(OutputHeadArg, Code)
            ;   fsharp_output_goals(OutputGoals, VarMap, Code)
            )
        ;   native_fsharp_goal_sequence(Goals, VarMap, GoalConditions, Code)
        )
    ),
    append(HeadConditions, GoalConditions, AllConditions),
    combine_fsharp_conditions(AllConditions, Condition).

%% fsharp_head_conditions(+HeadArgs, +Index, +Arity, -Conditions)
fsharp_head_conditions([], _, _, []).
fsharp_head_conditions([_], _, Arity, []) :- Arity > 1, !.
fsharp_head_conditions([HeadArg|Rest], Index, Arity, Conditions) :-
    (   var(HeadArg)
    ->  Conditions = RestConditions
    ;   format(string(ArgName), 'arg~w', [Index]),
        fsharp_literal(HeadArg, Literal),
        format(string(Cond), '~w = ~w', [ArgName, Literal]),
        Conditions = [Cond|RestConditions]
    ),
    NextIndex is Index + 1,
    fsharp_head_conditions(Rest, NextIndex, Arity, RestConditions).

%% native_fsharp_goal_sequence(+Goals, +VarMap, -Conditions, -Code)
%  Uses classify_goal_sequence for advanced pattern detection.
%  Falls back to clause_guard_output_split if classification fails.
native_fsharp_goal_sequence(Goals, VarMap, Conditions, Code) :-
    classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
    ClassifiedGoals \= [],
    fsharp_render_classified_goals(ClassifiedGoals, VarMap, Conditions, Lines),
    Lines \= [],
    atomic_list_concat(Lines, '\n', Code),
    !.
native_fsharp_goal_sequence(Goals, VarMap, Conditions, Code) :-
    clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
    maplist(fsharp_guard_condition(VarMap), GuardGoals, Conditions),
    fsharp_output_goals(OutputGoals, VarMap, Code).

%% fsharp_render_classified_goals(+ClassifiedGoals, +VarMap, -Conditions, -Lines)
fsharp_render_classified_goals([], _VarMap, [], []).
fsharp_render_classified_goals([Classified], VarMap, Conds, Lines) :-
    !,
    fsharp_render_classified_last(Classified, VarMap, Conds, Lines).
%% Guarded tail: output followed by guard(s)
fsharp_render_classified_goals([output(Goal, _, _)|Rest], VarMap, [], Lines) :-
    Rest = [guard(_, _)|_],
    !,
    fsharp_output_goal(Goal, VarMap, LetBinding, VarMap1),
    fsharp_collect_trailing_guards(Rest, VarMap1, GuardGoals, _Remaining),
    maplist(fsharp_guard_condition(VarMap1), GuardGoals, GuardConds),
    atomic_list_concat(GuardConds, ' && ', GuardExpr),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMap1, OutName)
    ->  true
    ;   OutName = '_'
    ),
    format(string(IfLine), '    if ~w then ~w else failwith "guard failed"', [GuardExpr, OutName]),
    Lines = [LetBinding, IfLine].
fsharp_render_classified_goals([Classified|Rest], VarMap, Conds, Lines) :-
    fsharp_render_classified_mid(Classified, VarMap, MidConds, MidLines, VarMap1),
    fsharp_render_classified_goals(Rest, VarMap1, RestConds, RestLines),
    append(MidConds, RestConds, Conds),
    append(MidLines, RestLines, Lines).

%% fsharp_render_classified_mid(+Classified, +VarMap, -Conds, -Lines, -VarMapOut)
fsharp_render_classified_mid(guard(Goal, _), VarMap, [Cond], [], VarMap) :-
    fsharp_guard_condition(VarMap, Goal, Cond).
fsharp_render_classified_mid(output(Goal, _, _), VarMap0, [], [Line], VarMapOut) :-
    fsharp_output_goal(Goal, VarMap0, Line, VarMapOut).
fsharp_render_classified_mid(output_ite(If, Then, Else, _SharedVars), VarMap0, [], Lines, VarMap0) :-
    fsharp_guard_condition(VarMap0, If, Cond),
    fsharp_branch_value(Then, VarMap0, ThenExpr),
    fsharp_branch_value(Else, VarMap0, ElseExpr),
    format(string(IfLine), '    if ~w then', [Cond]),
    format(string(ThenLine), '        ~w', [ThenExpr]),
    ElseLine = '    else',
    format(string(ElseRetLine), '        ~w', [ElseExpr]),
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine].
fsharp_render_classified_mid(passthrough(Goal), VarMap0, [], [Line], VarMapOut) :-
    fsharp_output_goal(Goal, VarMap0, Line, VarMapOut).
fsharp_render_classified_mid(_, VarMap, [], [], VarMap).

%% fsharp_render_classified_last(+Classified, +VarMap, -Conds, -Lines)
fsharp_render_classified_last(guard(Goal, _), VarMap, [Cond], []) :-
    fsharp_guard_condition(VarMap, Goal, Cond).
fsharp_render_classified_last(output(Goal, _, _), VarMap, [], Lines) :-
    fsharp_render_output_goal_last(Goal, VarMap, Lines).
fsharp_render_classified_last(output_ite(If, Then, Else, _), VarMap, [], Lines) :-
    fsharp_guard_condition(VarMap, If, Cond),
    fsharp_branch_value(Then, VarMap, ThenExpr),
    fsharp_branch_value(Else, VarMap, ElseExpr),
    format(string(IfLine), '    if ~w then', [Cond]),
    format(string(ThenLine), '        ~w', [ThenExpr]),
    ElseLine = '    else',
    format(string(ElseRetLine), '        ~w', [ElseExpr]),
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine].
fsharp_render_classified_last(output_disj(Alternatives, _SharedVars), VarMap, [], Lines) :-
    fsharp_disj_if_chain(Alternatives, VarMap, Lines).
fsharp_render_classified_last(passthrough(Goal), VarMap, [], Lines) :-
    fsharp_render_output_goal_last(Goal, VarMap, Lines).
fsharp_render_classified_last(_, _, [], []).

%% fsharp_render_output_goal_last(+Goal, +VarMap, -Lines)
%  3-arg wrapper used by classified goal renderers.
fsharp_render_output_goal_last(Goal, VarMap, [Expr]) :-
    fsharp_output_goal_last(Goal, VarMap, Expr, _VarMapOut),
    !.
fsharp_render_output_goal_last(Goal, VarMap, [Expr]) :-
    fsharp_branch_value(Goal, VarMap, Expr).

%% fsharp_collect_trailing_guards(+ClassifiedGoals, +VarMap, -GuardGoals, -Remaining)
fsharp_collect_trailing_guards([guard(Goal, _)|Rest], VarMap, [Goal|Guards], Remaining) :-
    !, fsharp_collect_trailing_guards(Rest, VarMap, Guards, Remaining).
fsharp_collect_trailing_guards(Remaining, _, [], Remaining).

%% fsharp_disj_if_chain(+Alternatives, +VarMap, -Lines)
fsharp_disj_if_chain([], _, []).
fsharp_disj_if_chain([Alt], VarMap, [ElseLine, RetLine]) :-
    !,
    fsharp_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    else',
    format(string(RetLine), '        ~w', [ValExpr]).
fsharp_disj_if_chain([Alt|Rest], VarMap, [IfLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(fsharp_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = 'true'
    ),
    fsharp_branch_value(Alt, VarMap, ValExpr),
    format(string(IfLine), '    if ~w then', [CondExpr]),
    format(string(RetLine), '        ~w', [ValExpr]),
    fsharp_disj_elif_chain(Rest, VarMap, RestLines).

%% fsharp_disj_elif_chain(+Alternatives, +VarMap, -Lines)
fsharp_disj_elif_chain([], _, []).
fsharp_disj_elif_chain([Alt], VarMap, [ElseLine, RetLine]) :-
    !,
    fsharp_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    else',
    format(string(RetLine), '        ~w', [ValExpr]).
fsharp_disj_elif_chain([Alt|Rest], VarMap, [ElifLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(fsharp_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = 'true'
    ),
    fsharp_branch_value(Alt, VarMap, ValExpr),
    format(string(ElifLine), '    elif ~w then', [CondExpr]),
    format(string(RetLine), '        ~w', [ValExpr]),
    fsharp_disj_elif_chain(Rest, VarMap, RestLines).

%% fsharp_guard_condition(+VarMap, +Goal, -Condition)
fsharp_guard_condition(VarMap, _Module:Goal, Condition) :-
    !, fsharp_guard_condition(VarMap, Goal, Condition).
fsharp_guard_condition(VarMap, Goal, Condition) :-
    compound(Goal),
    Goal =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    fsharp_expr(Left, VarMap, FsLeft),
    fsharp_expr(Right, VarMap, FsRight),
    fsharp_op(StdOp, FsOp),
    format(string(Condition), '~w ~w ~w', [FsLeft, FsOp, FsRight]).
fsharp_guard_condition(VarMap, integer(X), Condition) :-
    !, fsharp_expr(X, VarMap, FsX),
    format(string(Condition), '~w :? int', [FsX]).
fsharp_guard_condition(VarMap, float(X), Condition) :-
    !, fsharp_expr(X, VarMap, FsX),
    format(string(Condition), '~w :? float', [FsX]).

%% fsharp_output_goals(+Goals, +VarMap, -Code)
fsharp_output_goals([], _VarMap, 'failwith "no output"') :- !.
fsharp_output_goals(Goals, VarMap, Code) :-
    fsharp_output_goals_acc(Goals, VarMap, Parts, _VarMapOut),
    (   Parts = [SingleExpr]
    ->  Code = SingleExpr
    ;   last(Parts, ResultExpr),
        append(LetParts, [_], Parts),
        findall(LetLine, (
            member(LP, LetParts),
            format(string(LetLine), '    let ~w', [LP])
        ), LetLines),
        atomic_list_concat(LetLines, '\n', LetBlock),
        format(string(Code), '~w\n    ~w', [LetBlock, ResultExpr])
    ).

fsharp_output_goals_acc([], VarMap, [], VarMap).
fsharp_output_goals_acc([Goal], VarMap, [Expr], VarMapOut) :-
    !, fsharp_output_goal_last(Goal, VarMap, Expr, VarMapOut).
fsharp_output_goals_acc([Goal|Rest], VarMap0, [Binding|RestParts], VarMapOut) :-
    fsharp_output_goal(Goal, VarMap0, Binding, VarMap1),
    fsharp_output_goals_acc(Rest, VarMap1, RestParts, VarMapOut).

%% fsharp_output_goal_last — produce the result expression
fsharp_output_goal_last(_Module:Goal, VarMap, Expr, VarMapOut) :-
    !, fsharp_output_goal_last(Goal, VarMap, Expr, VarMapOut).
fsharp_output_goal_last(Goal, VarMap0, Expr, VarMapOut) :-
    if_then_else_goal(Goal, IfGoal, ThenGoal, ElseGoal),
    !,
    fsharp_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap0, Expr, VarMapOut).
fsharp_output_goal_last(=(Var, Value), VarMap, Expr, VarMap) :-
    var(Var), !,
    fsharp_expr(Value, VarMap, Expr).
fsharp_output_goal_last(is(Var, Value), VarMap, Expr, VarMap) :-
    var(Var), !,
    fsharp_expr(Value, VarMap, Expr).
fsharp_output_goal_last(Goal, VarMap0, Expr, VarMapOut) :-
    fsharp_output_goal(Goal, VarMap0, Binding, VarMapOut),
    (   goal_output_var(Goal, OutVar),
        lookup_var(OutVar, VarMapOut, OutName)
    ->  format(string(Expr), 'let ~w in ~w', [Binding, OutName])
    ;   Expr = Binding
    ).

%% fsharp_output_goal — produce a let binding
fsharp_output_goal(_Module:Goal, VarMap0, Binding, VarMapOut) :-
    !, fsharp_output_goal(Goal, VarMap0, Binding, VarMapOut).
fsharp_output_goal(=(Var, Value), VarMap0, Binding, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    fsharp_expr(Value, VarMap0, FsExpr),
    format(string(Binding), '~w = ~w', [VarName, FsExpr]).
fsharp_output_goal(is(Var, Value), VarMap0, Binding, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    fsharp_expr(Value, VarMap0, FsExpr),
    format(string(Binding), '~w = ~w', [VarName, FsExpr]).

%% fsharp_if_then_else_output — generate if/elif/else expression
fsharp_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap0, Expr, VarMapOut) :-
    flatten_fsharp_if_branches(IfGoal, ThenGoal, ElseGoal, Branches, DefaultGoal),
    fsharp_branches_to_expr(Branches, DefaultGoal, VarMap0, Expr),
    VarMapOut = VarMap0.

flatten_fsharp_if_branches(If, Then, Else, [branch(If, Then)|RestBranches], Default) :-
    if_then_else_goal(Else, If2, Then2, Else2),
    !,
    flatten_fsharp_if_branches(If2, Then2, Else2, RestBranches, Default).
flatten_fsharp_if_branches(If, Then, Else, [branch(If, Then)], Else).

fsharp_branches_to_expr([branch(If, Then)], DefaultGoal, VarMap, Expr) :-
    !,
    fsharp_guard_condition(VarMap, If, IfCond),
    fsharp_branch_value(Then, VarMap, ThenVal),
    fsharp_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Expr), 'if ~w then ~w else ~w', [IfCond, ThenVal, ElseVal]).
fsharp_branches_to_expr(Branches, DefaultGoal, VarMap, Expr) :-
    fsharp_nested_if_expr(Branches, DefaultGoal, VarMap, Expr).

fsharp_nested_if_expr([branch(If, Then)], DefaultGoal, VarMap, Expr) :-
    !,
    fsharp_guard_condition(VarMap, If, IfCond),
    fsharp_branch_value(Then, VarMap, ThenVal),
    fsharp_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Expr), 'if ~w then ~w else ~w', [IfCond, ThenVal, ElseVal]).
fsharp_nested_if_expr([branch(If, Then)|Rest], DefaultGoal, VarMap, Expr) :-
    fsharp_guard_condition(VarMap, If, IfCond),
    fsharp_branch_value(Then, VarMap, ThenVal),
    fsharp_nested_if_expr(Rest, DefaultGoal, VarMap, ElseExpr),
    format(string(Expr), 'if ~w then ~w el~w', [IfCond, ThenVal, ElseExpr]).

%% fsharp_branch_value — extract result value from a branch
fsharp_branch_value(_Module:Goal, VarMap, Value) :-
    !, fsharp_branch_value(Goal, VarMap, Value).
fsharp_branch_value(Goal, VarMap, Value) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    fsharp_guard_condition(VarMap, If, Cond),
    fsharp_branch_value(Then, VarMap, ThenVal),
    fsharp_branch_value(Else, VarMap, ElseVal),
    format(string(Value), 'if ~w then ~w else ~w', [Cond, ThenVal, ElseVal]).
fsharp_branch_value((A, B), VarMap, Value) :-
    !,
    normalize_goals((A, B), Goals),
    last(Goals, LastGoal),
    fsharp_branch_value(LastGoal, VarMap, Value).
fsharp_branch_value(=(_, Expr), VarMap, Value) :-
    !, fsharp_expr(Expr, VarMap, Value).
fsharp_branch_value(is(_, Expr), VarMap, Value) :-
    !, fsharp_expr(Expr, VarMap, Value).
fsharp_branch_value(Goal, VarMap, Value) :-
    fsharp_expr(Goal, VarMap, Value).

% ============================================================================
% MULTIFILE HOOKS — Register F# renderers for shared compile_expression
% ============================================================================

clause_body_analysis:render_output_goal(fsharp, Goal, VarMap, Line, VarName, VarMapOut) :-
    fsharp_output_goal(Goal, VarMap, Line, VarMapOut),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMapOut, VarName)
    ->  true
    ;   VarName = "_"
    ).

clause_body_analysis:render_guard_condition(fsharp, Goal, VarMap, CondStr) :-
    fsharp_guard_condition(VarMap, Goal, CondStr).

clause_body_analysis:render_branch_value(fsharp, Branch, VarMap, ExprStr) :-
    fsharp_branch_value(Branch, VarMap, ExprStr).

clause_body_analysis:render_ite_block(fsharp, Cond, ThenLines, ElseLines, Indent, _ReturnVars, Lines) :-
    format(string(IfLine), '~wif ~w then', [Indent, Cond]),
    fsharp_indent_lines(ThenLines, Indent, IndentedThen),
    (   ElseLines \= []
    ->  format(string(ElseLine), '~welse', [Indent]),
        fsharp_indent_lines(ElseLines, Indent, IndentedElse),
        append([IfLine|IndentedThen], [ElseLine|IndentedElse], Lines)
    ;   append([IfLine|IndentedThen], [], Lines)
    ).

fsharp_indent_lines([], _, []).
fsharp_indent_lines([Line|Rest], Indent, [Indented|RestIndented]) :-
    format(string(Indented), '~w    ~w', [Indent, Line]),
    fsharp_indent_lines(Rest, Indent, RestIndented).

%% fsharp_expr — convert Prolog expression to F# syntax
fsharp_expr(Var, VarMap, FsExpr) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  FsExpr = Name
    ;   term_string(Var, FsExpr)
    ).
fsharp_expr(Expr, VarMap, FsExpr) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    fsharp_expr(Left, VarMap, FsLeft),
    fsharp_expr(Right, VarMap, FsRight),
    fsharp_op(StdOp, FsOp),
    format(string(FsExpr), '(~w ~w ~w)', [FsLeft, FsOp, FsRight]).
fsharp_expr(-Expr, VarMap, FsExpr) :-
    !,
    fsharp_expr(Expr, VarMap, Inner),
    format(string(FsExpr), '(-~w)', [Inner]).
fsharp_expr(abs(Expr), VarMap, FsExpr) :-
    !,
    fsharp_expr(Expr, VarMap, Inner),
    format(string(FsExpr), '(abs ~w)', [Inner]).
fsharp_expr(min(A, B), VarMap, FsExpr) :-
    !,
    fsharp_expr(A, VarMap, FsA),
    fsharp_expr(B, VarMap, FsB),
    format(string(FsExpr), '(min ~w ~w)', [FsA, FsB]).
fsharp_expr(max(A, B), VarMap, FsExpr) :-
    !,
    fsharp_expr(A, VarMap, FsA),
    fsharp_expr(B, VarMap, FsB),
    format(string(FsExpr), '(max ~w ~w)', [FsA, FsB]).
fsharp_expr(Atom, _VarMap, FsExpr) :-
    atom(Atom), !,
    fsharp_literal(Atom, FsExpr).
fsharp_expr(Number, _VarMap, FsExpr) :-
    number(Number), !,
    format(string(FsExpr), '~w', [Number]).
fsharp_expr(String, _VarMap, FsExpr) :-
    string(String), !,
    format(string(FsExpr), '"~w"', [String]).

%% fsharp_literal — convert Prolog value to F# literal
fsharp_literal(Value, 'None') :- var(Value), !.
fsharp_literal(true, 'true') :- !.
fsharp_literal(false, 'false') :- !.
fsharp_literal([], '[]') :- !.
fsharp_literal(Value, FsLiteral) :-
    number(Value), !,
    format(string(FsLiteral), '~w', [Value]).
fsharp_literal(Value, FsLiteral) :-
    atom(Value), !,
    format(string(FsLiteral), '"~w"', [Value]).
fsharp_literal(Value, FsLiteral) :-
    string(Value), !,
    format(string(FsLiteral), '"~w"', [Value]).
fsharp_literal(Value, FsLiteral) :-
    term_string(Value, FsLiteral).

%% fsharp_resolve_value — resolve variable or constant to F# expression
fsharp_resolve_value(VarMap, Var, FsExpr) :-
    var(Var), !,
    lookup_var(Var, VarMap, FsExpr).
fsharp_resolve_value(_VarMap, Value, FsExpr) :-
    fsharp_literal(Value, FsExpr).

%% fsharp_op — map standard operator to F# syntax
fsharp_op('>', '>').
fsharp_op('<', '<').
fsharp_op('>=', '>=').
fsharp_op('<=', '<=').
fsharp_op('==', '=').
fsharp_op('!=', '<>').
fsharp_op('+', '+').
fsharp_op('-', '-').
fsharp_op('*', '*').
fsharp_op('/', '/').
fsharp_op('%', '%').
fsharp_op('&&', '&&').
fsharp_op('||', '||').

%% combine_fsharp_conditions — join conditions with &&
combine_fsharp_conditions([], "true") :- !.
combine_fsharp_conditions([Condition], Condition) :- !.
combine_fsharp_conditions(Conditions, Combined) :-
    atomic_list_concat(Conditions, ' && ', Combined).

%% branches_to_fsharp_if_chain — build F# if/elif/else chain
branches_to_fsharp_if_chain(Branches, PredSpec, Code) :-
    branches_to_fsharp_if_lines(Branches, PredSpec, Lines),
    atomic_list_concat(Lines, '\n', Code).

branches_to_fsharp_if_lines([branch(Condition, ClauseCode)], PredSpec, [IfLine, ThenLine, ElseLine, DefaultLine]) :-
    !,
    format(string(IfLine), '    if ~w then', [Condition]),
    format(string(ThenLine), '        ~w', [ClauseCode]),
    ElseLine = '    else',
    format(string(DefaultLine), '        failwith "No matching clause for ~w"', [PredSpec]).
branches_to_fsharp_if_lines([branch(Condition, ClauseCode)|Rest], PredSpec, [IfLine, ThenLine|RestLines]) :-
    format(string(IfLine), '    if ~w then', [Condition]),
    format(string(ThenLine), '        ~w', [ClauseCode]),
    branches_to_fsharp_elif_lines(Rest, PredSpec, RestLines).

branches_to_fsharp_elif_lines([branch(Condition, ClauseCode)], PredSpec, [ElifLine, ThenLine, ElseLine, DefaultLine]) :-
    !,
    format(string(ElifLine), '    elif ~w then', [Condition]),
    format(string(ThenLine), '        ~w', [ClauseCode]),
    ElseLine = '    else',
    format(string(DefaultLine), '        failwith "No matching clause for ~w"', [PredSpec]).
branches_to_fsharp_elif_lines([branch(Condition, ClauseCode)|Rest], PredSpec, [ElifLine, ThenLine|RestLines]) :-
    format(string(ElifLine), '    elif ~w then', [Condition]),
    format(string(ThenLine), '        ~w', [ClauseCode]),
    branches_to_fsharp_elif_lines(Rest, PredSpec, RestLines).

%% ============================================
%% TAIL RECURSION (let rec with accumulator)
%% ============================================

compile_tail_recursion_fsharp(Pred/Arity, Options, Code) :-
    compile_tail_recursion_fsharp_(Pred/Arity, Options, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, Code).
compile_tail_recursion_fsharp_(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Tail Recursion
// Predicate: ~w/~w
// Optimized to O(1) stack space using tail-recursive let rec

open System

// Tail-recursive function with accumulator
let ~w n =
    let rec loop current acc =
        if current <= 0 then acc
        else loop (current - 1) (acc + current)
    loop n 0

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let n = int argv.[0]
        printfn "%d" (~w n)
    0
', [PredStr, Arity, PredStr, PredStr]).

%% ============================================
%% LINEAR RECURSION (Map-based memoization)
%% ============================================

compile_linear_recursion_fsharp(Pred/Arity, Options, Code) :-
    compile_linear_recursion_fsharp_(Pred/Arity, Options, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, Code).
compile_linear_recursion_fsharp_(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Linear Recursion
// Predicate: ~w/~w
// Uses mutable Dictionary for O(n) memoization

open System
open System.Collections.Generic

let private memo = Dictionary<int, int>()

let rec ~w n =
    match memo.TryGetValue(n) with
    | true, v -> v
    | false, _ ->
        let result =
            match n with
            | n when n <= 0 -> 0
            | 1 -> 1
            | n -> (~w (n - 1)) + n
        memo.[n] <- result
        result

let clearMemo () = memo.Clear()

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let n = int argv.[0]
        printfn "%d" (~w n)
    0
', [PredStr, Arity, PredStr, PredStr, PredStr]).

%% ============================================
%% MUTUAL RECURSION (and keyword)
%% ============================================

compile_mutual_recursion_fsharp(Predicates, Options, Code) :-
    compile_mutual_recursion_fsharp_(Predicates, Options, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, Code).
compile_mutual_recursion_fsharp_(Predicates, _Options, Code) :-
    findall(PredStr, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr)
    ), PredStrs),
    atomic_list_concat(PredStrs, '_', GroupName),
    
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Mutual Recursion
// Group: ~w
// Uses F# mutual recursion with "and" keyword

open System
open System.Collections.Generic

let private memo = Dictionary<string, bool>()

// Mutually recursive functions using "and"
let rec is_even n =
    let key = sprintf "is_even:%d" n
    match memo.TryGetValue(key) with
    | true, v -> v
    | false, _ ->
        let result =
            match n with
            | 0 -> true
            | n when n > 0 -> is_odd (n - 1)
            | _ -> false
        memo.[key] <- result
        result

and is_odd n =
    let key = sprintf "is_odd:%d" n
    match memo.TryGetValue(key) with
    | true, v -> v
    | false, _ ->
        let result =
            match n with
            | 0 -> false
            | n when n > 0 -> is_even (n - 1)
            | _ -> false
        memo.[key] <- result
        result

let clearMemo () = memo.Clear()

[<EntryPoint>]
let main argv =
    if argv.Length >= 2 then
        let func = argv.[0]
        let n = int argv.[1]
        match func with
        | "is_even" -> printfn "%b" (is_even n)
        | "is_odd" -> printfn "%b" (is_odd n)
        | _ -> printfn "Unknown function"
    0
', [GroupName]).

%% compile_facts_to_fsharp(+Pred, +Arity, -Code)
compile_facts_to_fsharp(Pred, Arity, Code) :-
    compile_predicate_to_fsharp(Pred/Arity, [], Code).

%% write_fsharp_program(+Code, +Filename)
write_fsharp_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('F# program written to: ~w~n', [Filename]).

%% Helper predicates
generate_fsharp_fields(Arity, Fields) :-
    findall(Field, (
        between(1, Arity, N),
        format(string(Field), 'Arg~w: string', [N])
    ), FieldList),
    atomic_list_concat(FieldList, '\n    ', Fields).

generate_fsharp_fact_entry(Args, Entry) :-
    findall(FieldVal, (
        nth1(N, Args, Arg),
        format(string(FieldVal), 'Arg~w = "~w"', [N, Arg])
    ), FieldVals),
    atomic_list_concat(FieldVals, '; ', FieldsStr),
    format(string(Entry), '{ ~w }', [FieldsStr]).

generate_fsharp_print_pattern(Arity, Pattern) :-
    findall('%s', between(1, Arity, _), Placeholders),
    atomic_list_concat(Placeholders, ':', Pattern).

generate_fsharp_print_args(Arity, Result) :-
    findall(Arg, (
        between(1, Arity, N),
        format(string(Arg), 'fact.Arg~w', [N])
    ), Args),
    atomic_list_concat(Args, ' ', Result).

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(fsharp, PredStr, Arity, BaseClauses, RecClauses, AccPos, StepOp, ExitAfterResult, Code) :-
    tail_recursion:compile_tail_pattern_(fsharp, PredStr, Arity, BaseClauses, RecClauses, AccPos, StepOp, ExitAfterResult, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, Code).
tail_recursion:compile_tail_pattern_(fsharp, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    (   Arity =:= 3 ->
        step_op_to_fsharp(StepOp, FSharpStepExpr),
        format(string(Code),
'// Generated by UnifyWeaver F# Target - Tail Recursion (multifile dispatch)
// Predicate: ~w/~w

open System

let ~w (items: int list) =
    let rec loop remaining acc =
        match remaining with
        | [] -> acc
        | item :: rest -> loop rest (~w)
    loop items 0

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let items = argv.[0].Split('','') |> Array.map int |> Array.toList
        printfn "%d" (~w items)
    0
', [PredStr, Arity, PredStr, FSharpStepExpr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'// Generated by UnifyWeaver F# Target - Tail Recursion (binary, multifile dispatch)
// Predicate: ~w/~w

open System

let ~w (items: ''a list) =
    let rec loop remaining count =
        match remaining with
        | [] -> count
        | _ :: rest -> loop rest (count + 1)
    loop items 0

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let items = argv.[0].Split('','') |> Array.toList
        printfn "%d" (~w items)
    0
', [PredStr, Arity, PredStr, PredStr])
    ;   format('Warning: F# tail recursion with arity ~w not supported~n', [Arity]),
        fail
    ).

%% step_op_to_fsharp(+StepOp, -FSharpExpr)
step_op_to_fsharp(arithmetic(Expr), FSharpExpr) :-
    expr_to_fsharp(Expr, FSharpExpr).
step_op_to_fsharp(unknown, 'acc + 1').

%% expr_to_fsharp(+PrologExpr, -FSharpExpr)
expr_to_fsharp(_ + Const, FSharpExpr) :- integer(Const), !,
    format(atom(FSharpExpr), 'acc + ~w', [Const]).
expr_to_fsharp(_ + _, 'acc + item') :- !.
expr_to_fsharp(_ - _, 'acc - item') :- !.
expr_to_fsharp(_ * _, 'acc * item') :- !.
expr_to_fsharp(_, 'acc + 1').

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(fsharp, PredStr, Arity, BaseClauses, RecClauses, MemoEnabled, MemoStrategy, Code) :-
    linear_recursion:compile_linear_pattern_(fsharp, PredStr, Arity, BaseClauses, RecClauses, MemoEnabled, MemoStrategy, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, Code).
linear_recursion:compile_linear_pattern_(fsharp, PredStr, Arity, BaseClauses, RecClauses, MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_based_fsharp(PredStr, BaseClauses, RecClauses, MemoEnabled, Code)
    ;   linear_generic_fsharp(PredStr, Arity, MemoEnabled, Code)
    ).

%% linear_fold_based_fsharp(+PredStr, +BaseClauses, +RecClauses, +MemoEnabled, -Code)
linear_fold_based_fsharp(PredStr, BaseClauses, RecClauses, MemoEnabled, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    (   InputType = numeric ->
        linear_numeric_fsharp(PredStr, BaseInput, BaseOutput, RecClauses, MemoEnabled, Code)
    ;   InputType = list ->
        linear_list_fsharp(PredStr, BaseOutput, RecClauses, MemoEnabled, Code)
    ;   linear_generic_fsharp(PredStr, 2, MemoEnabled, Code)
    ).

%% linear_numeric_fsharp(+PredStr, +BaseInput, +BaseOutput, +RecClauses, +MemoEnabled, -Code)
linear_numeric_fsharp(PredStr, BaseInput, BaseOutput, RecClauses, MemoEnabled, Code) :-
    % Extract fold operation from rec clauses
    atom_string(Pred, PredStr),
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
    partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRecClauses, _),
    (   ActualRecClauses = [clause(RHead, RBody)|_] ->
        RHead =.. [_, InputVar, _],
        linear_recursion:find_recursive_call(RBody, RecCall),
        RecCall =.. [_, _, AccVar],
        linear_recursion:find_last_is_expression(RBody, _ is ActualFoldExpr),
        translate_fold_expr_fsharp(ActualFoldExpr, InputVar, AccVar, FSharpFoldOp)
    ;   RecClauses = [clause(RHead2, RBody2)|_] ->
        RHead2 =.. [_, InputVar2, _],
        linear_recursion:find_recursive_call(RBody2, RecCall2),
        RecCall2 =.. [_, _, AccVar2],
        linear_recursion:find_last_is_expression(RBody2, _ is ActualFoldExpr2),
        translate_fold_expr_fsharp(ActualFoldExpr2, InputVar2, AccVar2, FSharpFoldOp)
    ;   FSharpFoldOp = "current * acc"
    ),

    (   MemoEnabled = true ->
        format(string(MemoDecl), 'let private memo = System.Collections.Generic.Dictionary<int, int>()', []),
        format(string(MemoCheck), '    match memo.TryGetValue(n) with~n    | true, v -> v~n    | false, _ ->', []),
        format(string(MemoStore), '        memo.[n] <- result~n        result', [])
    ;   MemoDecl = '// Memoization disabled',
        MemoCheck = '    let compute () =',
        MemoStore = '        result'
    ),

    format(string(Code),
'// Generated by UnifyWeaver F# Target - Linear Recursion (numeric fold, multifile dispatch)
// Predicate: ~w/2

open System
open System.Collections.Generic

~w

let ~w_op current acc = ~w

let rec ~w n =
~w
        let result =
            match n with
            | ~w -> ~w
            | n -> ~w_op n (~w (n - 1))
~w

let clearMemo () = memo.Clear()

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let n = int argv.[0]
        printfn "%d" (~w n)
    0
', [PredStr, MemoDecl, PredStr, FSharpFoldOp, PredStr, MemoCheck, BaseInput, BaseOutput, PredStr, PredStr, MemoStore, PredStr]).

%% linear_list_fsharp(+PredStr, +BaseOutput, +RecClauses, +MemoEnabled, -Code)
linear_list_fsharp(PredStr, BaseOutput, _RecClauses, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        MemoDecl = "let private memo = System.Collections.Generic.Dictionary<string, int>()"
    ;   MemoDecl = "// Memoization disabled"
    ),
    format(string(Code),
'// Generated by UnifyWeaver F# Target - Linear Recursion (list fold, multifile dispatch)
// Predicate: ~w/2

open System
open System.Collections.Generic

~w

let rec ~w (lst: int list) =
    match lst with
    | [] -> ~w
    | h :: t -> h + (~w t)

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let items = argv.[0].Split('','') |> Array.map int |> Array.toList
        printfn "%d" (~w items)
    0
', [PredStr, MemoDecl, PredStr, BaseOutput, PredStr, PredStr]).

%% linear_generic_fsharp(+PredStr, +Arity, +MemoEnabled, -Code)
linear_generic_fsharp(PredStr, Arity, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        format(string(Code),
'// Generated by UnifyWeaver F# Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

open System
open System.Collections.Generic

let private memo = System.Collections.Generic.Dictionary<int, int>()

let rec ~w n =
    match memo.TryGetValue(n) with
    | true, v -> v
    | false, _ ->
        let result =
            match n with
            | n when n <= 0 -> 0
            | 1 -> 1
            | n -> (~w (n - 1)) + n
        memo.[n] <- result
        result

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let n = int argv.[0]
        printfn "%d" (~w n)
    0
', [PredStr, Arity, PredStr, PredStr, PredStr])
    ;   format(string(Code),
'// Generated by UnifyWeaver F# Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

open System

let rec ~w n =
    match n with
    | n when n <= 0 -> 0
    | 1 -> 1
    | n -> (~w (n - 1)) + n

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        let n = int argv.[0]
        printfn "%d" (~w n)
    0
', [PredStr, Arity, PredStr, PredStr, PredStr])
    ).

%% translate_fold_expr_fsharp(+PrologExpr, +InputVar, +AccVar, -FSharpExpr)
translate_fold_expr_fsharp(Expr, InputVar, AccVar, FSharpExpr) :-
    translate_fsharp_expr(Expr, InputVar, AccVar, FSharpExpr).

translate_fsharp_expr(A * B, InputVar, AccVar, FSharpExpr) :-
    translate_fsharp_term(A, InputVar, AccVar, AT),
    translate_fsharp_term(B, InputVar, AccVar, BT),
    format(string(FSharpExpr), '~w * ~w', [AT, BT]).
translate_fsharp_expr(A + B, InputVar, AccVar, FSharpExpr) :-
    translate_fsharp_term(A, InputVar, AccVar, AT),
    translate_fsharp_term(B, InputVar, AccVar, BT),
    format(string(FSharpExpr), '~w + ~w', [AT, BT]).
translate_fsharp_expr(A - B, InputVar, AccVar, FSharpExpr) :-
    translate_fsharp_term(A, InputVar, AccVar, AT),
    translate_fsharp_term(B, InputVar, AccVar, BT),
    format(string(FSharpExpr), '~w - ~w', [AT, BT]).
translate_fsharp_expr(Term, InputVar, AccVar, FSharpExpr) :-
    translate_fsharp_term(Term, InputVar, AccVar, FSharpExpr).

translate_fsharp_term(Term, InputVar, _AccVar, 'current') :-
    Term == InputVar, !.
translate_fsharp_term(Term, _InputVar, AccVar, 'acc') :-
    Term == AccVar, !.
translate_fsharp_term(Number, _, _, FSharpTerm) :-
    integer(Number), !,
    format(string(FSharpTerm), '~w', [Number]).
translate_fsharp_term(Atom, _, _, FSharpTerm) :-
    format(string(FSharpTerm), '~w', [Atom]).

% ============================================================================
% MULTIFILE DISPATCH - Mutual Recursion
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(fsharp, Predicates, MemoEnabled, MemoStrategy, Code) :-
    mutual_recursion:compile_mutual_pattern_(fsharp, Predicates, MemoEnabled, MemoStrategy, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, Code).
mutual_recursion:compile_mutual_pattern_(fsharp, Predicates, MemoEnabled, MemoStrategy, Code) :-
    findall(PredStr, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr)
    ), PredStrs),
    atomic_list_concat(PredStrs, '_', GroupName),

    % Generate header
    (   MemoEnabled = true ->
        format(string(MemoDecl),
'open System.Collections.Generic

let private memo = Dictionary<string, bool>()', [])
    ;   MemoDecl = '// Shared memoization disabled'
    ),
    format(string(HeaderCode),
'// Generated by UnifyWeaver F# Target - Mutual Recursion (multifile dispatch)
// Group: ~w
// Constraints: memo=~w, strategy=~w

open System

~w
', [GroupName, MemoEnabled, MemoStrategy, MemoDecl]),

    % Generate mutually recursive function block
    mutual_functions_fsharp(Predicates, MemoEnabled, FunctionsCode),

    % Generate dispatch
    mutual_dispatch_fsharp(Predicates, DispatchCode),

    atomic_list_concat([HeaderCode, '\n', FunctionsCode, '\n\n', DispatchCode], Code).

%% mutual_functions_fsharp(+Predicates, +MemoEnabled, -Code)
mutual_functions_fsharp(Predicates, MemoEnabled, Code) :-
    mutual_functions_fsharp_(Predicates, Predicates, MemoEnabled, first, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', Code).

mutual_functions_fsharp_([], _AllPreds, _MemoEnabled, _Pos, []).
mutual_functions_fsharp_([Pred/Arity|Rest], AllPreds, MemoEnabled, Pos, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    % Get clauses for this predicate
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),

    % Keyword: first function uses 'let rec', others use 'and'
    (   Pos = first -> Keyword = "let rec"
    ;   Keyword = "and"
    ),

    % Base cases
    mutual_base_cases_fsharp(BaseClauses, BaseParts),

    % Recursive cases
    mutual_rec_cases_fsharp(RecClauses, MemoEnabled, RecParts),

    % Combine match arms
    append(BaseParts, RecParts, AllParts),
    (   AllParts = [] ->
        MatchCode = "    | _ -> false"
    ;   atomic_list_concat(AllParts, '\n', MatchCode)
    ),

    % Memo wrapping
    (   MemoEnabled = true ->
        format(string(FuncCode),
'~w ~w n =
    let key = sprintf "~w:%d" n
    match memo.TryGetValue(key) with
    | true, v -> v
    | false, _ ->
        let result =
            match n with
~w
            | _ -> false
        memo.[key] <- result
        result', [Keyword, PredStr, PredStr, MatchCode])
    ;   format(string(FuncCode),
'~w ~w n =
    match n with
~w
    | _ -> false', [Keyword, PredStr, MatchCode])
    ),

    mutual_functions_fsharp_(Rest, AllPreds, MemoEnabled, subsequent, RestCodes).

%% mutual_base_cases_fsharp(+BaseClauses, -Parts)
mutual_base_cases_fsharp([], []).
mutual_base_cases_fsharp([clause(Head, true)|Rest], [Part|RestParts]) :-
    Head =.. [_Pred, Value],
    (   Value == 0 -> format(string(Part), '            | 0 -> true', [])
    ;   Value == 1 -> format(string(Part), '            | 1 -> true', [])
    ;   format(string(Part), '            | ~w -> true', [Value])
    ),
    mutual_base_cases_fsharp(Rest, RestParts).
mutual_base_cases_fsharp([_|Rest], RestParts) :-
    mutual_base_cases_fsharp(Rest, RestParts).

%% mutual_rec_cases_fsharp(+RecClauses, +MemoEnabled, -Parts)
mutual_rec_cases_fsharp([], _MemoEnabled, []).
mutual_rec_cases_fsharp([clause(Head, Body)|Rest], MemoEnabled, [Part|RestParts]) :-
    Head =.. [_Pred|_Args],
    % Extract the guard condition and recursive call from body
    extract_mutual_rec_info_fsharp(Body, Guard, CalledPred, ArgExpr),
    (   Guard = (N > Threshold) ->
        (   var(N) -> GuardStr = "n"
        ;   format(string(GuardStr), '~w', [N])
        ),
        format(string(Part), '            | n when ~w > ~w -> ~w (n ~w)', [GuardStr, Threshold, CalledPred, ArgExpr])
    ;   format(string(Part), '            | n -> ~w (n ~w)', [CalledPred, ArgExpr])
    ),
    mutual_rec_cases_fsharp(Rest, MemoEnabled, RestParts).
mutual_rec_cases_fsharp([_|Rest], MemoEnabled, RestParts) :-
    mutual_rec_cases_fsharp(Rest, MemoEnabled, RestParts).

%% extract_mutual_rec_info_fsharp(+Body, -Guard, -CalledPred, -ArgExpr)
extract_mutual_rec_info_fsharp(Body, Guard, CalledPred, ArgExpr) :-
    extract_goals_from_body(Body, Goals),
    % Find guard (comparison)
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    % Find the recursive call (non-arithmetic, non-comparison goal)
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    % Find arithmetic step (N1 is N - 1 pattern)
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(ArgExpr), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(ArgExpr), '- ~w', [AbsK])
    ;   ArgExpr = "- 1"
    ).

%% extract_goals_from_body(+Body, -Goals)
extract_goals_from_body((A, B), Goals) :- !,
    extract_goals_from_body(A, GA),
    extract_goals_from_body(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body(true, []) :- !.
extract_goals_from_body(Goal, [Goal]).

%% mutual_dispatch_fsharp(+Predicates, -Code)
mutual_dispatch_fsharp(Predicates, Code) :-
    findall(MatchArm, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(MatchArm), '        | "~w" -> printfn "%b" (~w n)', [PredStr, PredStr])
    ), Arms),
    atomic_list_concat(Arms, '\n', ArmsCode),
    format(string(Code),
'[<EntryPoint>]
let main argv =
    if argv.Length >= 2 then
        let func = argv.[0]
        let n = int argv.[1]
        match func with
~w
        | _ -> printfn "Unknown function"
    0
', [ArmsCode]).

% ============================================================================
% TREE RECURSION - F# target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(fsharp, Pattern, Pred, Arity, UseMemo, FsCode) :-
    tree_recursion:compile_tree_pattern_(fsharp, Pattern, Pred, Arity, UseMemo, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, FsCode).
tree_recursion:compile_tree_pattern_(fsharp, _Pattern, Pred, _Arity, _UseMemo, FsCode) :-
    atom_string(Pred, PredStr),
    format(string(FsCode),
'// Generated by UnifyWeaver F# Target - Tree Recursion (fibonacci, multifile dispatch)
open System
open System.Collections.Generic

let private memo = Dictionary<int, int>()

let rec ~w n =
    if n <= 0 then 0
    elif n = 1 then 1
    elif memo.ContainsKey(n) then memo.[n]
    else
        let result = ~w (n - 1) + ~w (n - 2)
        memo.[n] <- result
        result

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        printfn "%d" (~w (int argv.[0]))
    0
', [PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTICALL LINEAR RECURSION - F# target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(fsharp, PredStr, BaseClauses, RecClauses, MemoEnabled, FsCode) :-
    multicall_linear_recursion:compile_multicall_pattern_(fsharp, PredStr, BaseClauses, RecClauses, MemoEnabled, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, FsCode).
multicall_linear_recursion:compile_multicall_pattern_(fsharp, PredStr, BaseClauses, _RecClauses, _MemoEnabled, FsCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    | ~w -> ~w', [BInput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(FsCode),
'// Generated by UnifyWeaver F# Target - Multicall Linear Recursion (multifile dispatch)
open System
open System.Collections.Generic

let private memo = Dictionary<int, int>()

let rec ~w n =
    match n with
~w
    | _ when memo.ContainsKey(n) -> memo.[n]
    | _ ->
        let result = ~w (n - 1) + ~w (n - 2)
        memo.[n] <- result
        result

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        printfn "%d" (~w (int argv.[0]))
    0
', [PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% DIRECT MULTI-CALL RECURSION - F# target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- use_module('../core/advanced/pattern_matchers', [is_per_path_visited_pattern/4]).
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(fsharp, PredStr, BaseClauses, RecClause, FsCode) :-
    direct_multi_call_recursion:compile_direct_multicall_pattern_(fsharp, PredStr, BaseClauses, RecClause, RawCode),
    fsharp_ensure_fsi_compatible(RawCode, FsCode).
direct_multi_call_recursion:compile_direct_multicall_pattern_(fsharp, PredStr, BaseClauses, _RecClause, FsCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '        | ~w -> memo.[~w] <- ~w; ~w', [BInput, BInput, BOutput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(FsCode),
'// Generated by UnifyWeaver F# Target - Direct Multicall Recursion (multifile dispatch)
open System
open System.Collections.Generic

let private memo = Dictionary<int, int>()

let rec ~w input =
    if memo.ContainsKey(input) then memo.[input]
    else
        match input with
~w
        | _ ->
            let result = ~w (input - 1) + ~w (input - 2)
            memo.[input] <- result
            result

[<EntryPoint>]
let main argv =
    if argv.Length >= 1 then
        printfn "%d" (~w (int argv.[0]))
    0
', [PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

%% ============================================
%% GENERAL RECURSIVE PATTERN (visited-set cycle safety)
%% ============================================

:- multifile advanced_recursive_compiler:compile_general_recursive_pattern/6.

%% No-visited-pattern — plain recursive without cycle detection
advanced_recursive_compiler:compile_general_recursive_pattern(fsharp, PredStr, Arity, BaseClauses, RecClauses, Code) :-
    atom_string(Pred, PredStr),
    append(BaseClauses, RecClauses, AllClauses),
    \+ is_per_path_visited_pattern(Pred, Arity, AllClauses, _),
    !,
    (   BaseClauses = [(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs], last(BaseArgs, BaseResult)
    ->  term_to_atom(BaseResult, BaseValAtom), atom_string(BaseValAtom, BaseValStr),
        BaseArgs = [BaseInput|_], term_to_atom(BaseInput, BaseInAtom), atom_string(BaseInAtom, BaseInStr)
    ;   BaseValStr = "[]", BaseInStr = "0"
    ),
    format(string(Code),
'// General recursive: ~w (plain, no visited pattern)\n\c
\n\c
let rec ~w arg1 =\n\c
    if arg1 = ~w then [~w]\n\c
    else ~w (string arg1)\n',
    [PredStr, PredStr, BaseInStr, BaseValStr, PredStr]).

advanced_recursive_compiler:compile_general_recursive_pattern(fsharp, PredStr, _Arity, BaseClauses, _RecClauses, Code) :-
    %% Extract base value from first base clause
    (   BaseClauses = [(BaseHead, _BaseBody)|_],
        BaseHead =.. [_|BaseArgs],
        last(BaseArgs, BaseResult)
    ->  term_to_atom(BaseResult, BaseValAtom),
        atom_string(BaseValAtom, BaseValStr)
    ;   BaseValStr = "[]"
    ),
    %% Extract base input from first base clause
    (   BaseClauses = [(BaseHead2, _)|_],
        BaseHead2 =.. [_|BaseArgs2],
        BaseArgs2 = [BaseInput|_]
    ->  term_to_atom(BaseInput, BaseInAtom),
        atom_string(BaseInAtom, BaseInStr)
    ;   BaseInStr = "0"
    ),
    string_concat(PredStr, "Worker", WorkerStr),
    format(string(Code),
'// Generated by UnifyWeaver F# Target - General Recursion with Visited Set

let ~w arg1 = ~w arg1 Set.empty

let rec ~w arg1 visited =
    if Set.contains arg1 visited then []
    else if arg1 = ~w then [~w]
    else
        let visited = Set.add arg1 visited in
        ~w (string arg1) visited',
        [PredStr, WorkerStr,
         WorkerStr,
         BaseInStr, BaseValStr,
         WorkerStr]).
