:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% haskell_target.pl - Haskell Code Generation Target
%
% Compiles Prolog predicates to Haskell for:
% - Type-safe functional programming integration
% - Pattern matching natural fit with Prolog clauses
% - Lazy evaluation for streams and backtracking
% - GHC optimization (tail call elimination)
% - Parsec parser combinators from DCGs

:- module(haskell_target, [
    % Standard interface (for target_module/2)
    target_info/1,                      % -Info
    compile_predicate/3,                % +Pred/Arity, +Options, -Code
    
    % Legacy interface
    compile_predicate_to_haskell/3,     % +Pred/Arity, +Options, -HaskellCode
    compile_facts_to_haskell/3,         % +Pred, +Arity, -HaskellCode
    compile_rules_to_haskell/3,         % +Pred/Arity, +Options, -HaskellCode
    compile_recursion_to_haskell/3,     % +Pred/Arity, +Options, -HaskellCode
    compile_module_to_haskell/3,        % +Predicates, +Options, -HaskellCode
    
    % Parsec (DCG → Parser Combinators)
    compile_dcg_to_parsec/3,            % +DCG, +Options, -HaskellCode
    compile_grammar_to_parsec/3,        % +GrammarRules, +Options, -HaskellCode
    
    % File output
    write_haskell_module/2,             % +Code, +Filename
    init_haskell_target/0
]).

:- use_module(library(lists)).
:- use_module(library(option)).
:- use_module('../core/clause_body_analysis').

%% ============================================
%% TARGET INFO (Standard Interface)
%% ============================================

target_info(info{
    name: "Haskell",
    family: functional,
    file_extension: ".hs",
    runtime: ghc,
    features: [types, lazy, pattern_matching, type_classes, monads],
    recursion_patterns: [tail_recursion, linear_recursion, list_fold, list_tail_recursion, transitive_closure],
    parser_support: parsec,
    compile_command: "ghc -O2"
}).

%% ============================================
%% STANDARD INTERFACE
%% ============================================

%% compile_predicate(+Pred/Arity, +Options, -Code)
%  Standard interface for target_module/2 dispatch
compile_predicate(PredArity, Options, Code) :-
    compile_predicate_to_haskell(PredArity, Options, Code).

%% init_haskell_target
init_haskell_target :-
    format('[Haskell Target] Initialized~n', []).

%% ============================================
%% COMPILE PREDICATE (dispatcher)
%% ============================================

% Try native clause body lowering first
compile_predicate_to_haskell(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    Clauses \= [],
    native_haskell_clause_body(Pred/Arity, Clauses, FuncBody),
    !,
    atom_string(Pred, PredStr),
    capitalize(PredStr, ModCap),
    Arity1 is Arity - 1,
    build_haskell_arg_list(Arity1, ArgList),
    build_haskell_type_sig(Arity1, TypeSig),
    option(module_name(ModName), Options, ModCap),
    capitalize(ModName, ModCapName),
    % Detect if body uses guards (starts with "  |") or is a direct expression
    (   sub_string(FuncBody, 0, _, _, "  |")
    ->  format(string(Code),
'-- Generated by UnifyWeaver Haskell Target - Native Clause Lowering
module ~w where

~w :: ~w
~w ~w
~w
', [ModCapName, PredStr, TypeSig, PredStr, ArgList, FuncBody])
    ;   format(string(Code),
'-- Generated by UnifyWeaver Haskell Target - Native Clause Lowering
module ~w where

~w :: ~w
~w ~w= ~w
', [ModCapName, PredStr, TypeSig, PredStr, ArgList, FuncBody])
    ).

% Fallback to existing dispatch
compile_predicate_to_haskell(Pred/Arity, Options, Code) :-
    option(type(Type), Options, facts),
    (   Type == facts
    ->  compile_facts_to_haskell(Pred, Arity, Code)
    ;   Type == recursion
    ->  compile_recursion_to_haskell(Pred/Arity, Options, Code)
    ;   Type == rules
    ->  compile_rules_to_haskell(Pred/Arity, Options, Code)
    ;   compile_facts_to_haskell(Pred, Arity, Code)
    ).

%% ============================================
%% FACTS → LIST OF TUPLES
%% ============================================

%% compile_facts_to_haskell(+Pred, +Arity, -HaskellCode)
%  Compile facts to a list of tuples
compile_facts_to_haskell(Pred, Arity, Code) :-
    atom_string(Pred, PredStr),
    capitalize(PredStr, TypeName),
    
    % Generate fact tuples
    findall(Tuple, (
        functor(Goal, Pred, Arity),
        call(Goal),
        Goal =.. [_|Args],
        format_tuple(Args, Tuple)
    ), Tuples),
    
    % Build list representation
    atomic_list_concat(Tuples, ', ', TupleList),
    
    % Generate type signature
    generate_type_sig(Arity, TypeSig),
    
    format(string(Code),
'{-# LANGUAGE DeriveGeneric #-}
-- Generated by UnifyWeaver Haskell Target
module ~w where

import GHC.Generics (Generic)

-- | Facts for ~w/~w
~w :: [~w]
~w = [~w]

-- | Query function
is~w :: ~w -> Bool
is~w args = args `elem` ~w
', [TypeName, PredStr, Arity, PredStr, TypeSig, PredStr, TupleList,
    TypeName, TypeSig, TypeName, PredStr]).

%% format_tuple(+Args, -TupleStr)
format_tuple([Arg], Str) :-
    format_arg(Arg, Str).
format_tuple(Args, Str) :-
    Args = [_,_|_],
    maplist(format_arg, Args, ArgStrs),
    atomic_list_concat(ArgStrs, ', ', Inner),
    format(string(Str), '(~w)', [Inner]).

format_arg(Arg, Str) :-
    atom(Arg),
    atom_string(Arg, S),
    capitalize(S, Str).
format_arg(Arg, Str) :-
    number(Arg),
    number_string(Arg, Str).
format_arg(Arg, Str) :-
    string(Arg),
    format(string(Str), '"~w"', [Arg]).

%% generate_type_sig(+Arity, -TypeSig)
generate_type_sig(1, "String").
generate_type_sig(2, "(String, String)").
generate_type_sig(3, "(String, String, String)").
generate_type_sig(N, Sig) :-
    N > 3,
    length(Types, N),
    maplist(=("String"), Types),
    atomic_list_concat(Types, ', ', Inner),
    format(string(Sig), '(~w)', [Inner]).

%% capitalize(+Str, -Capitalized)
capitalize(Str, Cap) :-
    atom_string(Str, S),
    string_chars(S, [H|T]),
    upcase_atom(H, HU),
    atom_chars(HU, [HC]),
    string_chars(Cap, [HC|T]).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_haskell_arg_list(+N, -ArgList)
%  Generates "arg1 arg2 " (trailing space for format convenience)
build_haskell_arg_list(0, "") :- !.
build_haskell_arg_list(N, ArgList) :-
    findall(ArgName, (
        between(1, N, I),
        format(string(ArgName), 'arg~w', [I])
    ), ArgNames),
    atomic_list_concat(ArgNames, ' ', ArgListNoTrail),
    format(string(ArgList), '~w ', [ArgListNoTrail]).

%% build_haskell_type_sig(+InputArity, -TypeSig)
%  Generates "Int -> Int -> String" (inputs are Int, output is String)
build_haskell_type_sig(0, "String") :- !.
build_haskell_type_sig(N, TypeSig) :-
    findall("Int", between(1, N, _), InputTypes),
    append(InputTypes, ["String"], AllTypes),
    atomic_list_concat(AllTypes, ' -> ', TypeSig).

%% native_haskell_clause_body(+PredSpec, +Clauses, -Code)

% Single clause
native_haskell_clause_body(PredSpec, [Head-Body], Code) :-
    native_haskell_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !,
    (   Condition == "true"
    ->  Code = ClauseCode
    ;   format(string(Code),
'if ~w then ~w else error "No matching clause for ~w"', [Condition, ClauseCode, PredSpec])
    ).

% Multi-clause — use guards
native_haskell_clause_body(PredSpec, Clauses, Code) :-
    Clauses = [_|[_|_]],
    maplist(native_haskell_clause_pair(PredSpec), Clauses, Branches),
    Branches \= [],
    branches_to_haskell_guards(Branches, PredSpec, Code).

native_haskell_clause_pair(PredSpec, Head-Body, branch(Condition, ClauseCode)) :-
    native_haskell_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !.

%% native_haskell_clause(+PredSpec, +Head, +Body, -Condition, -Code)
native_haskell_clause(_PredSpec, Head, Body, Condition, Code) :-
    Head =.. [_Pred|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputHeadArgs, [OutputHeadArg], HeadArgs),
        haskell_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ;   OutputHeadArg = _,
        haskell_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ),
    normalize_goals(Body, Goals),
    (   Goals == []
    ->  haskell_resolve_value(VarMap, OutputHeadArg, OutputExpr),
        Code = OutputExpr,
        GoalConditions = []
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
            maplist(haskell_guard_condition(VarMap), GuardGoals, GoalConditions),
            (   OutputGoals == []
            ->  haskell_literal(OutputHeadArg, Code)
            ;   haskell_output_goals(OutputGoals, VarMap, Code)
            )
        ;   native_haskell_goal_sequence(Goals, VarMap, GoalConditions, Code)
        )
    ),
    append(HeadConditions, GoalConditions, AllConditions),
    combine_haskell_conditions(AllConditions, Condition).

%% haskell_head_conditions(+HeadArgs, +Index, +Arity, -Conditions)
haskell_head_conditions([], _, _, []).
haskell_head_conditions([_], _, Arity, []) :- Arity > 1, !.
haskell_head_conditions([HeadArg|Rest], Index, Arity, Conditions) :-
    (   var(HeadArg)
    ->  Conditions = RestConditions
    ;   format(string(ArgName), 'arg~w', [Index]),
        haskell_literal(HeadArg, Literal),
        format(string(Cond), '~w == ~w', [ArgName, Literal]),
        Conditions = [Cond|RestConditions]
    ),
    NextIndex is Index + 1,
    haskell_head_conditions(Rest, NextIndex, Arity, RestConditions).

%% native_haskell_goal_sequence(+Goals, +VarMap, -Conditions, -Code)
%  Uses classify_goal_sequence for advanced pattern detection.
%  Falls back to clause_guard_output_split if classification fails.
native_haskell_goal_sequence(Goals, VarMap, Conditions, Code) :-
    classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
    ClassifiedGoals \= [],
    haskell_render_classified_goals(ClassifiedGoals, VarMap, Conditions, Lines),
    Lines \= [],
    atomic_list_concat(Lines, '\n', Code),
    !.
native_haskell_goal_sequence(Goals, VarMap, Conditions, Code) :-
    clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
    maplist(haskell_guard_condition(VarMap), GuardGoals, Conditions),
    haskell_output_goals(OutputGoals, VarMap, Code).

%% haskell_render_classified_goals(+ClassifiedGoals, +VarMap, -Conditions, -Lines)
haskell_render_classified_goals([], _VarMap, [], []).
haskell_render_classified_goals([Classified], VarMap, Conds, Lines) :-
    !,
    haskell_render_classified_last(Classified, VarMap, Conds, Lines).
%% Guarded tail: output followed by guard(s)
haskell_render_classified_goals([output(Goal, _, _)|Rest], VarMap, [], Lines) :-
    Rest = [guard(_, _)|_],
    !,
    haskell_output_goal(Goal, VarMap, LetBinding, VarMap1),
    haskell_collect_trailing_guards(Rest, VarMap1, GuardGoals, _Remaining),
    maplist(haskell_guard_condition(VarMap1), GuardGoals, GuardConds),
    atomic_list_concat(GuardConds, ' && ', GuardExpr),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMap1, OutName)
    ->  true
    ;   OutName = '_'
    ),
    format(string(IfLine), 'if ~w then ~w else error "guard failed"', [GuardExpr, OutName]),
    Lines = [LetBinding, IfLine].
haskell_render_classified_goals([Classified|Rest], VarMap, Conds, Lines) :-
    haskell_render_classified_mid(Classified, VarMap, MidConds, MidLines, VarMap1),
    haskell_render_classified_goals(Rest, VarMap1, RestConds, RestLines),
    append(MidConds, RestConds, Conds),
    append(MidLines, RestLines, Lines).

%% haskell_render_classified_mid(+Classified, +VarMap, -Conds, -Lines, -VarMapOut)
haskell_render_classified_mid(guard(Goal, _), VarMap, [Cond], [], VarMap) :-
    haskell_guard_condition(VarMap, Goal, Cond).
haskell_render_classified_mid(output(Goal, _, _), VarMap0, [], [Line], VarMapOut) :-
    haskell_output_goal(Goal, VarMap0, Line, VarMapOut).
haskell_render_classified_mid(output_ite(If, Then, Else, _SharedVars), VarMap0, [], [Line], VarMap0) :-
    haskell_guard_condition(VarMap0, If, Cond),
    haskell_branch_value(Then, VarMap0, ThenExpr),
    haskell_branch_value(Else, VarMap0, ElseExpr),
    format(string(Line), 'if ~w then ~w else ~w', [Cond, ThenExpr, ElseExpr]).
haskell_render_classified_mid(passthrough(Goal), VarMap0, [], [Line], VarMapOut) :-
    haskell_output_goal(Goal, VarMap0, Line, VarMapOut).
haskell_render_classified_mid(_, VarMap, [], [], VarMap).

%% haskell_render_classified_last(+Classified, +VarMap, -Conds, -Lines)
haskell_render_classified_last(guard(Goal, _), VarMap, [Cond], []) :-
    haskell_guard_condition(VarMap, Goal, Cond).
haskell_render_classified_last(output(Goal, _, _), VarMap, [], Lines) :-
    haskell_render_output_goal_last(Goal, VarMap, Lines).
haskell_render_classified_last(output_ite(If, Then, Else, _), VarMap, [], [Line]) :-
    haskell_guard_condition(VarMap, If, Cond),
    haskell_branch_value(Then, VarMap, ThenExpr),
    haskell_branch_value(Else, VarMap, ElseExpr),
    format(string(Line), 'if ~w then ~w else ~w', [Cond, ThenExpr, ElseExpr]).
haskell_render_classified_last(output_disj(Alternatives, _SharedVars), VarMap, [], Lines) :-
    haskell_disj_if_chain(Alternatives, VarMap, Lines).
haskell_render_classified_last(passthrough(Goal), VarMap, [], Lines) :-
    haskell_render_output_goal_last(Goal, VarMap, Lines).
haskell_render_classified_last(_, _, [], []).

%% haskell_render_output_goal_last(+Goal, +VarMap, -Lines)
%  3-arg wrapper used by classified goal renderers.
haskell_render_output_goal_last(Goal, VarMap, [Expr]) :-
    haskell_output_goal_last(Goal, VarMap, Expr, _VarMapOut),
    !.
haskell_render_output_goal_last(Goal, VarMap, [Expr]) :-
    haskell_branch_value(Goal, VarMap, Expr).

%% haskell_collect_trailing_guards(+ClassifiedGoals, +VarMap, -GuardGoals, -Remaining)
haskell_collect_trailing_guards([guard(Goal, _)|Rest], VarMap, [Goal|Guards], Remaining) :-
    !, haskell_collect_trailing_guards(Rest, VarMap, Guards, Remaining).
haskell_collect_trailing_guards(Remaining, _, [], Remaining).

%% haskell_disj_if_chain(+Alternatives, +VarMap, -Lines)
haskell_disj_if_chain([], _, []).
haskell_disj_if_chain([Alt], VarMap, [Line]) :-
    !,
    haskell_branch_value(Alt, VarMap, ValExpr),
    format(string(Line), 'else ~w', [ValExpr]).
haskell_disj_if_chain([Alt|Rest], VarMap, [Line|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(haskell_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = 'True'
    ),
    haskell_branch_value(Alt, VarMap, ValExpr),
    format(string(Line), 'if ~w then ~w', [CondExpr, ValExpr]),
    haskell_disj_elif_chain(Rest, VarMap, RestLines).

%% haskell_disj_elif_chain(+Alternatives, +VarMap, -Lines)
haskell_disj_elif_chain([], _, []).
haskell_disj_elif_chain([Alt], VarMap, [Line]) :-
    !,
    haskell_branch_value(Alt, VarMap, ValExpr),
    format(string(Line), 'else ~w', [ValExpr]).
haskell_disj_elif_chain([Alt|Rest], VarMap, [Line|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(haskell_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = 'True'
    ),
    haskell_branch_value(Alt, VarMap, ValExpr),
    format(string(Line), 'else if ~w then ~w', [CondExpr, ValExpr]),
    haskell_disj_elif_chain(Rest, VarMap, RestLines).

%% haskell_guard_condition(+VarMap, +Goal, -Condition)
haskell_guard_condition(VarMap, _Module:Goal, Condition) :-
    !, haskell_guard_condition(VarMap, Goal, Condition).
haskell_guard_condition(VarMap, Goal, Condition) :-
    compound(Goal),
    Goal =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    haskell_expr(Left, VarMap, HsLeft),
    haskell_expr(Right, VarMap, HsRight),
    haskell_op(StdOp, HsOp),
    format(string(Condition), '~w ~w ~w', [HsLeft, HsOp, HsRight]).

%% haskell_output_goals(+Goals, +VarMap, -Code)
haskell_output_goals([], _VarMap, 'error "no output"') :- !.
haskell_output_goals(Goals, VarMap, Code) :-
    haskell_output_goals_acc(Goals, VarMap, Parts, _VarMapOut),
    (   Parts = [SingleExpr]
    ->  Code = SingleExpr
    ;   % Multiple outputs: use let..in
        last(Parts, ResultExpr),
        append(LetParts, [_], Parts),
        atomic_list_concat(LetParts, '; ', LetBindings),
        format(string(Code), 'let ~w in ~w', [LetBindings, ResultExpr])
    ).

haskell_output_goals_acc([], VarMap, [], VarMap).
haskell_output_goals_acc([Goal], VarMap, [Expr], VarMapOut) :-
    !, haskell_output_goal_last(Goal, VarMap, Expr, VarMapOut).
haskell_output_goals_acc([Goal|Rest], VarMap0, [Binding|RestParts], VarMapOut) :-
    haskell_output_goal(Goal, VarMap0, Binding, VarMap1),
    haskell_output_goals_acc(Rest, VarMap1, RestParts, VarMapOut).

%% haskell_output_goal_last — produce the result expression
haskell_output_goal_last(_Module:Goal, VarMap, Expr, VarMapOut) :-
    !, haskell_output_goal_last(Goal, VarMap, Expr, VarMapOut).
haskell_output_goal_last(Goal, VarMap0, Expr, VarMapOut) :-
    if_then_else_goal(Goal, IfGoal, ThenGoal, ElseGoal),
    !,
    haskell_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap0, Expr, VarMapOut).
haskell_output_goal_last(=(Var, Value), VarMap, Expr, VarMap) :-
    var(Var), !,
    haskell_expr(Value, VarMap, Expr).
haskell_output_goal_last(is(Var, Value), VarMap, Expr, VarMap) :-
    var(Var), !,
    haskell_expr(Value, VarMap, Expr).
haskell_output_goal_last(Goal, VarMap0, Expr, VarMapOut) :-
    haskell_output_goal(Goal, VarMap0, Binding, VarMapOut),
    (   goal_output_var(Goal, OutVar),
        lookup_var(OutVar, VarMapOut, OutName)
    ->  format(string(Expr), 'let ~w in ~w', [Binding, OutName])
    ;   Expr = Binding
    ).

%% haskell_output_goal — produce a let binding
haskell_output_goal(_Module:Goal, VarMap0, Binding, VarMapOut) :-
    !, haskell_output_goal(Goal, VarMap0, Binding, VarMapOut).
haskell_output_goal(=(Var, Value), VarMap0, Binding, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    haskell_expr(Value, VarMap0, HsExpr),
    format(string(Binding), '~w = ~w', [VarName, HsExpr]).
haskell_output_goal(is(Var, Value), VarMap0, Binding, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    haskell_expr(Value, VarMap0, HsExpr),
    format(string(Binding), '~w = ~w', [VarName, HsExpr]).

%% haskell_if_then_else_output — generate if/then/else expression
haskell_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap0, Expr, VarMapOut) :-
    flatten_haskell_if_branches(IfGoal, ThenGoal, ElseGoal, Branches, DefaultGoal),
    haskell_guard_condition(VarMap0, IfGoal, _),  % verify guards translate
    haskell_branches_to_expr(Branches, DefaultGoal, VarMap0, Expr),
    VarMapOut = VarMap0.

flatten_haskell_if_branches(If, Then, Else, [branch(If, Then)|RestBranches], Default) :-
    if_then_else_goal(Else, If2, Then2, Else2),
    !,
    flatten_haskell_if_branches(If2, Then2, Else2, RestBranches, Default).
flatten_haskell_if_branches(If, Then, Else, [branch(If, Then)], Else).

haskell_branches_to_expr([branch(If, Then)], DefaultGoal, VarMap, Expr) :-
    !,
    haskell_guard_condition(VarMap, If, IfCond),
    haskell_branch_value(Then, VarMap, ThenVal),
    haskell_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Expr), 'if ~w then ~w else ~w', [IfCond, ThenVal, ElseVal]).
haskell_branches_to_expr(Branches, DefaultGoal, VarMap, Expr) :-
    % Multiple branches: use nested if/then/else
    haskell_nested_if_expr(Branches, DefaultGoal, VarMap, Expr).

haskell_nested_if_expr([branch(If, Then)], DefaultGoal, VarMap, Expr) :-
    !,
    haskell_guard_condition(VarMap, If, IfCond),
    haskell_branch_value(Then, VarMap, ThenVal),
    haskell_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Expr), 'if ~w then ~w else ~w', [IfCond, ThenVal, ElseVal]).
haskell_nested_if_expr([branch(If, Then)|Rest], DefaultGoal, VarMap, Expr) :-
    haskell_guard_condition(VarMap, If, IfCond),
    haskell_branch_value(Then, VarMap, ThenVal),
    haskell_nested_if_expr(Rest, DefaultGoal, VarMap, ElseExpr),
    format(string(Expr), 'if ~w then ~w else ~w', [IfCond, ThenVal, ElseExpr]).

%% haskell_branch_value — extract result value from a branch
haskell_branch_value(_Module:Goal, VarMap, Value) :-
    !, haskell_branch_value(Goal, VarMap, Value).
haskell_branch_value(Goal, VarMap, Value) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    haskell_guard_condition(VarMap, If, Cond),
    haskell_branch_value(Then, VarMap, ThenVal),
    haskell_branch_value(Else, VarMap, ElseVal),
    format(string(Value), 'if ~w then ~w else ~w', [Cond, ThenVal, ElseVal]).
haskell_branch_value((A, B), VarMap, Value) :-
    !,
    normalize_goals((A, B), Goals),
    last(Goals, LastGoal),
    haskell_branch_value(LastGoal, VarMap, Value).
haskell_branch_value(=(_, Expr), VarMap, Value) :-
    !, haskell_expr(Expr, VarMap, Value).
haskell_branch_value(is(_, Expr), VarMap, Value) :-
    !, haskell_expr(Expr, VarMap, Value).
haskell_branch_value(Goal, VarMap, Value) :-
    haskell_expr(Goal, VarMap, Value).

% ============================================================================
% MULTIFILE HOOKS — Register Haskell renderers for shared compile_expression
% ============================================================================

clause_body_analysis:render_output_goal(haskell, Goal, VarMap, Line, VarName, VarMapOut) :-
    haskell_output_goal(Goal, VarMap, Line, VarMapOut),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMapOut, VarName)
    ->  true
    ;   VarName = "_"
    ).

clause_body_analysis:render_guard_condition(haskell, Goal, VarMap, CondStr) :-
    haskell_guard_condition(VarMap, Goal, CondStr).

clause_body_analysis:render_branch_value(haskell, Branch, VarMap, ExprStr) :-
    haskell_branch_value(Branch, VarMap, ExprStr).

clause_body_analysis:render_ite_block(haskell, Cond, ThenLines, ElseLines, Indent, _ReturnVars, Lines) :-
    format(string(IfLine), '~wif ~w', [Indent, Cond]),
    format(string(ThenHead), '~w  then', [Indent]),
    haskell_indent_lines(ThenLines, Indent, IndentedThen),
    (   ElseLines \= []
    ->  format(string(ElseHead), '~w  else', [Indent]),
        haskell_indent_lines(ElseLines, Indent, IndentedElse),
        append([IfLine, ThenHead|IndentedThen], [ElseHead|IndentedElse], Lines)
    ;   append([IfLine, ThenHead|IndentedThen], [], Lines)
    ).

haskell_indent_lines([], _, []).
haskell_indent_lines([Line|Rest], Indent, [Indented|RestIndented]) :-
    format(string(Indented), '~w    ~w', [Indent, Line]),
    haskell_indent_lines(Rest, Indent, RestIndented).

%% haskell_expr — convert Prolog expression to Haskell syntax
haskell_expr(Var, VarMap, HsExpr) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  HsExpr = Name
    ;   term_string(Var, HsExpr)
    ).
haskell_expr(Expr, VarMap, HsExpr) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    haskell_expr(Left, VarMap, HsLeft),
    haskell_expr(Right, VarMap, HsRight),
    haskell_op(StdOp, HsOp),
    format(string(HsExpr), '(~w ~w ~w)', [HsLeft, HsOp, HsRight]).
haskell_expr(-Expr, VarMap, HsExpr) :-
    !,
    haskell_expr(Expr, VarMap, Inner),
    format(string(HsExpr), '(negate ~w)', [Inner]).
haskell_expr(abs(Expr), VarMap, HsExpr) :-
    !,
    haskell_expr(Expr, VarMap, Inner),
    format(string(HsExpr), '(abs ~w)', [Inner]).
haskell_expr(min(A, B), VarMap, HsExpr) :-
    !,
    haskell_expr(A, VarMap, HsA),
    haskell_expr(B, VarMap, HsB),
    format(string(HsExpr), '(min ~w ~w)', [HsA, HsB]).
haskell_expr(max(A, B), VarMap, HsExpr) :-
    !,
    haskell_expr(A, VarMap, HsA),
    haskell_expr(B, VarMap, HsB),
    format(string(HsExpr), '(max ~w ~w)', [HsA, HsB]).
haskell_expr(Atom, _VarMap, HsExpr) :-
    atom(Atom), !,
    haskell_literal(Atom, HsExpr).
haskell_expr(Number, _VarMap, HsExpr) :-
    number(Number), !,
    format(string(HsExpr), '~w', [Number]).
haskell_expr(String, _VarMap, HsExpr) :-
    string(String), !,
    format(string(HsExpr), '"~w"', [String]).

%% haskell_literal — convert Prolog value to Haskell literal
haskell_literal(Value, 'Nothing') :- var(Value), !.
haskell_literal(true, 'True') :- !.
haskell_literal(false, 'False') :- !.
haskell_literal([], '[]') :- !.
haskell_literal(Value, HsLiteral) :-
    number(Value), !,
    format(string(HsLiteral), '~w', [Value]).
haskell_literal(Value, HsLiteral) :-
    atom(Value), !,
    format(string(HsLiteral), '"~w"', [Value]).
haskell_literal(Value, HsLiteral) :-
    string(Value), !,
    format(string(HsLiteral), '"~w"', [Value]).
haskell_literal(Value, HsLiteral) :-
    term_string(Value, HsLiteral).

%% haskell_resolve_value — resolve variable or constant to Haskell expression
haskell_resolve_value(VarMap, Var, HsExpr) :-
    var(Var), !,
    lookup_var(Var, VarMap, HsExpr).
haskell_resolve_value(_VarMap, Value, HsExpr) :-
    haskell_literal(Value, HsExpr).

%% haskell_op — map standard operator to Haskell syntax
haskell_op('>', '>').
haskell_op('<', '<').
haskell_op('>=', '>=').
haskell_op('<=', '<=').
haskell_op('==', '==').
haskell_op('!=', '/=').
haskell_op('+', '+').
haskell_op('-', '-').
haskell_op('*', '*').
haskell_op('/', '`div`').
haskell_op('%', '`mod`').
haskell_op('&&', '&&').
haskell_op('||', '||').

%% combine_haskell_conditions — join conditions with &&
combine_haskell_conditions([], "true") :- !.
combine_haskell_conditions([], "True") :- !.
combine_haskell_conditions([Condition], Condition) :- !.
combine_haskell_conditions(Conditions, Combined) :-
    atomic_list_concat(Conditions, ' && ', Combined).

%% branches_to_haskell_guards — build Haskell guards
branches_to_haskell_guards(Branches, PredSpec, Code) :-
    findall(GuardLine, (
        member(branch(Condition, ClauseCode), Branches),
        format(string(GuardLine), '  | ~w = ~w', [Condition, ClauseCode])
    ), GuardLines),
    format(string(DefaultLine), '  | otherwise = error "No matching clause for ~w"', [PredSpec]),
    append(GuardLines, [DefaultLine], AllLines),
    atomic_list_concat(AllLines, '\n', Code).

%% ============================================
%% RECURSION → TAIL-RECURSIVE FUNCTION
%% ============================================

%% compile_recursion_to_haskell(+Pred/Arity, +Options, -HaskellCode)
%  Compile recursive predicates to Haskell functions
compile_recursion_to_haskell(Pred/_Arity, Options, Code) :-
    atom_string(Pred, PredStr),
    option(module_name(ModName), Options, PredStr),
    capitalize(ModName, ModCap),
    
    format(string(Code),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target
module ~w where

-- | ~w with tail-call optimization
-- GHC compiles this to a loop
~w :: Int -> Int -> Int
~w 0 !acc = acc
~w n !acc = ~w (n - 1) (acc + n)

-- | Wrapper function
~wResult :: Int -> Int
~wResult n = ~w n 0
', [ModCap, PredStr, PredStr, PredStr, PredStr, PredStr, 
    PredStr, PredStr, PredStr]).

%% ============================================
%% RULES → PATTERN MATCHING FUNCTIONS
%% ============================================

%% compile_rules_to_haskell(+Pred/Arity, +Options, -HaskellCode)
%  Compile Prolog rules to Haskell functions
compile_rules_to_haskell(Pred/_Arity, Options, Code) :-
    atom_string(Pred, PredStr),
    option(module_name(ModName), Options, PredStr),
    capitalize(ModName, ModCap),
    option(base_pred(BasePred), Options, parent),
    atom_string(BasePred, BaseStr),
    
    format(string(Code),
'-- Generated by UnifyWeaver Haskell Target
module ~w where

import Data.List (nub)

-- | Data type for entities
data Entity = Tom | Bob | Jim | Mary
  deriving (Eq, Show, Enum, Bounded)

allEntities :: [Entity]
allEntities = [minBound..maxBound]

-- | Base relation (facts)
~w :: Entity -> Entity -> Bool
~w x y = (x, y) `elem` [(Tom, Bob), (Bob, Jim)]

-- | ~w relation (transitive closure)
~w :: Entity -> Entity -> Bool
~w x y = ~w x y
      || any (\\z -> ~w x z && ~w z y) allEntities
', [ModCap, BaseStr, BaseStr, PredStr, PredStr, PredStr, BaseStr, BaseStr, PredStr]).

%% ============================================
%% MODULE COMPILATION
%% ============================================

%% compile_module_to_haskell(+Predicates, +Options, -HaskellCode)
%  Compile multiple predicates to a single module
compile_module_to_haskell(Predicates, Options, Code) :-
    option(module_name(ModName), Options, 'Generated'),
    capitalize(ModName, ModCap),
    
    % Generate exports
    findall(Export, (
        member(pred(Name, _Arity, _Type), Predicates),
        atom_string(Name, Export)
    ), Exports),
    atomic_list_concat(Exports, ', ', ExportList),
    
    % Generate code for each predicate
    findall(PredCode, (
        member(pred(Name, Arity, Type), Predicates),
        generate_pred_code(Name, Arity, Type, PredCode)
    ), PredCodes),
    atomic_list_concat(PredCodes, '\n\n', PredsSection),
    
    format(string(Code),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target
module ~w
    ( ~w
    ) where

~w
', [ModCap, ExportList, PredsSection]).

%% generate_pred_code(+Name, +Arity, +Type, -Code)
generate_pred_code(Name, _Arity, tail_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'-- | ~w (tail recursion)
~w :: Int -> Int -> Int
~w 0 !acc = acc
~w n !acc = ~w (n - 1) (acc + n)', [NameStr, NameStr, NameStr, NameStr, NameStr]).

generate_pred_code(Name, _Arity, factorial, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'-- | ~w (factorial)
~w :: Int -> Int
~w 0 = 1
~w 1 = 1
~w n = n * ~w (n - 1)', [NameStr, NameStr, NameStr, NameStr, NameStr, NameStr]).

generate_pred_code(Name, _Arity, linear_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'-- | ~w (linear recursion)
~w :: Int -> Int
~w 0 = 0
~w 1 = 1
~w n = ~w (n - 1) + ~w (n - 2)', [NameStr, NameStr, NameStr, NameStr, NameStr, NameStr, NameStr]).

%% list_fold - generates foldr-based list operations
generate_pred_code(Name, _Arity, list_fold, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'-- | ~w (list fold using foldr)
~w :: [Int] -> Int
~w = foldr (+) 0', [NameStr, NameStr, NameStr]).

%% list_tail_recursion - tail recursive list operations with accumulator
generate_pred_code(Name, _Arity, list_tail_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'-- | ~w (tail recursive list sum)
~w :: [Int] -> Int -> Int
~w [] !acc = acc
~w (h:t) !acc = ~w t (acc + h)', [NameStr, NameStr, NameStr, NameStr, NameStr]).

%% ============================================
%% FILE OUTPUT
%% ============================================

write_haskell_module(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('Haskell module written to: ~w~n', [Filename]),
    format('Compile with: ghc -O2 ~w~n', [Filename]).

%% ============================================
%% PARSEC: DCG → PARSER COMBINATORS
%% ============================================
%%
%% Compiles Prolog DCGs (Definite Clause Grammars) to Haskell Parsec
%% parser combinators. This enables:
%% - Type-safe parsing with automatic error messages
%% - Composable parser components
%% - Integration with Haskell's parser ecosystem
%%
%% DCG Pattern → Parsec Pattern:
%%   dcg_rule --> [char].          →  char
%%   dcg_rule --> "literal".       →  string "literal"
%%   dcg_rule --> a, b.            →  a >> b  (or a *> b)
%%   dcg_rule --> a | b.           →  a <|> b
%%   dcg_rule --> {goal}.          →  guard/pure
%%   dcg_rule --> dcg_rule.        →  recursive call
%%

%% compile_dcg_to_parsec(+DCGRule, +Options, -HaskellCode)
%  Compile a single DCG rule to Parsec combinator.
%
compile_dcg_to_parsec(Head --> Body, Options, Code) :-
    option(module_name(ModName), Options, 'Parser'),
    Head =.. [Name|_Args],
    atom_string(Name, NameStr),
    
    % Translate DCG body to Parsec
    dcg_body_to_parsec(Body, ParsecExpr),
    
    format(string(Code),
'{-# LANGUAGE OverloadedStrings #-}
-- Generated by UnifyWeaver Haskell Target (Parsec)
-- DCG: ~w --> ...
module ~w where

import Text.Parsec
import Text.Parsec.String (Parser)
import Control.Applicative ((<|>), many, some)
import Control.Monad (void)

-- | Parser for ~w
~w :: Parser String
~w = ~w
', [NameStr, ModName, NameStr, NameStr, NameStr, ParsecExpr]).

%% compile_grammar_to_parsec(+GrammarRules, +Options, -HaskellCode)
%  Compile multiple DCG rules to a Parsec module.
%
compile_grammar_to_parsec(Rules, Options, Code) :-
    option(module_name(ModName), Options, 'Grammar'),
    option(start_symbol(Start), Options, expr),
    atom_string(Start, StartStr),
    
    % Generate parser for each rule
    findall(ParserDef, (
        member(Rule, Rules),
        dcg_rule_to_parser_def(Rule, ParserDef)
    ), ParserDefs),
    atomic_list_concat(ParserDefs, '\n\n', ParsersSection),
    
    format(string(Code),
'{-# LANGUAGE OverloadedStrings #-}
-- Generated by UnifyWeaver Haskell Target (Parsec Grammar)
module ~w 
    ( parse~w
    , ~w
    ) where

import Text.Parsec
import Text.Parsec.String (Parser)
import Control.Applicative ((<|>), many, some)
import Control.Monad (void)
import Data.Char (isDigit, isAlpha, isAlphaNum)

-- | Main entry point
parse~w :: String -> Either ParseError String
parse~w = parse ~w "(input)"

~w
', [ModName, StartStr, StartStr, StartStr, StartStr, StartStr, ParsersSection]).

%% dcg_rule_to_parser_def(+Rule, -ParserDef)
%  Convert a DCG rule to a Parsec parser definition.
%
dcg_rule_to_parser_def(Head --> Body, Def) :-
    Head =.. [Name|_],
    atom_string(Name, NameStr),
    dcg_body_to_parsec(Body, ParsecExpr),
    format(string(Def),
'-- | Parser for ~w
~w :: Parser String
~w = ~w', [NameStr, NameStr, NameStr, ParsecExpr]).

%% dcg_body_to_parsec(+Body, -ParsecExpr)
%  Translate DCG body to Parsec expression.
%
% Terminal: single character list
dcg_body_to_parsec([Char], Expr) :-
    atom(Char), !,
    atom_string(Char, CharStr),
    format(string(Expr), 'string \"~w\"', [CharStr]).
dcg_body_to_parsec([Char], Expr) :-
    number(Char), !,
    char_code(C, Char),
    format(string(Expr), 'char ''~w''', [C]).

% Terminal: string literal (only for lists of char codes)
dcg_body_to_parsec(String, Expr) :-
    is_list(String),
    String \= [],
    maplist(number, String), !,
    atom_codes(Atom, String),
    format(string(Expr), 'string \"~w\"', [Atom]).

% Sequence: A, B
dcg_body_to_parsec((A, B), Expr) :- !,
    dcg_body_to_parsec(A, EA),
    dcg_body_to_parsec(B, EB),
    format(string(Expr), '(~w *> ~w)', [EA, EB]).

% Alternative: A | B  (using ;)
dcg_body_to_parsec((A ; B), Expr) :- !,
    dcg_body_to_parsec(A, EA),
    dcg_body_to_parsec(B, EB),
    format(string(Expr), '(try ~w <|> ~w)', [EA, EB]).

% Prolog goal: {Goal}
dcg_body_to_parsec({Goal}, Expr) :-
    term_to_haskell_guard(Goal, HaskellGuard),
    format(string(Expr), '(pure () <?> \"~w\")', [HaskellGuard]).

% Non-terminal: call another rule
dcg_body_to_parsec(NonTerminal, Expr) :-
    atom(NonTerminal),
    atom_string(NonTerminal, Expr).

% Non-terminal with args
dcg_body_to_parsec(NonTerminal, Expr) :-
    compound(NonTerminal),
    NonTerminal \= (_,_),
    NonTerminal \= (_;_),
    NonTerminal \= {_},
    NonTerminal =.. [Name|_Args],
    atom_string(Name, Expr).

% Kleene star: *
dcg_body_to_parsec('*'(A), Expr) :-
    dcg_body_to_parsec(A, EA),
    format(string(Expr), 'many ~w', [EA]).

% Kleene plus: +
dcg_body_to_parsec('+'(A), Expr) :-
    dcg_body_to_parsec(A, EA),
    format(string(Expr), 'some ~w', [EA]).

% Optional: ?
dcg_body_to_parsec('?'(A), Expr) :-
    dcg_body_to_parsec(A, EA),
    format(string(Expr), 'optional ~w', [EA]).

% Character classes (special atoms)
dcg_body_to_parsec(letter, "letter").
dcg_body_to_parsec(digit, "digit").
dcg_body_to_parsec(alpha_num, "alphaNum").
dcg_body_to_parsec(space, "space").
dcg_body_to_parsec(any_char, "anyChar").

% Negation: not(A)
dcg_body_to_parsec(not(A), Expr) :-
    dcg_body_to_parsec(A, EA),
    format(string(Expr), 'notFollowedBy ~w', [EA]).

% Lookahead: lookahead(A)
dcg_body_to_parsec(lookahead(A), Expr) :-
    dcg_body_to_parsec(A, EA),
    format(string(Expr), 'lookAhead ~w', [EA]).

%% term_to_haskell_guard(+Term, -HaskellExpr)
%  Convert Prolog term to Haskell expression (for guards).
%
term_to_haskell_guard(true, "True").
term_to_haskell_guard(fail, "False").
term_to_haskell_guard(A =:= B, Expr) :-
    format(string(Expr), '(~w == ~w)', [A, B]).
term_to_haskell_guard(A =\= B, Expr) :-
    format(string(Expr), '(~w /= ~w)', [A, B]).
term_to_haskell_guard(A < B, Expr) :-
    format(string(Expr), '(~w < ~w)', [A, B]).
term_to_haskell_guard(A > B, Expr) :-
    format(string(Expr), '(~w > ~w)', [A, B]).
term_to_haskell_guard(Term, Str) :-
    term_string(Term, Str).

%% ============================================
%% COMMON PARSEC COMBINATORS (built-in helpers)
%% ============================================

parsec_common_helpers('
-- Common helpers
whitespace :: Parser ()
whitespace = void $ many (oneOf " \\t\\n\\r")

lexeme :: Parser a -> Parser a
lexeme p = p <* whitespace

symbol :: String -> Parser String
symbol s = lexeme (string s)

identifier :: Parser String
identifier = lexeme $ (:) <$> letter <*> many alphaNum

integer :: Parser Int
integer = lexeme $ read <$> some digit

parens :: Parser a -> Parser a
parens = between (symbol "(") (symbol ")")

brackets :: Parser a -> Parser a
brackets = between (symbol "[") (symbol "]")
').

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(haskell, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_haskell(StepOp, HaskellStepExpr),
    (   Arity =:= 3 ->
        format(string(Code),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target - Tail Recursion (multifile dispatch)
-- Predicate: ~w/~w

module Main where

import System.Environment (getArgs)

~w :: [Int] -> Int
~w xs = go xs 0
  where
    go []     !acc = acc
    go (item:rest) !acc = go rest (~w)

main :: IO ()
main = do
    args <- getArgs
    case args of
        (arg:_) -> print $ ~w (map read $ words $ map (\\c -> if c == '','' then '' '' else c) arg :: [Int])
        _       -> putStrLn "Usage: ~w <comma-separated-list>"
', [PredStr, Arity, PredStr, PredStr, HaskellStepExpr, PredStr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target - Tail Recursion (binary, multifile dispatch)
-- Predicate: ~w/~w

module Main where

import System.Environment (getArgs)

~w :: [a] -> Int
~w xs = go xs 0
  where
    go []     !count = count
    go (_:rest) !count = go rest (count + 1)

main :: IO ()
main = do
    args <- getArgs
    case args of
        (arg:_) -> print $ ~w (words $ map (\\c -> if c == '','' then '' '' else c) arg)
        _       -> putStrLn "Usage: ~w <comma-separated-list>"
', [PredStr, Arity, PredStr, PredStr, PredStr, PredStr])
    ;   fail
    ).

%% step_op_to_haskell(+StepOp, -HaskellExpr)
step_op_to_haskell(arithmetic(Expr), HaskellExpr) :-
    expr_to_haskell(Expr, HaskellExpr).
step_op_to_haskell(unknown, 'acc + 1').

%% expr_to_haskell(+PrologExpr, -HaskellExpr)
expr_to_haskell(_ + Const, HaskellExpr) :- integer(Const), !,
    format(atom(HaskellExpr), 'acc + ~w', [Const]).
expr_to_haskell(_ + _, 'acc + item') :- !.
expr_to_haskell(_ - _, 'acc - item') :- !.
expr_to_haskell(_ * _, 'acc * item') :- !.
expr_to_haskell(_, 'acc + 1').

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

% Note: MemoEnabled intentionally unused — Haskell's lazy evaluation and GHC's
% common subexpression elimination provide implicit memoization for most cases.
linear_recursion:compile_linear_pattern(haskell, PredStr, Arity, BaseClauses, RecClauses, _MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_haskell(PredStr, BaseClauses, RecClauses, Code)
    ;   linear_generic_haskell(PredStr, Arity, Code)
    ).

%% linear_fold_haskell(+PredStr, +BaseClauses, +RecClauses, -Code)
linear_fold_haskell(PredStr, BaseClauses, _RecClauses, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    (   InputType = numeric ->
        % Extract fold operation from actual clauses
        atom_string(Pred, PredStr),
        functor(Head, Pred, 2),
        findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
        partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRec, _),
        (   ActualRec = [clause(RHead, RBody)|_] ->
            RHead =.. [_, InputVar, _],
            linear_recursion:find_recursive_call(RBody, RecCall),
            RecCall =.. [_, _, AccVar],
            linear_recursion:find_last_is_expression(RBody, _ is FoldExpr),
            translate_fold_expr_haskell(FoldExpr, InputVar, AccVar, HaskellOp)
        ;   HaskellOp = "current * acc"
        ),
        % Extract step size for range expression
        (   linear_recursion:extract_step_info_for(Pred/2, Step, down) ->
            (   Step =:= 1 ->
                format(string(RangeExpr), '[n, n-1 .. 1]', [])
            ;   format(string(RangeExpr), '[n, n-~w .. 1]', [Step])
            )
        ;   RangeExpr = "[n, n-1 .. 1]"
        ),
        format(string(Code),
'-- Generated by UnifyWeaver Haskell Target - Linear Recursion (numeric, multifile dispatch)
-- Predicate: ~w/2

module Main where

import System.Environment (getArgs)
import qualified Data.Map.Strict as Map
import Data.IORef

~w :: Int -> Int
~w ~w = ~w
~w n = foldl (\\acc current -> ~w) ~w ~w

main :: IO ()
main = do
    args <- getArgs
    case args of
        (arg:_) -> print $ ~w (read arg :: Int)
        _       -> putStrLn "Usage: ~w <n>"
', [PredStr, PredStr, PredStr, BaseInput, BaseOutput, PredStr, HaskellOp, BaseOutput, RangeExpr, PredStr, PredStr])
    ;   InputType = list ->
        % Extract fold operation from actual clauses for list recursion
        atom_string(LPred, PredStr),
        functor(LHead, LPred, 2),
        findall(clause(LHead, LBody), user:clause(LHead, LBody), LAllClauses),
        partition(linear_recursion:is_recursive_clause(LPred), LAllClauses, LActualRec, _),
        (   LActualRec = [clause(LRHead, LRBody)|_] ->
            linear_recursion:find_last_is_expression(LRBody, _ is LFoldExpr),
            linear_recursion:find_recursive_call(LRBody, LRecCall),
            LRecCall =.. [_, _, LAccVar],
            LRHead =.. [_, [LHeadVar|_], _],
            translate_list_fold_haskell(LFoldExpr, LHeadVar, LAccVar, ListFoldOp)
        ;   ListFoldOp = "h + acc"
        ),
        format(string(Code),
'-- Generated by UnifyWeaver Haskell Target - Linear Recursion (list, multifile dispatch)
-- Predicate: ~w/2

module Main where

import System.Environment (getArgs)

~w :: [Int] -> Int
~w [] = ~w
~w (h:t) = let acc = ~w t in ~w

main :: IO ()
main = do
    args <- getArgs
    case args of
        (arg:_) -> print $ ~w (map read $ words $ map (\\c -> if c == '','' then '' '' else c) arg :: [Int])
        _       -> putStrLn "Usage: ~w <comma-separated-list>"
', [PredStr, PredStr, PredStr, BaseOutput, PredStr, PredStr, ListFoldOp, PredStr, PredStr])
    ;   linear_generic_haskell(PredStr, 2, Code)
    ).

%% linear_generic_haskell(+PredStr, +Arity, -Code)
linear_generic_haskell(PredStr, Arity, Code) :-
    format(string(Code),
'-- Generated by UnifyWeaver Haskell Target - Linear Recursion (generic, multifile dispatch)
-- Predicate: ~w/~w

module Main where

import System.Environment (getArgs)

~w :: Int -> Int
~w 0 = 0
~w 1 = 1
~w n = ~w (n - 1) + n

main :: IO ()
main = do
    args <- getArgs
    case args of
        (arg:_) -> print $ ~w (read arg :: Int)
        _       -> putStrLn "Usage: ~w <n>"
', [PredStr, Arity, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr]).

%% translate_fold_expr_haskell(+PrologExpr, +InputVar, +AccVar, -HaskellExpr)
translate_fold_expr_haskell(A * B, InputVar, AccVar, HaskellExpr) :-
    translate_haskell_term(A, InputVar, AccVar, AT),
    translate_haskell_term(B, InputVar, AccVar, BT),
    format(string(HaskellExpr), '~w * ~w', [AT, BT]).
translate_fold_expr_haskell(A + B, InputVar, AccVar, HaskellExpr) :-
    translate_haskell_term(A, InputVar, AccVar, AT),
    translate_haskell_term(B, InputVar, AccVar, BT),
    format(string(HaskellExpr), '~w + ~w', [AT, BT]).
translate_fold_expr_haskell(A - B, InputVar, AccVar, HaskellExpr) :-
    translate_haskell_term(A, InputVar, AccVar, AT),
    translate_haskell_term(B, InputVar, AccVar, BT),
    format(string(HaskellExpr), '~w - ~w', [AT, BT]).
translate_fold_expr_haskell(Term, InputVar, AccVar, HaskellExpr) :-
    translate_haskell_term(Term, InputVar, AccVar, HaskellExpr).

translate_haskell_term(Term, InputVar, _AccVar, 'current') :- Term == InputVar, !.
translate_haskell_term(Term, _InputVar, AccVar, 'acc') :- Term == AccVar, !.
translate_haskell_term(Number, _, _, HaskellTerm) :- integer(Number), !,
    format(string(HaskellTerm), '~w', [Number]).
translate_haskell_term(Atom, _, _, HaskellTerm) :-
    format(string(HaskellTerm), '~w', [Atom]).

%% translate_list_fold_haskell(+PrologExpr, +HeadVar, +AccVar, -HaskellExpr)
%  Like translate_fold_expr_haskell but maps HeadVar -> 'h' and AccVar -> 'acc'
translate_list_fold_haskell(A * B, HeadVar, AccVar, HaskellExpr) :-
    translate_list_term_haskell(A, HeadVar, AccVar, AT),
    translate_list_term_haskell(B, HeadVar, AccVar, BT),
    format(string(HaskellExpr), '~w * ~w', [AT, BT]).
translate_list_fold_haskell(A + B, HeadVar, AccVar, HaskellExpr) :-
    translate_list_term_haskell(A, HeadVar, AccVar, AT),
    translate_list_term_haskell(B, HeadVar, AccVar, BT),
    format(string(HaskellExpr), '~w + ~w', [AT, BT]).
translate_list_fold_haskell(A - B, HeadVar, AccVar, HaskellExpr) :-
    translate_list_term_haskell(A, HeadVar, AccVar, AT),
    translate_list_term_haskell(B, HeadVar, AccVar, BT),
    format(string(HaskellExpr), '~w - ~w', [AT, BT]).
translate_list_fold_haskell(Term, HeadVar, AccVar, HaskellExpr) :-
    translate_list_term_haskell(Term, HeadVar, AccVar, HaskellExpr).

translate_list_term_haskell(Term, HeadVar, _AccVar, 'h') :- Term == HeadVar, !.
translate_list_term_haskell(Term, _HeadVar, AccVar, 'acc') :- Term == AccVar, !.
translate_list_term_haskell(Number, _, _, HsTerm) :- integer(Number), !,
    format(string(HsTerm), '~w', [Number]).
translate_list_term_haskell(Atom, _, _, HsTerm) :-
    format(string(HsTerm), '~w', [Atom]).

% ============================================================================
% TREE RECURSION - Haskell target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(haskell, _Pattern, Pred, _Arity, _UseMemo, HsCode) :-
    atom_string(Pred, PredStr),
    format(string(HsCode),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target - Tree Recursion (fibonacci, multifile dispatch)
module Main where

import qualified Data.Map.Strict as Map
import Data.IORef
import System.IO.Unsafe (unsafePerformIO)
import System.Environment (getArgs)

{-# NOINLINE ~wMemo #-}
~wMemo :: IORef (Map.Map Int Int)
~wMemo = unsafePerformIO (newIORef Map.empty)

~w :: Int -> Int
~w 0 = 0
~w 1 = 1
~w n = unsafePerformIO $ do
    m <- readIORef ~wMemo
    case Map.lookup n m of
        Just v  -> return v
        Nothing -> do
            let !result = ~w (n - 1) + ~w (n - 2)
            modifyIORef ~wMemo (Map.insert n result)
            return result

main :: IO ()
main = do
    args <- getArgs
    case args of
        (x:_) -> print (~w (read x :: Int))
        _     -> return ()
', [PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTICALL LINEAR RECURSION - Haskell target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(haskell, PredStr, BaseClauses, _RecClauses, _MemoEnabled, HsCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '~w ~w = ~w', [PredStr, BInput, BOutput])
    ), BaseCaseCodes0),
    sort(BaseCaseCodes0, BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(HsCode),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target - Multicall Linear Recursion (multifile dispatch)
module Main where

import qualified Data.Map.Strict as Map
import Data.IORef
import System.IO.Unsafe (unsafePerformIO)
import System.Environment (getArgs)

{-# NOINLINE ~wMemo #-}
~wMemo :: IORef (Map.Map Int Int)
~wMemo = unsafePerformIO (newIORef Map.empty)

~w :: Int -> Int
~w
~w n = unsafePerformIO $ do
    m <- readIORef ~wMemo
    case Map.lookup n m of
        Just v  -> return v
        Nothing -> do
            let !result = ~w (n - 1) + ~w (n - 2)
            modifyIORef ~wMemo (Map.insert n result)
            return result

main :: IO ()
main = do
    args <- getArgs
    case args of
        (x:_) -> print (~w (read x :: Int))
        _     -> return ()
', [PredStr, PredStr, PredStr, PredStr, BaseCaseStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% DIRECT MULTI-CALL RECURSION - Haskell target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(haskell, PredStr, BaseClauses, _RecClause, HsCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '~w ~w = ~w', [PredStr, BInput, BOutput])
    ), BaseCaseCodes0),
    sort(BaseCaseCodes0, BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(HsCode),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target - Direct Multicall Recursion (multifile dispatch)
module Main where

import qualified Data.Map.Strict as Map
import Data.IORef
import System.IO.Unsafe (unsafePerformIO)
import System.Environment (getArgs)

{-# NOINLINE ~wMemo #-}
~wMemo :: IORef (Map.Map Int Int)
~wMemo = unsafePerformIO (newIORef Map.empty)

~w :: Int -> Int
~w
~w n = unsafePerformIO $ do
    m <- readIORef ~wMemo
    case Map.lookup n m of
        Just v  -> return v
        Nothing -> do
            let !result = ~w (n - 1) + ~w (n - 2)
            modifyIORef ~wMemo (Map.insert n result)
            return result

main :: IO ()
main = do
    args <- getArgs
    case args of
        (x:_) -> print (~w (read x :: Int))
        _     -> return ()
', [PredStr, PredStr, PredStr, PredStr, BaseCaseStr, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MUTUAL RECURSION - Haskell target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(haskell, Predicates, MemoEnabled, _MemoStrategy, HsCode) :-
    % Generate function code for each predicate
    mutual_functions_hs(Predicates, Predicates, MemoEnabled, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    % Generate dispatch
    mutual_dispatch_hs(Predicates, DispatchCode),
    (   MemoEnabled = true ->
        MemoDecl = '{-# NOINLINE memoRef #-}\nmemoRef :: IORef (Map.Map String Bool)\nmemoRef = unsafePerformIO (newIORef Map.empty)'
    ;   MemoDecl = '-- Shared memoization disabled'
    ),
    format(string(HsCode),
'{-# LANGUAGE BangPatterns #-}
-- Generated by UnifyWeaver Haskell Target - Mutual Recursion (multifile dispatch)
module Main where

import qualified Data.Map.Strict as Map
import Data.IORef
import System.IO.Unsafe (unsafePerformIO)
import System.Environment (getArgs)

~w

~w

~w
', [MemoDecl, FunctionsCode, DispatchCode]).

mutual_functions_hs([], _AllPreds, _MemoEnabled, []).
mutual_functions_hs([Pred/Arity|Rest], AllPreds, MemoEnabled, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    % Base case pattern matches
    findall(BaseLine, (
        member(clause(BHead, true), BaseClauses),
        BHead =.. [_P, BValue],
        format(string(BaseLine), '~w ~w = True', [PredStr, BValue])
    ), BaseLines),
    atomic_list_concat(BaseLines, '\n', BaseCode),
    % Recursive case
    (   RecClauses = [clause(_RHead, RBody)|_] ->
        extract_mutual_rec_info_hs(RBody, Guard, CalledPred, Step),
        atom_string(CalledPred, CalledStr),
        (   Guard = (N > Threshold), var(N) ->
            (   MemoEnabled = true ->
                format(string(RecCode),
'~w n
    | n > ~w = unsafePerformIO $ do
        let key = "~w:" ++ show n
        m <- readIORef memoRef
        case Map.lookup key m of
            Just v  -> return v
            Nothing -> do
                let !result = ~w (n ~w)
                modifyIORef memoRef (Map.insert key result)
                return result
    | otherwise = False', [PredStr, Threshold, PredStr, CalledStr, Step])
            ;   format(string(RecCode),
'~w n
    | n > ~w = ~w (n ~w)
    | otherwise = False', [PredStr, Threshold, CalledStr, Step])
            )
        ;   format(string(RecCode),
'~w n = ~w (n ~w)', [PredStr, CalledStr, Step])
        )
    ;   RecCode = ''
    ),
    format(string(FuncCode),
'~w :: Int -> Bool
~w
~w', [PredStr, BaseCode, RecCode]),
    mutual_functions_hs(Rest, AllPreds, MemoEnabled, RestCodes).

extract_mutual_rec_info_hs(Body, Guard, CalledPred, Step) :-
    extract_goals_from_body_hs(Body, Goals),
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(Step), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(Step), '- ~w', [AbsK])
    ;   Step = "- 1"
    ).

extract_goals_from_body_hs((A, B), Goals) :- !,
    extract_goals_from_body_hs(A, GA),
    extract_goals_from_body_hs(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body_hs(true, []) :- !.
extract_goals_from_body_hs(Goal, [Goal]).

mutual_dispatch_hs(Predicates, Code) :-
    findall(MatchLine, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(MatchLine), '            "~w" -> print (~w (read x :: Int))', [PredStr, PredStr])
    ), Lines),
    atomic_list_concat(Lines, '\n', MatchCode),
    format(string(Code),
'main :: IO ()
main = do
    args <- getArgs
    case args of
        (func:x:_) -> case func of
~w
            _         -> putStrLn "Unknown function"
        _ -> return ()', [MatchCode]).
