:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025-2026 John William Creighton (@s243a)
%
% ilasm_target.pl — .NET ILAsm (CIL assembly) target.
% Produces IL assembly text compilable by ilasm.

:- module(ilasm_target, [
    compile_predicate_to_ilasm/3     % +PredIndicator, +Options, -ILCode
]).

:- use_module('../core/clause_body_analysis').
:- use_module('../core/cil_bytecode').
:- use_module('../core/component_registry').
:- use_module('../core/advanced/pattern_matchers', [is_per_path_visited_pattern/4]).
:- use_module(library(lists)).

%% Register ILAsm component type for custom IL injection
:- initialization((
    catch(
        register_component_type(source, custom_ilasm, custom_ilasm, [
            description('Injects custom CIL assembly as a component')
        ]),
        _, true
    )
)).

% ============================================================================
% ENTRY POINT
% ============================================================================

compile_predicate_to_ilasm(PredIndicator, Options, ILCode) :-
    (   PredIndicator = Module:Name/Arity
    ->  true
    ;   PredIndicator = Name/Arity, Module = user
    ),
    atom_string(Name, PredStr),
    functor(Head, Name, Arity),
    findall(Head-Body, Module:clause(Head, Body), Clauses),
    (   Clauses == []
    ->  throw(error(clause_not_found(Module:Head), _))
    ;   true
    ),
    %% Determine input/output split
    Arity1 is Arity - 1,
    %% Try native clause body lowering
    (   native_ilasm_clause_body(PredStr/Arity, Clauses, MethodBody)
    ->  true
    ;   MethodBody = "    ldstr \"Compilation failed\"\n    throw"
    ),
    %% Build typed method signature
    ilasm_typed_arg_list(Name/Arity, Arity1, ArgDecls),
    ilasm_return_type(Name/Arity, ReturnType),
    ilasm_locals_from_body(MethodBody, LocalDecls),
    %% Wrap in class
    option(class_name(ClassName), Options, 'PrologGenerated'),
    option(include_main(IncludeMain), Options, true),
    (   IncludeMain
    ->  ilasm_main_method(ClassName, PredStr, ArgDecls, ReturnType, MainMethod)
    ;   MainMethod = ""
    ),
    format(string(ILCode),
'// Generated by UnifyWeaver ILAsm Target
// Predicate: ~w/~w

.assembly extern mscorlib {}
.assembly ~w {}

.class public auto ansi ~w extends [mscorlib]System.Object {

.method public static ~w ~w(~w) cil managed {
    .maxstack 8
~w
~w
}

~w

}
', [PredStr, Arity, ClassName, ClassName, ReturnType, PredStr, ArgDecls, LocalDecls, MethodBody, MainMethod]).

%% ilasm_arg_list(+N, -ArgDecls)
ilasm_arg_list(0, "") :- !.
ilasm_arg_list(N, ArgDecls) :-
    findall(Decl, (
        between(1, N, I),
        format(string(Decl), 'int64 arg~w', [I])
    ), Decls),
    atomic_list_concat(Decls, ', ', ArgDecls).

%% ilasm_typed_arg_list(+PredSpec, +InputArity, -ArgDecls)
%  Build typed arg list using uw_type declarations if available.
ilasm_typed_arg_list(Name/Arity, InputArity, ArgDecls) :-
    (   ilasm_has_type_annotations(Name/Arity)
    ->  ilasm_typed_args(Name/Arity, 1, InputArity, Args),
        atomic_list_concat(Args, ', ', ArgDecls)
    ;   ilasm_arg_list(InputArity, ArgDecls)
    ).

ilasm_has_type_annotations(Name/Arity) :-
    (   clause(type_declarations:uw_type(Name/Arity, _, _), true)
    ;   clause(user:uw_type(Name/Arity, _, _), true)
    ), !.

ilasm_typed_args(_PredSpec, I, InputArity, []) :- I > InputArity, !.
ilasm_typed_args(Name/Arity, I, InputArity, [TypedArg|Rest]) :-
    (   (clause(type_declarations:uw_type(Name/Arity, I, Type), true)
        ; clause(user:uw_type(Name/Arity, I, Type), true)),
        type_declarations:resolve_type(Type, ilasm, CILType)
    ->  format(string(TypedArg), '~w arg~w', [CILType, I])
    ;   format(string(TypedArg), 'int64 arg~w', [I])
    ),
    I1 is I + 1,
    ilasm_typed_args(Name/Arity, I1, InputArity, Rest).

%% ilasm_return_type(+PredSpec, -ReturnType)
%  Get CIL return type from uw_return_type or default to int64.
ilasm_return_type(Name/Arity, ReturnType) :-
    (   (clause(type_declarations:uw_return_type(Name/Arity, Type), true)
        ; clause(user:uw_return_type(Name/Arity, Type), true)),
        type_declarations:resolve_type(Type, ilasm, CILType)
    ->  ReturnType = CILType
    ;   ReturnType = "int64"
    ).

%% ilasm_main_method(+ClassName, +PredStr, +ArgDecls, +ReturnType, -MainMethod)
%  Generate Main method with type-appropriate parse and print.
ilasm_main_method(ClassName, PredStr, ArgDecls, ReturnType, MainMethod) :-
    (   ReturnType = "string"
    ->  ParseInstr = "",
        PrintInstr = "    call void [mscorlib]System.Console::WriteLine(string)"
    ;   ReturnType = "float64"
    ->  ParseInstr = "    call float64 [mscorlib]System.Double::Parse(string)",
        PrintInstr = "    call void [mscorlib]System.Console::WriteLine(float64)"
    ;   ReturnType = "bool"
    ->  ParseInstr = "    call int64 [mscorlib]System.Int64::Parse(string)",
        PrintInstr = "    call void [mscorlib]System.Console::WriteLine(bool)"
    ;   ParseInstr = "    call int64 [mscorlib]System.Int64::Parse(string)",
        PrintInstr = "    call void [mscorlib]System.Console::WriteLine(int64)"
    ),
    format(string(MainMethod),
'.method public static void Main(string[] args) cil managed {
    .entrypoint
    .maxstack 8
    ldarg.0
    ldc.i4.0
    ldelem.ref
    call string [mscorlib]System.String::Trim(string)
~w
    call ~w ~w::~w(~w)
~w
    ret
}', [ParseInstr, ReturnType, ClassName, PredStr, ArgDecls, PrintInstr]).

%% ilasm_locals_from_body(+Body, -LocalDecls)
%  Extract local variable declarations from method body.
ilasm_locals_from_body(Body, LocalDecls) :-
    split_string(Body, "\n", "", Lines),
    findall(VarName, (
        member(Line, Lines),
        (   sub_string(Line, _, _, _, "stloc ")
        ->  split_string(Line, " ", " ", Parts),
            last(Parts, VarName)
        ;   fail
        )
    ), VarNames0),
    sort(VarNames0, VarNames),
    (   VarNames == []
    ->  LocalDecls = ""
    ;   findall(Decl, (
            member(V, VarNames),
            format(string(Decl), 'int64 ~w', [V])
        ), Decls),
        atomic_list_concat(Decls, ', ', DeclStr),
        format(string(LocalDecls), '    .locals init (~w)', [DeclStr])
    ).

% ============================================================================
% NATIVE CLAUSE BODY LOWERING
% ============================================================================

%% native_ilasm_clause_body(+PredSpec, +Clauses, -Code)
native_ilasm_clause_body(PredStr/Arity, Clauses, Code) :-
    Arity1 is Arity - 1,
    ilasm_clauses_to_branches(Clauses, Arity1, Branches),
    Branches \= [],
    cil_if_chain(Branches, 0, "CL", AllInstrs),
    cil_ensure_strings(AllInstrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', Code).

%% ilasm_clauses_to_branches(+Clauses, +Arity1, -Branches)
ilasm_clauses_to_branches([], _, []).
ilasm_clauses_to_branches([Head-Body|Rest], Arity1, Result) :-
    ilasm_clauses_to_branches(Rest, Arity1, RestBranches),
    (   Body \== true,
        Head =.. [_|AllArgs],
        length(InputArgs, Arity1),
        append(InputArgs, [OutputArg], AllArgs),
        build_head_varmap(InputArgs, 1, VarMap),
        normalize_goals(Body, Goals),
        %% Try classify_goal_sequence first
        (   classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
            ClassifiedGoals \= [],
            ilasm_compile_classified(ClassifiedGoals, OutputArg, VarMap, GuardInstrs, ValueInstrs)
        ->  true
        ;   %% Fallback to basic split
            once(clause_guard_output_split(Goals, VarMap, Guards, Outputs)),
            ilasm_compile_guards(Guards, VarMap, GuardInstrs),
            ilasm_output_to_instrs(OutputArg, Outputs, VarMap, ValueInstrs)
        )
    ->  Result = [branch(GuardInstrs, ValueInstrs)|RestBranches]
    ;   %% Pure fact clause
        Head =.. [_|AllArgs],
        length(InputArgs, Arity1),
        append(InputArgs, [OutputArg], AllArgs),
        build_head_varmap(InputArgs, 1, VarMap),
        Body == true,
        ilasm_head_guard_instrs(InputArgs, 1, VarMap, GuardInstrs),
        cil_resolve_value(OutputArg, VarMap, ValInstr),
        ValueInstrs = [ValInstr]
    ->  Result = [branch(GuardInstrs, ValueInstrs)|RestBranches]
    ;   Result = RestBranches
    ).

%% ilasm_compile_guards(+Guards, +VarMap, -Instructions)
ilasm_compile_guards([], _, []).
ilasm_compile_guards([G|Gs], VarMap, AllInstrs) :-
    cil_guard_to_instrs(G, VarMap, "NEXT", GInstrs),
    ilasm_compile_guards(Gs, VarMap, RestInstrs),
    append(GInstrs, RestInstrs, AllInstrs).

%% ilasm_output_to_instrs(+OutputArg, +Outputs, +VarMap, -Instructions)
ilasm_output_to_instrs(OutputArg, [], VarMap, [Instr]) :- !,
    cil_resolve_value(OutputArg, VarMap, Instr).
ilasm_output_to_instrs(_OutputArg, Outputs, VarMap, Instrs) :-
    last(Outputs, LastGoal),
    (   LastGoal = (_ is ArithExpr)
    ->  cil_expr_to_instrs(ArithExpr, VarMap, Instrs)
    ;   LastGoal = (_ = Expr)
    ->  cil_expr_to_instrs(Expr, VarMap, Instrs)
    ;   cil_resolve_value(LastGoal, VarMap, Instr),
        Instrs = [Instr]
    ).

%% ilasm_head_guard_instrs(+InputArgs, +Index, +VarMap, -Instructions)
ilasm_head_guard_instrs([], _, _, []).
ilasm_head_guard_instrs([Arg|Rest], Index, VarMap, Instrs) :-
    NextIndex is Index + 1,
    ilasm_head_guard_instrs(Rest, NextIndex, VarMap, RestInstrs),
    (   nonvar(Arg)
    ->  format(string(LoadArg), '    ldarg.~w', [Index]),
        (   integer(Arg)
        ->  format(string(LoadConst), '    ldc.i8 ~w', [Arg]),
            BrInstr = '    bne.un NEXT'
        ;   format(string(LoadConst), '    ldstr "~w"', [Arg]),
            BrInstr = '    call bool [mscorlib]System.String::op_Inequality(string, string)\n    brtrue NEXT'
        ),
        Instrs = [LoadArg, LoadConst, BrInstr|RestInstrs]
    ;   Instrs = RestInstrs
    ).

% ============================================================================
% CLASSIFIED GOAL COMPILATION
% ============================================================================

%% ilasm_compile_classified(+ClassifiedGoals, +OutputArg, +VarMap, -GuardInstrs, -ValueInstrs)
ilasm_compile_classified(ClassifiedGoals, OutputArg, VarMap, GuardInstrs, ValueInstrs) :-
    findall(GInstrs, (
        member(guard(G, _), ClassifiedGoals),
        cil_guard_to_instrs(G, VarMap, "NEXT", GInstrs)
    ), GuardInstrLists),
    append(GuardInstrLists, GuardInstrs),
    %% Find output value
    (   member(output(Goal, _, _), ClassifiedGoals)
    ->  ilasm_classified_output(Goal, VarMap, ValueInstrs)
    ;   member(output_ite(If, Then, Else, _), ClassifiedGoals)
    ->  ilasm_classified_ite(If, Then, Else, VarMap, ValueInstrs)
    ;   cil_resolve_value(OutputArg, VarMap, ValInstr),
        ValueInstrs = [ValInstr]
    ).

%% ilasm_classified_output(+Goal, +VarMap, -Instrs)
ilasm_classified_output(Goal, VarMap, Instrs) :-
    (   Goal = (_ is ArithExpr)
    ->  cil_expr_to_instrs(ArithExpr, VarMap, Instrs)
    ;   Goal = (_ = Expr)
    ->  cil_expr_to_instrs(Expr, VarMap, Instrs)
    ;   cil_resolve_value(Goal, VarMap, Instr),
        Instrs = [Instr]
    ).

%% ilasm_classified_ite(+If, +Then, +Else, +VarMap, -Instrs)
ilasm_classified_ite(If, Then, Else, VarMap, Instrs) :-
    cil_guard_to_instrs(If, VarMap, "ITE_else", CondInstrs),
    %% Then branch value
    normalize_goals(Then, ThenGoals),
    last(ThenGoals, ThenLast),
    ilasm_classified_output(ThenLast, VarMap, ThenInstrs),
    %% Else branch value
    normalize_goals(Else, ElseGoals),
    last(ElseGoals, ElseLast),
    ilasm_classified_output(ElseLast, VarMap, ElseInstrs),
    %% Assemble
    append(CondInstrs, ThenInstrs, PreBr),
    append(PreBr, ['    br ITE_end', 'ITE_else:'], PreElse),
    append(PreElse, ElseInstrs, PreEnd),
    append(PreEnd, ['ITE_end:'], Instrs).

% ============================================================================
% MULTIFILE HOOKS — compile_expression framework
% ============================================================================

clause_body_analysis:render_output_goal(ilasm, Goal, VarMap, Line, VarName, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        cil_expr_to_instrs(Expr, VarMap, ExprInstrs),
        cil_ensure_strings(ExprInstrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprCode),
        format(string(Line), '~w\n    stloc ~w', [ExprCode, VarName])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        cil_expr_to_instrs(ArithExpr, VarMap, ExprInstrs),
        cil_ensure_strings(ExprInstrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprCode),
        format(string(Line), '~w\n    stloc ~w', [ExprCode, VarName])
    ;   VarName = "_", VarMapOut = VarMap,
        Line = "    // unsupported output goal"
    ).

clause_body_analysis:render_guard_condition(ilasm, Goal, VarMap, CondStr) :-
    cil_guard_to_instrs(Goal, VarMap, "L_false", Instrs),
    cil_ensure_strings(Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', CondStr).

clause_body_analysis:render_branch_value(ilasm, Branch, VarMap, ExprStr) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   LastGoal = (_ = Expr)
    ->  cil_resolve_value(Expr, VarMap, ExprStr)
    ;   LastGoal = (_ is ArithExpr)
    ->  cil_expr_to_instrs(ArithExpr, VarMap, Instrs),
        cil_ensure_strings(Instrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprStr)
    ;   cil_resolve_value(LastGoal, VarMap, ExprStr)
    ).

clause_body_analysis:render_ite_block(ilasm, Cond, ThenLines, ElseLines, _Indent, _ReturnVars, Lines) :-
    (   ElseLines \= []
    ->  append([Cond, 'L_then:'|ThenLines], ['    br L_end', 'L_else:'|ElseLines], Pre),
        append(Pre, ['L_end:'], Lines)
    ;   append([Cond, 'L_then:'|ThenLines], ['L_end:'], Lines)
    ).

% ============================================================================
% GUARD CONDITION (text-based for classify_goal_sequence)
% ============================================================================

ilasm_guard_condition(Goal, VarMap, CondStr) :-
    cil_guard_to_instrs(Goal, VarMap, "L_false", Instrs),
    cil_ensure_strings(Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', CondStr).

% ============================================================================
% MULTIFILE RECURSION PATTERNS
% ============================================================================

%% Tail recursion → CIL loop with starg.s
tail_recursion:compile_tail_pattern(ilasm, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, _StepOp, _ExitAfterResult, Code) :-
    cil_tail_recursion_bytecode(PredStr, Arity, BodyInstrs),
    cil_ensure_strings(BodyInstrs, BodyStrs),
    atomic_list_concat(BodyStrs, '\n', BodyCode),
    cil_tail_recursion_entry(PredStr, 'PrologGenerated', EntryInstrs),
    cil_ensure_strings(EntryInstrs, EntryStrs),
    atomic_list_concat(EntryStrs, '\n', EntryCode),
    format(string(Code),
'// Generated by UnifyWeaver ILAsm Target - Tail Recursion
// Predicate: ~w/~w

.assembly extern mscorlib {}
.assembly PrologGenerated {}

.class public auto ansi PrologGenerated extends [mscorlib]System.Object {

.method public static int64 ~w_worker(int64 arg0, int64 arg1) cil managed {
    .maxstack 4
~w
}

.method public static int64 ~w(int64 arg0) cil managed {
    .maxstack 4
~w
}

.method public static void Main(string[] args) cil managed {
    .entrypoint
    .maxstack 4
    ldarg.0
    ldc.i4.0
    ldelem.ref
    call int64 [mscorlib]System.Int64::Parse(string)
    call int64 PrologGenerated::~w(int64)
    call void [mscorlib]System.Console::WriteLine(int64)
    ret
}

}
', [PredStr, Arity, PredStr, BodyCode, PredStr, EntryCode, PredStr]).

%% Linear recursion → CIL iterative loop
linear_recursion:compile_linear_pattern(ilasm, PredStr, Arity, _BaseClauses, _RecClauses, _MemoEnabled, _MemoStrategy, Code) :-
    cil_linear_recursion_bytecode(PredStr, Arity, BodyInstrs),
    cil_ensure_strings(BodyInstrs, BodyStrs),
    atomic_list_concat(BodyStrs, '\n', BodyCode),
    format(string(Code),
'// Generated by UnifyWeaver ILAsm Target - Linear Recursion
// Predicate: ~w/~w

.assembly extern mscorlib {}
.assembly PrologGenerated {}

.class public auto ansi PrologGenerated extends [mscorlib]System.Object {

.method public static int64 ~w(int64 arg0) cil managed {
    .maxstack 4
    .locals init (int64 result, int64 i)
~w
}

.method public static void Main(string[] args) cil managed {
    .entrypoint
    .maxstack 4
    ldarg.0
    ldc.i4.0
    ldelem.ref
    call int64 [mscorlib]System.Int64::Parse(string)
    call int64 PrologGenerated::~w(int64)
    call void [mscorlib]System.Console::WriteLine(int64)
    ret
}

}
', [PredStr, Arity, PredStr, BodyCode, PredStr]).

%% Tree recursion → CIL recursive with .tail (no memoization in IL)
tree_recursion:compile_tree_pattern(ilasm, PredStr, _Arity, _BaseClauses, _RecClauses, Code) :-
    atom_string(Pred, PredStr),
    ClassName = 'PrologGenerated',
    cil_tree_recursion_bytecode(PredStr, ClassName, BodyInstrs),
    cil_ensure_strings(BodyInstrs, BodyStrs),
    atomic_list_concat(BodyStrs, '\n', BodyCode),
    format(string(Code),
'// Generated by UnifyWeaver ILAsm Target - Tree Recursion
// Predicate: ~w/2

.assembly extern mscorlib {}
.assembly PrologGenerated {}

.class public auto ansi PrologGenerated extends [mscorlib]System.Object {

.method public static int64 ~w(int64 arg0) cil managed {
    .maxstack 4
~w
}

.method public static void Main(string[] args) cil managed {
    .entrypoint
    .maxstack 4
    ldarg.0
    ldc.i4.0
    ldelem.ref
    call int64 [mscorlib]System.Int64::Parse(string)
    call int64 PrologGenerated::~w(int64)
    call void [mscorlib]System.Console::WriteLine(int64)
    ret
}

}
', [Pred, PredStr, BodyCode, PredStr]).

%% Mutual recursion → CIL static methods with .tail prefix
mutual_recursion:compile_mutual_pattern(ilasm, Predicates, _MemoEnabled, _MemoStrategy, Code) :-
    ClassName = 'PrologGenerated',
    %% Generate a method for each predicate
    ilasm_mutual_methods(Predicates, Predicates, ClassName, MethodCodes),
    atomic_list_concat(MethodCodes, '\n\n', MethodSection),
    %% Entry point uses first predicate
    Predicates = [FirstPred/_|_],
    atom_string(FirstPred, FirstStr),
    format(string(Code),
'// Generated by UnifyWeaver ILAsm Target - Mutual Recursion
// Group: ~w

.assembly extern mscorlib {}
.assembly PrologGenerated {}

.class public auto ansi PrologGenerated extends [mscorlib]System.Object {

~w

.method public static void Main(string[] args) cil managed {
    .entrypoint
    .maxstack 4
    ldarg.0
    ldc.i4.0
    ldelem.ref
    call int64 [mscorlib]System.Int64::Parse(string)
    call int64 PrologGenerated::~w(int64)
    call void [mscorlib]System.Console::WriteLine(int64)
    ret
}

}
', [Predicates, MethodSection, FirstStr]).

ilasm_mutual_methods([], _, _, []).
ilasm_mutual_methods([Pred/Arity|Rest], AllPreds, ClassName, [MethodCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    %% Base case value
    (   BaseClauses = [clause(BHead, true)|_],
        BHead =.. [_, BaseInput]
    ->  (number(BaseInput) -> true ; BaseInput = 0)
    ;   BaseInput = 0
    ),
    %% Find called predicate
    (   RecClauses = [clause(_, RBody)|_]
    ->  normalize_goals(RBody, Goals),
        (   member(Call, Goals), compound(Call), Call =.. [CalledPred, _],
            member(CalledPred/_CA, AllPreds), CalledPred \= Pred
        ->  atom_string(CalledPred, CalledStr)
        ;   CalledStr = PredStr
        )
    ;   CalledStr = PredStr
    ),
    format(string(CallInstr), '    .tail\n    call int64 ~w::~w(int64)', [ClassName, CalledStr]),
    format(string(MethodCode),
'.method public static int64 ~w(int64 arg0) cil managed {
    .maxstack 4
    // Base case: arg0 == ~w
    ldarg.0
    ldc.i8 ~w
    beq BASE_~w
    // Recursive: .tail call ~w(arg0 - 1)
    ldarg.0
    ldc.i8 1
    sub
~w
    ret
BASE_~w:
    ldc.i8 1
    ret
}', [PredStr, BaseInput, BaseInput, PredStr, CalledStr, CallInstr, PredStr]),
    ilasm_mutual_methods(Rest, AllPreds, ClassName, RestCodes).

%% ============================================
%% GENERAL RECURSIVE PATTERN (visited-set cycle safety)
%% ============================================

:- multifile advanced_recursive_compiler:compile_general_recursive_pattern/6.

%% No-visited-pattern — plain recursive CIL without HashSet
advanced_recursive_compiler:compile_general_recursive_pattern(ilasm, PredStr, Arity, BaseClauses, RecClauses, Code) :-
    atom_string(Pred, PredStr),
    append(BaseClauses, RecClauses, AllClauses),
    \+ is_per_path_visited_pattern(Pred, Arity, AllClauses, _),
    !,
    (   BaseClauses = [(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs], last(BaseArgs, BaseResult), integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    format(string(Code),
'// General recursive: ~w (plain, no visited pattern)\n\c
\n\c
.method public static int32 ~w(string arg1) cil managed {\n\c
    .maxstack 4\n\c
    // Base case + recursive call (no visited set)\n\c
    ldc.i4 ~w\n\c
    ret\n\c
}\n',
    [PredStr, PredStr, BaseVal]).

advanced_recursive_compiler:compile_general_recursive_pattern(ilasm, PredStr, _Arity, BaseClauses, _RecClauses, Code) :-
    %% Extract base value from first base clause
    (   BaseClauses = [(BaseHead, _BaseBody)|_],
        BaseHead =.. [_|BaseArgs],
        last(BaseArgs, BaseResult),
        integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    %% Extract base input from first base clause
    (   BaseClauses = [(BaseHead2, _)|_],
        BaseHead2 =.. [_|BaseArgs2],
        BaseArgs2 = [BaseInput|_],
        integer(BaseInput)
    ->  BaseIn = BaseInput
    ;   BaseIn = 0
    ),
    format(string(Code),
'// Generated by UnifyWeaver ILAsm Target - General Recursion with Visited Set

.method public static int32 ~w(string arg1) cil managed {
    .maxstack 4
    .locals init (class [mscorlib]System.Collections.Generic.HashSet`1<string> visited)
    newobj instance void class [mscorlib]System.Collections.Generic.HashSet`1<string>::.ctor()
    stloc.0
    ldarg.0
    ldloc.0
    call int32 ~wWorker(string, class [mscorlib]System.Collections.Generic.HashSet`1<string>)
    ret
}

.method public static int32 ~wWorker(string arg1, class [mscorlib]System.Collections.Generic.HashSet`1<string> visited) cil managed {
    .maxstack 4
    // Check if visited contains arg1
    ldarg.1
    ldarg.0
    callvirt instance bool class [mscorlib]System.Collections.Generic.HashSet`1<string>::Contains(!0)
    brfalse NOT_VISITED
    ldc.i4 ~w
    ret
NOT_VISITED:
    // Add arg1 to visited
    ldarg.1
    ldarg.0
    callvirt instance bool class [mscorlib]System.Collections.Generic.HashSet`1<string>::Add(!0)
    pop
    // Base case check
    ldarg.0
    ldstr "~w"
    call bool string::op_Equality(string, string)
    brfalse RECURSIVE
    ldc.i4 ~w
    ret
RECURSIVE:
    // Recursive call
    ldarg.0
    ldarg.1
    call int32 ~wWorker(string, class [mscorlib]System.Collections.Generic.HashSet`1<string>)
    ret
}',
        [PredStr, PredStr,
         PredStr,
         BaseVal,
         BaseIn, BaseVal,
         PredStr]).
