:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025-2026 John William Creighton (@s243a)
%
% ilasm_target.pl — .NET ILAsm (CIL assembly) target.
% Produces IL assembly text compilable by ilasm.

:- module(ilasm_target, [
    compile_predicate_to_ilasm/3     % +PredIndicator, +Options, -ILCode
]).

:- use_module('../core/clause_body_analysis').
:- use_module('../core/cil_bytecode').
:- use_module(library(lists)).

% ============================================================================
% ENTRY POINT
% ============================================================================

compile_predicate_to_ilasm(PredIndicator, Options, ILCode) :-
    (   PredIndicator = Module:Name/Arity
    ->  true
    ;   PredIndicator = Name/Arity, Module = user
    ),
    atom_string(Name, PredStr),
    functor(Head, Name, Arity),
    findall(Head-Body, Module:clause(Head, Body), Clauses),
    (   Clauses == []
    ->  throw(error(clause_not_found(Module:Head), _))
    ;   true
    ),
    %% Determine input/output split
    Arity1 is Arity - 1,
    %% Try native clause body lowering
    (   native_ilasm_clause_body(PredStr/Arity, Clauses, MethodBody)
    ->  true
    ;   MethodBody = "    ldstr \"Compilation failed\"\n    throw"
    ),
    %% Build method signature
    ilasm_arg_list(Arity1, ArgDecls),
    ilasm_locals_from_body(MethodBody, LocalDecls),
    %% Wrap in class
    option(class_name(ClassName), Options, 'PrologGenerated'),
    option(include_main(IncludeMain), Options, true),
    (   IncludeMain
    ->  format(string(MainMethod),
'.method public static void Main(string[] args) cil managed {
    .entrypoint
    .maxstack 8
    // Example: call with first arg
    ldarg.0
    ldc.i4.0
    ldelem.ref
    call string [mscorlib]System.String::Trim(string)
    call int64 [mscorlib]System.Int64::Parse(string)
    call int64 ~w.~w::~w(~w)
    call void [mscorlib]System.Console::WriteLine(int64)
    ret
}', [ClassName, ClassName, PredStr, ArgDecls])
    ;   MainMethod = ""
    ),
    format(string(ILCode),
'// Generated by UnifyWeaver ILAsm Target
// Predicate: ~w/~w

.assembly extern mscorlib {}
.assembly ~w {}

.class public auto ansi ~w extends [mscorlib]System.Object {

.method public static int64 ~w(~w) cil managed {
    .maxstack 8
~w
~w
}

~w

}
', [PredStr, Arity, ClassName, ClassName, PredStr, ArgDecls, LocalDecls, MethodBody, MainMethod]).

%% ilasm_arg_list(+N, -ArgDecls)
ilasm_arg_list(0, "") :- !.
ilasm_arg_list(N, ArgDecls) :-
    findall(Decl, (
        between(1, N, I),
        format(string(Decl), 'int64 arg~w', [I])
    ), Decls),
    atomic_list_concat(Decls, ', ', ArgDecls).

%% ilasm_locals_from_body(+Body, -LocalDecls)
%  Extract local variable declarations from method body.
ilasm_locals_from_body(Body, LocalDecls) :-
    split_string(Body, "\n", "", Lines),
    findall(VarName, (
        member(Line, Lines),
        (   sub_string(Line, _, _, _, "stloc ")
        ->  split_string(Line, " ", " ", Parts),
            last(Parts, VarName)
        ;   fail
        )
    ), VarNames0),
    sort(VarNames0, VarNames),
    (   VarNames == []
    ->  LocalDecls = ""
    ;   findall(Decl, (
            member(V, VarNames),
            format(string(Decl), 'int64 ~w', [V])
        ), Decls),
        atomic_list_concat(Decls, ', ', DeclStr),
        format(string(LocalDecls), '    .locals init (~w)', [DeclStr])
    ).

% ============================================================================
% NATIVE CLAUSE BODY LOWERING
% ============================================================================

%% native_ilasm_clause_body(+PredSpec, +Clauses, -Code)
native_ilasm_clause_body(PredStr/Arity, Clauses, Code) :-
    Arity1 is Arity - 1,
    ilasm_clauses_to_branches(Clauses, Arity1, Branches),
    Branches \= [],
    cil_if_chain(Branches, 0, "CL", AllInstrs),
    cil_ensure_strings(AllInstrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', Code).

%% ilasm_clauses_to_branches(+Clauses, +Arity1, -Branches)
ilasm_clauses_to_branches([], _, []).
ilasm_clauses_to_branches([Head-Body|Rest], Arity1, Result) :-
    ilasm_clauses_to_branches(Rest, Arity1, RestBranches),
    (   Body \== true,
        Head =.. [_|AllArgs],
        length(InputArgs, Arity1),
        append(InputArgs, [OutputArg], AllArgs),
        build_head_varmap(InputArgs, 1, VarMap),
        normalize_goals(Body, Goals),
        %% Try classify_goal_sequence first
        (   classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
            ClassifiedGoals \= [],
            ilasm_compile_classified(ClassifiedGoals, OutputArg, VarMap, GuardInstrs, ValueInstrs)
        ->  true
        ;   %% Fallback to basic split
            once(clause_guard_output_split(Goals, VarMap, Guards, Outputs)),
            ilasm_compile_guards(Guards, VarMap, GuardInstrs),
            ilasm_output_to_instrs(OutputArg, Outputs, VarMap, ValueInstrs)
        )
    ->  Result = [branch(GuardInstrs, ValueInstrs)|RestBranches]
    ;   %% Pure fact clause
        Head =.. [_|AllArgs],
        length(InputArgs, Arity1),
        append(InputArgs, [OutputArg], AllArgs),
        build_head_varmap(InputArgs, 1, VarMap),
        Body == true,
        ilasm_head_guard_instrs(InputArgs, 1, VarMap, GuardInstrs),
        cil_resolve_value(OutputArg, VarMap, ValInstr),
        ValueInstrs = [ValInstr]
    ->  Result = [branch(GuardInstrs, ValueInstrs)|RestBranches]
    ;   Result = RestBranches
    ).

%% ilasm_compile_guards(+Guards, +VarMap, -Instructions)
ilasm_compile_guards([], _, []).
ilasm_compile_guards([G|Gs], VarMap, AllInstrs) :-
    cil_guard_to_instrs(G, VarMap, "NEXT", GInstrs),
    ilasm_compile_guards(Gs, VarMap, RestInstrs),
    append(GInstrs, RestInstrs, AllInstrs).

%% ilasm_output_to_instrs(+OutputArg, +Outputs, +VarMap, -Instructions)
ilasm_output_to_instrs(OutputArg, [], VarMap, [Instr]) :- !,
    cil_resolve_value(OutputArg, VarMap, Instr).
ilasm_output_to_instrs(_OutputArg, Outputs, VarMap, Instrs) :-
    last(Outputs, LastGoal),
    (   LastGoal = (_ is ArithExpr)
    ->  cil_expr_to_instrs(ArithExpr, VarMap, Instrs)
    ;   LastGoal = (_ = Expr)
    ->  cil_expr_to_instrs(Expr, VarMap, Instrs)
    ;   cil_resolve_value(LastGoal, VarMap, Instr),
        Instrs = [Instr]
    ).

%% ilasm_head_guard_instrs(+InputArgs, +Index, +VarMap, -Instructions)
ilasm_head_guard_instrs([], _, _, []).
ilasm_head_guard_instrs([Arg|Rest], Index, VarMap, Instrs) :-
    NextIndex is Index + 1,
    ilasm_head_guard_instrs(Rest, NextIndex, VarMap, RestInstrs),
    (   nonvar(Arg)
    ->  format(string(LoadArg), '    ldarg.~w', [Index]),
        (   integer(Arg)
        ->  format(string(LoadConst), '    ldc.i8 ~w', [Arg]),
            BrInstr = '    bne.un NEXT'
        ;   format(string(LoadConst), '    ldstr "~w"', [Arg]),
            BrInstr = '    call bool [mscorlib]System.String::op_Inequality(string, string)\n    brtrue NEXT'
        ),
        Instrs = [LoadArg, LoadConst, BrInstr|RestInstrs]
    ;   Instrs = RestInstrs
    ).

% ============================================================================
% CLASSIFIED GOAL COMPILATION
% ============================================================================

%% ilasm_compile_classified(+ClassifiedGoals, +OutputArg, +VarMap, -GuardInstrs, -ValueInstrs)
ilasm_compile_classified(ClassifiedGoals, OutputArg, VarMap, GuardInstrs, ValueInstrs) :-
    findall(GInstrs, (
        member(guard(G, _), ClassifiedGoals),
        cil_guard_to_instrs(G, VarMap, "NEXT", GInstrs)
    ), GuardInstrLists),
    append(GuardInstrLists, GuardInstrs),
    %% Find output value
    (   member(output(Goal, _, _), ClassifiedGoals)
    ->  ilasm_classified_output(Goal, VarMap, ValueInstrs)
    ;   member(output_ite(If, Then, Else, _), ClassifiedGoals)
    ->  ilasm_classified_ite(If, Then, Else, VarMap, ValueInstrs)
    ;   cil_resolve_value(OutputArg, VarMap, ValInstr),
        ValueInstrs = [ValInstr]
    ).

%% ilasm_classified_output(+Goal, +VarMap, -Instrs)
ilasm_classified_output(Goal, VarMap, Instrs) :-
    (   Goal = (_ is ArithExpr)
    ->  cil_expr_to_instrs(ArithExpr, VarMap, Instrs)
    ;   Goal = (_ = Expr)
    ->  cil_expr_to_instrs(Expr, VarMap, Instrs)
    ;   cil_resolve_value(Goal, VarMap, Instr),
        Instrs = [Instr]
    ).

%% ilasm_classified_ite(+If, +Then, +Else, +VarMap, -Instrs)
ilasm_classified_ite(If, Then, Else, VarMap, Instrs) :-
    cil_guard_to_instrs(If, VarMap, "ITE_else", CondInstrs),
    %% Then branch value
    normalize_goals(Then, ThenGoals),
    last(ThenGoals, ThenLast),
    ilasm_classified_output(ThenLast, VarMap, ThenInstrs),
    %% Else branch value
    normalize_goals(Else, ElseGoals),
    last(ElseGoals, ElseLast),
    ilasm_classified_output(ElseLast, VarMap, ElseInstrs),
    %% Assemble
    append(CondInstrs, ThenInstrs, PreBr),
    append(PreBr, ['    br ITE_end', 'ITE_else:'], PreElse),
    append(PreElse, ElseInstrs, PreEnd),
    append(PreEnd, ['ITE_end:'], Instrs).

% ============================================================================
% MULTIFILE HOOKS — compile_expression framework
% ============================================================================

clause_body_analysis:render_output_goal(ilasm, Goal, VarMap, Line, VarName, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        cil_expr_to_instrs(Expr, VarMap, ExprInstrs),
        cil_ensure_strings(ExprInstrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprCode),
        format(string(Line), '~w\n    stloc ~w', [ExprCode, VarName])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        cil_expr_to_instrs(ArithExpr, VarMap, ExprInstrs),
        cil_ensure_strings(ExprInstrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprCode),
        format(string(Line), '~w\n    stloc ~w', [ExprCode, VarName])
    ;   VarName = "_", VarMapOut = VarMap,
        Line = "    // unsupported output goal"
    ).

clause_body_analysis:render_guard_condition(ilasm, Goal, VarMap, CondStr) :-
    cil_guard_to_instrs(Goal, VarMap, "L_false", Instrs),
    cil_ensure_strings(Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', CondStr).

clause_body_analysis:render_branch_value(ilasm, Branch, VarMap, ExprStr) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   LastGoal = (_ = Expr)
    ->  cil_resolve_value(Expr, VarMap, ExprStr)
    ;   LastGoal = (_ is ArithExpr)
    ->  cil_expr_to_instrs(ArithExpr, VarMap, Instrs),
        cil_ensure_strings(Instrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprStr)
    ;   cil_resolve_value(LastGoal, VarMap, ExprStr)
    ).

clause_body_analysis:render_ite_block(ilasm, Cond, ThenLines, ElseLines, _Indent, _ReturnVars, Lines) :-
    (   ElseLines \= []
    ->  append([Cond, 'L_then:'|ThenLines], ['    br L_end', 'L_else:'|ElseLines], Pre),
        append(Pre, ['L_end:'], Lines)
    ;   append([Cond, 'L_then:'|ThenLines], ['L_end:'], Lines)
    ).

% ============================================================================
% GUARD CONDITION (text-based for classify_goal_sequence)
% ============================================================================

ilasm_guard_condition(Goal, VarMap, CondStr) :-
    cil_guard_to_instrs(Goal, VarMap, "L_false", Instrs),
    cil_ensure_strings(Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', CondStr).
