:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% jamaica_target.pl - Jamaica JVM Macro Assembly Target
% Compiles Prolog predicates to Jamaica assembly (.ja files).
% Uses Java-like class syntax with bytecode + macro method bodies.
% Shares JVM bytecode infrastructure with Krakatau target.

:- module(jamaica_target, [
    compile_predicate_to_jamaica/3,      % +PredIndicator, +Options, -Code
    compile_predicate/3,                 % +PredIndicator, +Options, -Code
    compile_jamaica_class/4,             % +ClassName, +Methods, +Options, -Code
    write_jamaica_program/2,             % +Code, +Filename
    init_jamaica_target/0
]).

:- use_module(library(lists)).
:- use_module('../core/clause_body_analysis').
:- use_module('../core/jvm_bytecode').

%% init_jamaica_target
init_jamaica_target.

%% compile_predicate/3 - dispatch alias
compile_predicate(PredArity, Options, Code) :-
    compile_predicate_to_jamaica(PredArity, Options, Code).

%% compile_predicate_to_jamaica(+PredIndicator, +Options, -Code)
compile_predicate_to_jamaica(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'Jamaica target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_jamaica(Pred, Arity, Clauses, Options, Code)
    ).

%% compile_clauses_to_jamaica(+Pred, +Arity, +Clauses, +Options, -Code)
compile_clauses_to_jamaica(Pred, Arity, Clauses, Options, Code) :-
    atom_string(Pred, PredStr),
    (   option(class_name(ClassName), Options)
    ->  true
    ;   format(string(ClassName), 'Prolog_~w', [PredStr])
    ),
    % Try native lowering first
    (   native_jamaica_clause_body(PredStr/Arity, Clauses, MethodBody)
    ->  true
    ;   % Fallback: simple identity
        Arity1 is Arity - 1,
        (   Arity1 > 0
        ->  MethodBody = "    iload arg1\n    ireturn"
        ;   MethodBody = "    iconst_0\n    ireturn"
        )
    ),
    Arity1 is Arity - 1,
    jamaica_param_list(Arity1, ParamList),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target
// Predicate: ~w/~w

public class ~w {

  %default_constructor public

  public static int ~w(~w) {
~w
  }
}
', [PredStr, Arity, ClassName, PredStr, ParamList, MethodBody]).

%% jamaica_param_list(+N, -ParamList)
jamaica_param_list(0, "") :- !.
jamaica_param_list(N, ParamList) :-
    findall(Param, (
        between(1, N, I),
        format(string(Param), 'int arg~w', [I])
    ), Params),
    atomic_list_concat(Params, ', ', ParamList).

%% native_jamaica_clause_body(+PredStr/Arity, +Clauses, -Code)
%%   Uses shared JVM bytecode infrastructure with symbolic variable style.
native_jamaica_clause_body(PredStr/Arity, Clauses, Code) :-
    \+ (member(_-Body, Clauses), Body == true),
    jvm_native_clause_body(PredStr/Arity, Clauses, symbolic, format(jamaica), Code).

%% compile_jamaica_class(+ClassName, +Methods, +Options, -Code)
%%   Compile a complete Jamaica class with multiple methods.
%%   Methods: list of method(Name, Params, RetType, Body)
compile_jamaica_class(ClassName, Methods, _Options, Code) :-
    maplist(jamaica_method_code, Methods, MethodCodes),
    atomic_list_concat(MethodCodes, '\n', MethodSection),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target

public class ~w {

  %default_constructor public

~w
}
', [ClassName, MethodSection]).

jamaica_method_code(method(Name, Params, RetType, Body), Code) :-
    maplist(jamaica_typed_param, Params, ParamStrs),
    atomic_list_concat(ParamStrs, ', ', ParamList),
    format(string(Code),
'  public static ~w ~w(~w) {
~w
  }
', [RetType, Name, ParamList, Body]).

jamaica_typed_param(param(Name, Type), Str) :-
    format(string(Str), '~w ~w', [Type, Name]).

%% write_jamaica_program(+Code, +Filename)
write_jamaica_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('Jamaica program written to: ~w~n', [Filename]).
