:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% jamaica_target.pl - Jamaica JVM Macro Assembly Target
% Compiles Prolog predicates to Jamaica assembly (.ja files).
% Uses Java-like class syntax with bytecode + macro method bodies.
% Shares JVM bytecode infrastructure with Krakatau target.

:- module(jamaica_target, [
    compile_predicate_to_jamaica/3,      % +PredIndicator, +Options, -Code
    compile_predicate/3,                 % +PredIndicator, +Options, -Code
    compile_jamaica_class/4,             % +ClassName, +Methods, +Options, -Code
    write_jamaica_program/2,             % +Code, +Filename
    init_jamaica_target/0,
    compile_tail_recursion_jamaica/3,
    compile_linear_recursion_jamaica/3,
    compile_tree_recursion_jamaica/3,
    compile_multicall_recursion_jamaica/3,
    compile_direct_multicall_jamaica/3,
    compile_mutual_recursion_jamaica/2
]).

:- use_module(library(lists)).
:- use_module('../core/clause_body_analysis').
:- use_module('../core/jvm_bytecode').
:- use_module('../bindings/jvm_asm_bindings', [init_jvm_asm_bindings/0]).
:- use_module('../core/component_registry').

% Component registration
:- initialization((
    catch(
        register_component_type(source, custom_jamaica, custom_jamaica, [
            description("Custom Jamaica JVM Assembly Component")
        ]),
        _,
        true
    )
), now).

% Advanced recursion multifile hooks
:- use_module('../core/advanced/tail_recursion', []).
:- use_module('../core/advanced/linear_recursion', []).
:- use_module('../core/advanced/tree_recursion', []).
:- use_module('../core/advanced/multicall_linear_recursion', []).
:- use_module('../core/advanced/direct_multi_call_recursion', []).
:- use_module('../core/advanced/mutual_recursion', []).

:- multifile tail_recursion:compile_tail_pattern/9.
:- multifile linear_recursion:compile_linear_pattern/8.
:- multifile tree_recursion:compile_tree_pattern/6.
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.
:- multifile mutual_recursion:compile_mutual_pattern/5.

%% init_jamaica_target
init_jamaica_target :-
    init_jvm_asm_bindings.

%% compile_predicate/3 - dispatch alias
compile_predicate(PredArity, Options, Code) :-
    compile_predicate_to_jamaica(PredArity, Options, Code).

%% compile_predicate_to_jamaica(+PredIndicator, +Options, -Code)
compile_predicate_to_jamaica(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'Jamaica target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_jamaica(Pred, Arity, Clauses, Options, Code)
    ).

%% compile_clauses_to_jamaica(+Pred, +Arity, +Clauses, +Options, -Code)
compile_clauses_to_jamaica(Pred, Arity, Clauses, Options, Code) :-
    atom_string(Pred, PredStr),
    (   option(class_name(ClassName), Options)
    ->  true
    ;   format(string(ClassName), 'Prolog_~w', [PredStr])
    ),
    % Try native lowering first
    (   native_jamaica_clause_body(PredStr/Arity, Clauses, MethodBody)
    ->  true
    ;   % Fallback: simple identity
        Arity1 is Arity - 1,
        (   Arity1 > 0
        ->  MethodBody = "    iload arg1\n    ireturn"
        ;   MethodBody = "    iconst_0\n    ireturn"
        )
    ),
    Arity1 is Arity - 1,
    jamaica_param_list(Arity1, ParamList),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target
// Predicate: ~w/~w

public class ~w {

  %default_constructor public

  public static int ~w(~w) {
~w
  }
}
', [PredStr, Arity, ClassName, PredStr, ParamList, MethodBody]).

%% jamaica_param_list(+N, -ParamList)
jamaica_param_list(0, "") :- !.
jamaica_param_list(N, ParamList) :-
    findall(Param, (
        between(1, N, I),
        format(string(Param), 'int arg~w', [I])
    ), Params),
    atomic_list_concat(Params, ', ', ParamList).

%% native_jamaica_clause_body(+PredStr/Arity, +Clauses, -Code)
%%   Uses shared JVM bytecode infrastructure with symbolic variable style.
native_jamaica_clause_body(PredStr/Arity, Clauses, Code) :-
    \+ (member(_-Body, Clauses), Body == true),
    jvm_native_clause_body(PredStr/Arity, Clauses, symbolic, format(jamaica), Code).

%% compile_jamaica_class(+ClassName, +Methods, +Options, -Code)
%%   Compile a complete Jamaica class with multiple methods.
%%   Methods: list of method(Name, Params, RetType, Body)
compile_jamaica_class(ClassName, Methods, _Options, Code) :-
    maplist(jamaica_method_code, Methods, MethodCodes),
    atomic_list_concat(MethodCodes, '\n', MethodSection),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target

public class ~w {

  %default_constructor public

~w
}
', [ClassName, MethodSection]).

jamaica_method_code(method(Name, Params, RetType, Body), Code) :-
    maplist(jamaica_typed_param, Params, ParamStrs),
    atomic_list_concat(ParamStrs, ', ', ParamList),
    format(string(Code),
'  public static ~w ~w(~w) {
~w
  }
', [RetType, Name, ParamList, Body]).

jamaica_typed_param(param(Name, Type), Str) :-
    format(string(Str), '~w ~w', [Type, Name]).

%% ============================================
%% RECURSION PATTERN HOOKS
%% ============================================

%% Tail recursion
tail_recursion:compile_tail_pattern(jamaica, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, _StepOp, _ExitAfterResult, Code) :-
    atom_string(Pred, PredStr),
    compile_tail_recursion_jamaica(Pred/Arity, [], Code).

compile_tail_recursion_jamaica(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_tail_recursion_bytecode(PredStr, Arity, symbolic, BodyInstrs),
    jvm_entry_method_bytecode(PredStr, Arity, symbolic, EntryInstrs),
    format(string(ClassName), 'Prolog_~w', [PredStr]),
    jamaica_wrap_recursion(ClassName, PredStr, Arity,
        "int arg1, int arg2", BodyInstrs,
        "int arg1", EntryInstrs, Code).

%% Linear recursion
linear_recursion:compile_linear_pattern(jamaica, PredStr, Arity, _BaseClauses, _RecClauses, _MemoEnabled, _MemoStrategy, Code) :-
    atom_string(Pred, PredStr),
    compile_linear_recursion_jamaica(Pred/Arity, [], Code).

compile_linear_recursion_jamaica(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_linear_recursion_bytecode(PredStr, Arity, symbolic, BodyInstrs),
    jamaica_wrap_single(PredStr, Arity, "int arg1", BodyInstrs, Code).

%% Tree recursion
tree_recursion:compile_tree_pattern(jamaica, PredStr, Arity, _BaseClauses, _RecClauses, Code) :-
    atom_string(Pred, PredStr),
    compile_tree_recursion_jamaica(Pred/Arity, [], Code).

compile_tree_recursion_jamaica(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_tree_recursion_bytecode(PredStr, Arity, symbolic, BodyInstrs),
    jamaica_wrap_single(PredStr, Arity, "int arg1", BodyInstrs, Code).

%% Multicall recursion
multicall_linear_recursion:compile_multicall_pattern(jamaica, PredStr, BaseClauses, _RecClauses, _MemoEnabled, Code) :-
    atom_string(Pred, PredStr),
    length(BaseClauses, _),
    compile_multicall_recursion_jamaica(Pred/2, [], Code).

compile_multicall_recursion_jamaica(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_multicall_recursion_bytecode(PredStr, Arity, symbolic, BodyInstrs),
    jamaica_wrap_single(PredStr, Arity, "int arg1", BodyInstrs, Code).

%% Direct multicall recursion
direct_multi_call_recursion:compile_direct_multicall_pattern(jamaica, PredStr, _BaseClauses, _RecClause, Code) :-
    atom_string(Pred, PredStr),
    compile_direct_multicall_jamaica(Pred/2, [], Code).

compile_direct_multicall_jamaica(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_direct_multicall_bytecode(PredStr, Arity, symbolic, BodyInstrs),
    jamaica_wrap_single(PredStr, Arity, "int arg1", BodyInstrs, Code).

%% Mutual recursion
mutual_recursion:compile_mutual_pattern(jamaica, Predicates, _MemoEnabled, _MemoStrategy, Code) :-
    compile_mutual_recursion_jamaica(Predicates, [], Code).

compile_mutual_recursion_jamaica(Predicates, _Options, Code) :-
    (   Predicates = [Pred1|_]
    ->  atom_string(Pred1, P1Str),
        format(string(ClassName), 'Prolog_~w', [P1Str])
    ;   ClassName = "Prolog_mutual"
    ),
    jvm_mutual_recursion_bytecode(Predicates, ClassName, symbolic, Methods),
    maplist(jamaica_mutual_method, Methods, MethodCodes),
    atomic_list_concat(MethodCodes, '\n', MethodSection),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target - Mutual Recursion

public class ~w {

  %default_constructor public

~w
}
', [ClassName, MethodSection]).

jamaica_mutual_method(method(Name, Instrs), Code) :-
    maplist(ensure_string, Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', Body),
    format(string(Code),
'  public static int ~w(int arg1) {
~w
  }
', [Name, Body]).

%% ============================================
%% WRAPPING HELPERS
%% ============================================

%% jamaica_wrap_single(+PredStr, +Arity, +ParamList, +Instructions, -Code)
jamaica_wrap_single(PredStr, _Arity, ParamList, Instructions, Code) :-
    maplist(ensure_string, Instructions, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', Body),
    format(string(ClassName), 'Prolog_~w', [PredStr]),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target - Recursion

public class ~w {

  %default_constructor public

  public static int ~w(~w) {
~w
  }
}
', [ClassName, PredStr, ParamList, Body]).

%% jamaica_wrap_recursion(+ClassName, +PredStr, +Arity, +CoreParams, +CoreInstrs, +EntryParams, +EntryInstrs, -Code)
jamaica_wrap_recursion(ClassName, PredStr, _Arity, CoreParams, CoreInstrs, EntryParams, EntryInstrs, Code) :-
    maplist(ensure_string, CoreInstrs, CoreStrs),
    atomic_list_concat(CoreStrs, '\n', CoreBody),
    maplist(ensure_string, EntryInstrs, EntryStrs),
    atomic_list_concat(EntryStrs, '\n', EntryBody),
    format(string(EntryName), '~w_entry', [PredStr]),
    format(string(Code),
'// Generated by UnifyWeaver Jamaica Target - Tail Recursion

public class ~w {

  %default_constructor public

  public static int ~w(~w) {
~w
  }

  public static int ~w(~w) {
~w
  }
}
', [ClassName, PredStr, CoreParams, CoreBody, EntryName, EntryParams, EntryBody]).

ensure_string(S, S) :- string(S), !.
ensure_string(A, S) :- atom_string(A, S).

%% write_jamaica_program(+Code, +Filename)
write_jamaica_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('Jamaica program written to: ~w~n', [Filename]).

% ============================================================================
% MULTIFILE HOOKS — Register Jamaica renderers for shared compile_expression
% ============================================================================
%
% Jamaica produces JVM assembly text. Output goals become istore/astore
% instructions. Guards become comparison + branch instructions.

clause_body_analysis:render_output_goal(jamaica, Goal, VarMap, Line, VarName, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        jvm_bytecode:jvm_expr_to_bytecode(Expr, VarMap, symbolic, ExprInstrs),
        maplist(ensure_string, ExprInstrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprCode),
        format(string(Line), '~w\nastore ~w', [ExprCode, VarName])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        jvm_bytecode:jvm_expr_to_bytecode(ArithExpr, VarMap, symbolic, ExprInstrs),
        maplist(ensure_string, ExprInstrs, StrInstrs),
        atomic_list_concat(StrInstrs, '\n', ExprCode),
        format(string(Line), '~w\nlstore ~w', [ExprCode, VarName])
    ;   VarName = "_", VarMapOut = VarMap,
        Line = "; unsupported output goal"
    ).

clause_body_analysis:render_guard_condition(jamaica, Goal, VarMap, CondStr) :-
    jvm_bytecode:jvm_guard_to_bytecode(Goal, VarMap, symbolic, "L_false", Instrs),
    maplist(ensure_string, Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', CondStr).

clause_body_analysis:render_branch_value(jamaica, Branch, VarMap, ExprStr) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   LastGoal = (_ = Expr) -> true ; LastGoal = (_ is Expr) -> true ; Expr = LastGoal),
    jvm_bytecode:jvm_expr_to_bytecode(Expr, VarMap, symbolic, Instrs),
    maplist(ensure_string, Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', ExprStr).

clause_body_analysis:render_ite_block(jamaica, Cond, ThenLines, ElseLines, _Indent, _ReturnVars, Lines) :-
    format(string(CondLine), '~w', [Cond]),
    format(string(ThenLabel), 'L_then:', []),
    format(string(ElseLabel), 'L_else:', []),
    format(string(EndLabel), 'L_end:', []),
    (   ElseLines \= []
    ->  append([CondLine, ThenLabel|ThenLines], ['goto L_end', ElseLabel|ElseLines], Pre),
        append(Pre, [EndLabel], Lines)
    ;   append([CondLine, ThenLabel|ThenLines], [EndLabel], Lines)
    ).

ensure_string(Atom, Str) :- atom(Atom), !, atom_string(Atom, Str).
ensure_string(Str, Str) :- string(Str), !.
ensure_string(Term, Str) :- term_string(Term, Str).
