:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% java_target.pl - Java Target for UnifyWeaver
% Generates standalone Java programs for record/field processing
% Supports streaming JSONL I/O and Gradle build integration

:- module(java_target, [
    compile_predicate_to_java/3,      % +Predicate, +Options, -JavaCode
    compile_java_pipeline/3,          % +Predicates, +Options, -JavaCode
    compile_facts_to_java/3,          % +Pred, +Arity, -JavaCode  -- NEW
    write_java_program/2,             % +JavaCode, +FilePath
    generate_gradle_build/2,          % +Options, -GradleCode
    init_java_target/0,               % Initialize Java target
    test_java_pipeline_mode/0         % Test pipeline mode
]).

:- use_module(library(lists)).

% Binding system integration
:- use_module('../core/binding_registry').
:- use_module('../bindings/java_bindings').

% Track required imports
:- dynamic required_java_import/1.

%% init_java_target
%  Initialize Java target with bindings
init_java_target :-
    retractall(required_java_import(_)),
    init_java_bindings.

%% clear_java_imports
%  Clear collected Java imports
clear_java_imports :-
    retractall(required_java_import(_)).

%% collect_java_import(+Import)
%  Record that an import is required
collect_java_import(Import) :-
    (   required_java_import(Import)
    ->  true
    ;   assertz(required_java_import(Import))
    ).

%% get_java_imports(-Imports)
%  Get all collected imports
get_java_imports(Imports) :-
    findall(I, required_java_import(I), Imports).

%% format_java_imports(+Imports, -FormattedStr)
%  Format a list of imports for Java
format_java_imports([], "").
format_java_imports(Imports, FormattedStr) :-
    Imports \= [],
    sort(Imports, UniqueImports),
    findall(Formatted,
        (   member(Import, UniqueImports),
            format(string(Formatted), "import ~w;~n", [Import])
        ),
        FormattedList),
    atomic_list_concat(FormattedList, '', FormattedStr).

%% ============================================
%% PUBLIC API
%% ============================================

%% compile_predicate_to_java(+Predicate, +Options, -JavaCode)
%  Compile a Prolog predicate to Java code
%
%  @arg Predicate Predicate indicator (Name/Arity)
%  @arg Options List of options
%  @arg JavaCode Generated Java code as atom
%
%  Options:
%  - package(Name) - Java package name (default: 'generated')
%  - class_name(Name) - Class name (default: predicate name capitalized)
%  - pipeline_input(true|false) - Enable streaming input
%  - generator_mode(true|false) - Enable generator mode with Stream.generate()
%  - json_input(true|false) - Use JSONL input format
%  - main_class(true|false) - Generate main method (default: true)
%
compile_predicate_to_java(PredIndicator, Options, JavaCode) :-
    (   PredIndicator = _Module:Pred/Arity
    ->  true
    ;   PredIndicator = Pred/Arity
    ),
    format('=== Compiling ~w/~w to Java ===~n', [Pred, Arity]),

    % Clear any previously collected imports
    clear_java_imports,

    % Check for mode
    (   option(generator_mode(true), Options)
    ->  format('  Mode: Generator (Stream.iterate)~n'),
        compile_generator_mode_java(Pred, Arity, Options, JavaCode)
    ;   option(pipeline_input(true), Options)
    ->  format('  Mode: Pipeline (streaming JSONL)~n'),
        compile_pipeline_mode_java(Pred, Arity, Options, JavaCode)
    % Default: simple predicate
    ;   format('  Mode: Simple predicate~n'),
        compile_simple_mode_java(Pred, Arity, Options, JavaCode)
    ).

%% ============================================
%% COMPILE FACTS TO JAVA (like Bash compile_facts)
%% ============================================

%% compile_facts_to_java(+Pred, +Arity, -JavaCode)
%  Compile facts to a Java class with static data
%  Matches stream_compiler:compile_facts for Bash
compile_facts_to_java(Pred, Arity, JavaCode) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredCap),
    functor(Head, Pred, Arity),
    
    % Gather all facts
    findall(Args, (clause(Head, true), Head =.. [_|Args]), AllFacts),
    
    % Generate Java array entries
    (   AllFacts == []
    ->  FactEntries = "        // No facts defined"
    ;   findall(Entry, (
            member(Args, AllFacts),
            format_java_fact_entry(Args, Entry)
        ), Entries),
        atomic_list_concat(Entries, ',\n', FactEntries)
    ),
    
    % Generate arity-specific types
    generate_java_fact_types(Arity, RecordType, StreamReturnType),
    
    % Generate formatter code
    generate_fact_formatter(Arity, FormatterCode),
    
    format(string(JavaCode),
'// Generated by UnifyWeaver Java Target - Facts Export
// Predicate: ~w/~w

package generated;

import java.util.*;
import java.util.stream.*;

/**
 * ~w facts as static Java data
 */
public class ~w {

    // Fact storage
    private static final List<~w> facts = Arrays.asList(
~w
    );

    /**
     * Get all facts as a stream
     */
    public static ~w stream() {
        return facts.stream();
    }

    /**
     * Get all facts as a list
     */
    public static List<~w> getAll() {
        return Collections.unmodifiableList(facts);
    }

    /**
     * Check if a fact exists
     */
    public static boolean contains(~w args) {
        return facts.contains(args);
    }

    /**
     * Print all facts in colon-separated format
     */
    public static void main(String[] args) {
        stream().forEach(f -> System.out.println(formatFact(f)));
    }

    private static String formatFact(~w fact) {
        ~w
    }
}
', [PredStr, Arity, PredStr, PredCap, RecordType, FactEntries, StreamReturnType, 
    RecordType, RecordType, RecordType, FormatterCode]).

%% format_java_fact_entry(+Args, -Entry)
%  Format arguments as a Java tuple/array entry
format_java_fact_entry(Args, Entry) :-
    findall(Formatted, (
        member(Arg, Args),
        format_java_value(Arg, Formatted)
    ), FormattedArgs),
    (   length(Args, 2)
    ->  FormattedArgs = [A1, A2],
        format(string(Entry), '        new String[]{~w, ~w}', [A1, A2])
    ;   atomic_list_concat(FormattedArgs, ', ', ArgsStr),
        format(string(Entry), '        new String[]{~w}', [ArgsStr])
    ).

format_java_value(Arg, Formatted) :-
    (   atom(Arg)
    ->  format(string(Formatted), '"~w"', [Arg])
    ;   number(Arg)
    ->  format(string(Formatted), '"~w"', [Arg])
    ;   format(string(Formatted), '"~w"', [Arg])
    ).

%% generate_java_fact_types(+Arity, -RecordType, -StreamReturnType)
generate_java_fact_types(1, "String", "Stream<String>").
generate_java_fact_types(2, "String[]", "Stream<String[]>").
generate_java_fact_types(N, "String[]", "Stream<String[]>") :- N > 2.

%% generate_fact_formatter(+Arity, -FormatterCode)
generate_fact_formatter(1, "return fact;").
generate_fact_formatter(2, "return fact[0] + \":\" + fact[1];").
generate_fact_formatter(N, "return String.join(\":\", fact);") :- N > 2.

%% ============================================
%% GENERATOR MODE (Java Stream.iterate/flatMap)
%% ============================================

compile_generator_mode_java(Pred, Arity, Options, JavaCode) :-
    % Standard imports for generator mode
    collect_java_import('java.util.*'),
    collect_java_import('java.util.stream.*'),
    collect_java_import('java.io.*'),
    collect_java_import('com.google.gson.Gson'),
    collect_java_import('com.google.gson.reflect.TypeToken'),
    collect_java_import('java.lang.reflect.Type'),
    
    option(package(Package), Options, generated),
    capitalize_atom(Pred, CapPred),
    
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate process function body
    (   Clauses == []
    ->  ProcessBody = "        // No clauses found - yield input unchanged\n        return Stream.of(record);"
    ;   generate_generator_body_java(Clauses, ProcessBody)
    ),
    
    get_java_imports(ImportList),
    format_java_imports(ImportList, ImportsStr),
    
    format(string(JavaCode),
"// Generated by UnifyWeaver Java Target - Generator Mode
// Predicate: ~w/~w
// Uses Java Stream.flatMap for generator semantics

package ~w;

~w

/**
 * Generator for ~w predicate.
 * Uses Java Streams for lazy, memory-efficient processing.
 */
public class ~wGenerator {

    private static final Gson gson = new Gson();
    private static final Type MAP_TYPE = new TypeToken<Map<String, Object>>(){}.getType();

    /**
     * Process a single record, returning zero or more results.
     * @param record Input record
     * @return Stream of output records
     */
    public static Stream<Map<String, Object>> process(Map<String, Object> record) {
~w
    }

    /**
     * Process all records, flattening results.
     */
    public static Stream<Map<String, Object>> processAll(Stream<Map<String, Object>> records) {
        return records.flatMap(~wGenerator::process);
    }

    /**
     * Parse a JSON line to a Map.
     */
    private static Map<String, Object> parseJson(String line) {
        try {
            return gson.fromJson(line, MAP_TYPE);
        } catch (Exception e) {
            System.err.println(\"JSON parse error: \" + e.getMessage());
            return null;
        }
    }

    /**
     * Run the generator pipeline.
     */
    public static void runPipeline() throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        
        reader.lines()
            .filter(line -> !line.isBlank())
            .map(~wGenerator::parseJson)
            .filter(Objects::nonNull)
            .flatMap(~wGenerator::process)
            .forEach(result -> System.out.println(gson.toJson(result)));
    }

    public static void main(String[] args) throws IOException {
        runPipeline();
    }
}
", [Pred, Arity, Package, ImportsStr, Pred, CapPred, ProcessBody, CapPred, CapPred, CapPred]).

%% generate_generator_body_java(+Clauses, -Code)
generate_generator_body_java(Clauses, Code) :-
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate(Name, Clauses)
    ->  % For recursive predicates, use Stream.iterate
        partition(is_recursive_clause(Name), Clauses, RecClauses, BaseClauses),
        compile_generator_recursive_java(Name, BaseClauses, RecClauses, Code)
    ;   % Non-recursive: return Stream.of(record)
        Code = "        // Non-recursive: pass through with transformations\n        return Stream.of(record);"
    ).

compile_generator_recursive_java(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),
    
    format(string(Code),
"        // Recursive generator: ~w - using Stream.iterate
        return Stream.iterate(record, current -> {
            // Transform for next iteration
            return new HashMap<>(current);
        })
        .limit(10000)
        .takeWhile(current -> !(~w))
        .map(HashMap::new);", [Name, BaseCondition]).

%% ============================================
%% SIMPLE MODE
%% ============================================

compile_simple_mode_java(Pred, Arity, Options, JavaCode) :-
    % Get options
    option(package(Package), Options, generated),
    option(class_name(ClassName), Options, Pred),
    capitalize_atom(ClassName, CapClassName),
    option(main_class(MainClass), Options, true),
    
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate method for each clause
    (   Clauses == []
    ->  MethodCode = "    // No clauses found"
    ;   findall(Code, (member((H, B), Clauses), clause_to_java(H, B, Code)), MethodCodes),
        atomic_list_concat(MethodCodes, '\n', MethodCode)
    ),
    
    % Generate main if requested
    (   MainClass == true
    ->  MainCode = "
    public static void main(String[] args) {
        // TODO: Add main logic
    }"
    ;   MainCode = ""
    ),
    
    % Standard imports for simple mode
    collect_java_import('java.util.*'),
    get_java_imports(ImportList),
    format_java_imports(ImportList, ImportsStr),
    
    format(string(JavaCode),
"// Generated by UnifyWeaver Java Target
// Predicate: ~w/~w

package ~w;

~w
public class ~w {

~w
~w
}
", [Pred, Arity, Package, ImportsStr, CapClassName, MethodCode, MainCode]).

%% clause_to_java(+Head, +Body, -Code)
%  Convert a single clause to Java code (stub for now)
clause_to_java(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    length(Args, _Arity),
    (   Body == true
    ->  format(string(Code), "    // Fact: ~w", [Head])
    ;   format(string(Code), "    // Rule: ~w :- ~w", [Head, Body])
    ).

%% ============================================
%% PIPELINE MODE
%% ============================================

compile_pipeline_mode_java(Pred, Arity, Options, JavaCode) :-
    % Get options
    option(package(Package), Options, generated),
    option(class_name(ClassName), Options, Pred),
    capitalize_atom(ClassName, CapClassName),
    
    % Standard pipeline imports
    collect_java_import('java.io.*'),
    collect_java_import('java.util.*'),
    collect_java_import('java.util.stream.*'),
    collect_java_import('com.google.gson.*'),
    collect_java_import('com.google.gson.reflect.TypeToken'),
    
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate process method
    (   Clauses == []
    ->  ProcessCode = "        // No clauses found - pass through
        return Optional.of(record);"
    ;   generate_pipeline_process(Clauses, ProcessCode)
    ),
    
    get_java_imports(ImportList),
    format_java_imports(ImportList, ImportsStr),
    
    format(string(JavaCode),
"// Generated by UnifyWeaver Java Target - Pipeline Mode
// Predicate: ~w/~w

package ~w;

~w
/**
 * Pipeline processor for ~w predicate.
 * Reads JSONL from stdin, processes each record, writes JSONL to stdout.
 */
public class ~w {

    private static final Gson gson = new Gson();

    /**
     * Process a single input record.
     * @param record Input record as Map
     * @return Optional output record (empty to filter out)
     */
    public static Optional<Map<String, Object>> process(Map<String, Object> record) {
~w
    }

    /**
     * Run the pipeline: read from stdin, process, write to stdout.
     */
    public static void runPipeline() throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        PrintWriter writer = new PrintWriter(new BufferedWriter(new OutputStreamWriter(System.out)));
        
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.trim().isEmpty()) continue;
            
            try {
                Map<String, Object> record = gson.fromJson(
                    line, 
                    new TypeToken<Map<String, Object>>(){}.getType()
                );
                
                Optional<Map<String, Object>> result = process(record);
                result.ifPresent(r -> writer.println(gson.toJson(r)));
                
            } catch (JsonSyntaxException e) {
                System.err.println(\"JSON parse error: \" + e.getMessage());
            }
        }
        
        writer.flush();
    }

    public static void main(String[] args) {
        try {
            runPipeline();
        } catch (IOException e) {
            System.err.println(\"I/O error: \" + e.getMessage());
            System.exit(1);
        }
    }
}
", [Pred, Arity, Package, ImportsStr, Pred, CapClassName, ProcessCode]).

%% generate_pipeline_process(+Clauses, -Code)
%  Generate process method body from clauses with body translation
generate_pipeline_process([], "        return Optional.of(record);").
generate_pipeline_process(Clauses, Code) :-
    Clauses \= [],
    % Check for recursion
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_java(Name, Clauses)
    ->  % Separate base and recursive clauses
        partition(is_recursive_clause_java(Name), Clauses, RecClauses, BaseClauses),
        % Check if tail recursive
        (   is_tail_recursive_java(Name, RecClauses)
        ->  compile_tail_recursive_java(Name, BaseClauses, RecClauses, Code)
        ;   compile_general_recursive_java(Name, BaseClauses, RecClauses, Code)
        )
    ;   % Generate clause-based processing
        findall(ClauseCode, 
            (member((H, B), Clauses), translate_clause_java(H, B, ClauseCode)),
            ClauseCodes),
        atomic_list_concat(ClauseCodes, '\n', AllClausesCode),
        format(string(Code), "~w", [AllClausesCode])
    ).

%% ============================================
%% RECURSION DETECTION AND PATTERNS
%% ============================================

%% is_recursive_predicate_java(+Name, +Clauses)
%  Check if any clause body contains a recursive call
is_recursive_predicate_java(Name, Clauses) :-
    member((_, Body), Clauses),
    contains_recursive_call_java(Body, Name).

%% is_recursive_clause_java(+Name, +Clause)
is_recursive_clause_java(Name, (_, Body)) :-
    contains_recursive_call_java(Body, Name).

%% is_tail_recursive_java(+Name, +RecClauses)
%  Check if recursive call is in tail position
is_tail_recursive_java(Name, RecClauses) :-
    member((_, Body), RecClauses),
    get_last_goal_java(Body, LastGoal),
    functor(LastGoal, Name, _).

%% get_last_goal_java(+Body, -LastGoal)
get_last_goal_java((_, B), LastGoal) :- !, get_last_goal_java(B, LastGoal).
get_last_goal_java(Goal, Goal).

%% contains_recursive_call_java(+Body, +Name)
contains_recursive_call_java(Body, Name) :-
    extract_goal_java(Body, Goal),
    functor(Goal, Name, _),
    !.

%% extract_goal_java(+Body, -Goal)
extract_goal_java(Goal, Goal) :-
    compound(Goal),
    \+ Goal = (_,_),
    \+ Goal = (_;_).
extract_goal_java((A, _), Goal) :- extract_goal_java(A, Goal).
extract_goal_java((_, B), Goal) :- extract_goal_java(B, Goal).

%% ============================================
%% TAIL RECURSION PATTERN (→ while loop)
%% ============================================

%% compile_tail_recursive_java(+Name, +BaseClauses, +RecClauses, -Code)
%  Compile tail recursive predicate to iterative while loop
compile_tail_recursive_java(Name, BaseClauses, RecClauses, Code) :-
    % Generate base case condition
    (   BaseClauses = [(BaseHead, BaseBody)|_]
    ->  generate_base_condition_java(BaseHead, BaseBody, BaseCondition, _BaseReturn)
    ;   BaseCondition = "false", _BaseReturn = "record"
    ),
    
    % Generate recursive transformation
    (   RecClauses = [(_, RecBody)|_]
    ->  generate_recursive_transform_java(RecBody, Name, Transform)
    ;   Transform = "current"
    ),
    
    format(string(Code),
"        // Tail-recursive predicate: ~w - optimized to while loop
        Map<String, Object> current = new HashMap<>(record);
        int maxIterations = 10000;
        
        for (int i = 0; i < maxIterations; i++) {
            // Base case check
            if (~w) {
                return Optional.of(current);
            }
            
            // Recursive step (tail call transformed to loop)
            current = ~w;
        }
        
        // Exceeded max iterations
        System.err.println(\"Warning: Max iterations exceeded for ~w\");
        return Optional.of(current);", [Name, BaseCondition, Transform, Name]).

%% generate_base_condition_java(+Head, +Body, -Condition, -Return)
generate_base_condition_java(Head, Body, Condition, Return) :-
    Head =.. [_|Args],
    (   Args = [Arg|_],
        (   number(Arg)
        ->  format(string(Condition), "toDouble(current.get(\"arg0\")) == ~w", [Arg])
        ;   atom(Arg)
        ->  format(string(Condition), "\"~w\".equals(current.get(\"arg0\"))", [Arg])
        ;   Condition = "false"
        )
    ;   Condition = "false"
    ),
    (   Body == true
    ->  Return = "current"
    ;   Return = "current"
    ).

%% generate_recursive_transform_java(+Body, +Name, -Transform)
generate_recursive_transform_java(Body, Name, Transform) :-
    % Find recursive call and extract argument transformation
    extract_goal_java(Body, Goal),
    functor(Goal, Name, _),
    Goal =.. [_|Args],
    (   Args = [Expr|_],
        expr_to_java(Expr, JavaExpr),
        format(string(Transform), 
            "new HashMap<String, Object>() {{ put(\"arg0\", ~w); }}", [JavaExpr])
    ;   Transform = "current"
    ).

%% ============================================
%% GENERAL RECURSION PATTERN (→ memoization)
%% ============================================

%% compile_general_recursive_java(+Name, +BaseClauses, +RecClauses, -Code)
%  Compile general recursive predicate with memoization
compile_general_recursive_java(Name, BaseClauses, RecClauses, Code) :-
    % Generate base case
    (   BaseClauses = [(BaseHead, BaseBody)|_]
    ->  generate_base_condition_java(BaseHead, BaseBody, BaseCondition, _)
    ;   BaseCondition = "false"
    ),
    
    % Generate recursive case
    (   RecClauses = [(_, RecBody)|_]
    ->  generate_memoized_recursive_java(RecBody, Name, RecursiveComputation)
    ;   RecursiveComputation = "current"
    ),
    
    format(string(Code),
"        // General recursive predicate: ~w - with memoization
        // Cache to avoid recomputation
        @SuppressWarnings(\"unchecked\")
        Map<String, Object> memo = (Map<String, Object>) record.getOrDefault(\"__memo__\", new HashMap<>());
        
        String key = record.get(\"arg0\").toString();
        if (memo.containsKey(key)) {
            return Optional.of((Map<String, Object>) memo.get(key));
        }
        
        Map<String, Object> current = new HashMap<>(record);
        
        // Base case check
        if (~w) {
            memo.put(key, current);
            return Optional.of(current);
        }
        
        // Recursive computation with memoization
        Map<String, Object> result = ~w;
        memo.put(key, result);
        return Optional.of(result);", [Name, BaseCondition, RecursiveComputation]).

%% generate_memoized_recursive_java(+Body, +Name, -Code)
generate_memoized_recursive_java(Body, Name, Code) :-
    % Extract recursive call
    extract_goal_java(Body, Goal),
    functor(Goal, Name, _),
    Goal =.. [_|Args],
    (   Args = [Expr|_]
    ->  expr_to_java(Expr, JavaExpr),
        format(string(Code),
"processWithMemo(new HashMap<String, Object>() {{ put(\"arg0\", ~w); put(\"__memo__\", memo); }}).orElse(current)", [JavaExpr])
    ;   Code = "current"
    ).

%% ============================================
%% CLAUSE TRANSLATION
%% ============================================

%% translate_clause_java(+Head, +Body, -Code)
%  Translate a single clause to Java code
translate_clause_java(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    % Generate input extraction
    generate_input_extraction_java(Args, InputCode),
    % Translate body
    (   Body == true
    ->  BodyCode = "        // Fact - no conditions"
    ;   translate_body_java(Body, BodyCode)
    ),
    % Generate output construction  
    generate_output_construction_java(Args, OutputCode),
    format(string(Code), "~w\n~w\n~w", [InputCode, BodyCode, OutputCode]).

%% generate_input_extraction_java(+Args, -Code)
generate_input_extraction_java(Args, Code) :-
    findall(Line, (
        nth0(I, Args, Arg),
        (   var(Arg)
        ->  format(string(Line), "        Object arg~w = record.get(\"arg~w\");", [I, I])
        ;   format(string(Line), "        // arg~w = ~w (constant)", [I, Arg])
        )
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

%% generate_output_construction_java(+Args, -Code)
generate_output_construction_java(_Args, Code) :-
    Code = "        return Optional.of(record);".

%% ============================================
%% BODY TRANSLATION
%% ============================================

%% translate_body_java(+Body, -Code)
%  Translate clause body to Java code
translate_body_java((Goal, Rest), Code) :-
    !,
    translate_goal_java(Goal, Code1),
    translate_body_java(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_body_java(Goal, Code) :-
    translate_goal_java(Goal, Code).

%% translate_goal_java(+Goal, -Code)
%  Translate individual goals to Java

% Assignment: X = Value
translate_goal_java(=(Var, Value), Code) :-
    var(Var), !,
    var_to_java(Var, JavaVar),
    value_to_java(Value, JavaValue),
    format(string(Code), "        ~w = ~w;", [JavaVar, JavaValue]).

% Comparison: X > Y, X < Y, etc.
translate_goal_java(>(X, Y), Code) :-
    !,
    expr_to_java(X, JX),
    expr_to_java(Y, JY),
    format(string(Code), "        if (!(toDouble(~w) > toDouble(~w))) return Optional.empty();", [JX, JY]).

translate_goal_java(<(X, Y), Code) :-
    !,
    expr_to_java(X, JX),
    expr_to_java(Y, JY),
    format(string(Code), "        if (!(toDouble(~w) < toDouble(~w))) return Optional.empty();", [JX, JY]).

translate_goal_java(>=(X, Y), Code) :-
    !,
    expr_to_java(X, JX),
    expr_to_java(Y, JY),
    format(string(Code), "        if (!(toDouble(~w) >= toDouble(~w))) return Optional.empty();", [JX, JY]).

translate_goal_java(=<(X, Y), Code) :-
    !,
    expr_to_java(X, JX),
    expr_to_java(Y, JY),
    format(string(Code), "        if (!(toDouble(~w) <= toDouble(~w))) return Optional.empty();", [JX, JY]).

translate_goal_java(=:=(X, Y), Code) :-
    !,
    expr_to_java(X, JX),
    expr_to_java(Y, JY),
    format(string(Code), "        if (toDouble(~w) != toDouble(~w)) return Optional.empty();", [JX, JY]).

translate_goal_java(=\\=(X, Y), Code) :-
    !,
    expr_to_java(X, JX),
    expr_to_java(Y, JY),
    format(string(Code), "        if (toDouble(~w) == toDouble(~w)) return Optional.empty();", [JX, JY]).

% Arithmetic: X is Expr
translate_goal_java(is(Var, Expr), Code) :-
    !,
    var_to_java(Var, JavaVar),
    expr_to_java(Expr, JavaExpr),
    format(string(Code), "        ~w = ~w;", [JavaVar, JavaExpr]).

% get_dict/3: get_dict(Key, Dict, Value)
translate_goal_java(get_dict(Key, Dict, Value), Code) :-
    !,
    var_to_java(Dict, JavaDict),
    var_to_java(Value, JavaValue),
    format(string(Code), "        ~w = ~w.get(\"~w\");", [JavaValue, JavaDict, Key]).

% put_dict/3: put_dict(Key, Dict, Value)
translate_goal_java(put_dict(Updates, Dict, NewDict), Code) :-
    !,
    var_to_java(Dict, JavaDict),
    var_to_java(NewDict, JavaNewDict),
    format(string(Code), "        ~w = new HashMap<>(~w);\n        ~w.putAll(~w);", 
           [JavaNewDict, JavaDict, JavaNewDict, Updates]).

% true - no-op
translate_goal_java(true, Code) :-
    !,
    Code = "        // true".

% Unknown goal - comment
translate_goal_java(Goal, Code) :-
    format(string(Code), "        // TODO: ~w", [Goal]).

%% ============================================
%% HELPER PREDICATES FOR TRANSLATION
%% ============================================

%% var_to_java(+Var, -JavaVar)
var_to_java(Var, JavaVar) :-
    (   var(Var)
    ->  term_to_atom(Var, VarAtom),
        format(atom(JavaVar), "var_~w", [VarAtom])
    ;   Var = '$VAR'(N)
    ->  format(atom(JavaVar), "v_~w", [N])
    ;   term_to_atom(Var, JavaVar)
    ).

%% value_to_java(+Value, -JavaValue)
value_to_java(Value, JavaValue) :-
    (   number(Value)
    ->  format(atom(JavaValue), "~w", [Value])
    ;   atom(Value)
    ->  format(atom(JavaValue), "\"~w\"", [Value])
    ;   var(Value)
    ->  var_to_java(Value, JavaValue)
    ;   format(atom(JavaValue), "~w", [Value])
    ).

%% expr_to_java(+Expr, -JavaExpr)
%  Translate Prolog arithmetic expr to Java
expr_to_java(Expr, JavaExpr) :-
    (   number(Expr)
    ->  format(atom(JavaExpr), "~w", [Expr])
    ;   var(Expr)
    ->  var_to_java(Expr, JavaExpr)
    ;   Expr = '$VAR'(N)
    ->  format(atom(JavaExpr), "v_~w", [N])
    ;   Expr = X + Y
    ->  expr_to_java(X, JX), expr_to_java(Y, JY),
        format(atom(JavaExpr), "(~w + ~w)", [JX, JY])
    ;   Expr = X - Y
    ->  expr_to_java(X, JX), expr_to_java(Y, JY),
        format(atom(JavaExpr), "(~w - ~w)", [JX, JY])
    ;   Expr = X * Y
    ->  expr_to_java(X, JX), expr_to_java(Y, JY),
        format(atom(JavaExpr), "(~w * ~w)", [JX, JY])
    ;   Expr = X / Y
    ->  expr_to_java(X, JX), expr_to_java(Y, JY),
        format(atom(JavaExpr), "(~w / ~w)", [JX, JY])
    ;   Expr = X mod Y
    ->  expr_to_java(X, JX), expr_to_java(Y, JY),
        format(atom(JavaExpr), "(~w % ~w)", [JX, JY])
    ;   format(atom(JavaExpr), "~w", [Expr])
    ).

%% ============================================
%% GRADLE BUILD GENERATION
%% ============================================

%% generate_gradle_build(+Options, -GradleCode)
%  Generate a Gradle build file for the Java project
generate_gradle_build(Options, GradleCode) :-
    option(project_name(ProjectName), Options, 'unifyweaver-pipeline'),
    option(main_class(MainClass), Options, 'generated.Pipeline'),
    option(java_version(JavaVersion), Options, '25'),
    
    format(string(GradleCode),
"plugins {
    id 'java'
    id 'application'
}

group = 'com.unifyweaver'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(~w)
    }
}

application {
    mainClass = '~w'
}

tasks.named('test') {
    useJUnitPlatform()
}

// Create fat JAR for standalone execution
tasks.register('fatJar', Jar) {
    archiveBaseName = '~w'
    archiveClassifier = 'all'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': '~w'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    with jar
}
", [JavaVersion, MainClass, ProjectName, MainClass]).

%% ============================================
%% PIPELINE COMPILATION
%% ============================================

%% compile_java_pipeline(+Steps, +Options, -JavaCode)
%  Compile multiple steps into a Java pipeline
compile_java_pipeline(Steps, Options, JavaCode) :-
    option(package(Package), Options, generated),
    option(class_name(ClassName), Options, 'Pipeline'),
    
    % Standard pipeline imports
    collect_java_import('java.io.*'),
    collect_java_import('java.util.*'),
    collect_java_import('java.util.stream.*'),
    collect_java_import('com.google.gson.*'),
    
    % Generate step methods
    generate_step_methods_java(Steps, 1, StepMethods),
    
    % Generate pipeline orchestration
    generate_pipeline_orchestration(Steps, OrchestrationCode),
    
    get_java_imports(ImportList),
    format_java_imports(ImportList, ImportsStr),
    
    format(string(JavaCode),
"// Generated by UnifyWeaver Java Target - Multi-Step Pipeline
package ~w;

~w
/**
 * Multi-step data processing pipeline.
 */
public class ~w {

    private static final Gson gson = new Gson();

~w

    /**
     * Execute the full pipeline.
     */
    public static void main(String[] args) {
        try {
~w
        } catch (Exception e) {
            System.err.println(\"Pipeline error: \" + e.getMessage());
            System.exit(1);
        }
    }
}
", [Package, ImportsStr, ClassName, StepMethods, OrchestrationCode]).

%% generate_step_methods_java(+Steps, +N, -Code)
generate_step_methods_java([], _, "").
generate_step_methods_java([step(Name, Target, _Script, _Opts)|Rest], N, Code) :-
    format(string(StepCode),
"    /**
     * Step ~w: ~w (~w)
     */
    public static Optional<Map<String, Object>> step_~w(Map<String, Object> record) {
        // TODO: Implement ~w logic
        return Optional.of(record);
    }

", [N, Name, Target, Name, Target]),
    N1 is N + 1,
    generate_step_methods_java(Rest, N1, RestCode),
    atom_concat(StepCode, RestCode, Code).

%% generate_pipeline_orchestration(+Steps, -Code)
generate_pipeline_orchestration(Steps, Code) :-
    findall(CallCode,
        (   member(step(Name, _, _, _), Steps),
            format(string(CallCode), "            record = step_~w(record).orElse(null);
            if (record == null) continue;", [Name])
        ),
        Calls),
    atomic_list_concat(Calls, '\n', CallsStr),
    
    format(string(Code),
"            BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
            String line;
            while ((line = reader.readLine()) != null) {
                Map<String, Object> record = gson.fromJson(line, Map.class);
~w
                System.out.println(gson.toJson(record));
            }", [CallsStr]).

%% ============================================
%% UTILITY PREDICATES
%% ============================================

%% write_java_program(+JavaCode, +FilePath)
%  Write generated Java code to a file
write_java_program(JavaCode, FilePath) :-
    open(FilePath, write, Stream),
    write(Stream, JavaCode),
    close(Stream),
    format('Written Java program to: ~w~n', [FilePath]).

%% capitalize_atom(+Atom, -Capitalized)
%  Capitalize first letter of an atom
capitalize_atom(Atom, Capitalized) :-
    atom_codes(Atom, [H|T]),
    (   H >= 97, H =< 122
    ->  H1 is H - 32,
        atom_codes(Capitalized, [H1|T])
    ;   Capitalized = Atom
    ).

%% option(+Option, +Options, +Default)
%  Get option value with default
option(Option, Options, _Default) :-
    member(Option, Options),
    !.
option(Option, _Options, Default) :-
    Option =.. [_, Default].

%% ============================================
%% TESTS
%% ============================================

test_java_pipeline_mode :-
    format('~n=== Testing Java Pipeline Mode ===~n~n'),
    
    % Test 1: Basic pipeline generation
    format('Test 1: Basic pipeline generation~n'),
    compile_predicate_to_java(test_pred/2, [pipeline_input(true)], Code1),
    (   sub_atom(Code1, _, _, _, 'runPipeline')
    ->  format('  [PASS] Generated pipeline code~n')
    ;   format('  [FAIL] Missing pipeline code~n')
    ),
    
    % Test 2: Gradle build generation
    format('~nTest 2: Gradle build generation~n'),
    generate_gradle_build([java_version('21')], GradleCode),
    (   sub_atom(GradleCode, _, _, _, 'fatJar')
    ->  format('  [PASS] Generated Gradle build~n')
    ;   format('  [FAIL] Missing Gradle config~n')
    ),
    
    format('~n=== Java Pipeline Mode Tests Complete ===~n').

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(java, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_java(StepOp, JavaStepExpr),
    snake_to_pascal_java(PredStr, ClassName),
    (   Arity =:= 3 ->
        format(string(Code),
'// Generated by UnifyWeaver Java Target - Tail Recursion (multifile dispatch)
// Predicate: ~w/~w

import java.util.*;

public class ~w {
    public static int ~w(int[] items) {
        int acc = 0;
        for (int item : items) {
            acc = ~w;
        }
        return acc;
    }

    public static void main(String[] args) {
        if (args.length >= 1) {
            int[] items = Arrays.stream(args[0].split(","))
                                .mapToInt(Integer::parseInt).toArray();
            System.out.println(~w(items));
        }
    }
}
', [PredStr, Arity, ClassName, PredStr, JavaStepExpr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'// Generated by UnifyWeaver Java Target - Tail Recursion (binary, multifile dispatch)
// Predicate: ~w/~w

public class ~w {
    public static int ~w(Object[] items) {
        int count = 0;
        for (Object ignored : items) { count++; }
        return count;
    }

    public static void main(String[] args) {
        if (args.length >= 1) {
            String[] items = args[0].split(",");
            System.out.println(~w(items));
        }
    }
}
', [PredStr, Arity, ClassName, PredStr, PredStr])
    ;   fail
    ).

step_op_to_java(arithmetic(Expr), JExpr) :- tail_expr_to_java(Expr, JExpr).
step_op_to_java(unknown, 'acc + 1').

tail_expr_to_java(_ + Const, JExpr) :- integer(Const), !, format(atom(JExpr), 'acc + ~w', [Const]).
tail_expr_to_java(_ + _, 'acc + item') :- !.
tail_expr_to_java(_ - _, 'acc - item') :- !.
tail_expr_to_java(_ * _, 'acc * item') :- !.
tail_expr_to_java(_, 'acc + 1').

%% snake_to_pascal_java(+SnakeStr, -PascalStr)
%  Convert snake_case string to PascalCase for Java class names.
%  e.g. "test_sum" -> "TestSum", "factorial" -> "Factorial"
snake_to_pascal_java(SnakeStr, PascalStr) :-
    split_string(SnakeStr, "_", "", Parts),
    maplist(capitalize_first, Parts, CapParts),
    atomics_to_string(CapParts, PascalStr).

capitalize_first("", "") :- !.
capitalize_first(Str, Cap) :-
    string_code(1, Str, Code),
    (   Code >= 0'a, Code =< 0'z ->
        Upper is Code - 32,
        sub_string(Str, 1, _, 0, Rest),
        char_code(UpperChar, Upper),
        atom_string(UpperChar, UpperStr),
        string_concat(UpperStr, Rest, Cap)
    ;   Cap = Str
    ).

atomics_to_string(Parts, Str) :-
    atomic_list_concat(Parts, '', Atom),
    atom_string(Atom, Str).

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(java, PredStr, Arity, BaseClauses, _RecClauses, MemoEnabled, _MemoStrategy, Code) :-
    snake_to_pascal_java(PredStr, ClassName),
    (   Arity =:= 2 ->
        linear_fold_java(PredStr, ClassName, BaseClauses, MemoEnabled, Code)
    ;   linear_generic_java(PredStr, ClassName, Arity, MemoEnabled, Code)
    ).

linear_fold_java(PredStr, ClassName, BaseClauses, MemoEnabled, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    (   MemoEnabled = true ->
        MemoDecl = "    private static final HashMap<Integer, Integer> memo = new HashMap<>();",
        format(string(MemoCheck), '        if (memo.containsKey(n)) return memo.get(n);', []),
        format(string(MemoStore), '        memo.put(n, result);', [])
    ;   MemoDecl = "    // Memoization disabled",
        MemoCheck = '',
        MemoStore = ''
    ),
    % Extract fold
    atom_string(Pred, PredStr),
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
    partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRec, _),
    (   ActualRec = [clause(RHead, RBody)|_] ->
        RHead =.. [_, InputVar, _],
        linear_recursion:find_recursive_call(RBody, RecCall),
        RecCall =.. [_, _, AccVar],
        linear_recursion:find_last_is_expression(RBody, _ is FoldExpr),
        translate_fold_expr_java(FoldExpr, InputVar, AccVar, JavaOp)
    ;   JavaOp = "current * acc"
    ),
    (   InputType = numeric ->
        format(string(Code),
'// Generated by UnifyWeaver Java Target - Linear Recursion (numeric, multifile dispatch)
// Predicate: ~w/2

import java.util.*;

public class ~w {
~w

    public static int ~w(int n) {
~w
        if (n == ~w) return ~w;
        int result = ~w;
        for (int current = n; current >= 1; current--) {
            result = ~w;
        }
~w
        return result;
    }

    public static void main(String[] args) {
        if (args.length >= 1) System.out.println(~w(Integer.parseInt(args[0])));
    }
}
', [PredStr, ClassName, MemoDecl, PredStr, MemoCheck, BaseInput, BaseOutput, BaseOutput, JavaOp, MemoStore, PredStr])
    ;   InputType = list ->
        format(string(Code),
'// Generated by UnifyWeaver Java Target - Linear Recursion (list, multifile dispatch)
// Predicate: ~w/2

import java.util.*;

public class ~w {
~w

    public static int ~w(int[] lst) {
~w
        if (lst.length == 0) return ~w;
        int result = ~w;
        for (int current : lst) {
            result = ~w;
        }
~w
        return result;
    }

    public static void main(String[] args) {
        if (args.length >= 1) {
            int[] items = Arrays.stream(args[0].split(","))
                                .mapToInt(Integer::parseInt).toArray();
            System.out.println(~w(items));
        }
    }
}
', [PredStr, ClassName, MemoDecl, PredStr, MemoCheck, BaseOutput, BaseOutput, JavaOp, MemoStore, PredStr])
    ;   linear_generic_java(PredStr, ClassName, 2, MemoEnabled, Code)
    ).

linear_generic_java(PredStr, ClassName, Arity, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        format(string(Code),
'// Generated by UnifyWeaver Java Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

import java.util.*;

public class ~w {
    private static final HashMap<Integer, Integer> memo = new HashMap<>();

    public static int ~w(int n) {
        if (memo.containsKey(n)) return memo.get(n);
        int result;
        if (n <= 0) result = 0;
        else if (n == 1) result = 1;
        else result = ~w(n - 1) + n;
        memo.put(n, result);
        return result;
    }

    public static void main(String[] args) {
        if (args.length >= 1) System.out.println(~w(Integer.parseInt(args[0])));
    }
}
', [PredStr, Arity, ClassName, PredStr, PredStr, PredStr])
    ;   format(string(Code),
'// Generated by UnifyWeaver Java Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

public class ~w {
    public static int ~w(int n) {
        if (n <= 0) return 0;
        if (n == 1) return 1;
        return ~w(n - 1) + n;
    }

    public static void main(String[] args) {
        if (args.length >= 1) System.out.println(~w(Integer.parseInt(args[0])));
    }
}
', [PredStr, Arity, ClassName, PredStr, PredStr, PredStr])
    ).

translate_fold_expr_java(A * B, IV, AV, E) :- translate_java_term(A, IV, AV, AT), translate_java_term(B, IV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_fold_expr_java(A + B, IV, AV, E) :- translate_java_term(A, IV, AV, AT), translate_java_term(B, IV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_fold_expr_java(A - B, IV, AV, E) :- translate_java_term(A, IV, AV, AT), translate_java_term(B, IV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_fold_expr_java(T, IV, AV, E) :- translate_java_term(T, IV, AV, E).

translate_java_term(T, IV, _, 'current') :- T == IV, !.
translate_java_term(T, _, AV, 'result') :- T == AV, !.
translate_java_term(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_java_term(A, _, _, S) :- format(string(S), '~w', [A]).

% ============================================================================
% TREE RECURSION - Java target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(java, _Pattern, Pred, _Arity, _UseMemo, JavaCode) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredUpper),
    atom_string(PredUpper, ClassName),
    format(string(JavaCode),
'// Generated by UnifyWeaver Java Target - Tree Recursion (fibonacci, multifile dispatch)
import java.util.HashMap;

public class ~w {
    private static HashMap<Integer, Integer> memo = new HashMap<>();

    public static int ~w(int n) {
        if (n <= 0) return 0;
        if (n == 1) return 1;
        if (memo.containsKey(n)) return memo.get(n);
        int result = ~w(n - 1) + ~w(n - 2);
        memo.put(n, result);
        return result;
    }

    public static void main(String[] args) {
        if (args.length >= 1) System.out.println(~w(Integer.parseInt(args[0])));
    }
}
', [ClassName, PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTICALL LINEAR RECURSION - Java target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(java, PredStr, BaseClauses, _RecClauses, _MemoEnabled, JavaCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '        if (n == ~w) return ~w;', [BInput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    atom_string(PredAtom, PredStr),
    upcase_atom(PredAtom, PredUpper),
    atom_string(PredUpper, ClassName),
    format(string(JavaCode),
'// Generated by UnifyWeaver Java Target - Multicall Linear Recursion (multifile dispatch)
import java.util.HashMap;

public class ~w {
    private static HashMap<Integer, Integer> memo = new HashMap<>();

    public static int ~w(int n) {
~w
        if (memo.containsKey(n)) return memo.get(n);
        int result = ~w(n - 1) + ~w(n - 2);
        memo.put(n, result);
        return result;
    }

    public static void main(String[] args) {
        if (args.length >= 1) System.out.println(~w(Integer.parseInt(args[0])));
    }
}
', [ClassName, PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% DIRECT MULTI-CALL RECURSION - Java target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(java, PredStr, BaseClauses, _RecClause, JavaCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '        if (input == ~w) { memo.put(input, ~w); return ~w; }', [BInput, BOutput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    atom_string(PredAtom, PredStr),
    upcase_atom(PredAtom, PredUpper),
    atom_string(PredUpper, ClassName),
    format(string(JavaCode),
'// Generated by UnifyWeaver Java Target - Direct Multicall Recursion (multifile dispatch)
import java.util.HashMap;

public class ~w {
    private static HashMap<Integer, Integer> memo = new HashMap<>();

    public static int ~w(int input) {
        if (memo.containsKey(input)) return memo.get(input);
~w
        int result = ~w(input - 1) + ~w(input - 2);
        memo.put(input, result);
        return result;
    }

    public static void main(String[] args) {
        if (args.length >= 1) System.out.println(~w(Integer.parseInt(args[0])));
    }
}
', [ClassName, PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MUTUAL RECURSION - Java target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(java, Predicates, MemoEnabled, _MemoStrategy, JavaCode) :-
    % Generate methods for each predicate
    mutual_functions_java(Predicates, Predicates, MemoEnabled, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    % Generate dispatch
    mutual_dispatch_java(Predicates, DispatchCode),
    (   MemoEnabled = true ->
        MemoDecl = '    private static HashMap<String, Boolean> memo = new HashMap<>();'
    ;   MemoDecl = '    // Shared memoization disabled'
    ),
    format(string(JavaCode),
'// Generated by UnifyWeaver Java Target - Mutual Recursion (multifile dispatch)
import java.util.HashMap;

public class MutualGroup {
~w

~w

~w
}
', [MemoDecl, FunctionsCode, DispatchCode]).

mutual_functions_java([], _AllPreds, _MemoEnabled, []).
mutual_functions_java([Pred/Arity|Rest], AllPreds, MemoEnabled, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    % Base cases
    findall(BaseLine, (
        member(clause(BHead, true), BaseClauses),
        BHead =.. [_P, BValue],
        (   MemoEnabled = true ->
            format(string(BaseLine),
'        if (n == ~w) { memo.put(key, true); return true; }', [BValue])
        ;   format(string(BaseLine),
'        if (n == ~w) return true;', [BValue])
        )
    ), BaseLines),
    atomic_list_concat(BaseLines, '\n', BaseCode),
    % Recursive case
    (   RecClauses = [clause(_RHead, RBody)|_] ->
        extract_mutual_rec_info_java(RBody, Guard, CalledPred, Step),
        atom_string(CalledPred, CalledStr),
        (   Guard = (N > Threshold), var(N) ->
            (   MemoEnabled = true ->
                format(string(RecCode),
'        if (n > ~w) {
            boolean result = ~w(n ~w);
            memo.put(key, result);
            return result;
        }', [Threshold, CalledStr, Step])
            ;   format(string(RecCode),
'        if (n > ~w) return ~w(n ~w);', [Threshold, CalledStr, Step])
            )
        ;   format(string(RecCode),
'        return ~w(n ~w);', [CalledStr, Step])
        )
    ;   RecCode = ''
    ),
    (   MemoEnabled = true ->
        format(string(FuncCode),
'    public static boolean ~w(int n) {
        String key = "~w:" + n;
        if (memo.containsKey(key)) return memo.get(key);
~w
~w
        return false;
    }', [PredStr, PredStr, BaseCode, RecCode])
    ;   format(string(FuncCode),
'    public static boolean ~w(int n) {
~w
~w
        return false;
    }', [PredStr, BaseCode, RecCode])
    ),
    mutual_functions_java(Rest, AllPreds, MemoEnabled, RestCodes).

extract_mutual_rec_info_java(Body, Guard, CalledPred, Step) :-
    extract_goals_from_body_java(Body, Goals),
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(Step), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(Step), '- ~w', [AbsK])
    ;   Step = "- 1"
    ).

extract_goals_from_body_java((A, B), Goals) :- !,
    extract_goals_from_body_java(A, GA),
    extract_goals_from_body_java(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body_java(true, []) :- !.
extract_goals_from_body_java(Goal, [Goal]).

mutual_dispatch_java(Predicates, Code) :-
    findall(CaseLine, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(CaseLine),
'                case "~w": System.out.println(~w(n)); break;', [PredStr, PredStr])
    ), Lines),
    atomic_list_concat(Lines, '\n', CaseCode),
    format(string(Code),
'    public static void main(String[] args) {
        if (args.length >= 2) {
            int n = Integer.parseInt(args[1]);
            switch (args[0]) {
~w
            }
        }
    }', [CaseCode]).
