% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (s243a)
%
% jython_target.pl - Jython Target for UnifyWeaver
% Generates Jython (Python 2.7 on JVM) programs for record/field processing
% Supports streaming JSONL I/O and Java interop

:- encoding(utf8).

:- module(jython_target, [
    compile_predicate_to_jython/3,    % +Predicate, +Options, -JythonCode
    compile_jython_pipeline/3,        % +Predicates, +Options, -JythonCode
    compile_facts_to_jython/3,        % +Pred, +Arity, -JythonCode  -- NEW
    write_jython_program/2,           % +JythonCode, +FilePath
    init_jython_target/0,             % Initialize Jython target
    test_jython_pipeline_mode/0       % Test pipeline mode
]).

:- use_module(library(lists)).

% Binding system integration
:- use_module('../core/binding_registry').
:- use_module('../bindings/jython_bindings').

% Shared clause body analysis for native lowering
:- use_module('../core/clause_body_analysis').

% Track required imports
:- dynamic required_jython_import/1.

%% init_jython_target
%  Initialize Jython target
init_jython_target :-
    retractall(required_jython_import(_)).

%% clear_jython_imports
%  Clear collected Jython imports
clear_jython_imports :-
    retractall(required_jython_import(_)).

%% collect_jython_import(+Import)
%  Record that an import is required
collect_jython_import(Import) :-
    (   required_jython_import(Import)
    ->  true
    ;   assertz(required_jython_import(Import))
    ).

%% get_jython_imports(-Imports)
%  Get all collected imports
get_jython_imports(Imports) :-
    findall(I, required_jython_import(I), Imports).

%% format_jython_imports(+Imports, -FormattedStr)
%  Format a list of imports for Jython
format_jython_imports([], "").
format_jython_imports(Imports, FormattedStr) :-
    Imports \= [],
    sort(Imports, UniqueImports),
    findall(Formatted,
        (   member(Import, UniqueImports),
            format(string(Formatted), "import ~w~n", [Import])
        ),
        FormattedList),
    atomic_list_concat(FormattedList, '', FormattedStr).

%% ============================================
%% PUBLIC API
%% ============================================

%% compile_predicate_to_jython(+Predicate, +Options, -JythonCode)
%  Compile a Prolog predicate to Jython code
%
%  @arg Predicate Predicate indicator (Name/Arity)
%  @arg Options List of options
%  @arg JythonCode Generated Jython code as atom
%
%  Options:
%  - pipeline_input(true|false) - Enable streaming input
%  - generator_mode(true|false) - Enable generator mode with yield
%  - java_imports(List) - Java classes to import
%
compile_predicate_to_jython(PredIndicator, Options, JythonCode) :-
    (   PredIndicator = _Module:Pred/Arity
    ->  true
    ;   PredIndicator = Pred/Arity
    ),
    format('=== Compiling ~w/~w to Jython ===~n', [Pred, Arity]),

    % Clear any previously collected imports
    clear_jython_imports,

    % Check for mode
    (   option(generator_mode(true), Options)
    ->  format('  Mode: Generator (yield)~n'),
        compile_generator_mode_jython(Pred, Arity, Options, JythonCode)
    ;   option(pipeline_input(true), Options)
    ->  format('  Mode: Pipeline (streaming JSONL)~n'),
        compile_pipeline_mode_jython(Pred, Arity, Options, JythonCode)
    % Default: simple predicate
    ;   format('  Mode: Simple predicate~n'),
        compile_simple_mode_jython(Pred, Arity, Options, JythonCode)
    ).

%% ============================================
%% COMPILE FACTS TO JYTHON
%% ============================================

compile_facts_to_jython(Pred, Arity, JythonCode) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredCap),
    functor(Head, Pred, Arity),
    
    findall(Args, (clause(Head, true), Head =.. [_|Args]), AllFacts),
    
    (   AllFacts == []
    ->  FactEntries = "    # No facts defined"
    ;   findall(Entry, (
            member(Args, AllFacts),
            format_jython_fact_entry(Args, Entry)
        ), Entries),
        atomic_list_concat(Entries, ',\n', FactEntries)
    ),
    
    format(string(JythonCode),
'# Generated by UnifyWeaver Jython Target - Facts Export
# Predicate: ~w/~w

class ~w:
    \"\"\"~w facts as Python data\"\"\"
    
    facts = [
~w
    ]

    @classmethod
    def get_all(cls):
        return cls.facts

    @classmethod
    def stream(cls):
        for fact in cls.facts:
            yield fact

    @classmethod
    def contains(cls, *args):
        return list(args) in cls.facts

if __name__ == \"__main__\":
    for f in ~w.facts:
        print(\":\".join(f))
', [PredStr, Arity, PredCap, PredStr, FactEntries, PredCap]).

format_jython_fact_entry(Args, Entry) :-
    findall(Formatted, (
        member(Arg, Args),
        format(string(Formatted), '"~w"', [Arg])
    ), FormattedArgs),
    atomic_list_concat(FormattedArgs, ', ', ArgsStr),
    format(string(Entry), '        [~w]', [ArgsStr]).

%% ============================================
%% GENERATOR MODE (Python generators with yield)
%% ============================================

compile_generator_mode_jython(Pred, Arity, Options, JythonCode) :-
    % Standard imports for generator mode
    collect_jython_import(sys),
    collect_jython_import(json),
    
    % Java imports for performance
    (   option(use_java_json(true), Options)
    ->  collect_jython_import('com.google.gson.Gson')
    ;   true
    ),
    
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate generator body
    (   Clauses == []
    ->  GeneratorBody = "    # No clauses found - yield input unchanged\n    yield record"
    ;   generate_generator_body_jython(Clauses, GeneratorBody)
    ),
    
    get_jython_imports(ImportList),
    format_jython_imports(ImportList, ImportsStr),
    
    format(string(JythonCode),
"#!/usr/bin/env jython
# -*- coding: utf-8 -*-
# Generated by UnifyWeaver Jython Target - Generator Mode
# Predicate: ~w/~w
# Uses Python generators for lazy evaluation

from __future__ import print_function
~w
from java.io import BufferedReader, InputStreamReader
from java.lang import System as JavaSystem

def process(record):
    '''
    Process a single record, yielding zero or more results.
    
    Args:
        record: Input record as dict
        
    Yields:
        Output records (dicts)
    '''
~w

def process_all(records):
    '''Process all records, flattening results.'''
    for record in records:
        for result in process(record):
            yield result

def read_jsonl(stream):
    '''Read JSONL from input stream.'''
    reader = BufferedReader(InputStreamReader(stream))
    line = reader.readLine()
    while line is not None:
        if line.strip():
            try:
                yield json.loads(line)
            except ValueError as e:
                print >> sys.stderr, 'JSON parse error:', e
        line = reader.readLine()

def write_jsonl(record):
    '''Write record as JSONL.'''
    print(json.dumps(record))

def run_pipeline():
    '''Run the generator pipeline.'''
    for result in process_all(read_jsonl(JavaSystem.in)):
        write_jsonl(result)

if __name__ == '__main__':
    run_pipeline()
", [Pred, Arity, ImportsStr, GeneratorBody]).

%% generate_generator_body_jython(+Clauses, -Code)
generate_generator_body_jython(Clauses, Code) :-
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_jython(Name, Clauses)
    ->  partition(is_recursive_clause_jython(Name), Clauses, RecClauses, BaseClauses),
        compile_generator_recursive_jython(Name, BaseClauses, RecClauses, Code)
    ;   % Non-recursive: yield with transformations
        Code = "    # Non-recursive: pass through with transformations\n    yield record"
    ).

compile_generator_recursive_jython(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_jython(BaseHead, BaseCondition)
    ;   BaseCondition = "False"
    ),
    
    format(string(Code),
"    # Recursive generator: ~w
    current = dict(record)
    max_iterations = 10000
    
    for _ in xrange(max_iterations):
        # Yield current state
        yield dict(current)
        
        # Check base case - stop generating
        if ~w:
            return
        
        # Transform for next iteration (placeholder)
        pass
    
    print >> sys.stderr, 'Warning: Max iterations exceeded for ~w'", [Name, BaseCondition, Name]).

%% ============================================
%% SIMPLE MODE
%% ============================================

% Try native clause body lowering first
compile_simple_mode_jython(Pred, Arity, _Options, JythonCode) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    Clauses \= [],
    \+ (member(_-Body, Clauses), Body == true),
    native_jython_clause_body(Pred/Arity, Clauses, FuncBody),
    !,
    atom_string(Pred, PredStr),
    Arity1 is Arity - 1,
    build_jython_arg_list(Arity1, ArgList),
    format(string(JythonCode),
'#!/usr/bin/env jython
# -*- coding: utf-8 -*-
# Generated by UnifyWeaver Jython Target - Native Clause Lowering
# Predicate: ~w/~w

import sys

def ~w(~w):
~w

if __name__ == "__main__":
    if len(sys.argv) > 1:
        print(~w(int(sys.argv[1])))
', [PredStr, Arity, PredStr, ArgList, FuncBody, PredStr]).

% Fallback: existing compilation
compile_simple_mode_jython(Pred, Arity, Options, JythonCode) :-
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate function for each clause
    (   Clauses == []
    ->  FunctionCode = "    # No clauses found\n    pass"
    ;   findall(Code, (member((H, B), Clauses), clause_to_jython(H, B, Code)), FunctionCodes),
        atomic_list_concat(FunctionCodes, '\n', FunctionCode)
    ),
    
    % Standard imports
    collect_jython_import(sys),
    collect_jython_import(json),
    
    % Java imports if specified
    (   option(java_imports(JavaImports), Options)
    ->  forall(member(JI, JavaImports), collect_jython_import(JI))
    ;   true
    ),
    
    get_jython_imports(ImportList),
    format_jython_imports(ImportList, ImportsStr),
    
    format(string(JythonCode),
"#!/usr/bin/env jython
# -*- coding: utf-8 -*-
# Generated by UnifyWeaver Jython Target
# Predicate: ~w/~w

~w

def ~w(*args):
    '''Generated predicate ~w/~w'''
~w

if __name__ == '__main__':
    # TODO: Add main logic
    pass
", [Pred, Arity, ImportsStr, Pred, Pred, Arity, FunctionCode]).

%% clause_to_jython(+Head, +Body, -Code)
%  Convert a single clause to Jython code (stub)
clause_to_jython(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    length(Args, _Arity),
    (   Body == true
    ->  format(string(Code), "    # Fact: ~w", [Head])
    ;   format(string(Code), "    # Rule: ~w :- ~w", [Head, Body])
    ).

%% ============================================
%% PIPELINE MODE
%% ============================================

compile_pipeline_mode_jython(Pred, Arity, Options, JythonCode) :-
    % Standard pipeline imports
    collect_jython_import(sys),
    collect_jython_import(json),
    
    % Java imports for performance (optional)
    (   option(use_java_json(true), Options)
    ->  collect_jython_import('com.google.gson.Gson'),
        collect_jython_import('com.google.gson.JsonParser')
    ;   true
    ),
    
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate process function
    (   Clauses == []
    ->  ProcessCode = "    # No clauses found - pass through\n    yield record"
    ;   generate_pipeline_process_jython(Clauses, ProcessCode)
    ),
    
    get_jython_imports(ImportList),
    format_jython_imports(ImportList, ImportsStr),
    
    format(string(JythonCode),
"#!/usr/bin/env jython
# -*- coding: utf-8 -*-
# Generated by UnifyWeaver Jython Target - Pipeline Mode
# Predicate: ~w/~w
# Note: Jython uses Python 2.7 syntax

from __future__ import print_function
~w
from java.io import BufferedReader, InputStreamReader
from java.lang import System as JavaSystem

def process(record):
    '''
    Process a single input record.
    
    Args:
        record: Input record as dict
        
    Yields:
        Output records (dicts)
    '''
~w

def read_jsonl(stream):
    '''Read JSONL from input stream.'''
    reader = BufferedReader(InputStreamReader(stream))
    line = reader.readLine()
    while line is not None:
        if line.strip():
            yield json.loads(line)
        line = reader.readLine()

def write_jsonl(record, stream=None):
    '''Write record as JSONL.'''
    if stream is None:
        print(json.dumps(record))
    else:
        stream.write(json.dumps(record) + '\\n')

def run_pipeline():
    '''Run the pipeline: read from stdin, process, write to stdout.'''
    for record in read_jsonl(JavaSystem.in):
        for result in process(record):
            write_jsonl(result)

if __name__ == '__main__':
    run_pipeline()
", [Pred, Arity, ImportsStr, ProcessCode]).

%% generate_pipeline_process_jython(+Clauses, -Code)
%  Generate process function body from clauses
generate_pipeline_process_jython([], "    yield record").
generate_pipeline_process_jython(Clauses, Code) :-
    Clauses \= [],
    % Check for recursion
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_jython(Name, Clauses)
    ->  % Separate base and recursive clauses
        partition(is_recursive_clause_jython(Name), Clauses, RecClauses, BaseClauses),
        % Check if tail recursive
        (   is_tail_recursive_jython(Name, RecClauses)
        ->  compile_tail_recursive_jython(Name, BaseClauses, RecClauses, Code)
        ;   compile_general_recursive_jython(Name, BaseClauses, RecClauses, Code)
        )
    ;   % Generate clause-based processing
        findall(ClauseCode, 
            (member((H, B), Clauses), translate_clause_jython(H, B, ClauseCode)),
            ClauseCodes),
        atomic_list_concat(ClauseCodes, '\n', AllClausesCode),
        format(string(Code), "~w", [AllClausesCode])
    ).

%% ============================================
%% RECURSION DETECTION AND PATTERNS
%% ============================================

%% is_recursive_predicate_jython(+Name, +Clauses)
is_recursive_predicate_jython(Name, Clauses) :-
    member((_, Body), Clauses),
    contains_recursive_call_jython(Body, Name).

%% is_recursive_clause_jython(+Name, +Clause)
is_recursive_clause_jython(Name, (_, Body)) :-
    contains_recursive_call_jython(Body, Name).

%% is_tail_recursive_jython(+Name, +RecClauses)
is_tail_recursive_jython(Name, RecClauses) :-
    member((_, Body), RecClauses),
    get_last_goal_jython(Body, LastGoal),
    functor(LastGoal, Name, _).

%% get_last_goal_jython(+Body, -LastGoal)
get_last_goal_jython((_, B), LastGoal) :- !, get_last_goal_jython(B, LastGoal).
get_last_goal_jython(Goal, Goal).

%% contains_recursive_call_jython(+Body, +Name)
contains_recursive_call_jython(Body, Name) :-
    extract_goal_jython(Body, Goal),
    functor(Goal, Name, _),
    !.

%% extract_goal_jython(+Body, -Goal)
extract_goal_jython(Goal, Goal) :-
    compound(Goal),
    \+ Goal = (_,_),
    \+ Goal = (_;_).
extract_goal_jython((A, _), Goal) :- extract_goal_jython(A, Goal).
extract_goal_jython((_, B), Goal) :- extract_goal_jython(B, Goal).

%% ============================================
%% TAIL RECURSION PATTERN (→ while loop)
%% ============================================

%% compile_tail_recursive_jython(+Name, +BaseClauses, +RecClauses, -Code)
compile_tail_recursive_jython(Name, BaseClauses, RecClauses, Code) :-
    % Generate base case condition
    (   BaseClauses = [(BaseHead, _BaseBody)|_]
    ->  generate_base_condition_jython(BaseHead, BaseCondition)
    ;   BaseCondition = "False"
    ),
    
    % Generate recursive transformation
    (   RecClauses = [(_, RecBody)|_]
    ->  generate_recursive_transform_jython(RecBody, Name, Transform)
    ;   Transform = "current"
    ),
    
    format(string(Code),
"    # Tail-recursive predicate: ~w - optimized to while loop
    current = dict(record)
    max_iterations = 10000
    
    for _ in xrange(max_iterations):
        # Base case check
        if ~w:
            yield current
            return
        
        # Recursive step (tail call transformed to loop)
        current = ~w
    
    # Exceeded max iterations
    print >> sys.stderr, 'Warning: Max iterations exceeded for ~w'
    yield current", [Name, BaseCondition, Transform, Name]).

%% generate_base_condition_jython(+Head, -Condition)
generate_base_condition_jython(Head, Condition) :-
    Head =.. [_|Args],
    (   Args = [Arg|_],
        (   number(Arg)
        ->  format(string(Condition), "current.get('arg0') == ~w", [Arg])
        ;   atom(Arg)
        ->  format(string(Condition), "current.get('arg0') == '~w'", [Arg])
        ;   Condition = "False"
        )
    ;   Condition = "False"
    ).

%% generate_recursive_transform_jython(+Body, +Name, -Transform)
generate_recursive_transform_jython(Body, Name, Transform) :-
    extract_goal_jython(Body, Goal),
    functor(Goal, Name, _),
    Goal =.. [_|Args],
    (   Args = [Expr|_],
        expr_to_jython(Expr, JythonExpr),
        format(string(Transform), "{'arg0': ~w}", [JythonExpr])
    ;   Transform = "current"
    ).

%% ============================================
%% GENERAL RECURSION PATTERN (→ memoization)
%% ============================================

%% compile_general_recursive_jython(+Name, +BaseClauses, +RecClauses, -Code)
compile_general_recursive_jython(Name, BaseClauses, RecClauses, Code) :-
    % Generate base case
    (   BaseClauses = [(BaseHead, _BaseBody)|_]
    ->  generate_base_condition_jython(BaseHead, BaseCondition)
    ;   BaseCondition = "False"
    ),
    
    % Generate recursive case
    (   RecClauses = [(_, RecBody)|_]
    ->  generate_memoized_recursive_jython(RecBody, Name, RecursiveComputation)
    ;   RecursiveComputation = "current"
    ),
    
    format(string(Code),
"    # General recursive predicate: ~w - with memoization
    memo = record.get('__memo__', {})
    
    key = str(record.get('arg0'))
    if key in memo:
        yield memo[key]
        return
    
    current = dict(record)
    
    # Base case check
    if ~w:
        memo[key] = current
        yield current
        return
    
    # Recursive computation with memoization
    result = ~w
    memo[key] = result
    yield result", [Name, BaseCondition, RecursiveComputation]).

%% generate_memoized_recursive_jython(+Body, +Name, -Code)
generate_memoized_recursive_jython(Body, Name, Code) :-
    extract_goal_jython(Body, Goal),
    functor(Goal, Name, _),
    Goal =.. [_|Args],
    (   Args = [Expr|_]
    ->  expr_to_jython(Expr, JythonExpr),
        format(string(Code),
"list(process({'arg0': ~w, '__memo__': memo}))[0]", [JythonExpr])
    ;   Code = "current"
    ).

%% ============================================
%% CLAUSE TRANSLATION
%% ============================================

%% translate_clause_jython(+Head, +Body, -Code)
translate_clause_jython(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    % Generate input extraction
    generate_input_extraction_jython(Args, InputCode),
    % Translate body
    (   Body == true
    ->  BodyCode = "    # Fact - no conditions"
    ;   translate_body_jython(Body, BodyCode)
    ),
    % Generate output
    format(string(Code), "~w\n~w\n    yield record", [InputCode, BodyCode]).

%% generate_input_extraction_jython(+Args, -Code)
generate_input_extraction_jython(Args, Code) :-
    findall(Line, (
        nth0(I, Args, Arg),
        (   var(Arg)
        ->  format(string(Line), "    arg~w = record.get('arg~w')", [I, I])
        ;   format(string(Line), "    # arg~w = ~w (constant)", [I, Arg])
        )
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

%% ============================================
%% BODY TRANSLATION
%% ============================================

%% translate_body_jython(+Body, -Code)
translate_body_jython((Goal, Rest), Code) :-
    !,
    translate_goal_jython(Goal, Code1),
    translate_body_jython(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_body_jython(Goal, Code) :-
    translate_goal_jython(Goal, Code).

%% translate_goal_jython(+Goal, -Code)

% Assignment: X = Value
translate_goal_jython(=(Var, Value), Code) :-
    var(Var), !,
    var_to_jython(Var, JythonVar),
    value_to_jython(Value, JythonValue),
    format(string(Code), "    ~w = ~w", [JythonVar, JythonValue]).

% Comparison: X > Y, X < Y, etc.
translate_goal_jython(>(X, Y), Code) :-
    !,
    expr_to_jython(X, JX),
    expr_to_jython(Y, JY),
    format(string(Code), "    if not (~w > ~w): return", [JX, JY]).

translate_goal_jython(<(X, Y), Code) :-
    !,
    expr_to_jython(X, JX),
    expr_to_jython(Y, JY),
    format(string(Code), "    if not (~w < ~w): return", [JX, JY]).

translate_goal_jython(>=(X, Y), Code) :-
    !,
    expr_to_jython(X, JX),
    expr_to_jython(Y, JY),
    format(string(Code), "    if not (~w >= ~w): return", [JX, JY]).

translate_goal_jython(=<(X, Y), Code) :-
    !,
    expr_to_jython(X, JX),
    expr_to_jython(Y, JY),
    format(string(Code), "    if not (~w <= ~w): return", [JX, JY]).

translate_goal_jython(=:=(X, Y), Code) :-
    !,
    expr_to_jython(X, JX),
    expr_to_jython(Y, JY),
    format(string(Code), "    if ~w != ~w: return", [JX, JY]).

translate_goal_jython(=\\=(X, Y), Code) :-
    !,
    expr_to_jython(X, JX),
    expr_to_jython(Y, JY),
    format(string(Code), "    if ~w == ~w: return", [JX, JY]).

% Arithmetic: X is Expr
translate_goal_jython(is(Var, Expr), Code) :-
    !,
    var_to_jython(Var, JythonVar),
    expr_to_jython(Expr, JythonExpr),
    format(string(Code), "    ~w = ~w", [JythonVar, JythonExpr]).

% get_dict/3: get_dict(Key, Dict, Value)
translate_goal_jython(get_dict(Key, Dict, Value), Code) :-
    !,
    var_to_jython(Dict, JythonDict),
    var_to_jython(Value, JythonValue),
    format(string(Code), "    ~w = ~w.get('~w')", [JythonValue, JythonDict, Key]).

% put_dict/3
translate_goal_jython(put_dict(Updates, Dict, NewDict), Code) :-
    !,
    var_to_jython(Dict, JythonDict),
    var_to_jython(NewDict, JythonNewDict),
    format(string(Code), "    ~w = dict(~w)\n    ~w.update(~w)", 
           [JythonNewDict, JythonDict, JythonNewDict, Updates]).

% true - no-op
translate_goal_jython(true, Code) :-
    !,
    Code = "    pass  # true".

% Unknown goal - comment
translate_goal_jython(Goal, Code) :-
    format(string(Code), "    # TODO: ~w", [Goal]).

%% ============================================
%% HELPER PREDICATES
%% ============================================

%% var_to_jython(+Var, -JythonVar)
var_to_jython(Var, JythonVar) :-
    (   var(Var)
    ->  term_to_atom(Var, VarAtom),
        format(atom(JythonVar), "var_~w", [VarAtom])
    ;   Var = '$VAR'(N)
    ->  format(atom(JythonVar), "v_~w", [N])
    ;   term_to_atom(Var, JythonVar)
    ).

%% value_to_jython(+Value, -JythonValue)
value_to_jython(Value, JythonValue) :-
    (   number(Value)
    ->  format(atom(JythonValue), "~w", [Value])
    ;   atom(Value)
    ->  format(atom(JythonValue), "'~w'", [Value])
    ;   var(Value)
    ->  var_to_jython(Value, JythonValue)
    ;   format(atom(JythonValue), "~w", [Value])
    ).

%% expr_to_jython(+Expr, -JythonExpr)
expr_to_jython(Expr, JythonExpr) :-
    (   number(Expr)
    ->  format(atom(JythonExpr), "~w", [Expr])
    ;   var(Expr)
    ->  var_to_jython(Expr, JythonExpr)
    ;   Expr = '$VAR'(N)
    ->  format(atom(JythonExpr), "v_~w", [N])
    ;   Expr = X + Y
    ->  expr_to_jython(X, JX), expr_to_jython(Y, JY),
        format(atom(JythonExpr), "(~w + ~w)", [JX, JY])
    ;   Expr = X - Y
    ->  expr_to_jython(X, JX), expr_to_jython(Y, JY),
        format(atom(JythonExpr), "(~w - ~w)", [JX, JY])
    ;   Expr = X * Y
    ->  expr_to_jython(X, JX), expr_to_jython(Y, JY),
        format(atom(JythonExpr), "(~w * ~w)", [JX, JY])
    ;   Expr = X / Y
    ->  expr_to_jython(X, JX), expr_to_jython(Y, JY),
        format(atom(JythonExpr), "(~w / ~w)", [JX, JY])
    ;   Expr = X mod Y
    ->  expr_to_jython(X, JX), expr_to_jython(Y, JY),
        format(atom(JythonExpr), "(~w % ~w)", [JX, JY])
    ;   format(atom(JythonExpr), "~w", [Expr])
    ).

%% ============================================
%% PIPELINE COMPILATION
%% ============================================

%% compile_jython_pipeline(+Steps, +Options, -JythonCode)
compile_jython_pipeline(Steps, Options, JythonCode) :-
    % Standard imports
    collect_jython_import(sys),
    collect_jython_import(json),
    
    % Generate step functions
    generate_step_functions_jython(Steps, 1, StepFunctions),
    
    % Generate pipeline orchestration
    generate_pipeline_orchestration_jython(Steps, OrchestrationCode),
    
    get_jython_imports(ImportList),
    format_jython_imports(ImportList, ImportsStr),
    
    (   option(pipeline_name(PipelineName), Options)
    ->  true
    ;   PipelineName = 'pipeline'
    ),
    
    format(string(JythonCode),
"#!/usr/bin/env jython
# -*- coding: utf-8 -*-
# Generated by UnifyWeaver Jython Target - Multi-Step Pipeline

from __future__ import print_function
~w
from java.io import BufferedReader, InputStreamReader
from java.lang import System as JavaSystem

~w

def ~w(records):
    '''Execute the full pipeline.'''
    for record in records:
~w
        yield record

def read_jsonl(stream):
    '''Read JSONL from input stream.'''
    reader = BufferedReader(InputStreamReader(stream))
    line = reader.readLine()
    while line is not None:
        if line.strip():
            yield json.loads(line)
        line = reader.readLine()

if __name__ == '__main__':
    for result in ~w(read_jsonl(JavaSystem.in)):
        print(json.dumps(result))
", [ImportsStr, StepFunctions, PipelineName, OrchestrationCode, PipelineName]).

%% generate_step_functions_jython(+Steps, +N, -Code)
generate_step_functions_jython([], _, "").
generate_step_functions_jython([step(Name, Target, _Script, _Opts)|Rest], N, Code) :-
    format(string(StepCode),
"def step_~w(record):
    '''Step ~w: ~w (~w)'''
    # TODO: Implement ~w logic
    return record

", [Name, N, Name, Target, Target]),
    N1 is N + 1,
    generate_step_functions_jython(Rest, N1, RestCode),
    atom_concat(StepCode, RestCode, Code).

%% generate_pipeline_orchestration_jython(+Steps, -Code)
generate_pipeline_orchestration_jython(Steps, Code) :-
    findall(CallCode,
        (   member(step(Name, _, _, _), Steps),
            format(string(CallCode), "        record = step_~w(record)\n        if record is None: continue", [Name])
        ),
        Calls),
    atomic_list_concat(Calls, '\n', Code).

%% ============================================
%% UTILITY PREDICATES
%% ============================================

%% write_jython_program(+JythonCode, +FilePath)
write_jython_program(JythonCode, FilePath) :-
    open(FilePath, write, Stream),
    write(Stream, JythonCode),
    close(Stream),
    format('Written Jython program to: ~w~n', [FilePath]).

%% option(+Option, +Options, +Default)
option(Option, Options, _Default) :-
    member(Option, Options),
    !.
option(Option, _Options, Default) :-
    Option =.. [_, Default].

%% ============================================
%% TESTS
%% ============================================

test_jython_pipeline_mode :-
    format('~n=== Testing Jython Pipeline Mode ===~n~n'),
    
    % Test 1: Basic pipeline generation
    format('Test 1: Basic pipeline generation~n'),
    compile_predicate_to_jython(test_pred/2, [pipeline_input(true)], Code1),
    (   sub_atom(Code1, _, _, _, 'run_pipeline')
    ->  format('  [PASS] Generated pipeline code~n')
    ;   format('  [FAIL] Missing pipeline code~n')
    ),
    
    % Test 2: Java imports
    format('~nTest 2: Java System imports~n'),
    (   sub_atom(Code1, _, _, _, 'JavaSystem')
    ->  format('  [PASS] Java System import present~n')
    ;   format('  [FAIL] Missing Java imports~n')
    ),
    
    % Test 3: Python 2 syntax
    format('~nTest 3: Python 2 syntax (xrange in tail recursion)~n'),
    format('  [INFO] Uses print_function from __future__~n'),
    
    format('~n=== Jython Pipeline Mode Tests Complete ===~n').

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(jython, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_jython(StepOp, JythonStepExpr),
    (   Arity =:= 3 ->
        format(string(Code),
'# Generated by UnifyWeaver Jython Target - Tail Recursion (multifile dispatch)
# Predicate: ~w/~w
# Python 2.7 compatible (Jython)
from __future__ import print_function

def ~w(items, acc=0):
    for item in items:
        acc = ~w
    return acc

if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 2:
        items = [int(x) for x in sys.argv[1].split(",")]
        print(~w(items))
', [PredStr, Arity, PredStr, JythonStepExpr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'# Generated by UnifyWeaver Jython Target - Tail Recursion (binary, multifile dispatch)
# Predicate: ~w/~w
# Python 2.7 compatible (Jython)
from __future__ import print_function

def ~w(items):
    count = 0
    for _ in items:
        count += 1
    return count

if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 2:
        items = sys.argv[1].split(",")
        print(~w(items))
', [PredStr, Arity, PredStr, PredStr])
    ;   fail
    ).

step_op_to_jython(arithmetic(Expr), JExpr) :- tail_expr_to_jython(Expr, JExpr).
step_op_to_jython(unknown, 'acc + 1').

tail_expr_to_jython(_ + Const, JExpr) :- integer(Const), !, format(atom(JExpr), 'acc + ~w', [Const]).
tail_expr_to_jython(_ + _, 'acc + item') :- !.
tail_expr_to_jython(_ - _, 'acc - item') :- !.
tail_expr_to_jython(_ * _, 'acc * item') :- !.
tail_expr_to_jython(_, 'acc + 1').

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(jython, PredStr, Arity, BaseClauses, _RecClauses, MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_jython(PredStr, BaseClauses, MemoEnabled, Code)
    ;   linear_generic_jython(PredStr, Arity, MemoEnabled, Code)
    ).

linear_fold_jython(PredStr, BaseClauses, MemoEnabled, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    (   MemoEnabled = true ->
        format(string(MemoDecl), '~w_memo = {}', [PredStr])
    ;   MemoDecl = '# Memoization disabled'
    ),
    % Extract fold
    atom_string(Pred, PredStr),
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
    partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRec, _),
    (   ActualRec = [clause(RHead, RBody)|_] ->
        RHead =.. [_, InputVar, _],
        linear_recursion:find_recursive_call(RBody, RecCall),
        RecCall =.. [_, _, AccVar],
        linear_recursion:find_last_is_expression(RBody, _ is FoldExpr),
        translate_fold_expr_jython(FoldExpr, InputVar, AccVar, JythonOp)
    ;   JythonOp = "current * acc"
    ),
    (   InputType = numeric ->
        (   MemoEnabled = true ->
            format(string(MemoCheck_N), '    if n in ~w_memo: return ~w_memo[n]', [PredStr, PredStr]),
            format(string(MemoStore_N), '    ~w_memo[n] = result', [PredStr])
        ;   MemoCheck_N = '', MemoStore_N = ''
        ),
        format(string(Code),
'# Generated by UnifyWeaver Jython Target - Linear Recursion (numeric, multifile dispatch)
# Predicate: ~w/2
# Python 2/3 compatible
from __future__ import print_function
try:
    from functools import reduce
except ImportError:
    pass  # Python 2 has reduce built-in

~w

def ~w(n):
~w
    if n == ~w: return ~w
    result = reduce(lambda acc, current: ~w, range(n, 0, -1), ~w)
~w
    return result

if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 2:
        print(~w(int(sys.argv[1])))
', [PredStr, MemoDecl, PredStr, MemoCheck_N, BaseInput, BaseOutput, JythonOp, BaseOutput, MemoStore_N, PredStr])
    ;   InputType = list ->
        (   MemoEnabled = true ->
            format(string(MemoCheck_L), '    if tuple(lst) in ~w_memo: return ~w_memo[tuple(lst)]', [PredStr, PredStr]),
            format(string(MemoStore_L), '    ~w_memo[tuple(lst)] = result', [PredStr])
        ;   MemoCheck_L = '', MemoStore_L = ''
        ),
        format(string(Code),
'# Generated by UnifyWeaver Jython Target - Linear Recursion (list, multifile dispatch)
# Predicate: ~w/2
# Python 2/3 compatible
from __future__ import print_function
try:
    from functools import reduce
except ImportError:
    pass  # Python 2 has reduce built-in

~w

def ~w(lst):
~w
    if not lst: return ~w
    result = reduce(lambda acc, current: ~w, lst, ~w)
~w
    return result

if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 2:
        items = [int(x) for x in sys.argv[1].split(",")]
        print(~w(items))
', [PredStr, MemoDecl, PredStr, MemoCheck_L, BaseOutput, JythonOp, BaseOutput, MemoStore_L, PredStr])
    ;   linear_generic_jython(PredStr, 2, MemoEnabled, Code)
    ).

linear_generic_jython(PredStr, Arity, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        format(string(MemoDecl), '~w_memo = {}', [PredStr])
    ;   MemoDecl = '# Memoization disabled'
    ),
    format(string(Code),
'# Generated by UnifyWeaver Jython Target - Linear Recursion (generic, multifile dispatch)
# Predicate: ~w/~w
# Python 2.7 compatible (Jython)
from __future__ import print_function

~w

def ~w(n):
    if n in ~w_memo: return ~w_memo[n]
    if n <= 0: result = 0
    elif n == 1: result = 1
    else: result = ~w(n - 1) + n
    ~w_memo[n] = result
    return result

if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 2:
        print(~w(int(sys.argv[1])))
', [PredStr, Arity, MemoDecl, PredStr, PredStr, PredStr, PredStr, PredStr, PredStr]).

translate_fold_expr_jython(A * B, IV, AV, E) :- translate_jython_term(A, IV, AV, AT), translate_jython_term(B, IV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_fold_expr_jython(A + B, IV, AV, E) :- translate_jython_term(A, IV, AV, AT), translate_jython_term(B, IV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_fold_expr_jython(A - B, IV, AV, E) :- translate_jython_term(A, IV, AV, AT), translate_jython_term(B, IV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_fold_expr_jython(T, IV, AV, E) :- translate_jython_term(T, IV, AV, E).

translate_jython_term(T, IV, _, 'current') :- T == IV, !.
translate_jython_term(T, _, AV, 'acc') :- T == AV, !.
translate_jython_term(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_jython_term(T, _, _, 'current') :- var(T), !.
translate_jython_term(A, _, _, S) :- format(string(S), '~w', [A]).

% ============================================================================
% MULTIFILE DISPATCH - Tree Recursion
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(jython, _Pattern, Pred, _Arity, _UseMemo, JythonCode) :-
    atom_string(Pred, PredStr),
    format(string(JythonCode),
'# Generated by UnifyWeaver Jython Target - Tree Recursion (multifile dispatch)
# Predicate: ~w
# Python 2.7 compatible (Jython)
from __future__ import print_function
import sys

memo = {}

def ~w(n):
    if n in memo:
        return memo[n]
    if n <= 0:
        return 0
    if n == 1:
        return 1
    result = ~w(n - 1) + ~w(n - 2)
    memo[n] = result
    return result

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        print(~w(int(sys.argv[1])))
', [PredStr, PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTIFILE DISPATCH - Multicall Linear Recursion
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(jython, PredStr, BaseClauses, _RecClauses, _MemoEnabled, JythonCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    if n == ~w: return ~w', [BInput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(JythonCode),
'# Generated by UnifyWeaver Jython Target - Multicall Linear Recursion (multifile dispatch)
# Predicate: ~w
# Python 2.7 compatible (Jython)
from __future__ import print_function
import sys

memo = {}

def ~w(n):
    if n in memo:
        return memo[n]
~w
    result = ~w(n - 1) + ~w(n - 2)
    memo[n] = result
    return result

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        print(~w(int(sys.argv[1])))
', [PredStr, PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTIFILE DISPATCH - Direct Multicall Recursion
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(jython, PredStr, BaseClauses, _RecClause, JythonCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '    if n == ~w:\n        memo[n] = ~w\n        return ~w', [BInput, BOutput, BOutput])
    ), BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(JythonCode),
'# Generated by UnifyWeaver Jython Target - Direct Multicall Recursion (multifile dispatch)
# Predicate: ~w
# Python 2.7 compatible (Jython)
from __future__ import print_function
import sys

memo = {}

def ~w(n):
    if n in memo:
        return memo[n]
~w
    result = ~w(n - 1) + ~w(n - 2)
    memo[n] = result
    return result

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        print(~w(int(sys.argv[1])))
', [PredStr, PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTIFILE DISPATCH - Mutual Recursion
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(jython, Predicates, MemoEnabled, _MemoStrategy, JythonCode) :-
    % Generate functions for each predicate
    mutual_functions_jython(Predicates, Predicates, MemoEnabled, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    % Generate CLI dispatch
    mutual_dispatch_jython(Predicates, DispatchCode),
    format(string(JythonCode),
'# Generated by UnifyWeaver Jython Target - Mutual Recursion (multifile dispatch)
# Python 2.7 compatible (Jython)
from __future__ import print_function
import sys

~w

~w
', [FunctionsCode, DispatchCode]).

mutual_functions_jython([], _AllPreds, _MemoEnabled, []).
mutual_functions_jython([Pred/Arity|Rest], AllPreds, MemoEnabled, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    % Base cases
    findall(BaseLine, (
        member(clause(BHead, true), BaseClauses),
        BHead =.. [_P, BValue],
        format(string(BaseLine), '    if n == ~w:\n        return True', [BValue])
    ), BaseLines),
    atomic_list_concat(BaseLines, '\n', BaseCode),
    % Recursive case
    (   RecClauses = [clause(_RHead, RBody)|_] ->
        extract_mutual_rec_info_jython(RBody, Guard, CalledPred, Step),
        atom_string(CalledPred, CalledStr),
        (   Guard = (N > Threshold), var(N) ->
            format(string(RecCode),
'    if n > ~w:\n        return ~w(n ~w)', [Threshold, CalledStr, Step])
        ;   format(string(RecCode),
'    return ~w(n ~w)', [CalledStr, Step])
        )
    ;   RecCode = ''
    ),
    format(string(FuncCode),
'def ~w(n):
~w
~w
    return False', [PredStr, BaseCode, RecCode]),
    mutual_functions_jython(Rest, AllPreds, MemoEnabled, RestCodes).

extract_mutual_rec_info_jython(Body, Guard, CalledPred, Step) :-
    extract_goals_from_body_jython(Body, Goals),
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(Step), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(Step), '- ~w', [AbsK])
    ;   Step = "- 1"
    ).

extract_goals_from_body_jython((A, B), Goals) :- !,
    extract_goals_from_body_jython(A, GA),
    extract_goals_from_body_jython(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body_jython(true, []) :- !.
extract_goals_from_body_jython(Goal, [Goal]).

mutual_dispatch_jython(Predicates, Code) :-
    findall(ElifLine, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(ElifLine),
'        elif func == "~w":\n            print(~w(n))', [PredStr, PredStr])
    ), Lines),
    atomic_list_concat(Lines, '\n', ElifCode),
    format(string(Code),
'if __name__ == "__main__":
    if len(sys.argv) >= 3:
        func = sys.argv[1]
        n = int(sys.argv[2])
        if False:
            pass
~w
', [ElifCode]).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_jython_arg_list(+N, -ArgList)
build_jython_arg_list(0, "") :- !.
build_jython_arg_list(N, ArgList) :-
    findall(Arg, (
        between(1, N, I),
        format(string(Arg), 'arg~w', [I])
    ), Args),
    atomic_list_concat(Args, ', ', ArgList).

%% native_jython_clause_body(+PredSpec, +Clauses, -Code)

% Single clause
native_jython_clause_body(PredSpec, [Head-Body], Code) :-
    native_jython_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !,
    (   Condition == "True"
    ->  format(string(Code), '    return ~w', [ClauseCode])
    ;   format(string(Code),
'    if ~w:
        return ~w
    raise ValueError("No matching clause for ~w")', [Condition, ClauseCode, PredSpec])
    ).

% Multi-clause → if/elif/else
native_jython_clause_body(PredSpec, Clauses, Code) :-
    Clauses = [_|[_|_]],
    maplist(native_jython_clause_pair(PredSpec), Clauses, Branches),
    Branches \= [],
    branches_to_jython_if_chain(Branches, PredSpec, Code).

native_jython_clause_pair(PredSpec, Head-Body, branch(Condition, ClauseCode)) :-
    native_jython_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !.

%% native_jython_clause(+PredSpec, +Head, +Body, -Condition, -Code)
native_jython_clause(_PredSpec, Head, Body, Condition, Code) :-
    Head =.. [_Pred|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputHeadArgs, [OutputHeadArg], HeadArgs),
        jython_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ;   OutputHeadArg = _,
        jython_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ),
    normalize_goals(Body, Goals),
    (   Goals == []
    ->  jython_resolve_value(VarMap, OutputHeadArg, Code),
        GoalConditions = []
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
            maplist(jython_guard_condition(VarMap), GuardGoals, GoalConditions),
            (   OutputGoals == []
            ->  jython_literal(OutputHeadArg, Code)
            ;   jython_output_goals(OutputGoals, VarMap, Code)
            )
        ;   native_jython_goal_sequence(Goals, VarMap, GoalConditions, Code)
        )
    ),
    append(HeadConditions, GoalConditions, AllConditions),
    combine_jython_conditions(AllConditions, Condition).

%% jython_head_conditions(+HeadArgs, +Index, +Arity, -Conditions)
jython_head_conditions([], _, _, []).
jython_head_conditions([_], _, Arity, []) :- Arity > 1, !.
jython_head_conditions([HeadArg|Rest], Index, Arity, Conditions) :-
    (   var(HeadArg)
    ->  Conditions = RestConditions
    ;   format(string(ArgName), 'arg~w', [Index]),
        jython_literal(HeadArg, Literal),
        format(string(Cond), '~w == ~w', [ArgName, Literal]),
        Conditions = [Cond|RestConditions]
    ),
    NextIndex is Index + 1,
    jython_head_conditions(Rest, NextIndex, Arity, RestConditions).

%% native_jython_goal_sequence(+Goals, +VarMap, -Conditions, -Code)
%  Uses classify_goal_sequence for advanced pattern detection.
%  Falls back to clause_guard_output_split if classification fails.
native_jython_goal_sequence(Goals, VarMap, Conditions, Code) :-
    classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
    ClassifiedGoals \= [],
    jython_render_classified_goals(ClassifiedGoals, VarMap, Conditions, Lines),
    Lines \= [],
    atomic_list_concat(Lines, '\n', Code),
    !.
native_jython_goal_sequence(Goals, VarMap, Conditions, Code) :-
    clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
    maplist(jython_guard_condition(VarMap), GuardGoals, Conditions),
    jython_output_goals(OutputGoals, VarMap, Code).

%% jython_render_classified_goals(+ClassifiedGoals, +VarMap, -Conditions, -Lines)
jython_render_classified_goals([], _VarMap, [], []).
jython_render_classified_goals([Classified], VarMap, Conds, Lines) :-
    !,
    jython_render_classified_last(Classified, VarMap, Conds, Lines).
%% Guarded tail: output followed by guard(s)
jython_render_classified_goals([output(Goal, _, _)|Rest], VarMap, [], Lines) :-
    Rest = [guard(_, _)|_],
    !,
    jython_classified_output_goal(Goal, VarMap, LetBinding, VarMap1),
    jython_collect_trailing_guards(Rest, VarMap1, GuardGoals, _Remaining),
    maplist(jython_guard_condition(VarMap1), GuardGoals, GuardConds),
    atomic_list_concat(GuardConds, ' and ', GuardExpr),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMap1, OutName)
    ->  true
    ;   OutName = '_'
    ),
    format(string(IfLine), '    if ~w:', [GuardExpr]),
    format(string(RetLine), '        return ~w', [OutName]),
    Lines = [LetBinding, IfLine, RetLine].
jython_render_classified_goals([Classified|Rest], VarMap, Conds, Lines) :-
    jython_render_classified_mid(Classified, VarMap, MidConds, MidLines, VarMap1),
    jython_render_classified_goals(Rest, VarMap1, RestConds, RestLines),
    append(MidConds, RestConds, Conds),
    append(MidLines, RestLines, Lines).

%% jython_render_classified_mid(+Classified, +VarMap, -Conds, -Lines, -VarMapOut)
jython_render_classified_mid(guard(Goal, _), VarMap, [Cond], [], VarMap) :-
    jython_guard_condition(VarMap, Goal, Cond).
jython_render_classified_mid(output(Goal, _, _), VarMap0, [], [Line], VarMapOut) :-
    jython_classified_output_goal(Goal, VarMap0, Line, VarMapOut).
jython_render_classified_mid(output_ite(If, Then, Else, _SharedVars), VarMap0, [], Lines, VarMap0) :-
    jython_guard_condition(VarMap0, If, Cond),
    jython_branch_value(Then, VarMap0, ThenExpr),
    jython_branch_value(Else, VarMap0, ElseExpr),
    format(string(IfLine), '    if ~w:', [Cond]),
    format(string(ThenLine), '        ~w', [ThenExpr]),
    ElseLine = '    else:',
    format(string(ElseRetLine), '        ~w', [ElseExpr]),
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine].
jython_render_classified_mid(passthrough(Goal), VarMap0, [], [Line], VarMapOut) :-
    jython_classified_output_goal(Goal, VarMap0, Line, VarMapOut).
jython_render_classified_mid(_, VarMap, [], [], VarMap).

%% jython_render_classified_last(+Classified, +VarMap, -Conds, -Lines)
jython_render_classified_last(guard(Goal, _), VarMap, [Cond], []) :-
    jython_guard_condition(VarMap, Goal, Cond).
jython_render_classified_last(output(Goal, _, _), VarMap, [], Lines) :-
    jython_render_output_goal_last(Goal, VarMap, Lines).
jython_render_classified_last(output_ite(If, Then, Else, _), VarMap, [], Lines) :-
    jython_guard_condition(VarMap, If, Cond),
    jython_branch_value(Then, VarMap, ThenExpr),
    jython_branch_value(Else, VarMap, ElseExpr),
    format(string(IfLine), '    if ~w:', [Cond]),
    format(string(ThenLine), '        ~w', [ThenExpr]),
    ElseLine = '    else:',
    format(string(ElseRetLine), '        ~w', [ElseExpr]),
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine].
jython_render_classified_last(output_disj(Alternatives, _SharedVars), VarMap, [], Lines) :-
    jython_disj_if_chain(Alternatives, VarMap, Lines).
jython_render_classified_last(passthrough(Goal), VarMap, [], Lines) :-
    jython_render_output_goal_last(Goal, VarMap, Lines).

%% jython_classified_output_goal(+Goal, +VarMap0, -Line, -VarMapOut)
jython_classified_output_goal(Goal, VarMap0, Line, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap0, Var, VarName, VarMapOut),
        jython_expr(Expr, VarMap0, ExprStr),
        format(string(Line), '    ~w = ~w', [VarName, ExprStr])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap0, Var, VarName, VarMapOut),
        jython_expr(ArithExpr, VarMap0, ExprStr),
        format(string(Line), '    ~w = ~w', [VarName, ExprStr])
    ;   VarMapOut = VarMap0,
        Line = '    # unsupported'
    ).

%% jython_render_output_goal_last(+Goal, +VarMap, -Lines)
%  3-arg wrapper used by classified goal renderers.
jython_render_output_goal_last(Goal, VarMap, [Expr]) :-
    jython_output_goal_last(Goal, VarMap, Expr),
    !.
jython_render_output_goal_last(Goal, VarMap, [Expr]) :-
    jython_branch_value(Goal, VarMap, Expr).

%% jython_collect_trailing_guards(+ClassifiedGoals, +VarMap, -GuardGoals, -Remaining)
jython_collect_trailing_guards([guard(Goal, _)|Rest], VarMap, [Goal|Guards], Remaining) :-
    !, jython_collect_trailing_guards(Rest, VarMap, Guards, Remaining).
jython_collect_trailing_guards(Remaining, _, [], Remaining).

%% jython_disj_if_chain(+Alternatives, +VarMap, -Lines)
jython_disj_if_chain([], _, []).
jython_disj_if_chain([Alt], VarMap, [ElseLine, RetLine]) :-
    !,
    jython_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    else:',
    format(string(RetLine), '        ~w', [ValExpr]).
jython_disj_if_chain([Alt|Rest], VarMap, [IfLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(jython_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' and ', CondExpr)
    ;   CondExpr = 'True'
    ),
    jython_branch_value(Alt, VarMap, ValExpr),
    format(string(IfLine), '    if ~w:', [CondExpr]),
    format(string(RetLine), '        ~w', [ValExpr]),
    jython_disj_elif_chain(Rest, VarMap, RestLines).

%% jython_disj_elif_chain(+Alternatives, +VarMap, -Lines)
jython_disj_elif_chain([], _, []).
jython_disj_elif_chain([Alt], VarMap, [ElseLine, RetLine]) :-
    !,
    jython_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    else:',
    format(string(RetLine), '        ~w', [ValExpr]).
jython_disj_elif_chain([Alt|Rest], VarMap, [ElifLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(jython_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' and ', CondExpr)
    ;   CondExpr = 'True'
    ),
    jython_branch_value(Alt, VarMap, ValExpr),
    format(string(ElifLine), '    elif ~w:', [CondExpr]),
    format(string(RetLine), '        ~w', [ValExpr]),
    jython_disj_elif_chain(Rest, VarMap, RestLines).

%% jython_guard_condition(+VarMap, +Goal, -Condition)
jython_guard_condition(VarMap, _Module:Goal, Condition) :-
    !, jython_guard_condition(VarMap, Goal, Condition).
jython_guard_condition(VarMap, Goal, Condition) :-
    compound(Goal),
    Goal =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    jython_expr(Left, VarMap, JLeft),
    jython_expr(Right, VarMap, JRight),
    jython_op(StdOp, JOp),
    format(string(Condition), '~w ~w ~w', [JLeft, JOp, JRight]).

%% jython_output_goals(+Goals, +VarMap, -Code)
jython_output_goals([], _VarMap, '"error"') :- !.
jython_output_goals([Goal], VarMap, Code) :-
    !, jython_output_goal_last(Goal, VarMap, Code).
jython_output_goals([_Goal|Rest], VarMap, Code) :-
    jython_output_goals(Rest, VarMap, Code).

%% jython_output_goal_last — produce the return expression
jython_output_goal_last(_Module:Goal, VarMap, Code) :-
    !, jython_output_goal_last(Goal, VarMap, Code).
jython_output_goal_last(Goal, VarMap, Code) :-
    if_then_else_goal(Goal, IfGoal, ThenGoal, ElseGoal),
    !,
    jython_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap, Code).
jython_output_goal_last(=(Var, Expr), VarMap, Code) :-
    var(Var), !,
    jython_expr(Expr, VarMap, Code).
jython_output_goal_last(is(Var, Expr), VarMap, Code) :-
    var(Var), !,
    jython_expr(Expr, VarMap, Code).

%% jython_if_then_else_output — generate ternary expressions (Python 2.7 style)
jython_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap, Code) :-
    flatten_jython_if_branches(IfGoal, ThenGoal, ElseGoal, Branches, DefaultGoal),
    jython_branches_to_ternary(Branches, DefaultGoal, VarMap, Code).

flatten_jython_if_branches(If, Then, Else, [branch(If, Then)|RestBranches], Default) :-
    if_then_else_goal(Else, If2, Then2, Else2),
    !,
    flatten_jython_if_branches(If2, Then2, Else2, RestBranches, Default).
flatten_jython_if_branches(If, Then, Else, [branch(If, Then)], Else).

jython_branches_to_ternary([branch(If, Then)], DefaultGoal, VarMap, Code) :-
    !,
    jython_guard_condition(VarMap, If, IfCond),
    jython_branch_value(Then, VarMap, ThenVal),
    jython_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Code), '~w if ~w else ~w', [ThenVal, IfCond, ElseVal]).
jython_branches_to_ternary([branch(If, Then)|Rest], DefaultGoal, VarMap, Code) :-
    jython_guard_condition(VarMap, If, IfCond),
    jython_branch_value(Then, VarMap, ThenVal),
    jython_branches_to_ternary(Rest, DefaultGoal, VarMap, ElseCode),
    format(string(Code), '~w if ~w else ~w', [ThenVal, IfCond, ElseCode]).

%% jython_branch_value — extract result value from a branch
jython_branch_value(_Module:Goal, VarMap, Value) :-
    !, jython_branch_value(Goal, VarMap, Value).
jython_branch_value((A, B), VarMap, Value) :-
    !,
    normalize_goals((A, B), Goals),
    last(Goals, LastGoal),
    jython_branch_value(LastGoal, VarMap, Value).
jython_branch_value(=(_, Expr), VarMap, Value) :-
    !, jython_expr(Expr, VarMap, Value).
jython_branch_value(is(_, Expr), VarMap, Value) :-
    !, jython_expr(Expr, VarMap, Value).
jython_branch_value(Goal, VarMap, Value) :-
    jython_expr(Goal, VarMap, Value).

% ============================================================================
% MULTIFILE HOOKS — Register Jython renderers for shared compile_expression
% ============================================================================

clause_body_analysis:render_output_goal(jython, =(Var, Expr), VarMap0, Line, VarName, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    jython_expr(Expr, VarMap0, ExprStr),
    format(string(Line), '    ~w = ~w', [VarName, ExprStr]).
clause_body_analysis:render_output_goal(jython, is(Var, Expr), VarMap0, Line, VarName, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    jython_expr(Expr, VarMap0, ExprStr),
    format(string(Line), '    ~w = ~w', [VarName, ExprStr]).

clause_body_analysis:render_guard_condition(jython, Goal, VarMap, CondStr) :-
    jython_guard_condition(VarMap, Goal, CondStr).

clause_body_analysis:render_branch_value(jython, Branch, VarMap, ExprStr) :-
    jython_branch_value(Branch, VarMap, ExprStr).

clause_body_analysis:render_ite_block(jython, Cond, ThenLines, ElseLines, Indent, _ReturnVars, Lines) :-
    format(string(IfLine), '~wif ~w:', [Indent, Cond]),
    jython_indent_lines(ThenLines, Indent, IndentedThen),
    (   ElseLines \= []
    ->  format(string(ElseLine), '~welse:', [Indent]),
        jython_indent_lines(ElseLines, Indent, IndentedElse),
        append([IfLine|IndentedThen], [ElseLine|IndentedElse], Lines)
    ;   Lines = [IfLine|IndentedThen]
    ).

jython_indent_lines([], _, []).
jython_indent_lines([Line|Rest], Indent, [Indented|RestIndented]) :-
    format(string(Indented), '~w    ~w', [Indent, Line]),
    jython_indent_lines(Rest, Indent, RestIndented).

%% jython_expr — convert Prolog expression to Jython syntax
jython_expr(Var, VarMap, JExpr) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  atom_string(Name, JExpr)
    ;   JExpr = "0"
    ).
jython_expr(Expr, VarMap, JExpr) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    jython_expr(Left, VarMap, JLeft),
    jython_expr(Right, VarMap, JRight),
    jython_op(StdOp, JOp),
    format(string(JExpr), '(~w ~w ~w)', [JLeft, JOp, JRight]).
jython_expr(-Expr, VarMap, JExpr) :-
    !,
    jython_expr(Expr, VarMap, Inner),
    format(string(JExpr), '(-~w)', [Inner]).
jython_expr(abs(Expr), VarMap, JExpr) :-
    !,
    jython_expr(Expr, VarMap, Inner),
    format(string(JExpr), 'abs(~w)', [Inner]).
jython_expr(Atom, _VarMap, JExpr) :-
    atom(Atom), !,
    jython_literal(Atom, JExpr).
jython_expr(Number, _VarMap, JExpr) :-
    number(Number), !,
    format(string(JExpr), '~w', [Number]).

%% jython_literal — convert Prolog value to Jython literal
jython_literal(Value, '""') :- var(Value), !.
jython_literal(Value, JLit) :-
    number(Value), !,
    format(string(JLit), '~w', [Value]).
jython_literal(Value, JLit) :-
    atom(Value), !,
    format(string(JLit), '"~w"', [Value]).
jython_literal(Value, JLit) :-
    format(string(JLit), '"~w"', [Value]).

%% jython_resolve_value — resolve head arg to Jython expression
jython_resolve_value(VarMap, Var, Value) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  atom_string(Name, Value)
    ;   Value = "''"
    ).
jython_resolve_value(_VarMap, Atom, Value) :-
    atom(Atom), !,
    format(string(Value), '"~w"', [Atom]).
jython_resolve_value(_VarMap, Number, Value) :-
    number(Number), !,
    format(string(Value), 'str(~w)', [Number]).
jython_resolve_value(_VarMap, _, '""').

%% jython_op — map comparison/arithmetic operator to Jython
jython_op('>', '>').
jython_op('<', '<').
jython_op('>=', '>=').
jython_op('<=', '<=').
jython_op('==', '==').
jython_op('!=', '!=').
jython_op('+', '+').
jython_op('-', '-').
jython_op('*', '*').
jython_op('/', '//').
jython_op('%', '%').

%% combine_jython_conditions(+Conditions, -Combined)
combine_jython_conditions([], "True") :- !.
combine_jython_conditions([C], C) :- !.
combine_jython_conditions([C|Rest], Combined) :-
    combine_jython_conditions(Rest, RestCombined),
    format(string(Combined), '~w and ~w', [C, RestCombined]).

%% branches_to_jython_if_chain(+Branches, +PredSpec, -Code)
branches_to_jython_if_chain(Branches, PredSpec, Code) :-
    jython_if_chain_lines(Branches, PredSpec, true, Lines),
    atomic_list_concat(Lines, '\n', Code).

jython_if_chain_lines([branch(Cond, ClauseCode)], PredSpec, IsFirst, Lines) :-
    !,
    (   Cond == "True"
    ->  (   IsFirst == true
        ->  format(string(Line), '    return ~w', [ClauseCode]),
            Lines = [Line]
        ;   format(string(Line), '    else:~n        return ~w', [ClauseCode]),
            Lines = [Line]
        )
    ;   (   IsFirst == true
        ->  format(string(L1), '    if ~w:', [Cond]),
            format(string(L2), '        return ~w', [ClauseCode]),
            format(string(L3), '    raise ValueError("No matching clause for ~w")', [PredSpec]),
            Lines = [L1, L2, L3]
        ;   format(string(L1), '    elif ~w:', [Cond]),
            format(string(L2), '        return ~w', [ClauseCode]),
            format(string(L3), '    raise ValueError("No matching clause for ~w")', [PredSpec]),
            Lines = [L1, L2, L3]
        )
    ).
jython_if_chain_lines([branch(Cond, ClauseCode)|Rest], PredSpec, IsFirst, [L1, L2|RestLines]) :-
    (   IsFirst == true
    ->  format(string(L1), '    if ~w:', [Cond])
    ;   format(string(L1), '    elif ~w:', [Cond])
    ),
    format(string(L2), '        return ~w', [ClauseCode]),
    jython_if_chain_lines(Rest, PredSpec, false, RestLines).
