:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% krakatau_target.pl - Krakatau JVM Assembly Target
% Compiles Prolog predicates to Krakatau assembly (.j files).
% Uses Jasmin-like directive syntax with numeric slot references.
% Shares JVM bytecode infrastructure with Jamaica target.

:- module(krakatau_target, [
    compile_predicate_to_krakatau/3,     % +PredIndicator, +Options, -Code
    compile_predicate/3,                 % +PredIndicator, +Options, -Code
    compile_krakatau_class/4,            % +ClassName, +Methods, +Options, -Code
    write_krakatau_program/2,            % +Code, +Filename
    init_krakatau_target/0
]).

:- use_module(library(lists)).
:- use_module('../core/clause_body_analysis').
:- use_module('../core/jvm_bytecode').

%% init_krakatau_target
init_krakatau_target.

%% compile_predicate/3 - dispatch alias
compile_predicate(PredArity, Options, Code) :-
    compile_predicate_to_krakatau(PredArity, Options, Code).

%% compile_predicate_to_krakatau(+PredIndicator, +Options, -Code)
compile_predicate_to_krakatau(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'Krakatau target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_krakatau(Pred, Arity, Clauses, Options, Code)
    ).

%% compile_clauses_to_krakatau(+Pred, +Arity, +Clauses, +Options, -Code)
compile_clauses_to_krakatau(Pred, Arity, Clauses, Options, Code) :-
    atom_string(Pred, PredStr),
    (   option(class_name(ClassName), Options)
    ->  true
    ;   format(string(ClassName), 'Prolog_~w', [PredStr])
    ),
    % Try native lowering first
    (   native_krakatau_clause_body(PredStr/Arity, Clauses, MethodBody)
    ->  true
    ;   % Fallback: simple identity
        Arity1 is Arity - 1,
        (   Arity1 > 0
        ->  MethodBody = "    iload_0\n    ireturn"
        ;   MethodBody = "    iconst_0\n    ireturn"
        )
    ),
    Arity1 is Arity - 1,
    krakatau_method_descriptor(Arity1, Descriptor),
    % Estimate stack/locals
    string_codes(MethodBody, BodyCodes),
    findall(1, (member(0'\n, BodyCodes)), NLs),
    length(NLs, LineCount),
    StackLimit is max(10, LineCount),
    LocalsLimit is max(10, Arity1 + 5),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target
; Predicate: ~w/~w

.version 52 0
.class public ~w
.super java/lang/Object

.method public static ~w : ~w
    .limit stack ~w
    .limit locals ~w

~w
.end method
', [PredStr, Arity, ClassName, PredStr, Descriptor, StackLimit, LocalsLimit, MethodBody]).

%% krakatau_method_descriptor(+ParamCount, -Descriptor)
krakatau_method_descriptor(N, Descriptor) :-
    length(Params, N),
    maplist(=(int), Params),
    jvm_method_descriptor(Params, int, Descriptor).

%% native_krakatau_clause_body(+PredStr/Arity, +Clauses, -Code)
%%   Uses shared JVM bytecode infrastructure with numeric slot style.
native_krakatau_clause_body(PredStr/Arity, Clauses, Code) :-
    \+ (member(_-Body, Clauses), Body == true),
    jvm_native_clause_body(PredStr/Arity, Clauses, numeric, format(krakatau), Code).

%% compile_krakatau_class(+ClassName, +Methods, +Options, -Code)
%%   Compile a complete Krakatau class with multiple methods.
%%   Methods: list of method(Name, ParamTypes, RetType, Body)
compile_krakatau_class(ClassName, Methods, _Options, Code) :-
    maplist(krakatau_method_code, Methods, MethodCodes),
    atomic_list_concat(MethodCodes, '\n', MethodSection),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target

.version 52 0
.class public ~w
.super java/lang/Object

~w
', [ClassName, MethodSection]).

krakatau_method_code(method(Name, ParamTypes, RetType, Body), Code) :-
    jvm_method_descriptor(ParamTypes, RetType, Descriptor),
    format(string(Code),
'.method public static ~w : ~w
    .limit stack 10
    .limit locals 10

~w
.end method
', [Name, Descriptor, Body]).

%% write_krakatau_program(+Code, +Filename)
write_krakatau_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('Krakatau program written to: ~w~n', [Filename]).
