:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% krakatau_target.pl - Krakatau JVM Assembly Target
% Compiles Prolog predicates to Krakatau assembly (.j files).
% Uses Jasmin-like directive syntax with numeric slot references.
% Shares JVM bytecode infrastructure with Jamaica target.

:- module(krakatau_target, [
    compile_predicate_to_krakatau/3,     % +PredIndicator, +Options, -Code
    compile_predicate/3,                 % +PredIndicator, +Options, -Code
    compile_krakatau_class/4,            % +ClassName, +Methods, +Options, -Code
    write_krakatau_program/2,            % +Code, +Filename
    init_krakatau_target/0,
    compile_tail_recursion_krakatau/3,
    compile_linear_recursion_krakatau/3,
    compile_tree_recursion_krakatau/3,
    compile_multicall_recursion_krakatau/3,
    compile_direct_multicall_krakatau/3,
    compile_mutual_recursion_krakatau/2
]).

:- use_module(library(lists)).
:- use_module('../core/clause_body_analysis').
:- use_module('../core/jvm_bytecode').
:- use_module('../bindings/jvm_asm_bindings', [init_jvm_asm_bindings/0]).
:- use_module('../core/component_registry').

% Component registration
:- initialization((
    catch(
        register_component_type(source, custom_krakatau, custom_krakatau, [
            description("Custom Krakatau JVM Assembly Component")
        ]),
        _,
        true
    )
), now).

% Advanced recursion multifile hooks
:- use_module('../core/advanced/tail_recursion', []).
:- use_module('../core/advanced/linear_recursion', []).
:- use_module('../core/advanced/tree_recursion', []).
:- use_module('../core/advanced/multicall_linear_recursion', []).
:- use_module('../core/advanced/direct_multi_call_recursion', []).
:- use_module('../core/advanced/mutual_recursion', []).

:- multifile tail_recursion:compile_tail_pattern/9.
:- multifile linear_recursion:compile_linear_pattern/8.
:- multifile tree_recursion:compile_tree_pattern/6.
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.
:- multifile mutual_recursion:compile_mutual_pattern/5.

%% init_krakatau_target
init_krakatau_target :-
    init_jvm_asm_bindings.

%% compile_predicate/3 - dispatch alias
compile_predicate(PredArity, Options, Code) :-
    compile_predicate_to_krakatau(PredArity, Options, Code).

%% compile_predicate_to_krakatau(+PredIndicator, +Options, -Code)
compile_predicate_to_krakatau(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'Krakatau target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_krakatau(Pred, Arity, Clauses, Options, Code)
    ).

%% compile_clauses_to_krakatau(+Pred, +Arity, +Clauses, +Options, -Code)
compile_clauses_to_krakatau(Pred, Arity, Clauses, Options, Code) :-
    atom_string(Pred, PredStr),
    (   option(class_name(ClassName), Options)
    ->  true
    ;   format(string(ClassName), 'Prolog_~w', [PredStr])
    ),
    % Try native lowering first
    (   native_krakatau_clause_body(PredStr/Arity, Clauses, MethodBody)
    ->  true
    ;   % Fallback: simple identity
        Arity1 is Arity - 1,
        (   Arity1 > 0
        ->  MethodBody = "    iload_0\n    ireturn"
        ;   MethodBody = "    iconst_0\n    ireturn"
        )
    ),
    Arity1 is Arity - 1,
    krakatau_method_descriptor(Arity1, Descriptor),
    % Estimate stack/locals
    string_codes(MethodBody, BodyCodes),
    findall(1, (member(0'\n, BodyCodes)), NLs),
    length(NLs, LineCount),
    StackLimit is max(10, LineCount),
    LocalsLimit is max(10, Arity1 + 5),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target
; Predicate: ~w/~w

.version 52 0
.class public ~w
.super java/lang/Object

.method public static ~w : ~w
    .limit stack ~w
    .limit locals ~w

~w
.end method
', [PredStr, Arity, ClassName, PredStr, Descriptor, StackLimit, LocalsLimit, MethodBody]).

%% krakatau_method_descriptor(+ParamCount, -Descriptor)
krakatau_method_descriptor(N, Descriptor) :-
    length(Params, N),
    maplist(=(int), Params),
    jvm_method_descriptor(Params, int, Descriptor).

%% native_krakatau_clause_body(+PredStr/Arity, +Clauses, -Code)
%%   Uses shared JVM bytecode infrastructure with numeric slot style.
native_krakatau_clause_body(PredStr/Arity, Clauses, Code) :-
    \+ (member(_-Body, Clauses), Body == true),
    jvm_native_clause_body(PredStr/Arity, Clauses, numeric, format(krakatau), Code).

%% compile_krakatau_class(+ClassName, +Methods, +Options, -Code)
%%   Compile a complete Krakatau class with multiple methods.
%%   Methods: list of method(Name, ParamTypes, RetType, Body)
compile_krakatau_class(ClassName, Methods, _Options, Code) :-
    maplist(krakatau_method_code, Methods, MethodCodes),
    atomic_list_concat(MethodCodes, '\n', MethodSection),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target

.version 52 0
.class public ~w
.super java/lang/Object

~w
', [ClassName, MethodSection]).

krakatau_method_code(method(Name, ParamTypes, RetType, Body), Code) :-
    jvm_method_descriptor(ParamTypes, RetType, Descriptor),
    format(string(Code),
'.method public static ~w : ~w
    .limit stack 10
    .limit locals 10

~w
.end method
', [Name, Descriptor, Body]).

%% ============================================
%% RECURSION PATTERN HOOKS
%% ============================================

%% Tail recursion
tail_recursion:compile_tail_pattern(krakatau, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, _StepOp, _ExitAfterResult, Code) :-
    atom_string(Pred, PredStr),
    compile_tail_recursion_krakatau(Pred/Arity, [], Code).

compile_tail_recursion_krakatau(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_tail_recursion_bytecode(PredStr, Arity, numeric, BodyInstrs),
    jvm_entry_method_bytecode(PredStr, Arity, numeric, EntryInstrs),
    format(string(ClassName), 'Prolog_~w', [PredStr]),
    krakatau_wrap_recursion(ClassName, PredStr, "(II)I", BodyInstrs,
        "(I)I", EntryInstrs, Code).

%% Linear recursion
linear_recursion:compile_linear_pattern(krakatau, PredStr, Arity, _BaseClauses, _RecClauses, _MemoEnabled, _MemoStrategy, Code) :-
    atom_string(Pred, PredStr),
    compile_linear_recursion_krakatau(Pred/Arity, [], Code).

compile_linear_recursion_krakatau(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_linear_recursion_bytecode(PredStr, Arity, numeric, BodyInstrs),
    krakatau_wrap_single(PredStr, "(I)I", BodyInstrs, Code).

%% Tree recursion
tree_recursion:compile_tree_pattern(krakatau, PredStr, Arity, _BaseClauses, _RecClauses, Code) :-
    atom_string(Pred, PredStr),
    compile_tree_recursion_krakatau(Pred/Arity, [], Code).

compile_tree_recursion_krakatau(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_tree_recursion_bytecode(PredStr, Arity, numeric, BodyInstrs),
    krakatau_wrap_single(PredStr, "(I)I", BodyInstrs, Code).

%% Multicall recursion
multicall_linear_recursion:compile_multicall_pattern(krakatau, PredStr, BaseClauses, _RecClauses, _MemoEnabled, Code) :-
    atom_string(Pred, PredStr),
    length(BaseClauses, _),
    compile_multicall_recursion_krakatau(Pred/2, [], Code).

compile_multicall_recursion_krakatau(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_multicall_recursion_bytecode(PredStr, Arity, numeric, BodyInstrs),
    krakatau_wrap_single(PredStr, "(I)I", BodyInstrs, Code).

%% Direct multicall recursion
direct_multi_call_recursion:compile_direct_multicall_pattern(krakatau, PredStr, _BaseClauses, _RecClause, Code) :-
    atom_string(Pred, PredStr),
    compile_direct_multicall_krakatau(Pred/2, [], Code).

compile_direct_multicall_krakatau(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    jvm_direct_multicall_bytecode(PredStr, Arity, numeric, BodyInstrs),
    krakatau_wrap_single(PredStr, "(I)I", BodyInstrs, Code).

%% Mutual recursion
mutual_recursion:compile_mutual_pattern(krakatau, Predicates, _MemoEnabled, _MemoStrategy, Code) :-
    compile_mutual_recursion_krakatau(Predicates, [], Code).

compile_mutual_recursion_krakatau(Predicates, _Options, Code) :-
    (   Predicates = [Pred1|_]
    ->  atom_string(Pred1, P1Str),
        format(string(ClassName), 'Prolog_~w', [P1Str])
    ;   ClassName = "Prolog_mutual"
    ),
    jvm_mutual_recursion_bytecode(Predicates, ClassName, numeric, Methods),
    maplist(krakatau_mutual_method, Methods, MethodCodes),
    atomic_list_concat(MethodCodes, '\n', MethodSection),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target - Mutual Recursion

.version 52 0
.class public ~w
.super java/lang/Object

~w
', [ClassName, MethodSection]).

krakatau_mutual_method(method(Name, Instrs), Code) :-
    maplist(ensure_string, Instrs, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', Body),
    format(string(Code),
'.method public static ~w : (I)I
    .limit stack 10
    .limit locals 10

~w
.end method
', [Name, Body]).

%% ============================================
%% WRAPPING HELPERS
%% ============================================

krakatau_wrap_single(PredStr, Descriptor, Instructions, Code) :-
    maplist(ensure_string, Instructions, StrInstrs),
    atomic_list_concat(StrInstrs, '\n', Body),
    format(string(ClassName), 'Prolog_~w', [PredStr]),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target - Recursion

.version 52 0
.class public ~w
.super java/lang/Object

.method public static ~w : ~w
    .limit stack 10
    .limit locals 10

~w
.end method
', [ClassName, PredStr, Descriptor, Body]).

krakatau_wrap_recursion(ClassName, PredStr, CoreDesc, CoreInstrs, EntryDesc, EntryInstrs, Code) :-
    maplist(ensure_string, CoreInstrs, CoreStrs),
    atomic_list_concat(CoreStrs, '\n', CoreBody),
    maplist(ensure_string, EntryInstrs, EntryStrs),
    atomic_list_concat(EntryStrs, '\n', EntryBody),
    format(string(EntryName), '~w_entry', [PredStr]),
    format(string(Code),
'; Generated by UnifyWeaver Krakatau Target - Tail Recursion

.version 52 0
.class public ~w
.super java/lang/Object

.method public static ~w : ~w
    .limit stack 10
    .limit locals 10

~w
.end method

.method public static ~w : ~w
    .limit stack 10
    .limit locals 10

~w
.end method
', [ClassName, PredStr, CoreDesc, CoreBody, EntryName, EntryDesc, EntryBody]).

ensure_string(S, S) :- string(S), !.
ensure_string(A, S) :- atom_string(A, S).

%% write_krakatau_program(+Code, +Filename)
write_krakatau_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('Krakatau program written to: ~w~n', [Filename]).
