:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% llvm_target.pl - LLVM IR Code Generation Target
%
% Compiles Prolog predicates to LLVM IR for:
% - Guaranteed tail call optimization (musttail)
% - Cross-platform native code generation
% - C ABI compatibility for FFI with Go/Rust/C

:- module(llvm_target, [
    compile_predicate_to_llvm/3,       % +PredIndicator, +Options, -LLVMCode
    compile_facts_to_llvm/3,           % +Pred, +Arity, -LLVMCode
    compile_tail_recursion_llvm/3,     % +Pred/Arity, +Options, -LLVMCode
    compile_linear_recursion_llvm/3,   % +Pred/Arity, +Options, -LLVMCode
    compile_mutual_recursion_llvm/3,   % +Predicates, +Options, -LLVMCode
    compile_transitive_closure_llvm/3, % +Pred/Arity, +Options, -LLVMCode
    write_llvm_program/2,              % +Code, +Filename
    init_llvm_target/0,
    % Phase 2: C ABI Integration
    compile_shared_library_llvm/3,     % +Functions, +Options, -LLVMCode
    generate_c_header/2,               % +Functions, -HeaderCode
    generate_cgo_bindings/2,           % +Functions, -GoCode
    generate_rust_ffi/2,               % +Functions, -RustCode
    build_shared_library/3,            % +LLFile, +OutputName, -Commands
    % Phase 4: WebAssembly Target
    compile_wasm_module/3,             % +Functions, +Options, -LLVMCode
    generate_js_bindings/2,            % +Functions, -JSCode
    generate_ts_bindings/2,            % +Functions, -TSCode
    build_wasm_module/3,               % +LLFile, +OutputName, -Commands
    % Phase 5: WebAssembly String Support
    compile_wasm_string_module/3,      % +Functions, +Options, -LLVMCode
    generate_wasm_string_runtime/1,    % -LLVMCode (alloc, dealloc, memcpy)
    generate_ts_string_bindings/2,     % +Functions, -TSCode
    generate_graph_data_export/2       % +EdgePred, -LLVMCode
]).

:- use_module(library(lists)).
:- use_module(library(option)).
:- use_module('../core/clause_body_analysis').

%% init_llvm_target
init_llvm_target :-
    format('[LLVM Target] Initialized~n', []).

%% ============================================
%% FACTS COMPILATION
%% ============================================

compile_facts_to_llvm(Pred, Arity, Code) :-
    compile_predicate_to_llvm(Pred/Arity, [], Code).

compile_predicate_to_llvm(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'LLVM target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   (   forall(member(_-Body, Clauses), Body == true)
        ->  compile_facts_llvm(Pred, Arity, Clauses, Options, Code)
        ;   compile_rule_llvm(Pred, Arity, Clauses, Options, Code)
        )
    ).

%% compile_facts_llvm(+Pred, +Arity, +Clauses, +Options, -Code)
compile_facts_llvm(Pred, Arity, Clauses, _Options, Code) :-
    atom_string(Pred, PredStr),
    length(Clauses, Count),
    
    % Generate string constants
    findall(StrConst, (
        member(Head-true, Clauses),
        Head =.. [_|Args],
        nth0(Idx, Args, Arg),
        format(string(StrConst), '@str.~w_~w = private constant [~w x i8] c"~w\\00"',
            [PredStr, Idx, length(Arg) + 1, Arg])
    ), StrConsts),
    atomic_list_concat(StrConsts, '\n', StrSection),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target
; Predicate: ~w/~w
; ModuleID = ''~w''
source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; String constants
~w

; Fact count
@~w_count = constant i64 ~w

; Get count function
define i64 @get_~w_count() {
entry:
  ret i64 ~w
}
', [PredStr, Arity, PredStr, PredStr, StrSection, PredStr, Count, PredStr, Count]).

%% compile_rule_llvm(+Pred, +Arity, +Clauses, +Options, -Code)

% Try native clause body lowering first
compile_rule_llvm(Pred, Arity, Clauses, _Options, Code) :-
    native_llvm_clause_body(Pred/Arity, Clauses, FuncBody, StrConstants),
    !,
    atom_string(Pred, PredStr),
    Arity1 is Arity - 1,
    build_llvm_arg_list(Arity1, ArgList),
    build_llvm_param_list(Arity1, ParamList),
    % Calculate error string length: "No matching clause for Pred/Arity\n\0"
    format(string(ErrContent), 'No matching clause for ~w/~w', [PredStr, Arity]),
    string_length(ErrContent, ContentLen),
    ErrLen is ContentLen + 2,  % +1 for \0A, +1 for \00
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Native Clause Lowering
; Predicate: ~w/~w

source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

~w
declare i32 @printf(i8*, ...)
declare void @exit(i32)

@.str.fmt = private constant [5 x i8] c"%ld\\0A\\00"
@.str.err = private constant [~w x i8] c"~w\\0A\\00"

define i64 @~w(~w) {
~w
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  %result = call i64 @~w(~w)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.str.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [PredStr, Arity, PredStr, StrConstants,
    ErrLen, ErrContent,
    PredStr, ArgList, FuncBody,
    PredStr, ParamList]).

% Fallback stub
compile_rule_llvm(Pred, Arity, _Clauses, _Options, Code) :-
    atom_string(Pred, PredStr),
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Rule
; Predicate: ~w/~w
; TODO: Implement rule compilation

define i64 @~w(i64 %%arg0) {
entry:
  ret i64 %%arg0
}
', [PredStr, Arity, PredStr]).

%% ============================================
%% TAIL RECURSION (musttail)
%% ============================================

compile_tail_recursion_llvm(Pred/Arity, Options, Code) :-
    atom_string(Pred, PredStr),
    option(export(Export), Options, false),
    
    % Generate extern wrapper if export requested
    (   Export == true
    ->  format(string(ExternWrapper),
'
; Extern C wrapper for FFI
define dllexport i64 @~w_ext(i64 %%n) {
entry:
  %%result = call i64 @~w(i64 %%n, i64 0)
  ret i64 %%result
}
', [PredStr, PredStr])
    ;   ExternWrapper = ""
    ),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Tail Recursion
; Predicate: ~w/~w
; Guaranteed O(1) stack space via musttail

source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Tail-recursive function with musttail optimization
define i64 @~w(i64 %%n, i64 %%acc) {
entry:
  %%cmp = icmp sle i64 %%n, 0
  br i1 %%cmp, label %%base, label %%recurse

base:
  ret i64 %%acc

recurse:
  %%n1 = sub i64 %%n, 1
  %%acc1 = add i64 %%acc, %%n
  %%result = musttail call i64 @~w(i64 %%n1, i64 %%acc1)
  ret i64 %%result
}

; Entry point wrapper (single argument)
define i64 @~w_entry(i64 %%n) {
entry:
  %%result = call i64 @~w(i64 %%n, i64 0)
  ret i64 %%result
}
~w
; Main function for standalone execution
define i32 @main(i32 %%argc, i8** %%argv) {
entry:
  %%result = call i64 @~w_entry(i64 10)
  %%exitcode = trunc i64 %%result to i32
  ret i32 0
}
', [PredStr, Arity, PredStr, PredStr, PredStr, PredStr, PredStr, ExternWrapper, PredStr]).

%% ============================================
%% LINEAR RECURSION (with memoization)
%% ============================================

compile_linear_recursion_llvm(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Linear Recursion
; Predicate: ~w/~w
; Note: Memoization requires runtime support

source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Memo table (fixed size for simplicity)
@memo = internal global [1000 x i64] zeroinitializer
@memo_valid = internal global [1000 x i1] zeroinitializer

define i64 @~w(i64 %%n) {
entry:
  ; Check bounds
  %%in_bounds = icmp slt i64 %%n, 1000
  br i1 %%in_bounds, label %%check_memo, label %%compute

check_memo:
  %%valid_ptr = getelementptr [1000 x i1], [1000 x i1]* @memo_valid, i64 0, i64 %%n
  %%is_valid = load i1, i1* %%valid_ptr
  br i1 %%is_valid, label %%return_memo, label %%compute

return_memo:
  %%memo_ptr = getelementptr [1000 x i64], [1000 x i64]* @memo, i64 0, i64 %%n
  %%memo_val = load i64, i64* %%memo_ptr
  ret i64 %%memo_val

compute:
  ; Base cases
  %%is_zero = icmp sle i64 %%n, 0
  br i1 %%is_zero, label %%base_zero, label %%check_one

base_zero:
  ret i64 0

check_one:
  %%is_one = icmp eq i64 %%n, 1
  br i1 %%is_one, label %%base_one, label %%recursive

base_one:
  ret i64 1

recursive:
  %%n1 = sub i64 %%n, 1
  %%sub_result = call i64 @~w(i64 %%n1)
  %%result = add i64 %%sub_result, %%n
  
  ; Store in memo
  %%store_ptr = getelementptr [1000 x i64], [1000 x i64]* @memo, i64 0, i64 %%n
  store i64 %%result, i64* %%store_ptr
  %%valid_store = getelementptr [1000 x i1], [1000 x i1]* @memo_valid, i64 0, i64 %%n
  store i1 true, i1* %%valid_store
  
  ret i64 %%result
}

define i32 @main(i32 %%argc, i8** %%argv) {
entry:
  %%result = call i64 @~w(i64 10)
  ret i32 0
}
', [PredStr, Arity, PredStr, PredStr, PredStr, PredStr]).

%% ============================================
%% MUTUAL RECURSION
%% ============================================

compile_mutual_recursion_llvm(Predicates, _Options, Code) :-
    findall(PredStr, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr)
    ), PredStrs),
    atomic_list_concat(PredStrs, '_', GroupName),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Mutual Recursion
; Group: ~w
; is_even / is_odd mutual recursion

source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Forward declaration
declare i1 @is_odd(i64)

define i1 @is_even(i64 %%n) {
entry:
  %%is_zero = icmp eq i64 %%n, 0
  br i1 %%is_zero, label %%base_true, label %%check_positive

base_true:
  ret i1 true

check_positive:
  %%is_positive = icmp sgt i64 %%n, 0
  br i1 %%is_positive, label %%recurse, label %%base_false

recurse:
  %%n1 = sub i64 %%n, 1
  %%result = musttail call i1 @is_odd(i64 %%n1)
  ret i1 %%result

base_false:
  ret i1 false
}

define i1 @is_odd(i64 %%n) {
entry:
  %%is_zero = icmp eq i64 %%n, 0
  br i1 %%is_zero, label %%base_false, label %%check_positive

base_false:
  ret i1 false

check_positive:
  %%is_positive = icmp sgt i64 %%n, 0
  br i1 %%is_positive, label %%recurse, label %%base_false2

recurse:
  %%n1 = sub i64 %%n, 1
  %%result = musttail call i1 @is_even(i64 %%n1)
  ret i1 %%result

base_false2:
  ret i1 false
}

define i32 @main(i32 %%argc, i8** %%argv) {
entry:
  %%even_10 = call i1 @is_even(i64 10)
  %%odd_10 = call i1 @is_odd(i64 10)
  ret i32 0
}
', [GroupName, GroupName]).

%% ============================================
%% TRANSITIVE CLOSURE (BFS worklist)
%% ============================================

%% compile_transitive_closure_llvm(+Pred/Arity, +Options, -Code)
%  Generates LLVM IR for graph reachability using BFS.
%  Useful for: ancestor/descendant queries, graph connectivity.
compile_transitive_closure_llvm(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Transitive Closure
; Predicate: ~w/~w
; Algorithm: BFS worklist for graph reachability

source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Edge representation: adjacency list (simplified as array pairs)
; Edge: [from, to] stored contiguously
@edges = internal global [100 x i64] zeroinitializer
@edge_count = internal global i64 0

; Visited set (bitmap for efficiency)
@visited = internal global [1000 x i1] zeroinitializer

; BFS queue
@queue = internal global [1000 x i64] zeroinitializer
@queue_head = internal global i64 0
@queue_tail = internal global i64 0

; Add an edge to the graph
define void @add_edge(i64 %from, i64 %to) {
entry:
  %count = load i64, i64* @edge_count
  %idx1 = mul i64 %count, 2
  %idx2 = add i64 %idx1, 1
  %ptr1 = getelementptr [100 x i64], [100 x i64]* @edges, i64 0, i64 %idx1
  %ptr2 = getelementptr [100 x i64], [100 x i64]* @edges, i64 0, i64 %idx2
  store i64 %from, i64* %ptr1
  store i64 %to, i64* %ptr2
  %new_count = add i64 %count, 1
  store i64 %new_count, i64* @edge_count
  ret void
}

; Enqueue a node
define void @enqueue(i64 %node) {
entry:
  %tail = load i64, i64* @queue_tail
  %ptr = getelementptr [1000 x i64], [1000 x i64]* @queue, i64 0, i64 %tail
  store i64 %node, i64* %ptr
  %new_tail = add i64 %tail, 1
  store i64 %new_tail, i64* @queue_tail
  ret void
}

; Dequeue a node
define i64 @dequeue() {
entry:
  %head = load i64, i64* @queue_head
  %ptr = getelementptr [1000 x i64], [1000 x i64]* @queue, i64 0, i64 %head
  %node = load i64, i64* %ptr
  %new_head = add i64 %head, 1
  store i64 %new_head, i64* @queue_head
  ret i64 %node
}

; Check if queue is empty
define i1 @queue_empty() {
entry:
  %head = load i64, i64* @queue_head
  %tail = load i64, i64* @queue_tail
  %empty = icmp eq i64 %head, %tail
  ret i1 %empty
}

; Check if node is visited
define i1 @is_visited(i64 %node) {
entry:
  %ptr = getelementptr [1000 x i1], [1000 x i1]* @visited, i64 0, i64 %node
  %val = load i1, i1* %ptr
  ret i1 %val
}

; Mark node as visited
define void @mark_visited(i64 %node) {
entry:
  %ptr = getelementptr [1000 x i1], [1000 x i1]* @visited, i64 0, i64 %node
  store i1 true, i1* %ptr
  ret void
}

; Transitive closure: can we reach target from source?
; reachable(Source, Target) -> bool
define i1 @~w(i64 %source, i64 %target) {
entry:
  ; Reset visited and queue
  store i64 0, i64* @queue_head
  store i64 0, i64* @queue_tail
  
  ; Mark source visited and enqueue
  call void @mark_visited(i64 %source)
  call void @enqueue(i64 %source)
  
  br label %bfs_loop

bfs_loop:
  %empty = call i1 @queue_empty()
  br i1 %empty, label %not_found, label %process_node

process_node:
  %current = call i64 @dequeue()
  
  ; Check if we found target
  %found = icmp eq i64 %current, %target
  br i1 %found, label %found_target, label %explore_neighbors

found_target:
  ret i1 true

explore_neighbors:
  ; Iterate through edges (simplified: check all edges)
  %edge_cnt = load i64, i64* @edge_count
  br label %edge_loop

edge_loop:
  %i = phi i64 [ 0, %explore_neighbors ], [ %i_next, %edge_continue ]
  %done = icmp sge i64 %i, %edge_cnt
  br i1 %done, label %bfs_loop, label %check_edge

check_edge:
  %from_idx = mul i64 %i, 2
  %to_idx = add i64 %from_idx, 1
  %from_ptr = getelementptr [100 x i64], [100 x i64]* @edges, i64 0, i64 %from_idx
  %to_ptr = getelementptr [100 x i64], [100 x i64]* @edges, i64 0, i64 %to_idx
  %from = load i64, i64* %from_ptr
  %to = load i64, i64* %to_ptr
  
  ; Check if this edge starts from current node
  %is_match = icmp eq i64 %from, %current
  br i1 %is_match, label %maybe_enqueue, label %edge_continue

maybe_enqueue:
  ; Check if neighbor not visited
  %already_visited = call i1 @is_visited(i64 %to)
  br i1 %already_visited, label %edge_continue, label %do_enqueue

do_enqueue:
  call void @mark_visited(i64 %to)
  call void @enqueue(i64 %to)
  br label %edge_continue

edge_continue:
  %i_next = add i64 %i, 1
  br label %edge_loop

not_found:
  ret i1 false
}

; Main entry point for testing
define i32 @main(i32 %argc, i8** %argv) {
entry:
  ; Create test graph: 0 -> 1 -> 2 -> 3
  call void @add_edge(i64 0, i64 1)
  call void @add_edge(i64 1, i64 2)
  call void @add_edge(i64 2, i64 3)
  
  ; Test: can we reach 3 from 0?
  %result = call i1 @~w(i64 0, i64 3)
  
  ; Return 0 if reachable (success), 1 otherwise
  %exit = select i1 %result, i32 0, i32 1
  ret i32 %exit
}
', [PredStr, Arity, PredStr, PredStr, PredStr]).

%% ============================================
%% FILE OUTPUT
%% ============================================

write_llvm_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('LLVM IR written to: ~w~n', [Filename]),
    format('Compile with: llc -filetype=obj ~w -o ~w.o && clang ~w.o -o ~w~n', 
        [Filename, Filename, Filename, Filename]).

%% ============================================
%% PHASE 2: C ABI INTEGRATION
%% ============================================

%% compile_shared_library_llvm(+Functions, +Options, -LLVMCode)
%  Compile multiple functions into a shared library with C ABI exports.
%
%  @arg Functions List of func(Name, Arity, Type) where Type is:
%       - tail_recursion, linear_recursion, transitive_closure
%  @arg Options [library_name(Name)]
%  @arg LLVMCode Generated LLVM IR for shared library
compile_shared_library_llvm(Functions, Options, Code) :-
    option(library_name(LibName), Options, 'prolog_math'),
    
    % Generate each function with export wrapper
    findall(FuncCode, (
        member(func(Name, Arity, Type), Functions),
        generate_exported_function(Name, Arity, Type, FuncCode)
    ), FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsSection),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Shared Library
; Library: lib~w.so
; Phase 2: C ABI Integration

source_filename = "~w.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

~w
', [LibName, LibName, FunctionsSection]).

%% generate_exported_function(+Name, +Arity, +Type, -Code)
generate_exported_function(Name, Arity, tail_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w/~w (tail recursion)
define internal i64 @~w_impl(i64 %%n, i64 %%acc) {
entry:
  %%cmp = icmp sle i64 %%n, 0
  br i1 %%cmp, label %%base, label %%recurse
base:
  ret i64 %%acc
recurse:
  %%n1 = sub i64 %%n, 1
  %%acc1 = add i64 %%acc, %%n
  %%result = musttail call i64 @~w_impl(i64 %%n1, i64 %%acc1)
  ret i64 %%result
}

; Exported C ABI wrapper
define dllexport i64 @~w(i64 %%n) {
entry:
  %%result = call i64 @~w_impl(i64 %%n, i64 0)
  ret i64 %%result
}
', [NameStr, Arity, NameStr, NameStr, NameStr, NameStr]).

generate_exported_function(Name, Arity, linear_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w/~w (linear recursion with memo)
@~w_memo = internal global [1000 x i64] zeroinitializer
@~w_valid = internal global [1000 x i1] zeroinitializer

define dllexport i64 @~w(i64 %%n) {
entry:
  %%in_bounds = icmp slt i64 %%n, 1000
  br i1 %%in_bounds, label %%check_memo, label %%compute
check_memo:
  %%vptr = getelementptr [1000 x i1], [1000 x i1]* @~w_valid, i64 0, i64 %%n
  %%valid = load i1, i1* %%vptr
  br i1 %%valid, label %%return_memo, label %%compute
return_memo:
  %%mptr = getelementptr [1000 x i64], [1000 x i64]* @~w_memo, i64 0, i64 %%n
  %%mval = load i64, i64* %%mptr
  ret i64 %%mval
compute:
  %%is_base = icmp sle i64 %%n, 1
  br i1 %%is_base, label %%base, label %%recurse
base:
  ret i64 %%n
recurse:
  %%n1 = sub i64 %%n, 1
  %%sub = call i64 @~w(i64 %%n1)
  %%res = add i64 %%sub, %%n
  %%sptr = getelementptr [1000 x i64], [1000 x i64]* @~w_memo, i64 0, i64 %%n
  store i64 %%res, i64* %%sptr
  %%svptr = getelementptr [1000 x i1], [1000 x i1]* @~w_valid, i64 0, i64 %%n
  store i1 true, i1* %%svptr
  ret i64 %%res
}
', [NameStr, Arity, NameStr, NameStr, NameStr, NameStr, NameStr, NameStr, NameStr, NameStr]).

generate_exported_function(Name, _Arity, factorial, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w (factorial)
define dllexport i64 @~w(i64 %%n) {
entry:
  %%cmp = icmp sle i64 %%n, 1
  br i1 %%cmp, label %%base, label %%recurse
base:
  ret i64 1
recurse:
  %%n1 = sub i64 %%n, 1
  %%sub = call i64 @~w(i64 %%n1)
  %%res = mul i64 %%n, %%sub
  ret i64 %%res
}
', [NameStr, NameStr, NameStr]).

%% generate_c_header(+Functions, -HeaderCode)
%  Generate C header file for the exported functions.
generate_c_header(Functions, HeaderCode) :-
    findall(Decl, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(Decl), 'int64_t ~w(int64_t n);', [NameStr])
    ), Decls),
    atomic_list_concat(Decls, '\n', DeclSection),
    
    format(string(HeaderCode),
'/* Generated by UnifyWeaver LLVM Target - C Header */
#ifndef PROLOG_MATH_H
#define PROLOG_MATH_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

~w

#ifdef __cplusplus
}
#endif

#endif /* PROLOG_MATH_H */
', [DeclSection]).

%% generate_cgo_bindings(+Functions, -GoCode)
%  Generate Go code with cgo bindings.
generate_cgo_bindings(Functions, GoCode) :-
    findall(GoFunc, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(GoFunc),
'// ~w calls the LLVM-compiled ~w function
func ~w(n int64) int64 {
    return int64(C.~w(C.int64_t(n)))
}', [NameStr, NameStr, NameStr, NameStr])
    ), GoFuncs),
    atomic_list_concat(GoFuncs, '\n\n', GoFuncSection),
    
    format(string(GoCode),
'// Generated by UnifyWeaver LLVM Target - Go cgo bindings
package prologmath

/*
#cgo LDFLAGS: -L. -lprolog_math
#include "prolog_math.h"
*/
import "C"

~w
', [GoFuncSection]).

%% generate_rust_ffi(+Functions, -RustCode)
%  Generate Rust FFI bindings.
generate_rust_ffi(Functions, RustCode) :-
    findall(RustDecl, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(RustDecl), '    fn ~w(n: i64) -> i64;', [NameStr])
    ), RustDecls),
    atomic_list_concat(RustDecls, '\n', RustDeclSection),
    
    findall(RustWrapper, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(RustWrapper),
'/// Calls the LLVM-compiled ~w function
pub fn ~w(n: i64) -> i64 {
    unsafe { ffi::~w(n) }
}', [NameStr, NameStr, NameStr])
    ), RustWrappers),
    atomic_list_concat(RustWrappers, '\n\n', RustWrapperSection),
    
    format(string(RustCode),
'// Generated by UnifyWeaver LLVM Target - Rust FFI bindings

mod ffi {
    extern "C" {
~w
    }
}

~w
', [RustDeclSection, RustWrapperSection]).

%% build_shared_library(+LLFile, +OutputName, -Commands)
%  Generate shell commands to build shared library.
build_shared_library(LLFile, OutputName, Commands) :-
    format(string(Commands),
'# Build shared library from LLVM IR
# Step 1: Fix Prolog escaping
sed -i ''s/%%%%/%%/g'' ~w

# Step 2: Compile to object file
llc -filetype=obj -relocation-model=pic ~w -o ~w.o

# Step 3: Create shared library
clang -shared ~w.o -o lib~w.so

# Step 4: Verify exports
nm -D lib~w.so | grep -E ''T (sum|factorial|fib)''

echo "Created: lib~w.so"
echo "Header:  prolog_math.h"
', [LLFile, LLFile, OutputName, OutputName, OutputName, OutputName, OutputName]).

%% ============================================
%% PHASE 4: WEBASSEMBLY TARGET
%% ============================================

%% compile_wasm_module(+Functions, +Options, -LLVMCode)
%  Compile functions to WASM-compatible LLVM IR.
%  Uses wasm32 target triple and i32 types for WASM compatibility.
compile_wasm_module(Functions, Options, Code) :-
    option(module_name(ModName), Options, 'prolog_wasm'),
    
    % Generate each function for WASM
    findall(FuncCode, (
        member(func(Name, Arity, Type), Functions),
        generate_wasm_function(Name, Arity, Type, FuncCode)
    ), FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsSection),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - WebAssembly
; Module: ~w
; Target: wasm32-unknown-unknown

source_filename = "~w.ll"
target datalayout = "e-m:e-p:32:32-i64:64-n32:64-S128"
target triple = "wasm32-unknown-unknown"

~w
', [ModName, ModName, FunctionsSection]).

%% generate_wasm_function(+Name, +Arity, +Type, -Code)
generate_wasm_function(Name, Arity, tail_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w/~w (tail recursion for WASM)
; Note: WASM uses i32 for most values

define i32 @~w_impl(i32 %%n, i32 %%acc) {
entry:
  %%cmp = icmp sle i32 %%n, 0
  br i1 %%cmp, label %%base, label %%recurse
base:
  ret i32 %%acc
recurse:
  %%n1 = sub i32 %%n, 1
  %%acc1 = add i32 %%acc, %%n
  %%result = tail call i32 @~w_impl(i32 %%n1, i32 %%acc1)
  ret i32 %%result
}

; Exported wrapper
define i32 @~w(i32 %%n) {
entry:
  %%result = call i32 @~w_impl(i32 %%n, i32 0)
  ret i32 %%result
}
', [NameStr, Arity, NameStr, NameStr, NameStr, NameStr]).

generate_wasm_function(Name, _Arity, factorial, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w (factorial for WASM)
define i32 @~w(i32 %%n) {
entry:
  %%cmp = icmp sle i32 %%n, 1
  br i1 %%cmp, label %%base, label %%recurse
base:
  ret i32 1
recurse:
  %%n1 = sub i32 %%n, 1
  %%sub = call i32 @~w(i32 %%n1)
  %%res = mul i32 %%n, %%sub
  ret i32 %%res
}
', [NameStr, NameStr, NameStr]).

generate_wasm_function(Name, Arity, linear_recursion, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w/~w (linear recursion for WASM)
; Note: No memoization in basic WASM (no global state)

define i32 @~w(i32 %%n) {
entry:
  %%is_base = icmp sle i32 %%n, 1
  br i1 %%is_base, label %%base, label %%recurse
base:
  ret i32 %%n
recurse:
  %%n1 = sub i32 %%n, 1
  %%sub = call i32 @~w(i32 %%n1)
  %%res = add i32 %%sub, %%n
  ret i32 %%res
}
', [NameStr, Arity, NameStr, NameStr]).

%% generate_js_bindings(+Functions, -JSCode)
%  Generate JavaScript bindings for Node.js and browser.
generate_js_bindings(Functions, JSCode) :-
    findall(JSFunc, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(JSFunc),
'  ~w: (n) => instance.exports.~w(n)', [NameStr, NameStr])
    ), JSFuncs),
    atomic_list_concat(JSFuncs, ',\n', JSFuncSection),
    
    format(string(JSCode),
'// Generated by UnifyWeaver LLVM Target - JavaScript bindings
// Usage: const math = await loadPrologMath();

async function loadPrologMath(wasmPath = ''prolog_wasm.wasm'') {
  const response = await fetch(wasmPath);
  const bytes = await response.arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes);
  
  return {
~w
  };
}

// Node.js version
async function loadPrologMathNode(wasmPath = ''prolog_wasm.wasm'') {
  const fs = require(''fs'');
  const bytes = fs.readFileSync(wasmPath);
  const { instance } = await WebAssembly.instantiate(bytes);
  
  return {
~w
  };
}

module.exports = { loadPrologMath, loadPrologMathNode };
', [JSFuncSection, JSFuncSection]).

%% generate_ts_bindings(+Functions, -TSCode)
%  Generate TypeScript bindings with type definitions.
generate_ts_bindings(Functions, TSCode) :-
    findall(TSDecl, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(TSDecl), '  ~w(n: number): number;', [NameStr])
    ), TSDecls),
    atomic_list_concat(TSDecls, '\n', TSDeclSection),
    
    findall(TSFunc, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(TSFunc),
'  ~w: (n: number): number => instance.exports.~w(n)', [NameStr, NameStr])
    ), TSFuncs),
    atomic_list_concat(TSFuncs, ',\n', TSFuncSection),
    
    format(string(TSCode),
'// Generated by UnifyWeaver LLVM Target - TypeScript bindings

export interface PrologMathExports {
~w
}

export async function loadPrologMath(wasmPath = ''prolog_wasm.wasm''): Promise<PrologMathExports> {
  const response = await fetch(wasmPath);
  const bytes = await response.arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes);
  
  return {
~w
  } as PrologMathExports;
}
', [TSDeclSection, TSFuncSection]).

%% build_wasm_module(+LLFile, +OutputName, -Commands)
%  Generate shell commands to build WASM module.
build_wasm_module(LLFile, OutputName, Commands) :-
    format(string(Commands),
'# Build WebAssembly module from LLVM IR
# Requires: lld package (sudo apt install lld)

# Step 1: Fix Prolog escaping
sed -i ''s/%%%%/%%/g'' ~w

# Step 2: Compile to WASM object
llc -march=wasm32 -filetype=obj ~w -o ~w.o

# Step 3: Link to WASM module
wasm-ld --no-entry --export-all ~w.o -o ~w.wasm

# Step 4: Verify (optional)
wasm-objdump -x ~w.wasm | head -20

echo \"Created: ~w.wasm\"
echo \"Use with: loadPrologMath(''~w.wasm'')\"
', [LLFile, LLFile, OutputName, OutputName, OutputName, OutputName, OutputName, OutputName]).

%% ============================================
%% PHASE 5: WASM STRING SUPPORT
%% ============================================
%%
%% Extends WASM target to handle string types for graph data.
%% Uses linear memory with pointer+length convention.

%% generate_wasm_string_runtime(-Code)
%  Generate LLVM IR for WASM string runtime (alloc, dealloc, memcpy).
generate_wasm_string_runtime(Code) :-
    format(string(Code),
'; WASM String Runtime - Memory Management
; Global: heap pointer for bump allocator
@heap_ptr = global i32 1024  ; Start after stack

; Allocate memory (bump allocator)
define i32 @alloc(i32 %%size) {
entry:
  %%ptr = load i32, i32* @heap_ptr
  %%new_ptr = add i32 %%ptr, %%size
  store i32 %%new_ptr, i32* @heap_ptr
  ret i32 %%ptr
}

; Deallocate (no-op in bump allocator)
define void @dealloc(i32 %%ptr, i32 %%size) {
entry:
  ret void
}

; Memory copy (for string operations)
define void @memcpy_wasm(i32 %%dest, i32 %%src, i32 %%len) {
entry:
  %%cmp = icmp sle i32 %%len, 0
  br i1 %%cmp, label %%done, label %%loop
loop:
  %%idx = phi i32 [0, %%entry], [%%next_idx, %%loop]
  %%src_ptr = add i32 %%src, %%idx
  %%dest_ptr = add i32 %%dest, %%idx
  %%byte_ptr_src = inttoptr i32 %%src_ptr to i8*
  %%byte_ptr_dest = inttoptr i32 %%dest_ptr to i8*
  %%byte = load i8, i8* %%byte_ptr_src
  store i8 %%byte, i8* %%byte_ptr_dest
  %%next_idx = add i32 %%idx, 1
  %%continue = icmp slt i32 %%next_idx, %%len
  br i1 %%continue, label %%loop, label %%done
done:
  ret void
}

; String length (find null terminator)
define i32 @strlen_wasm(i32 %%ptr) {
entry:
  br label %%loop
loop:
  %%idx = phi i32 [0, %%entry], [%%next_idx, %%continue]
  %%char_ptr = add i32 %%ptr, %%idx
  %%byte_ptr = inttoptr i32 %%char_ptr to i8*
  %%byte = load i8, i8* %%byte_ptr
  %%is_null = icmp eq i8 %%byte, 0
  br i1 %%is_null, label %%done, label %%continue
continue:
  %%next_idx = add i32 %%idx, 1
  br label %%loop
done:
  ret i32 %%idx
}
', []).

%% compile_wasm_string_module(+Functions, +Options, -Code)
%  Compile functions with string support to WASM.
compile_wasm_string_module(Functions, Options, Code) :-
    option(module_name(ModName), Options, 'prolog_graph'),
    
    % Generate string runtime
    generate_wasm_string_runtime(RuntimeCode),
    
    % Generate edge storage (for graph data)
    generate_edge_storage(EdgeStorageCode),
    
    % Generate each function
    findall(FuncCode, (
        member(func(Name, Arity, Type), Functions),
        generate_wasm_string_function(Name, Arity, Type, FuncCode)
    ), FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsSection),
    
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - WebAssembly with String Support
; Module: ~w
; Target: wasm32-unknown-unknown

source_filename = \"~w.ll\"
target datalayout = \"e-m:e-p:32:32-i64:64-n32:64-S128\"
target triple = \"wasm32-unknown-unknown\"

; Memory (1 page = 64KB)
@memory = global [65536 x i8] zeroinitializer

~w

~w

~w
', [ModName, ModName, RuntimeCode, EdgeStorageCode, FunctionsSection]).

%% generate_edge_storage(-Code)
%  Generate storage for graph edges.
generate_edge_storage(Code) :-
    format(string(Code),
'; Edge storage for graph data
; Format: [count: i32] [edge0_from_ptr, edge0_from_len, edge0_to_ptr, edge0_to_len] ...
@edge_count = global i32 0
@edges = global [1024 x i32] zeroinitializer  ; Max 256 edges (4 i32 each)

; Add edge (from_ptr, from_len, to_ptr, to_len)
define void @addEdge(i32 %%from_ptr, i32 %%from_len, i32 %%to_ptr, i32 %%to_len) {
entry:
  %%count = load i32, i32* @edge_count
  %%base = mul i32 %%count, 4  ; 4 i32s per edge
  
  ; Store from pointer
  %%idx0 = add i32 %%base, 0
  %%ptr0 = getelementptr [1024 x i32], [1024 x i32]* @edges, i32 0, i32 %%idx0
  store i32 %%from_ptr, i32* %%ptr0
  
  ; Store from length
  %%idx1 = add i32 %%base, 1
  %%ptr1 = getelementptr [1024 x i32], [1024 x i32]* @edges, i32 0, i32 %%idx1
  store i32 %%from_len, i32* %%ptr1
  
  ; Store to pointer
  %%idx2 = add i32 %%base, 2
  %%ptr2 = getelementptr [1024 x i32], [1024 x i32]* @edges, i32 0, i32 %%idx2
  store i32 %%to_ptr, i32* %%ptr2
  
  ; Store to length
  %%idx3 = add i32 %%base, 3
  %%ptr3 = getelementptr [1024 x i32], [1024 x i32]* @edges, i32 0, i32 %%idx3
  store i32 %%to_len, i32* %%ptr3
  
  ; Increment count
  %%new_count = add i32 %%count, 1
  store i32 %%new_count, i32* @edge_count
  ret void
}

; Get edge count
define i32 @getEdgeCount() {
entry:
  %%count = load i32, i32* @edge_count
  ret i32 %%count
}

; Get edge data at index (returns pointer to 4 i32s)
define i32 @getEdge(i32 %%idx) {
entry:
  %%base = mul i32 %%idx, 4
  %%ptr = getelementptr [1024 x i32], [1024 x i32]* @edges, i32 0, i32 %%base
  %%addr = ptrtoint i32* %%ptr to i32
  ret i32 %%addr
}
', []).

%% generate_wasm_string_function(+Name, +Arity, +Type, -Code)
generate_wasm_string_function(Name, Arity, transitive_closure, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w/~w (transitive closure with strings)
; Uses BFS over edge storage

define i32 @~w(i32 %%start_ptr, i32 %%start_len) {
entry:
  ; Placeholder: returns count of reachable nodes
  ; Full implementation requires visited set and queue
  %%count = load i32, i32* @edge_count
  ret i32 %%count
}
', [NameStr, Arity, NameStr]).

generate_wasm_string_function(Name, Arity, graph_query, Code) :-
    atom_string(Name, NameStr),
    format(string(Code),
'; Function: ~w/~w (graph query)
define i32 @~w(i32 %%node_ptr, i32 %%node_len) {
entry:
  %%count = call i32 @getEdgeCount()
  ret i32 %%count
}
', [NameStr, Arity, NameStr]).

%% generate_ts_string_bindings(+Functions, -TSCode)
%  Generate TypeScript bindings with string support.
generate_ts_string_bindings(Functions, TSCode) :-
    findall(TSMethod, (
        member(func(Name, _Arity, _Type), Functions),
        atom_string(Name, NameStr),
        format(string(TSMethod),
'  ~w(node: string): string[] {
    const [ptr, len] = this.encodeString(node);
    const resultCount = this.exports.~w(ptr, len);
    // Collect results (simplified)
    return [];
  }', [NameStr, NameStr])
    ), TSMethods),
    atomic_list_concat(TSMethods, '\n\n', TSMethodsSection),
    
    format(string(TSCode),
'// Generated by UnifyWeaver LLVM Target - TypeScript String Bindings

interface WasmExports extends WebAssembly.Exports {
  memory: WebAssembly.Memory;
  alloc(size: number): number;
  dealloc(ptr: number, size: number): void;
  addEdge(fromPtr: number, fromLen: number, toPtr: number, toLen: number): void;
  getEdgeCount(): number;
  getEdge(idx: number): number;
}

export class GraphWasm {
  private exports: WasmExports;
  private memory: WebAssembly.Memory;
  private encoder = new TextEncoder();
  private decoder = new TextDecoder();

  private constructor(instance: WebAssembly.Instance) {
    this.exports = instance.exports as WasmExports;
    this.memory = this.exports.memory;
  }

  static async load(wasmPath: string): Promise<GraphWasm> {
    const response = await fetch(wasmPath);
    const bytes = await response.arrayBuffer();
    const { instance } = await WebAssembly.instantiate(bytes);
    return new GraphWasm(instance);
  }

  private encodeString(str: string): [number, number] {
    const bytes = this.encoder.encode(str);
    const ptr = this.exports.alloc(bytes.length + 1);
    const view = new Uint8Array(this.memory.buffer, ptr, bytes.length + 1);
    view.set(bytes);
    view[bytes.length] = 0; // Null terminator
    return [ptr, bytes.length];
  }

  private decodeString(ptr: number, len: number): string {
    const view = new Uint8Array(this.memory.buffer, ptr, len);
    return this.decoder.decode(view);
  }

  addEdge(from: string, to: string): void {
    const [fromPtr, fromLen] = this.encodeString(from);
    const [toPtr, toLen] = this.encodeString(to);
    this.exports.addEdge(fromPtr, fromLen, toPtr, toLen);
  }

  getEdgeCount(): number {
    return this.exports.getEdgeCount();
  }

  getEdges(): [string, string][] {
    const count = this.getEdgeCount();
    const edges: [string, string][] = [];
    const memory = new Int32Array(this.memory.buffer);
    
    for (let i = 0; i < count; i++) {
      const basePtr = this.exports.getEdge(i);
      const base = basePtr / 4; // Convert to i32 index
      const fromPtr = memory[base];
      const fromLen = memory[base + 1];
      const toPtr = memory[base + 2];
      const toLen = memory[base + 3];
      
      edges.push([
        this.decodeString(fromPtr, fromLen),
        this.decodeString(toPtr, toLen)
      ]);
    }
    return edges;
  }

~w
}
', [TSMethodsSection]).

%% generate_graph_data_export(+EdgePred, -Code)
%  Generate LLVM IR that exports graph edges from Prolog facts.
generate_graph_data_export(EdgePred, Code) :-
    atom_string(EdgePred, EdgePredStr),
    format(string(Code),
'; Graph data export for ~w/2
; Pre-populate edges from Prolog facts at initialization
', [EdgePredStr]).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_llvm_arg_list(+N, -ArgList) — for function definition
build_llvm_arg_list(0, "") :- !.
build_llvm_arg_list(N, ArgList) :-
    findall(ArgDecl, (
        between(1, N, I),
        format(string(ArgDecl), 'i64 %arg~w', [I])
    ), ArgDecls),
    atomic_list_concat(ArgDecls, ', ', ArgList).

%% build_llvm_param_list(+N, -ParamList) — for call site (values only)
build_llvm_param_list(0, "") :- !.
build_llvm_param_list(N, ParamList) :-
    findall(Param, (
        between(1, N, I),
        format(string(Param), 'i64 ~w', [I])
    ), Params),
    atomic_list_concat(Params, ', ', ParamList).

%% native_llvm_clause_body(+PredSpec, +Clauses, -FuncBody, -StrConstants)
%%
%% Generates LLVM IR basic blocks for if/else chains.
%% Returns i64 for numeric results.
%% StrConstants collects any global string constants needed.

% Single clause
native_llvm_clause_body(PredSpec, [Head-Body], FuncBody, "") :-
    native_llvm_clause(PredSpec, Head, Body, Conditions, ResultExpr),
    !,
    (   Conditions == []
    ->  % Unconditional: just compute and return
        format(string(FuncBody),
'entry:
~w
  ret i64 ~w', [ResultExpr.setup, ResultExpr.value])
    ;   % Conditional: branch to then or error
        llvm_combine_conditions(Conditions, 0, CondCode, CondReg, _RegOut),
        format(string(FuncBody),
'entry:
~w  br i1 ~w, label %then, label %error

then:
~w
  ret i64 ~w

error:
  %err_ptr = getelementptr [0 x i8], [0 x i8]* bitcast ([0 x i8]* @.str.err to [0 x i8]*), i64 0, i64 0
  call void @exit(i32 1)
  unreachable', [CondCode, CondReg, ResultExpr.setup, ResultExpr.value])
    ).

% Multi-clause → chained basic blocks
native_llvm_clause_body(PredSpec, Clauses, FuncBody, "") :-
    Clauses = [_|[_|_]],
    maplist(native_llvm_clause_pair(PredSpec), Clauses, Branches),
    Branches \= [],
    llvm_branches_to_blocks(Branches, 0, FuncBody).

native_llvm_clause_pair(PredSpec, Head-Body, branch(Conditions, ResultExpr)) :-
    native_llvm_clause(PredSpec, Head, Body, Conditions, ResultExpr),
    !.

%% native_llvm_clause(+PredSpec, +Head, +Body, -Conditions, -ResultExpr)
%%
%% ResultExpr is a dict with: value (SSA reg or literal), setup (IR code to compute it)
native_llvm_clause(_PredSpec, Head, Body, Conditions, ResultExpr) :-
    Head =.. [_Pred|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputHeadArgs, [OutputHeadArg], HeadArgs),
        llvm_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ;   OutputHeadArg = _,
        llvm_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ),
    normalize_goals(Body, Goals),
    (   Goals == []
    ->  llvm_resolve_value(VarMap, OutputHeadArg, Value),
        ResultExpr = result{value: Value, setup: "", setup2: ""},
        GoalConditions = []
    ;   %% Try classify_goal_sequence for advanced patterns
        (   classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
            ClassifiedGoals \= [],
            llvm_render_classified(ClassifiedGoals, VarMap, OutputHeadArg, Arity, GoalConditions, ResultExpr)
        ->  true
        ;   %% Fallback to basic split
            (   Arity > 1, nonvar(OutputHeadArg)
            ->  clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
                maplist(llvm_goal_to_condition(VarMap), GuardGoals, GoalConditions),
                (   OutputGoals == []
                ->  llvm_resolve_value(VarMap, OutputHeadArg, Value),
                    ResultExpr = result{value: Value, setup: "", setup2: ""}
                ;   llvm_output_expr(OutputGoals, VarMap, Value, SetupCode),
                    ResultExpr = result{value: Value, setup: SetupCode, setup2: SetupCode}
                )
            ;   clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
                maplist(llvm_goal_to_condition(VarMap), GuardGoals, GoalConditions),
                llvm_output_expr(OutputGoals, VarMap, Value, SetupCode),
                ResultExpr = result{value: Value, setup: SetupCode, setup2: SetupCode}
            )
        )
    ),
    append(HeadConditions, GoalConditions, Conditions).

%% llvm_render_classified(+ClassifiedGoals, +VarMap, +OutputHeadArg, +Arity, -Conditions, -ResultExpr)
%  Render classified goals for LLVM IR output.
llvm_render_classified(ClassifiedGoals, VarMap, OutputHeadArg, Arity, Conditions, ResultExpr) :-
    %% Collect guard conditions
    findall(C, (
        member(guard(G, _), ClassifiedGoals),
        llvm_goal_to_condition(VarMap, G, C)
    ), Conditions),
    %% Find the output value
    (   member(output(Goal, _, _), ClassifiedGoals)
    ->  (   Goal = (_ is ArithExpr)
        ->  llvm_arith_expr(ArithExpr, VarMap, Value, SetupCode),
            ResultExpr = result{value: Value, setup: SetupCode, setup2: SetupCode}
        ;   Goal = (_ = Expr)
        ->  llvm_resolve_value(VarMap, Expr, Value),
            ResultExpr = result{value: Value, setup: "", setup2: ""}
        ;   llvm_resolve_value(VarMap, Goal, Value),
            ResultExpr = result{value: Value, setup: "", setup2: ""}
        )
    ;   member(output_ite(If, Then, Else, _), ClassifiedGoals)
    ->  %% If-then-else: compile both branches
        llvm_goal_to_condition(VarMap, If, IfCond),
        llvm_branch_value_from_goals(Then, VarMap, ThenVal),
        llvm_branch_value_from_goals(Else, VarMap, ElseVal),
        format(string(SetupCode),
'  %%ite_cond = ~w
  br i1 %%ite_cond, label %%ite_then, label %%ite_else
ite_then:
  br label %%ite_end
ite_else:
  br label %%ite_end
ite_end:
  %%ite_result = phi i64 [~w, %%ite_then], [~w, %%ite_else]', [IfCond, ThenVal, ElseVal]),
        ResultExpr = result{value: "%ite_result", setup: SetupCode, setup2: SetupCode}
    ;   Arity > 1, nonvar(OutputHeadArg)
    ->  llvm_resolve_value(VarMap, OutputHeadArg, Value),
        ResultExpr = result{value: Value, setup: "", setup2: ""}
    ;   ResultExpr = result{value: "0", setup: "", setup2: ""}
    ).

%% llvm_branch_value_from_goals(+Branch, +VarMap, -Value)
llvm_branch_value_from_goals(Branch, VarMap, Value) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   LastGoal = (_ = Expr) -> llvm_resolve_value(VarMap, Expr, Value)
    ;   LastGoal = (_ is Expr) -> llvm_arith_expr(Expr, VarMap, Value, _)
    ;   llvm_resolve_value(VarMap, LastGoal, Value)
    ).

%% llvm_head_conditions(+HeadArgs, +Index, +Arity, -Conditions)
llvm_head_conditions([], _, _, []).
llvm_head_conditions([_], _, Arity, []) :- Arity > 1, !.
llvm_head_conditions([HeadArg|Rest], Index, Arity, Conditions) :-
    (   var(HeadArg)
    ->  Conditions = RestConditions
    ;   (   number(HeadArg)
        ->  format(string(ArgName), '%arg~w', [Index]),
            format(string(Cond), 'icmp eq i64 ~w, ~w', [ArgName, HeadArg]),
            Conditions = [Cond|RestConditions]
        ;   Conditions = RestConditions  % skip non-numeric head matches in LLVM
        )
    ),
    NextIndex is Index + 1,
    llvm_head_conditions(Rest, NextIndex, Arity, RestConditions).

%% llvm_goal_to_condition(+VarMap, +Goal, -Condition)
%%   Condition is an LLVM icmp instruction string (without result register)
llvm_goal_to_condition(VarMap, _Module:Goal, Condition) :-
    !, llvm_goal_to_condition(VarMap, Goal, Condition).
llvm_goal_to_condition(VarMap, Goal, Condition) :-
    compound(Goal),
    Goal =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    llvm_value(Left, VarMap, LVal),
    llvm_value(Right, VarMap, RVal),
    llvm_icmp_op(StdOp, IcmpOp),
    format(string(Condition), 'icmp ~w i64 ~w, ~w', [IcmpOp, LVal, RVal]).

%% llvm_output_expr(+Goals, +VarMap, -Value, -SetupCode)
%%   Generates LLVM IR instructions for the output expression
llvm_output_expr([], _VarMap, '0', "") :- !.
llvm_output_expr([Goal], VarMap, Value, SetupCode) :-
    !, llvm_output_expr_last(Goal, VarMap, Value, SetupCode).
llvm_output_expr([_Goal|Rest], VarMap, Value, SetupCode) :-
    llvm_output_expr(Rest, VarMap, Value, SetupCode).

llvm_output_expr_last(_Module:Goal, VarMap, Value, Setup) :-
    !, llvm_output_expr_last(Goal, VarMap, Value, Setup).
llvm_output_expr_last(=(Var, Expr), VarMap, Value, Setup) :-
    var(Var), !,
    llvm_arith_expr(Expr, VarMap, Value, Setup).
llvm_output_expr_last(is(Var, Expr), VarMap, Value, Setup) :-
    var(Var), !,
    llvm_arith_expr(Expr, VarMap, Value, Setup).
llvm_output_expr_last(Goal, VarMap, Value, Setup) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    % Generate LLVM select chain for if-then-else
    llvm_if_then_else_select(If, Then, Else, VarMap, Value, Setup).
llvm_output_expr_last(_Goal, _VarMap, '0', "") :- !.

%% llvm_arith_expr(+Expr, +VarMap, -Value, -SetupCode)
%%   Compile arithmetic expression to LLVM IR instructions
llvm_arith_expr(Var, VarMap, Value, "") :-
    var(Var), !,
    llvm_value(Var, VarMap, Value).
llvm_arith_expr(Expr, VarMap, Value, SetupCode) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    llvm_value(Left, VarMap, LVal),
    llvm_value(Right, VarMap, RVal),
    llvm_arith_op(StdOp, LLVMOp),
    gensym('%r', Value),
    format(string(SetupCode), '  ~w = ~w i64 ~w, ~w', [Value, LLVMOp, LVal, RVal]).
llvm_arith_expr(-Expr, VarMap, Value, SetupCode) :-
    !,
    llvm_value(Expr, VarMap, Inner),
    gensym('%r', Value),
    format(string(SetupCode), '  ~w = sub i64 0, ~w', [Value, Inner]).
llvm_arith_expr(Atom, _VarMap, Value, "") :-
    number(Atom), !,
    format(string(Value), '~w', [Atom]).
llvm_arith_expr(Var, VarMap, Value, "") :-
    var(Var), !,
    llvm_value(Var, VarMap, Value).
llvm_arith_expr(Atom, _VarMap, '0', "") :-
    atom(Atom), !.

%% llvm_if_then_else_select — generate LLVM select chain for if-then-else
%%   (Cond -> ThenGoal ; ElseGoal) → icmp + select
llvm_if_then_else_select(If, Then, Else, VarMap, Value, Setup) :-
    % Compile the condition
    llvm_goal_to_condition(VarMap, If, Cond),
    gensym('%sel_cond', CondReg),
    format(string(CondCode), '  ~w = ~w~n', [CondReg, Cond]),
    % Compile then value
    llvm_then_value(Then, VarMap, ThenVal, ThenSetup),
    % Compile else value (may be nested if-then-else)
    llvm_else_value(Else, VarMap, ElseVal, ElseSetup),
    % Generate select instruction
    gensym('%sel', Value),
    format(string(SelectCode), '  ~w = select i1 ~w, i64 ~w, i64 ~w~n',
           [Value, CondReg, ThenVal, ElseVal]),
    format(string(Setup), '~w~w~w~w', [ThenSetup, ElseSetup, CondCode, SelectCode]).

%% llvm_then_value — extract value from then branch (assignment or arithmetic)
llvm_then_value(=(_, Expr), VarMap, Value, Setup) :-
    !, llvm_arith_expr(Expr, VarMap, Value, Setup).
llvm_then_value(is(_, Expr), VarMap, Value, Setup) :-
    !, llvm_arith_expr(Expr, VarMap, Value, Setup).
llvm_then_value(Goal, VarMap, Value, Setup) :-
    normalize_goals(Goal, Goals),
    (   Goals = [SingleGoal]
    ->  llvm_then_value(SingleGoal, VarMap, Value, Setup)
    ;   llvm_value(Goal, VarMap, Value), Setup = ""
    ).

%% llvm_else_value — extract value from else branch (may be nested if-then-else)
llvm_else_value(Goal, VarMap, Value, Setup) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    llvm_if_then_else_select(If, Then, Else, VarMap, Value, Setup).
llvm_else_value(=(_, Expr), VarMap, Value, Setup) :-
    !, llvm_arith_expr(Expr, VarMap, Value, Setup).
llvm_else_value(is(_, Expr), VarMap, Value, Setup) :-
    !, llvm_arith_expr(Expr, VarMap, Value, Setup).
llvm_else_value(Goal, VarMap, Value, Setup) :-
    normalize_goals(Goal, Goals),
    (   Goals = [SingleGoal]
    ->  llvm_else_value(SingleGoal, VarMap, Value, Setup)
    ;   llvm_value(Goal, VarMap, Value), Setup = ""
    ).

%% llvm_value — resolve a Prolog term to an LLVM IR value
llvm_value(Var, VarMap, Value) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  format(string(Value), '%~w', [Name])
    ;   Value = '0'
    ).
llvm_value(Number, _VarMap, Value) :-
    number(Number), !,
    format(string(Value), '~w', [Number]).
llvm_value(Atom, _VarMap, '0') :-
    atom(Atom), !.
llvm_value(Expr, VarMap, Value) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, _),
    !,
    llvm_value(Left, VarMap, LVal),
    llvm_value(Right, VarMap, RVal),
    % For compound expressions used as values, just use left operand
    % (proper setup code handles the computation)
    Value = LVal.
llvm_value(_, _VarMap, '0').

%% llvm_resolve_value — resolve a head arg or variable to LLVM value
llvm_resolve_value(VarMap, Var, Value) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  format(string(Value), '%~w', [Name])
    ;   Value = '0'
    ).
llvm_resolve_value(_VarMap, Number, Value) :-
    number(Number), !,
    format(string(Value), '~w', [Number]).
llvm_resolve_value(_VarMap, _, '0').

%% llvm_icmp_op — map comparison to LLVM icmp predicate
llvm_icmp_op('>', 'sgt').
llvm_icmp_op('<', 'slt').
llvm_icmp_op('>=', 'sge').
llvm_icmp_op('<=', 'sle').
llvm_icmp_op('==', 'eq').
llvm_icmp_op('!=', 'ne').

%% llvm_arith_op — map arithmetic to LLVM instruction
llvm_arith_op('+', 'add').
llvm_arith_op('-', 'sub').
llvm_arith_op('*', 'mul').
llvm_arith_op('/', 'sdiv').
llvm_arith_op('%', 'srem').

%% llvm_combine_conditions — AND multiple icmp conditions
llvm_combine_conditions([], _, "", 'true', 0) :- !.
llvm_combine_conditions([Cond], RegIn, Code, ResultReg, RegOut) :-
    !,
    RegOut is RegIn + 1,
    format(string(ResultReg), '%cond~w', [RegIn]),
    format(string(Code), '  ~w = ~w~n', [ResultReg, Cond]).
llvm_combine_conditions([Cond|Rest], RegIn, Code, ResultReg, RegOut) :-
    Reg1 is RegIn + 1,
    format(string(ThisReg), '%cond~w', [RegIn]),
    format(string(ThisCode), '  ~w = ~w~n', [ThisReg, Cond]),
    llvm_combine_conditions(Rest, Reg1, RestCode, RestReg, RegMid),
    RegOut is RegMid + 1,
    format(string(ResultReg), '%cond~w', [RegMid]),
    format(string(AndCode), '  ~w = and i1 ~w, ~w~n', [ResultReg, ThisReg, RestReg]),
    format(string(Code), '~w~w~w', [ThisCode, RestCode, AndCode]).

%% llvm_branches_to_blocks — generate chained basic blocks for multi-clause
llvm_branches_to_blocks(Branches, StartReg, Code) :-
    llvm_gen_blocks(Branches, 0, StartReg, Blocks),
    atomic_list_concat(Blocks, '\n', Code).

llvm_gen_blocks([], _BranchIdx, _Reg, [ErrorBlock]) :-
    !,
    format(string(ErrorBlock),
'error:
  %err_ptr = getelementptr [0 x i8], [0 x i8]* bitcast ([0 x i8]* @.str.err to [0 x i8]*), i64 0, i64 0
  call void @exit(i32 1)
  unreachable', []).

llvm_gen_blocks([branch(Conditions, ResultExpr)|Rest], BranchIdx, _Reg, [EntryBlock|RestBlocks]) :-
    NextIdx is BranchIdx + 1,
    format(string(ThenLabel), 'then~w', [BranchIdx]),
    (   Rest == []
    ->  ElseLabel = "error"
    ;   format(string(ElseLabel), 'check~w', [NextIdx])
    ),
    (   BranchIdx == 0
    ->  BlockLabel = "entry"
    ;   format(string(BlockLabel), 'check~w', [BranchIdx])
    ),
    (   Conditions == []
    ->  % Unconditional branch to then
        format(string(EntryBlock),
'~w:
~w
  ret i64 ~w', [BlockLabel, ResultExpr.setup, ResultExpr.value])
    ;   RegBase is BranchIdx * 10,
        llvm_combine_conditions(Conditions, RegBase, CondCode, CondReg, _),
        format(string(EntryBlock),
'~w:
~w  br i1 ~w, label %~w, label %~w

~w:
~w
  ret i64 ~w', [BlockLabel, CondCode, CondReg, ThenLabel, ElseLabel,
                ThenLabel, ResultExpr.setup, ResultExpr.value])
    ),
    llvm_gen_blocks(Rest, NextIdx, 0, RestBlocks).

% ============================================================================
% MULTIFILE HOOKS — Register LLVM renderers for shared compile_expression
% ============================================================================
%
% LLVM IR produces SSA-style instructions. Output goals become
% alloca/store instructions. Guards become icmp + br instructions.

clause_body_analysis:render_output_goal(llvm, Goal, VarMap, Line, VarName, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        llvm_resolve_value(VarMap, Expr, LLVMVal),
        format(string(Line), '  %%~w = add i64 ~w, 0', [VarName, LLVMVal])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        llvm_arith_expr(ArithExpr, VarMap, LLVMVal, SetupCode),
        (   SetupCode \= ""
        ->  format(string(Line), '~w\n  %%~w = add i64 ~w, 0', [SetupCode, VarName, LLVMVal])
        ;   format(string(Line), '  %%~w = add i64 ~w, 0', [VarName, LLVMVal])
        )
    ;   VarName = "_", VarMapOut = VarMap,
        Line = "  ; unsupported output goal"
    ).

clause_body_analysis:render_guard_condition(llvm, Goal, VarMap, CondStr) :-
    llvm_goal_to_condition(VarMap, Goal, CondStr).

clause_body_analysis:render_branch_value(llvm, Branch, VarMap, ExprStr) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   LastGoal = (_ = Expr) -> llvm_resolve_value(VarMap, Expr, ExprStr)
    ;   LastGoal = (_ is Expr) -> llvm_arith_expr(Expr, VarMap, ExprStr, _)
    ;   llvm_resolve_value(VarMap, LastGoal, ExprStr)
    ).

clause_body_analysis:render_ite_block(llvm, Cond, ThenLines, ElseLines, _Indent, _ReturnVars, Lines) :-
    format(string(CmpLine), '  %%cmp_ce = ~w', [Cond]),
    format(string(BrLine), '  br i1 %%cmp_ce, label %%then_ce, label %%else_ce', []),
    (   ElseLines \= []
    ->  append([CmpLine, BrLine, 'then_ce:'|ThenLines], ['  br label %%end_ce', 'else_ce:'|ElseLines], Pre),
        append(Pre, ['  br label %%end_ce', 'end_ce:'], Lines)
    ;   append([CmpLine, BrLine, 'then_ce:'|ThenLines], ['  br label %%end_ce', 'end_ce:'], Lines)
    ).

% ===========================================================================
% Multifile Recursion Patterns for LLVM Target
% ===========================================================================

% ---------------------------------------------------------------------------
% 1. Tail Recursion (compile_tail_pattern/9)
% ---------------------------------------------------------------------------

:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(llvm, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    llvm_step_op(StepOp, LLVMOp),
    (   Arity =:= 3 ->
        % Arity 3: fold over array (simplified: takes single i64 arg, conceptual)
        format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Tail Recursion
; Predicate: ~w/~w (fold with accumulator)

define i64 @~w(i64 %n) {
entry:
  br label %loop

loop:
  %i = phi i64 [0, %entry], [%i_next, %loop]
  %acc = phi i64 [0, %entry], [%acc_next, %loop]
  %done = icmp sge i64 %i, %n
  br i1 %done, label %exit, label %body

body:
  %acc_next = ~w i64 %acc, %i
  %i_next = add i64 %i, 1
  br label %loop

exit:
  ret i64 %acc
}

@.fmt = private unnamed_addr constant [5 x i8] c"%%ld\\0A\\00"
declare i32 @printf(i8*, ...)
declare i64 @atol(i8*)

define i32 @main(i32 %argc, i8** %argv) {
  %ptr = getelementptr i8*, i8** %argv, i64 1
  %arg = load i8*, i8** %ptr
  %n = call i64 @atol(i8* %arg)
  %result = call i64 @~w(i64 %n)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [PredStr, Arity, PredStr, LLVMOp, PredStr])
    ;   Arity =:= 2 ->
        % Arity 2: numeric accumulator countdown
        format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Tail Recursion
; Predicate: ~w/~w (numeric accumulator)

define i64 @~w(i64 %n) {
entry:
  br label %loop

loop:
  %counter = phi i64 [%n, %entry], [%counter_next, %loop]
  %acc = phi i64 [1, %entry], [%acc_next, %loop]
  %done = icmp sle i64 %counter, 0
  br i1 %done, label %exit, label %body

body:
  %acc_next = ~w i64 %acc, %counter
  %counter_next = sub i64 %counter, 1
  br label %loop

exit:
  ret i64 %acc
}

@.fmt = private unnamed_addr constant [5 x i8] c"%%ld\\0A\\00"
declare i32 @printf(i8*, ...)
declare i64 @atol(i8*)

define i32 @main(i32 %argc, i8** %argv) {
  %ptr = getelementptr i8*, i8** %argv, i64 1
  %arg = load i8*, i8** %ptr
  %n = call i64 @atol(i8* %arg)
  %result = call i64 @~w(i64 %n)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [PredStr, Arity, PredStr, LLVMOp, PredStr])
    ;   format(string(Code), '; Unsupported arity ~d for tail recursion~n', [Arity])
    ).

llvm_step_op(add_element, add).
llvm_step_op(add_1, add).
llvm_step_op(mult_element, mul).
llvm_step_op(sub_element, sub).
llvm_step_op(mult, mul).
llvm_step_op(add, add).
llvm_step_op(Op, Op) :- atom(Op).

% ---------------------------------------------------------------------------
% 2. Linear Recursion (compile_linear_pattern/8)
% ---------------------------------------------------------------------------

:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(llvm, PredStr, Arity, BaseClauses, _RecClauses, _MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        llvm_linear_fold(PredStr, BaseClauses, Code)
    ;   format(string(Code), '; Unsupported arity ~d for linear recursion~n', [Arity])
    ).

llvm_linear_fold(PredStr, BaseClauses, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    (   integer(BaseInput) -> BaseIn = BaseInput ; BaseIn = 0 ),
    (   integer(BaseOutput) -> BaseOut = BaseOutput ; BaseOut = 0 ),
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Linear Recursion
; Predicate: ~w/2

define i64 @~w(i64 %n) {
entry:
  %base_check = icmp eq i64 %n, ~w
  br i1 %base_check, label %base, label %recurse

base:
  ret i64 ~w

recurse:
  %n_minus_1 = sub i64 %n, 1
  %sub_result = call i64 @~w(i64 %n_minus_1)
  %result = add i64 %n, %sub_result
  ret i64 %result
}

@.fmt = private unnamed_addr constant [5 x i8] c"%%ld\\0A\\00"
declare i32 @printf(i8*, ...)
declare i64 @atol(i8*)

define i32 @main(i32 %argc, i8** %argv) {
  %ptr = getelementptr i8*, i8** %argv, i64 1
  %arg = load i8*, i8** %ptr
  %n = call i64 @atol(i8* %arg)
  %result = call i64 @~w(i64 %n)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [PredStr, PredStr, BaseIn, BaseOut, PredStr, PredStr]).

% ---------------------------------------------------------------------------
% 3. Tree Recursion (compile_tree_pattern/6)
% ---------------------------------------------------------------------------

:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(llvm, PredStr, _Arity, _BaseClauses, _RecClauses, Code) :-
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Tree Recursion (memoized)
; Predicate: ~w/2

@.memo = internal global [1000 x i64] zeroinitializer
@.memo_set = internal global [1000 x i1] zeroinitializer

define i64 @~w(i64 %n) {
entry:
  %base_check = icmp sle i64 %n, 1
  br i1 %base_check, label %base, label %check_memo

base:
  ret i64 %n

check_memo:
  %memo_ptr = getelementptr [1000 x i1], [1000 x i1]* @.memo_set, i64 0, i64 %n
  %has_memo = load i1, i1* %memo_ptr
  br i1 %has_memo, label %use_memo, label %compute

use_memo:
  %val_ptr = getelementptr [1000 x i64], [1000 x i64]* @.memo, i64 0, i64 %n
  %cached = load i64, i64* %val_ptr
  ret i64 %cached

compute:
  %n1 = sub i64 %n, 1
  %n2 = sub i64 %n, 2
  %r1 = call i64 @~w(i64 %n1)
  %r2 = call i64 @~w(i64 %n2)
  %result = add i64 %r1, %r2
  ; Store in memo
  %store_ptr = getelementptr [1000 x i64], [1000 x i64]* @.memo, i64 0, i64 %n
  store i64 %result, i64* %store_ptr
  %set_ptr = getelementptr [1000 x i1], [1000 x i1]* @.memo_set, i64 0, i64 %n
  store i1 1, i1* %set_ptr
  ret i64 %result
}

@.fmt = private unnamed_addr constant [5 x i8] c"%%ld\\0A\\00"
declare i32 @printf(i8*, ...)
declare i64 @atol(i8*)

define i32 @main(i32 %argc, i8** %argv) {
  %ptr = getelementptr i8*, i8** %argv, i64 1
  %arg = load i8*, i8** %ptr
  %n = call i64 @atol(i8* %arg)
  %result = call i64 @~w(i64 %n)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [PredStr, PredStr, PredStr, PredStr, PredStr]).

% ---------------------------------------------------------------------------
% 4. Mutual Recursion (compile_mutual_pattern/5)
% ---------------------------------------------------------------------------

:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(llvm, Predicates, _MemoEnabled, _MemoStrategy, Code) :-
    llvm_mutual_functions(Predicates, Predicates, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FuncSection),
    Predicates = [FirstPred/_|_],
    atom_string(FirstPred, FirstStr),
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - Mutual Recursion
; Group: ~w

~w

@.fmt = private unnamed_addr constant [5 x i8] c"%%ld\\0A\\00"
declare i32 @printf(i8*, ...)
declare i64 @atol(i8*)

define i32 @main(i32 %argc, i8** %argv) {
  %ptr = getelementptr i8*, i8** %argv, i64 1
  %arg = load i8*, i8** %ptr
  %n = call i64 @atol(i8* %arg)
  %result = call i64 @~w(i64 %n)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [Predicates, FuncSection, FirstStr]).

llvm_mutual_functions([], _, []).
llvm_mutual_functions([Pred/Arity|Rest], AllPreds, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    %% Extract base value
    (   BaseClauses = [clause(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs],
        last(BaseArgs, BaseResult),
        integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    %% Extract base input
    (   BaseClauses = [clause(BaseHead2, _)|_],
        BaseHead2 =.. [_|BaseArgs2],
        BaseArgs2 = [BaseInput|_],
        integer(BaseInput)
    ->  BaseIn = BaseInput
    ;   BaseIn = 0
    ),
    %% Find the other predicate being called
    (   RecClauses = [clause(_, RecBody)|_],
        mutual_recursion:extract_mutual_call(RecBody, AllPreds, Pred, CalledPred, _)
    ->  atom_string(CalledPred, CalledStr)
    ;   CalledStr = PredStr
    ),
    (   Arity =:= 1 ->
        %% Boolean mutual recursion (is_even/is_odd)
        (   BaseVal =:= 1 -> RetBase = 1 ; RetBase = 0 ),
        format(string(FuncCode),
'define i1 @~w(i64 %n) {
entry:
  %base_check = icmp eq i64 %n, ~w
  br i1 %base_check, label %base, label %recurse

base:
  ret i1 ~w

recurse:
  %n_minus_1 = sub i64 %n, 1
  %result = call i1 @~w(i64 %n_minus_1)
  ret i1 %result
}', [PredStr, BaseIn, RetBase, CalledStr])
    ;   %% Value-returning mutual recursion
        format(string(FuncCode),
'define i64 @~w(i64 %n) {
entry:
  %base_check = icmp eq i64 %n, ~w
  br i1 %base_check, label %base, label %recurse

base:
  ret i64 ~w

recurse:
  %n_minus_1 = sub i64 %n, 1
  %sub_result = call i64 @~w(i64 %n_minus_1)
  %result = add i64 %sub_result, 1
  ret i64 %result
}', [PredStr, BaseIn, BaseVal, CalledStr])
    ),
    llvm_mutual_functions(Rest, AllPreds, RestCodes).

% ---------------------------------------------------------------------------
% 5. General Recursion with Visited Set (compile_general_recursive_pattern/6)
% ---------------------------------------------------------------------------

:- multifile advanced_recursive_compiler:compile_general_recursive_pattern/6.

advanced_recursive_compiler:compile_general_recursive_pattern(llvm, PredStr, _Arity, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs],
        last(BaseArgs, BaseResult),
        integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    format(string(Code),
'; Generated by UnifyWeaver LLVM Target - General Recursion with Visited Set
; Predicate: ~w (uses global visited array for cycle detection)

@.visited = internal global [1000 x i64] zeroinitializer
@.visited_count = internal global i64 0

define i1 @is_visited(i64 %val) {
entry:
  %count = load i64, i64* @.visited_count
  br label %loop

loop:
  %i = phi i64 [0, %entry], [%i_next, %not_found]
  %done = icmp sge i64 %i, %count
  br i1 %done, label %false_exit, label %check

check:
  %ptr = getelementptr [1000 x i64], [1000 x i64]* @.visited, i64 0, i64 %i
  %elem = load i64, i64* %ptr
  %eq = icmp eq i64 %elem, %val
  br i1 %eq, label %true_exit, label %not_found

not_found:
  %i_next = add i64 %i, 1
  br label %loop

true_exit:
  ret i1 1

false_exit:
  ret i1 0
}

define void @add_visited(i64 %val) {
  %count = load i64, i64* @.visited_count
  %ptr = getelementptr [1000 x i64], [1000 x i64]* @.visited, i64 0, i64 %count
  store i64 %val, i64* %ptr
  %new_count = add i64 %count, 1
  store i64 %new_count, i64* @.visited_count
  ret void
}

define i64 @~w(i64 %n) {
entry:
  %seen = call i1 @is_visited(i64 %n)
  br i1 %seen, label %already_visited, label %process

already_visited:
  ret i64 ~w

process:
  call void @add_visited(i64 %n)
  ; Base case and recursive case would be expanded from clause body
  ret i64 ~w
}

@.fmt = private unnamed_addr constant [5 x i8] c"%%ld\\0A\\00"
declare i32 @printf(i8*, ...)
declare i64 @atol(i8*)

define i32 @main(i32 %argc, i8** %argv) {
  %ptr = getelementptr i8*, i8** %argv, i64 1
  %arg = load i8*, i8** %ptr
  %n = call i64 @atol(i8* %arg)
  %result = call i64 @~w(i64 %n)
  %fmt = getelementptr [5 x i8], [5 x i8]* @.fmt, i64 0, i64 0
  call i32 (i8*, ...) @printf(i8* %fmt, i64 %result)
  ret i32 0
}
', [PredStr, PredStr, BaseVal, BaseVal, PredStr]).
