% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (s243a)
%
% This file is part of UnifyWeaver.
% Licensed under either MIT or Apache-2.0 at your option.

:- encoding(utf8).
% python_nuitka_target.pl - Nuitka Target for Python
%
% Generates Python code optimized for Nuitka compilation to native executables.
% Nuitka compiles entire Python programs to C for deployment.
%
% License: Apache 2.0 (Nuitka itself)
%
% Features:
% - Full Python compatibility (compiles any Python code)
% - Standalone executables
% - --onefile for single file distribution
% - Plugin system for frameworks (Flask, Qt, etc.)
%
% Use cases:
% - Web application deployment
% - Desktop application distribution
% - Hiding source code
%
% Example:
%   ?- compile_nuitka_module(my_app, [standalone(true)], Code).
%   ?- generate_nuitka_build_script(my_app, [onefile(true)], Script).

:- module(python_nuitka_target, [
    compile_nuitka_module/3,
    compile_nuitka_webapp/3,
    generate_nuitka_build_script/3,
    generate_nuitka_config/2,
    init_nuitka_target/0
]).

:- use_module(python_target).
:- use_module('../core/binding_registry').
:- use_module('../core/component_registry').
:- use_module('python_runtime/custom_nuitka', []).

%% init_nuitka_target
%  Initialize Nuitka target
init_nuitka_target :-
    init_python_target.

%% compile_nuitka_module(+ModuleName, +Options, -Code)
%  Compile predicates to a Nuitka-optimized Python module
%  Since Nuitka compiles standard Python, this mainly adds
%  optimization hints and proper structure
%  Options:
%    - predicates(List): List of Pred/Arity to compile
%    - main(true/false): Add __main__ block
compile_nuitka_module(ModuleName, Options, Code) :-
    % Nuitka-specific header with optimization hints
    format(string(Header),
"#!/usr/bin/env python3
# -*- coding: utf-8 -*-
\"\"\"
Module: ~w
Generated by UnifyWeaver for Nuitka compilation.

Compile with:
    nuitka --module ~w.py
    nuitka --standalone ~w.py
    nuitka --onefile ~w.py
\"\"\"

# Type hints help Nuitka optimize
from typing import List, Dict, Optional, Any, Tuple
import sys

", [ModuleName, ModuleName, ModuleName, ModuleName]),

    % Compile predicates if specified
    (   member(predicates(Preds), Options)
    ->  maplist(compile_pred_for_nuitka, Preds, PredCodes),
        atomic_list_concat(PredCodes, '\n\n', PredsCode)
    ;   PredsCode = "# Add your functions here\npass"
    ),

    % Add main block if requested
    (   member(main(true), Options)
    ->  format(string(MainBlock),
"
if __name__ == '__main__':
    # Entry point for standalone execution
    main()
", [])
    ;   MainBlock = ""
    ),

    format(string(Code), "~w~w~w", [Header, PredsCode, MainBlock]).

compile_pred_for_nuitka(Pred/Arity, Code) :-
    compile_predicate_to_python(Pred/Arity, [], Code).

%% compile_nuitka_webapp(+AppName, +Options, -Code)
%  Compile a web application for Nuitka
%  Options:
%    - framework(flask/fastapi/django): Web framework
%    - routes(List): Route definitions
compile_nuitka_webapp(AppName, Options, Code) :-
    (   member(framework(Framework), Options)
    ->  true
    ;   Framework = flask
    ),

    webapp_header(Framework, Header),
    webapp_routes(Framework, Options, RoutesCode),

    format(string(Code),
"~w
# Application: ~w
# Framework: ~w

~w

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
", [Header, AppName, Framework, RoutesCode]).

%% webapp_header(+Framework, -Header)
webapp_header(flask, Header) :-
    Header = "from flask import Flask, request, jsonify
from typing import Dict, Any

app = Flask(__name__)
".
webapp_header(fastapi, Header) :-
    Header = "from fastapi import FastAPI
from pydantic import BaseModel
from typing import Dict, Any

app = FastAPI()
".

%% webapp_routes(+Framework, +Options, -Code)
webapp_routes(Framework, Options, Code) :-
    (   member(routes(Routes), Options)
    ->  maplist(generate_route(Framework), Routes, RouteCodes),
        atomic_list_concat(RouteCodes, '\n\n', Code)
    ;   generate_default_route(Framework, Code)
    ).

generate_route(flask, route(Path, Method, Handler), Code) :-
    format(string(Code),
"@app.route('~w', methods=['~w'])
def ~w():
    return jsonify({'status': 'ok'})
", [Path, Method, Handler]).

generate_route(fastapi, route(Path, Method, Handler), Code) :-
    format(string(Code),
"@app.~w('~w')
async def ~w():
    return {'status': 'ok'}
", [Method, Path, Handler]).

generate_default_route(flask, Code) :-
    Code = "@app.route('/')
def index():
    return jsonify({'message': 'Hello from Nuitka-compiled Flask!'})
".
generate_default_route(fastapi, Code) :-
    Code = "@app.get('/')
async def index():
    return {'message': 'Hello from Nuitka-compiled FastAPI!'}
".

%% generate_nuitka_build_script(+ModuleName, +Options, -Script)
%  Generate a build script for Nuitka compilation
%  Options:
%    - standalone(true/false): Create standalone executable
%    - onefile(true/false): Single file output
%    - windows(true/false): Windows-specific options
%    - plugins(List): Nuitka plugins to enable
generate_nuitka_build_script(ModuleName, Options, Script) :-
    % Base command
    BaseCmd = "python -m nuitka",

    % Build options list
    findall(Opt, (
        (member(standalone(true), Options) -> Opt = "--standalone" ; fail)
    ;   (member(onefile(true), Options) -> Opt = "--onefile" ; fail)
    ;   (member(follow_imports(true), Options) -> Opt = "--follow-imports" ; fail)
    ;   (member(lto(true), Options) -> Opt = "--lto=yes" ; fail)
    ;   (member(remove_output(true), Options) -> Opt = "--remove-output" ; fail)
    ), OptList),

    % Add plugins
    (   member(plugins(Plugins), Options)
    ->  maplist(format_plugin, Plugins, PluginOpts),
        append(OptList, PluginOpts, AllOpts)
    ;   AllOpts = OptList
    ),

    % Windows-specific
    (   member(windows(true), Options)
    ->  append(AllOpts, ["--windows-disable-console"], FinalOpts)
    ;   FinalOpts = AllOpts
    ),

    atomic_list_concat(FinalOpts, ' ', OptsStr),
    format(string(Script),
"#!/bin/bash
# Nuitka build script for ~w
# Generated by UnifyWeaver

set -e

echo \"Building ~w with Nuitka...\"

~w ~w ~w.py

echo \"Build complete!\"
echo \"Output in ~w.dist/ or ~w.bin\"
", [ModuleName, ModuleName, BaseCmd, OptsStr, ModuleName, ModuleName, ModuleName]).

format_plugin(Plugin, Opt) :-
    format(atom(Opt), "--enable-plugin=~w", [Plugin]).

%% generate_nuitka_config(+Options, -Config)
%  Generate nuitka.yaml configuration file
generate_nuitka_config(Options, Config) :-
    (   member(product_name(Name), Options)
    ->  true
    ;   Name = "UnifyWeaver App"
    ),
    (   member(product_version(Version), Options)
    ->  true
    ;   Version = "1.0.0"
    ),

    format(string(Config),
"# Nuitka configuration
# Generated by UnifyWeaver

nuitka-project:
  product-name: ~w
  product-version: ~w

nuitka-project-options:
  - \"--standalone\"
  - \"--follow-imports\"

nuitka-project-when:
  - when: Linux
    options:
      - \"--linux-icon=icon.png\"
  - when: Windows
    options:
      - \"--windows-icon-from-ico=icon.ico\"
      - \"--windows-disable-console\"
  - when: Darwin
    options:
      - \"--macos-app-icon=icon.icns\"
", [Name, Version]).

%% test_nuitka_target/0
%  Test Nuitka target code generation
test_nuitka_target :-
    format('Testing Nuitka target...~n'),

    % Test module generation
    compile_nuitka_module(test_app, [main(true)], ModCode),
    format('Module code:~n~w~n', [ModCode]),

    % Test build script
    generate_nuitka_build_script(test_app, [standalone(true), onefile(true)], Script),
    format('Build script:~n~w~n', [Script]),

    format('Nuitka target tests passed.~n').
