% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (s243a)
%
% scala_target.pl - Scala Target for UnifyWeaver
% Generates Scala programs for record/field processing
% Supports streaming with LazyList, pattern matching, and case classes

:- encoding(utf8).

:- module(scala_target, [
    compile_predicate_to_scala/3,     % +Predicate, +Options, -ScalaCode
    compile_scala_pipeline/3,         % +Predicates, +Options, -ScalaCode
    compile_facts_to_scala/3,         % +Pred, +Arity, -ScalaCode  -- NEW
    generate_sbt_build/2,             % +Options, -BuildFile
    write_scala_program/2,            % +ScalaCode, +FilePath
    init_scala_target/0,              % Initialize Scala target
    test_scala_pipeline_mode/0        % Test pipeline mode
]).

:- use_module(library(lists)).

% Binding system integration
:- use_module('../core/binding_registry').

% Shared clause body analysis for native lowering
:- use_module('../core/clause_body_analysis').

% Track required imports
:- dynamic required_scala_import/1.

%% init_scala_target
init_scala_target :-
    retractall(required_scala_import(_)).

%% clear_scala_imports
clear_scala_imports :-
    retractall(required_scala_import(_)).

%% collect_scala_import(+Import)
collect_scala_import(Import) :-
    (   required_scala_import(Import)
    ->  true
    ;   assertz(required_scala_import(Import))
    ).

%% get_scala_imports(-Imports)
get_scala_imports(Imports) :-
    findall(I, required_scala_import(I), Imports).

%% format_scala_imports(+Imports, -FormattedStr)
format_scala_imports([], "").
format_scala_imports(Imports, FormattedStr) :-
    Imports \= [],
    sort(Imports, UniqueImports),
    findall(Formatted,
        (   member(Import, UniqueImports),
            format(string(Formatted), "import ~w~n", [Import])
        ),
        FormattedList),
    atomic_list_concat(FormattedList, '', FormattedStr).

%% ============================================
%% PUBLIC API
%% ============================================

%% compile_predicate_to_scala(+Predicate, +Options, -ScalaCode)
compile_predicate_to_scala(PredIndicator, Options, ScalaCode) :-
    (   PredIndicator = _Module:Pred/Arity
    ->  true
    ;   PredIndicator = Pred/Arity
    ),
    format('=== Compiling ~w/~w to Scala ===~n', [Pred, Arity]),

    clear_scala_imports,

    % Check mode
    (   option(generator_mode(true), Options)
    ->  format('  Mode: Generator (LazyList/Iterator)~n'),
        compile_generator_mode_scala(Pred, Arity, Options, ScalaCode)
    ;   option(pipeline_input(true), Options)
    ->  format('  Mode: Pipeline (streaming)~n'),
        compile_pipeline_mode_scala(Pred, Arity, Options, ScalaCode)
    ;   format('  Mode: Simple predicate~n'),
        compile_simple_mode_scala(Pred, Arity, Options, ScalaCode)
    ).

%% ============================================
%% SIMPLE MODE
%% ============================================

% Try native clause body lowering first
compile_simple_mode_scala(Pred, Arity, _Options, ScalaCode) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    Clauses \= [],
    \+ (member(_-Body, Clauses), Body == true),
    native_scala_clause_body(Pred/Arity, Clauses, FuncBody),
    !,
    atom_string(Pred, PredStr),
    Arity1 is Arity - 1,
    build_scala_arg_list(Arity1, ArgList),
    format(string(ScalaCode),
'// Generated by UnifyWeaver Scala Target - Native Clause Lowering
// Predicate: ~w/~w

object Main {
  def ~w(~w): String = {
~w
  }

  def main(args: Array[String]): Unit = {
    if (args.nonEmpty) println(~w(args(0).toLong))
  }
}
', [PredStr, Arity, PredStr, ArgList, FuncBody, PredStr]).

% Fallback stub
compile_simple_mode_scala(Pred, Arity, _Options, ScalaCode) :-
    format(string(ScalaCode),
"// Generated by UnifyWeaver Scala Target
// Predicate: ~w/~w

package generated

object ~wApp {
  def ~w(args: Any*): Option[Any] = {
    // TODO: Implement ~w logic
    None
  }

  def main(args: Array[String]): Unit = {
    // TODO: Add main logic
  }
}
", [Pred, Arity, Pred, Pred, Pred]).

%% ============================================
%% COMPILE FACTS TO SCALA
%% ============================================

compile_facts_to_scala(Pred, Arity, ScalaCode) :-
    atom_string(Pred, PredStr),
    upcase_atom_first(Pred, PredCap),
    functor(Head, Pred, Arity),
    
    findall(Args, (clause(Head, true), Head =.. [_|Args]), AllFacts),
    
    (   AllFacts == []
    ->  FactEntries = "    // No facts defined"
    ;   findall(Entry, (
            member(Args, AllFacts),
            format_scala_fact_entry(Args, Entry)
        ), Entries),
        atomic_list_concat(Entries, ',\n', FactEntries)
    ),
    
    format(string(ScalaCode),
'// Generated by UnifyWeaver Scala Target - Facts Export
// Predicate: ~w/~w

package generated

object ~w {
  val facts: List[Array[String]] = List(
~w
  )

  def stream: LazyList[Array[String]] = LazyList.from(facts)

  def getAll: List[Array[String]] = facts

  def contains(args: String*): Boolean =
    facts.exists(_.sameElements(args))

  def main(args: Array[String]): Unit =
    facts.foreach(f => println(f.mkString(":")))
}
', [PredStr, Arity, PredCap, FactEntries]).

format_scala_fact_entry(Args, Entry) :-
    findall(Formatted, (
        member(Arg, Args),
        format(string(Formatted), '"~w"', [Arg])
    ), FormattedArgs),
    atomic_list_concat(FormattedArgs, ', ', ArgsStr),
    format(string(Entry), '    Array(~w)', [ArgsStr]).

%% ============================================
%% GENERATOR MODE (Scala's LazyList/Iterator)
%% ============================================

compile_generator_mode_scala(Pred, Arity, Options, ScalaCode) :-
    collect_scala_import('scala.util.parsing.json.JSON'),
    collect_scala_import('scala.io.Source'),
    collect_scala_import('scala.collection.immutable.LazyList'),
    
    option(package(Package), Options, generated),
    
    % Gather clauses
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    % Generate generator body
    (   Clauses == []
    ->  GeneratorBody = "      // No clauses found - yield input unchanged\n      LazyList(record)"
    ;   generate_generator_body_scala(Clauses, GeneratorBody)
    ),
    
    get_scala_imports(ImportList),
    format_scala_imports(ImportList, ImportsStr),
    
    upcase_atom_first(Pred, CapPred),
    
    format(string(ScalaCode),
"// Generated by UnifyWeaver Scala Target - Generator Mode
// Predicate: ~w/~w
// Uses Scala's LazyList for lazy evaluation

package ~w

~w

/**
 * Generator for ~w predicate.
 * Uses LazyList for lazy, memory-efficient processing.
 */
object ~wGenerator {

  type Record = Map[String, Any]

  /**
   * Process a single record, yielding zero or more results.
   * @param record Input record
   * @return LazyList of output records
   */
  def process(record: Record): LazyList[Record] = {
~w
  }

  /**
   * Process all records, flattening results.
   */
  def processAll(records: LazyList[Record]): LazyList[Record] =
    records.flatMap(process)

  /**
   * Run the generator pipeline.
   */
  def runPipeline(): Unit = {
    val lines = Source.stdin.getLines()
    
    val inputRecords: LazyList[Record] = LazyList.from(
      lines.filter(_.nonEmpty).flatMap { line =>
        parseJson(line)
      }
    )
    
    processAll(inputRecords).foreach { result =>
      println(toJson(result))
    }
  }

  private def parseJson(s: String): Option[Record] = {
    JSON.parseFull(s).collect { case m: Map[String, Any] @unchecked => m }
  }

  private def toJson(m: Record): String = {
    m.map { case (k, v) => s\"\"\"\"$k\":${valueToJson(v)}\"\"\" }.mkString(\"{\", \",\", \"}\")
  }

  private def valueToJson(v: Any): String = v match {
    case s: String => s\"\"\"\"$s\"\"\"\"
    case n: Number => n.toString
    case b: Boolean => b.toString
    case null => \"null\"
    case m: Map[_, _] => toJson(m.asInstanceOf[Record])
    case _ => s\"\"\"\"${v.toString}\"\"\"\"
  }

  def main(args: Array[String]): Unit = runPipeline()
}
", [Pred, Arity, Package, ImportsStr, Pred, CapPred, GeneratorBody]).

%% generate_generator_body_scala(+Clauses, -Code)
generate_generator_body_scala(Clauses, Code) :-
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_scala(Name, Clauses)
    ->  partition(is_recursive_clause_scala(Name), Clauses, RecClauses, BaseClauses),
        compile_generator_recursive_scala(Name, BaseClauses, RecClauses, Code)
    ;   findall(ClauseCode, 
            (member((H, B), Clauses), translate_generator_clause_scala(H, B, ClauseCode)),
            ClauseCodes),
        atomic_list_concat(ClauseCodes, '\n', Code)
    ).

translate_generator_clause_scala(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    generate_input_extraction_scala(Args, InputCode),
    (   Body == true
    ->  BodyCode = "      // Fact - unconditional"
    ;   translate_generator_body_scala(Body, BodyCode)
    ),
    format(string(Code), "~w\n~w\n      LazyList(record)", [InputCode, BodyCode]).

translate_generator_body_scala((Goal, Rest), Code) :-
    !,
    translate_generator_goal_scala(Goal, Code1),
    translate_generator_body_scala(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_generator_body_scala(Goal, Code) :-
    translate_generator_goal_scala(Goal, Code).

translate_generator_goal_scala(>(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "      if (!(~w > ~w)) return LazyList.empty", [SX, SY]).

translate_generator_goal_scala(<(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "      if (!(~w < ~w)) return LazyList.empty", [SX, SY]).

translate_generator_goal_scala(=:=(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "      if (~w != ~w) return LazyList.empty", [SX, SY]).

translate_generator_goal_scala(true, "      // true") :- !.

translate_generator_goal_scala(Goal, Code) :-
    format(string(Code), "      // TODO: ~w", [Goal]).

compile_generator_recursive_scala(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_scala(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),
    
    format(string(Code),
"      // Recursive generator: ~w
      def iterate(current: Record, depth: Int): LazyList[Record] = {
        if (depth > 10000) {
          System.err.println(s\"Warning: Max depth exceeded for ~w\")
          LazyList.empty
        } else if (~w) {
          LazyList(current)
        } else {
          current #:: iterate(current, depth + 1)
        }
      }
      iterate(record, 0)", [Name, Name, BaseCondition]).

%% ============================================
%% PIPELINE MODE
%% ============================================

compile_pipeline_mode_scala(Pred, Arity, Options, ScalaCode) :-
    collect_scala_import('scala.util.parsing.json.JSON'),
    collect_scala_import('scala.io.Source'),
    
    option(package(Package), Options, generated),
    
    functor(Head, Pred, Arity),
    findall((Head, Body), clause(Head, Body), Clauses),
    
    (   Clauses == []
    ->  ProcessCode = "    // No clauses found - pass through\n    Some(record)"
    ;   generate_pipeline_process_scala(Clauses, ProcessCode)
    ),
    
    get_scala_imports(ImportList),
    format_scala_imports(ImportList, ImportsStr),
    
    upcase_atom_first(Pred, CapPred),
    
    format(string(ScalaCode),
"// Generated by UnifyWeaver Scala Target - Pipeline Mode
// Predicate: ~w/~w

package ~w

~w

/**
 * Pipeline processor for ~w predicate.
 */
object ~wPipeline {

  type Record = Map[String, Any]

  /**
   * Process a single input record.
   * @return Some(record) to keep, None to filter out
   */
  def process(record: Record): Option[Record] = {
~w
  }

  def runPipeline(): Unit = {
    Source.stdin.getLines()
      .filter(_.nonEmpty)
      .flatMap { line =>
        parseJson(line).flatMap(process)
      }
      .foreach { result =>
        println(toJson(result))
      }
  }

  private def parseJson(s: String): Option[Record] = {
    JSON.parseFull(s).collect { case m: Map[String, Any] @unchecked => m }
  }

  private def toJson(m: Record): String = {
    m.map { case (k, v) => s\"\"\"\"$k\":${valueToJson(v)}\"\"\" }.mkString(\"{\", \",\", \"}\")
  }

  private def valueToJson(v: Any): String = v match {
    case s: String => s\"\"\"\"$s\"\"\"\"
    case n: Number => n.toString
    case b: Boolean => b.toString
    case null => \"null\"
    case m: Map[_, _] => toJson(m.asInstanceOf[Record])
    case _ => s\"\"\"\"${v.toString}\"\"\"\"
  }

  def main(args: Array[String]): Unit = runPipeline()
}
", [Pred, Arity, Package, ImportsStr, Pred, CapPred, ProcessCode]).

%% upcase_atom_first(+Atom, -CapAtom)
upcase_atom_first(Atom, CapAtom) :-
    atom_codes(Atom, [H|T]),
    (   H >= 97, H =< 122
    ->  H2 is H - 32,
        atom_codes(CapAtom, [H2|T])
    ;   CapAtom = Atom
    ).

%% generate_pipeline_process_scala(+Clauses, -Code)
generate_pipeline_process_scala([], "    Some(record)").
generate_pipeline_process_scala(Clauses, Code) :-
    Clauses \= [],
    Clauses = [(Head, _)|_],
    functor(Head, Name, _),
    (   is_recursive_predicate_scala(Name, Clauses)
    ->  partition(is_recursive_clause_scala(Name), Clauses, RecClauses, BaseClauses),
        compile_tail_recursive_scala(Name, BaseClauses, RecClauses, Code)
    ;   findall(ClauseCode, 
            (member((H, B), Clauses), translate_clause_scala(H, B, ClauseCode)),
            ClauseCodes),
        atomic_list_concat(ClauseCodes, '\n', Code)
    ).

%% ============================================
%% RECURSION DETECTION
%% ============================================

is_recursive_predicate_scala(Name, Clauses) :-
    member((_, Body), Clauses),
    contains_recursive_call_scala(Body, Name).

is_recursive_clause_scala(Name, (_, Body)) :-
    contains_recursive_call_scala(Body, Name).

contains_recursive_call_scala(Body, Name) :-
    extract_goal_scala(Body, Goal),
    functor(Goal, Name, _),
    !.

extract_goal_scala(Goal, Goal) :-
    compound(Goal),
    \+ Goal = (_,_),
    \+ Goal = (_;_).
extract_goal_scala((A, _), Goal) :- extract_goal_scala(A, Goal).
extract_goal_scala((_, B), Goal) :- extract_goal_scala(B, Goal).

%% ============================================
%% TAIL RECURSION (Scala's @tailrec)
%% ============================================

compile_tail_recursive_scala(Name, BaseClauses, _RecClauses, Code) :-
    (   BaseClauses = [(BaseHead, _)|_]
    ->  generate_base_condition_scala(BaseHead, BaseCondition)
    ;   BaseCondition = "false"
    ),
    
    format(string(Code),
"    // Tail-recursive predicate: ~w
    import scala.annotation.tailrec
    
    @tailrec
    def iterate(current: Record, depth: Int): Option[Record] = {
      if (depth > 10000) {
        System.err.println(s\"Warning: Max depth for ~w\")
        Some(current)
      } else if (~w) {
        Some(current)
      } else {
        iterate(current, depth + 1)
      }
    }
    iterate(record, 0)", [Name, Name, BaseCondition]).

generate_base_condition_scala(Head, Condition) :-
    Head =.. [_|Args],
    (   Args = [Arg|_],
        (   number(Arg)
        ->  format(string(Condition), "current.get(\"arg0\").contains(~w)", [Arg])
        ;   atom(Arg)
        ->  format(string(Condition), "current.get(\"arg0\").contains(\"~w\")", [Arg])
        ;   Condition = "false"
        )
    ;   Condition = "false"
    ).

%% ============================================
%% CLAUSE TRANSLATION
%% ============================================

translate_clause_scala(Head, Body, Code) :-
    Head =.. [_Pred|Args],
    generate_input_extraction_scala(Args, InputCode),
    (   Body == true
    ->  BodyCode = "    // Fact - no conditions"
    ;   translate_body_scala(Body, BodyCode)
    ),
    format(string(Code), "~w\n~w\n    Some(record)", [InputCode, BodyCode]).

generate_input_extraction_scala(Args, Code) :-
    findall(Line, (
        nth0(I, Args, Arg),
        (   var(Arg)
        ->  format(string(Line), "    val arg~w = record.get(\"arg~w\")", [I, I])
        ;   format(string(Line), "    // arg~w = ~w (constant)", [I, Arg])
        )
    ), Lines),
    atomic_list_concat(Lines, '\n', Code).

%% ============================================
%% BODY TRANSLATION
%% ============================================

translate_body_scala((Goal, Rest), Code) :-
    !,
    translate_goal_scala(Goal, Code1),
    translate_body_scala(Rest, Code2),
    format(string(Code), "~w\n~w", [Code1, Code2]).
translate_body_scala(Goal, Code) :-
    translate_goal_scala(Goal, Code).

translate_goal_scala(>(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "    if (!(~w > ~w)) return None", [SX, SY]).

translate_goal_scala(<(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "    if (!(~w < ~w)) return None", [SX, SY]).

translate_goal_scala(>=(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "    if (!(~w >= ~w)) return None", [SX, SY]).

translate_goal_scala(=<(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "    if (!(~w <= ~w)) return None", [SX, SY]).

translate_goal_scala(=:=(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "    if (~w != ~w) return None", [SX, SY]).

translate_goal_scala(=\\=(X, Y), Code) :-
    !, expr_to_scala(X, SX), expr_to_scala(Y, SY),
    format(string(Code), "    if (~w == ~w) return None", [SX, SY]).

translate_goal_scala(is(Var, Expr), Code) :-
    !,
    var_to_scala(Var, ScalaVar),
    expr_to_scala(Expr, ScalaExpr),
    format(string(Code), "    val ~w = ~w", [ScalaVar, ScalaExpr]).

translate_goal_scala(true, "    // true") :- !.

translate_goal_scala(Goal, Code) :-
    format(string(Code), "    // TODO: ~w", [Goal]).

%% ============================================
%% HELPER PREDICATES
%% ============================================

var_to_scala(Var, ScalaVar) :-
    (   var(Var)
    ->  term_to_atom(Var, VarAtom),
        format(atom(ScalaVar), "var_~w", [VarAtom])
    ;   Var = '$VAR'(N)
    ->  format(atom(ScalaVar), "v~w", [N])
    ;   term_to_atom(Var, ScalaVar)
    ).

expr_to_scala(Expr, ScalaExpr) :-
    (   number(Expr)
    ->  format(atom(ScalaExpr), "~w", [Expr])
    ;   var(Expr)
    ->  var_to_scala(Expr, ScalaExpr)
    ;   Expr = '$VAR'(N)
    ->  format(atom(ScalaExpr), "v~w", [N])
    ;   Expr = X + Y
    ->  expr_to_scala(X, SX), expr_to_scala(Y, SY),
        format(atom(ScalaExpr), "(~w + ~w)", [SX, SY])
    ;   Expr = X - Y
    ->  expr_to_scala(X, SX), expr_to_scala(Y, SY),
        format(atom(ScalaExpr), "(~w - ~w)", [SX, SY])
    ;   Expr = X * Y
    ->  expr_to_scala(X, SX), expr_to_scala(Y, SY),
        format(atom(ScalaExpr), "(~w * ~w)", [SX, SY])
    ;   Expr = X / Y
    ->  expr_to_scala(X, SX), expr_to_scala(Y, SY),
        format(atom(ScalaExpr), "(~w / ~w)", [SX, SY])
    ;   Expr = X mod Y
    ->  expr_to_scala(X, SX), expr_to_scala(Y, SY),
        format(atom(ScalaExpr), "(~w % ~w)", [SX, SY])
    ;   format(atom(ScalaExpr), "~w", [Expr])
    ).

%% ============================================
%% SBT BUILD GENERATION
%% ============================================

generate_sbt_build(Options, BuildFile) :-
    option(scala_version(ScalaVersion), Options, '3.3.1'),
    option(name(Name), Options, 'pipeline'),
    option(version(Version), Options, '0.1.0'),
    
    format(string(BuildFile),
"// Generated by UnifyWeaver Scala Target

name := \"~w\"
version := \"~w\"
scalaVersion := \"~w\"

libraryDependencies ++= Seq(
  \"org.scala-lang.modules\" %% \"scala-parser-combinators\" % \"2.3.0\"
)

// Enable Scala 3 features
scalacOptions ++= Seq(
  \"-deprecation\",
  \"-feature\",
  \"-unchecked\"
)
", [Name, Version, ScalaVersion]).

%% ============================================
%% UTILITY PREDICATES
%% ============================================

write_scala_program(ScalaCode, FilePath) :-
    open(FilePath, write, Stream),
    write(Stream, ScalaCode),
    close(Stream),
    format('Written Scala program to: ~w~n', [FilePath]).

option(Option, Options, _Default) :-
    member(Option, Options), !.
option(Option, _Options, Default) :-
    Option =.. [_, Default].

compile_scala_pipeline(_Steps, _Options, Code) :-
    Code = "// Multi-step Scala pipeline - use compile_predicate_to_scala for now".

%% ============================================
%% TESTS
%% ============================================

test_scala_pipeline_mode :-
    format('~n=== Testing Scala Pipeline Mode ===~n~n'),
    
    format('Test 1: Basic pipeline generation~n'),
    compile_predicate_to_scala(test_pred/2, [pipeline_input(true)], Code1),
    (   sub_atom(Code1, _, _, _, 'runPipeline')
    ->  format('  [PASS] Generated pipeline code~n')
    ;   format('  [FAIL] Missing pipeline code~n')
    ),
    
    format('~nTest 2: Scala pattern matching~n'),
    (   sub_atom(Code1, _, _, _, 'case')
    ->  format('  [PASS] Uses pattern matching~n')
    ;   format('  [INFO] No pattern matching in this mode~n')
    ),
    
    format('~nTest 3: Option type~n'),
    (   sub_atom(Code1, _, _, _, 'Option[')
    ->  format('  [PASS] Uses Option type~n')
    ;   format('  [FAIL] Missing Option type~n')
    ),
    
    format('~nTest 4: Generator mode~n'),
    compile_predicate_to_scala(test_gen/2, [generator_mode(true)], Code2),
    (   sub_atom(Code2, _, _, _, 'LazyList')
    ->  format('  [PASS] Uses LazyList~n')
    ;   format('  [FAIL] Missing LazyList~n')
    ),
    
    format('~nTest 5: SBT build generation~n'),
    generate_sbt_build([scala_version('3.3.1')], BuildCode),
    (   sub_atom(BuildCode, _, _, _, 'scalaVersion')
    ->  format('  [PASS] Generated SBT build~n')
    ;   format('  [FAIL] Invalid SBT build~n')
    ),
    
    format('~n=== Scala Pipeline Mode Tests Complete ===~n').

% ============================================================================
% MULTIFILE DISPATCH - Tail Recursion
% ============================================================================

:- use_module('../core/advanced/tail_recursion').
:- multifile tail_recursion:compile_tail_pattern/9.

tail_recursion:compile_tail_pattern(scala, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_scala(StepOp, ScalaStepExpr),
    (   Arity =:= 3 ->
        format(string(Code),
'// Generated by UnifyWeaver Scala Target - Tail Recursion (multifile dispatch)
// Predicate: ~w/~w

import scala.annotation.tailrec

object Main {
  def ~w(items: List[Int]): Int = {
    @tailrec
    def loop(remaining: List[Int], acc: Int): Int = remaining match {
      case Nil => acc
      case item :: rest => loop(rest, ~w)
    }
    loop(items, 0)
  }

  def main(args: Array[String]): Unit = {
    if (args.length >= 1) {
      val items = args(0).split(",").map(_.toInt).toList
      println(~w(items))
    }
  }
}
', [PredStr, Arity, PredStr, ScalaStepExpr, PredStr])
    ;   Arity =:= 2 ->
        format(string(Code),
'// Generated by UnifyWeaver Scala Target - Tail Recursion (binary, multifile dispatch)
// Predicate: ~w/~w

import scala.annotation.tailrec

object Main {
  def ~w[A](items: List[A]): Int = {
    @tailrec
    def loop(remaining: List[A], count: Int): Int = remaining match {
      case Nil => count
      case _ :: rest => loop(rest, count + 1)
    }
    loop(items, 0)
  }

  def main(args: Array[String]): Unit = {
    if (args.length >= 1) {
      val items = args(0).split(",").toList
      println(~w(items))
    }
  }
}
', [PredStr, Arity, PredStr, PredStr])
    ;   fail
    ).

%% step_op_to_scala(+StepOp, -ScalaExpr)
step_op_to_scala(arithmetic(Expr), ScalaExpr) :- tail_expr_to_scala(Expr, ScalaExpr).
step_op_to_scala(unknown, 'acc + 1').

tail_expr_to_scala(_ + Const, ScalaExpr) :- integer(Const), !, format(atom(ScalaExpr), 'acc + ~w', [Const]).
tail_expr_to_scala(_ + _, 'acc + item') :- !.
tail_expr_to_scala(_ - _, 'acc - item') :- !.
tail_expr_to_scala(_ * _, 'acc * item') :- !.
tail_expr_to_scala(_, 'acc + 1').

% ============================================================================
% MULTIFILE DISPATCH - Linear Recursion
% ============================================================================

:- use_module('../core/advanced/linear_recursion').
:- multifile linear_recursion:compile_linear_pattern/8.

linear_recursion:compile_linear_pattern(scala, PredStr, Arity, BaseClauses, _RecClauses, MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_scala(PredStr, BaseClauses, MemoEnabled, Code)
    ;   linear_generic_scala(PredStr, Arity, MemoEnabled, Code)
    ).

linear_fold_scala(PredStr, BaseClauses, MemoEnabled, Code) :-
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    linear_recursion:detect_input_type(BaseInput, InputType),
    % Extract fold
    atom_string(Pred, PredStr),
    functor(Head, Pred, 2),
    findall(clause(Head, Body), user:clause(Head, Body), AllClauses),
    partition(linear_recursion:is_recursive_clause(Pred), AllClauses, ActualRec, _),
    (   ActualRec = [clause(RHead, RBody)|_] ->
        RHead =.. [_, InputVar, _],
        linear_recursion:find_recursive_call(RBody, RecCall),
        RecCall =.. [_, _, AccVar],
        linear_recursion:find_last_is_expression(RBody, _ is FoldExpr),
        translate_fold_expr_scala(FoldExpr, InputVar, AccVar, ScalaOp)
    ;   ScalaOp = "current * acc"
    ),
    (   InputType = numeric ->
        (   MemoEnabled = true ->
            MemoDecl = "  private val memo = scala.collection.mutable.Map[Int, Int]()",
            MemoCheck = "    memo.getOrElseUpdate(n, {",
            MemoStore = "    })"
        ;   MemoDecl = "  // Memoization disabled",
            MemoCheck = "    {",
            MemoStore = "    }"
        ),
        format(string(Code),
'// Generated by UnifyWeaver Scala Target - Linear Recursion (numeric, multifile dispatch)
// Predicate: ~w/2

object Main {
~w

  def ~w(n: Int): Int =
~w
      if (n == ~w) ~w
      else (n to 1 by -1).foldLeft(~w)((acc, current) => ~w)
~w

  def main(args: Array[String]): Unit = {
    if (args.length >= 1) println(~w(args(0).toInt))
  }
}
', [PredStr, MemoDecl, PredStr, MemoCheck, BaseInput, BaseOutput, BaseOutput, ScalaOp, MemoStore, PredStr])
    ;   InputType = list ->
        (   MemoEnabled = true ->
            MemoDecl = "  private val memo = scala.collection.mutable.Map[List[Int], Int]()",
            MemoCheck = "    memo.getOrElseUpdate(lst, {",
            MemoStore = "    })"
        ;   MemoDecl = "  // Memoization disabled",
            MemoCheck = "    {",
            MemoStore = "    }"
        ),
        format(string(Code),
'// Generated by UnifyWeaver Scala Target - Linear Recursion (list, multifile dispatch)
// Predicate: ~w/2

object Main {
~w

  def ~w(lst: List[Int]): Int =
~w
      if (lst.isEmpty) ~w
      else lst.foldLeft(~w)((acc, current) => ~w)
~w

  def main(args: Array[String]): Unit = {
    if (args.length >= 1) println(~w(args(0).split(",").map(_.toInt).toList))
  }
}
', [PredStr, MemoDecl, PredStr, MemoCheck, BaseOutput, BaseOutput, ScalaOp, MemoStore, PredStr])
    ;   linear_generic_scala(PredStr, 2, MemoEnabled, Code)
    ).

linear_generic_scala(PredStr, Arity, MemoEnabled, Code) :-
    (   MemoEnabled = true ->
        MemoDecl = "  private val memo = scala.collection.mutable.Map[Int, Int]()"
    ;   MemoDecl = "  // Memoization disabled"
    ),
    format(string(Code),
'// Generated by UnifyWeaver Scala Target - Linear Recursion (generic, multifile dispatch)
// Predicate: ~w/~w

object Main {
~w

  def ~w(n: Int): Int = memo.getOrElseUpdate(n, {
    if (n <= 0) 0
    else if (n == 1) 1
    else ~w(n - 1) + n
  })

  def main(args: Array[String]): Unit = {
    if (args.length >= 1) println(~w(args(0).toInt))
  }
}
', [PredStr, Arity, MemoDecl, PredStr, PredStr, PredStr]).

%% translate_fold_expr_scala
translate_fold_expr_scala(A * B, IV, AV, E) :- translate_scala_term(A, IV, AV, AT), translate_scala_term(B, IV, AV, BT), format(string(E), '~w * ~w', [AT, BT]).
translate_fold_expr_scala(A + B, IV, AV, E) :- translate_scala_term(A, IV, AV, AT), translate_scala_term(B, IV, AV, BT), format(string(E), '~w + ~w', [AT, BT]).
translate_fold_expr_scala(A - B, IV, AV, E) :- translate_scala_term(A, IV, AV, AT), translate_scala_term(B, IV, AV, BT), format(string(E), '~w - ~w', [AT, BT]).
translate_fold_expr_scala(T, IV, AV, E) :- translate_scala_term(T, IV, AV, E).

translate_scala_term(T, IV, _, 'current') :- T == IV, !.
translate_scala_term(T, _, AV, 'acc') :- T == AV, !.
translate_scala_term(N, _, _, S) :- integer(N), !, format(string(S), '~w', [N]).
translate_scala_term(T, _, _, 'current') :- var(T), !.
translate_scala_term(A, _, _, S) :- format(string(S), '~w', [A]).

% ============================================================================
% MULTIFILE DISPATCH - Tree Recursion
% ============================================================================

:- use_module('../core/advanced/tree_recursion').
:- multifile tree_recursion:compile_tree_pattern/6.

tree_recursion:compile_tree_pattern(scala, _Pattern, Pred, _Arity, _UseMemo, ScalaCode) :-
    atom_string(Pred, PredStr),
    format(string(ScalaCode),
'// Generated by UnifyWeaver Scala Target - Tree Recursion (multifile dispatch)

object Main {
  private val memo = scala.collection.mutable.Map[Int, Int]()

  def ~w(n: Int): Int = {
    if (memo.contains(n)) return memo(n)
    if (n <= 0) return 0
    if (n == 1) return 1
    val result = ~w(n - 1) + ~w(n - 2)
    memo(n) = result
    result
  }

  def main(args: Array[String]): Unit = {
    if (args.nonEmpty) println(~w(args(0).toInt))
  }
}
', [PredStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MULTICALL LINEAR RECURSION - Scala target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/multicall_linear_recursion').
:- multifile multicall_linear_recursion:compile_multicall_pattern/6.

multicall_linear_recursion:compile_multicall_pattern(scala, PredStr, BaseClauses, _RecClauses, _MemoEnabled, ScalaCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '      case ~w => ~w', [BInput, BOutput])
    ), BaseCaseCodes0),
    sort(BaseCaseCodes0, BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(ScalaCode),
'// Generated by UnifyWeaver Scala Target - Multicall Linear Recursion (multifile dispatch)

object Main {
  private val memo = scala.collection.mutable.Map[Int, Int]()

  def ~w(n: Int): Int = {
    if (memo.contains(n)) return memo(n)
    val result: Int = n match {
~w
      case _ => ~w(n - 1) + ~w(n - 2)
    }
    memo(n) = result
    result
  }

  def main(args: Array[String]): Unit = {
    if (args.nonEmpty) println(~w(args(0).toInt))
  }
}
', [PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% DIRECT MULTI-CALL RECURSION - Scala target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/direct_multi_call_recursion').
:- multifile direct_multi_call_recursion:compile_direct_multicall_pattern/5.

direct_multi_call_recursion:compile_direct_multicall_pattern(scala, PredStr, BaseClauses, _RecClause, ScalaCode) :-
    findall(BaseCaseCode, (
        member(clause(BHead, _), BaseClauses),
        BHead =.. [_P, BInput, BOutput],
        format(string(BaseCaseCode), '      case ~w => ~w', [BInput, BOutput])
    ), BaseCaseCodes0),
    sort(BaseCaseCodes0, BaseCaseCodes),
    atomic_list_concat(BaseCaseCodes, '\n', BaseCaseStr),
    format(string(ScalaCode),
'// Generated by UnifyWeaver Scala Target - Direct Multicall Recursion (multifile dispatch)

object Main {
  private val memo = scala.collection.mutable.Map[Int, Int]()

  def ~w(input: Int): Int = {
    if (memo.contains(input)) return memo(input)
    val result: Int = input match {
~w
      case _ => ~w(input - 1) + ~w(input - 2)
    }
    memo(input) = result
    result
  }

  def main(args: Array[String]): Unit = {
    if (args.nonEmpty) println(~w(args(0).toInt))
  }
}
', [PredStr, BaseCaseStr, PredStr, PredStr, PredStr]).

% ============================================================================
% MUTUAL RECURSION - Scala target delegation (multifile)
% ============================================================================

:- use_module('../core/advanced/mutual_recursion').
:- multifile mutual_recursion:compile_mutual_pattern/5.

mutual_recursion:compile_mutual_pattern(scala, Predicates, MemoEnabled, _MemoStrategy, ScalaCode) :-
    % Generate functions for each predicate
    mutual_functions_scala(Predicates, Predicates, MemoEnabled, FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    % Generate dispatch in main
    mutual_dispatch_scala(Predicates, DispatchCode),
    format(string(ScalaCode),
'// Generated by UnifyWeaver Scala Target - Mutual Recursion (multifile dispatch)

object Main {
~w

~w
}
', [FunctionsCode, DispatchCode]).

mutual_functions_scala([], _AllPreds, _MemoEnabled, []).
mutual_functions_scala([Pred/Arity|Rest], AllPreds, MemoEnabled, [FuncCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    % Base cases
    findall(BaseLine, (
        member(clause(BHead, true), BaseClauses),
        BHead =.. [_P, BValue],
        format(string(BaseLine), '      case ~w => true', [BValue])
    ), BaseLines),
    atomic_list_concat(BaseLines, '\n', BaseCode),
    % Recursive case
    (   RecClauses = [clause(_RHead, RBody)|_] ->
        extract_mutual_rec_info_scala(RBody, Guard, CalledPred, Step),
        atom_string(CalledPred, CalledStr),
        (   Guard = (N > Threshold), var(N) ->
            format(string(RecCode),
'      case _ if n > ~w => ~w(n ~w)', [Threshold, CalledStr, Step])
        ;   format(string(RecCode),
'      case _ => ~w(n ~w)', [CalledStr, Step])
        )
    ;   RecCode = '      case _ => false'
    ),
    format(string(FuncCode),
'  def ~w(n: Int): Boolean = n match {
~w
~w
  }', [PredStr, BaseCode, RecCode]),
    mutual_functions_scala(Rest, AllPreds, MemoEnabled, RestCodes).

extract_mutual_rec_info_scala(Body, Guard, CalledPred, Step) :-
    extract_goals_from_body_scala(Body, Goals),
    (   member(Guard, Goals), Guard = (_ > _) -> true
    ;   Guard = none
    ),
    member(Call, Goals),
    compound(Call),
    Call \= (_ is _), Call \= (_ > _), Call \= (_ < _),
    Call \= (_ >= _), Call \= (_ =< _),
    functor(Call, CalledPred, _),
    (   member(_ is _ - K, Goals), integer(K) ->
        format(string(Step), '- ~w', [K])
    ;   member(_ is _ + K, Goals), integer(K), K < 0 ->
        AbsK is abs(K),
        format(string(Step), '- ~w', [AbsK])
    ;   Step = "- 1"
    ).

extract_goals_from_body_scala((A, B), Goals) :- !,
    extract_goals_from_body_scala(A, GA),
    extract_goals_from_body_scala(B, GB),
    append(GA, GB, Goals).
extract_goals_from_body_scala(true, []) :- !.
extract_goals_from_body_scala(Goal, [Goal]).

mutual_dispatch_scala(Predicates, Code) :-
    findall(CaseLine, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr),
        format(string(CaseLine),
'        case "~w" => println(~w(n))', [PredStr, PredStr])
    ), Lines),
    atomic_list_concat(Lines, '\n', CaseCode),
    format(string(Code),
'  def main(args: Array[String]): Unit = {
    if (args.length >= 2) {
      val func = args(0)
      val n = args(1).toInt
      func match {
~w
      }
    }
  }', [CaseCode]).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_scala_arg_list(+N, -ArgList)
build_scala_arg_list(0, "") :- !.
build_scala_arg_list(N, ArgList) :-
    findall(ArgDecl, (
        between(1, N, I),
        format(string(ArgDecl), 'arg~w: Long', [I])
    ), ArgDecls),
    atomic_list_concat(ArgDecls, ', ', ArgList).

%% native_scala_clause_body(+PredSpec, +Clauses, -Code)

% Single clause
native_scala_clause_body(PredSpec, [Head-Body], Code) :-
    native_scala_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !,
    (   Condition == "true"
    ->  format(string(Code), '    ~w', [ClauseCode])
    ;   format(string(Code),
'    if (~w) ~w
    else throw new RuntimeException("No matching clause for ~w")', [Condition, ClauseCode, PredSpec])
    ).

% Multi-clause → if/else if/else
native_scala_clause_body(PredSpec, Clauses, Code) :-
    Clauses = [_|[_|_]],
    maplist(native_scala_clause_pair(PredSpec), Clauses, Branches),
    Branches \= [],
    branches_to_scala_if_chain(Branches, PredSpec, Code).

native_scala_clause_pair(PredSpec, Head-Body, branch(Condition, ClauseCode)) :-
    native_scala_clause(PredSpec, Head, Body, Condition, ClauseCode),
    !.

%% native_scala_clause(+PredSpec, +Head, +Body, -Condition, -Code)
native_scala_clause(_PredSpec, Head, Body, Condition, Code) :-
    Head =.. [_Pred|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputHeadArgs, [OutputHeadArg], HeadArgs),
        scala_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ;   OutputHeadArg = _,
        scala_head_conditions(HeadArgs, 1, Arity, HeadConditions)
    ),
    normalize_goals(Body, Goals),
    (   Goals == []
    ->  scala_resolve_value(VarMap, OutputHeadArg, Code),
        GoalConditions = []
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
            maplist(scala_guard_condition(VarMap), GuardGoals, GoalConditions),
            (   OutputGoals == []
            ->  scala_literal(OutputHeadArg, Code)
            ;   scala_output_goals(OutputGoals, VarMap, Code)
            )
        ;   native_scala_goal_sequence(Goals, VarMap, GoalConditions, Code)
        )
    ),
    append(HeadConditions, GoalConditions, AllConditions),
    combine_scala_conditions(AllConditions, Condition).

%% scala_head_conditions(+HeadArgs, +Index, +Arity, -Conditions)
scala_head_conditions([], _, _, []).
scala_head_conditions([_], _, Arity, []) :- Arity > 1, !.
scala_head_conditions([HeadArg|Rest], Index, Arity, Conditions) :-
    (   var(HeadArg)
    ->  Conditions = RestConditions
    ;   format(string(ArgName), 'arg~w', [Index]),
        scala_literal(HeadArg, Literal),
        format(string(Cond), '~w == ~w', [ArgName, Literal]),
        Conditions = [Cond|RestConditions]
    ),
    NextIndex is Index + 1,
    scala_head_conditions(Rest, NextIndex, Arity, RestConditions).

%% native_scala_goal_sequence(+Goals, +VarMap, -Conditions, -Code)
%  Uses classify_goal_sequence for advanced pattern detection.
%  Falls back to clause_guard_output_split if classification fails.
native_scala_goal_sequence(Goals, VarMap, Conditions, Code) :-
    classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
    ClassifiedGoals \= [],
    scala_render_classified_goals(ClassifiedGoals, VarMap, Conditions, Lines),
    Lines \= [],
    atomic_list_concat(Lines, '\n', Code),
    !.
native_scala_goal_sequence(Goals, VarMap, Conditions, Code) :-
    clause_guard_output_split(Goals, VarMap, GuardGoals, OutputGoals),
    maplist(scala_guard_condition(VarMap), GuardGoals, Conditions),
    scala_output_goals(OutputGoals, VarMap, Code).

%% scala_render_classified_goals(+ClassifiedGoals, +VarMap, -Conditions, -Lines)
scala_render_classified_goals([], _VarMap, [], []).
scala_render_classified_goals([Classified], VarMap, Conds, Lines) :-
    !,
    scala_render_classified_last(Classified, VarMap, Conds, Lines).
%% Guarded tail: output followed by guard(s)
scala_render_classified_goals([output(Goal, _, _)|Rest], VarMap, [], Lines) :-
    Rest = [guard(_, _)|_],
    !,
    scala_classified_output_goal(Goal, VarMap, LetBinding, VarMap1),
    scala_collect_trailing_guards(Rest, VarMap1, GuardGoals, _Remaining),
    maplist(scala_guard_condition(VarMap1), GuardGoals, GuardConds),
    atomic_list_concat(GuardConds, ' && ', GuardExpr),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMap1, OutName)
    ->  true
    ;   OutName = '_'
    ),
    format(string(IfLine), '    if (~w) ~w else throw new RuntimeException("guard failed")', [GuardExpr, OutName]),
    Lines = [LetBinding, IfLine].
scala_render_classified_goals([Classified|Rest], VarMap, Conds, Lines) :-
    scala_render_classified_mid(Classified, VarMap, MidConds, MidLines, VarMap1),
    scala_render_classified_goals(Rest, VarMap1, RestConds, RestLines),
    append(MidConds, RestConds, Conds),
    append(MidLines, RestLines, Lines).

%% scala_render_classified_mid(+Classified, +VarMap, -Conds, -Lines, -VarMapOut)
scala_render_classified_mid(guard(Goal, _), VarMap, [Cond], [], VarMap) :-
    scala_guard_condition(VarMap, Goal, Cond).
scala_render_classified_mid(output(Goal, _, _), VarMap0, [], [Line], VarMapOut) :-
    scala_classified_output_goal(Goal, VarMap0, Line, VarMapOut).
scala_render_classified_mid(output_ite(If, Then, Else, _SharedVars), VarMap0, [], Lines, VarMap0) :-
    scala_guard_condition(VarMap0, If, Cond),
    scala_branch_value(Then, VarMap0, ThenExpr),
    scala_branch_value(Else, VarMap0, ElseExpr),
    format(string(IfLine), '    if (~w) {', [Cond]),
    format(string(ThenLine), '        ~w', [ThenExpr]),
    ElseLine = '    } else {',
    format(string(ElseRetLine), '        ~w', [ElseExpr]),
    CloseLine = '    }',
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine, CloseLine].
scala_render_classified_mid(passthrough(Goal), VarMap0, [], [Line], VarMapOut) :-
    scala_classified_output_goal(Goal, VarMap0, Line, VarMapOut).
scala_render_classified_mid(_, VarMap, [], [], VarMap).

%% scala_render_classified_last(+Classified, +VarMap, -Conds, -Lines)
scala_render_classified_last(guard(Goal, _), VarMap, [Cond], []) :-
    scala_guard_condition(VarMap, Goal, Cond).
scala_render_classified_last(output(Goal, _, _), VarMap, [], Lines) :-
    scala_render_output_goal_last(Goal, VarMap, Lines).
scala_render_classified_last(output_ite(If, Then, Else, _), VarMap, [], Lines) :-
    scala_guard_condition(VarMap, If, Cond),
    scala_branch_value(Then, VarMap, ThenExpr),
    scala_branch_value(Else, VarMap, ElseExpr),
    format(string(IfLine), '    if (~w) {', [Cond]),
    format(string(ThenLine), '        ~w', [ThenExpr]),
    ElseLine = '    } else {',
    format(string(ElseRetLine), '        ~w', [ElseExpr]),
    CloseLine = '    }',
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine, CloseLine].
scala_render_classified_last(output_disj(Alternatives, _SharedVars), VarMap, [], Lines) :-
    scala_disj_if_chain(Alternatives, VarMap, Lines).
scala_render_classified_last(passthrough(Goal), VarMap, [], Lines) :-
    scala_render_output_goal_last(Goal, VarMap, Lines).

%% scala_classified_output_goal(+Goal, +VarMap0, -Line, -VarMapOut)
scala_classified_output_goal(Goal, VarMap0, Line, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap0, Var, VarName, VarMapOut),
        scala_expr(Expr, VarMap0, ExprStr),
        format(string(Line), '    val ~w = ~w', [VarName, ExprStr])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap0, Var, VarName, VarMapOut),
        scala_expr(ArithExpr, VarMap0, ExprStr),
        format(string(Line), '    val ~w = ~w', [VarName, ExprStr])
    ;   VarMapOut = VarMap0,
        Line = '    // unsupported'
    ).

%% scala_render_output_goal_last(+Goal, +VarMap, -Lines)
%  3-arg wrapper used by classified goal renderers.
scala_render_output_goal_last(Goal, VarMap, [Expr]) :-
    scala_output_goal_last(Goal, VarMap, Expr),
    !.
scala_render_output_goal_last(Goal, VarMap, [Expr]) :-
    scala_branch_value(Goal, VarMap, Expr).

%% scala_collect_trailing_guards(+ClassifiedGoals, +VarMap, -GuardGoals, -Remaining)
scala_collect_trailing_guards([guard(Goal, _)|Rest], VarMap, [Goal|Guards], Remaining) :-
    !, scala_collect_trailing_guards(Rest, VarMap, Guards, Remaining).
scala_collect_trailing_guards(Remaining, _, [], Remaining).

%% scala_disj_if_chain(+Alternatives, +VarMap, -Lines)
scala_disj_if_chain([], _, []).
scala_disj_if_chain([Alt], VarMap, [ElseLine, RetLine]) :-
    !,
    scala_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    } else {',
    format(string(RetLine), '        ~w', [ValExpr]).
scala_disj_if_chain([Alt|Rest], VarMap, [IfLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(scala_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = 'true'
    ),
    scala_branch_value(Alt, VarMap, ValExpr),
    format(string(IfLine), '    if (~w) {', [CondExpr]),
    format(string(RetLine), '        ~w', [ValExpr]),
    scala_disj_elif_chain(Rest, VarMap, RestLines).

%% scala_disj_elif_chain(+Alternatives, +VarMap, -Lines)
scala_disj_elif_chain([], _, []).
scala_disj_elif_chain([Alt], VarMap, [ElseLine, RetLine, CloseLine]) :-
    !,
    scala_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '    } else {',
    format(string(RetLine), '        ~w', [ValExpr]),
    CloseLine = '    }'.
scala_disj_elif_chain([Alt|Rest], VarMap, [ElifLine, RetLine|RestLines]) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  maplist(scala_guard_condition(VarMap), Guards, CondStrs),
        atomic_list_concat(CondStrs, ' && ', CondExpr)
    ;   CondExpr = 'true'
    ),
    scala_branch_value(Alt, VarMap, ValExpr),
    format(string(ElifLine), '    } else if (~w) {', [CondExpr]),
    format(string(RetLine), '        ~w', [ValExpr]),
    scala_disj_elif_chain(Rest, VarMap, RestLines).

%% scala_guard_condition(+VarMap, +Goal, -Condition)
scala_guard_condition(VarMap, _Module:Goal, Condition) :-
    !, scala_guard_condition(VarMap, Goal, Condition).
scala_guard_condition(VarMap, Goal, Condition) :-
    compound(Goal),
    Goal =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    scala_expr(Left, VarMap, SLeft),
    scala_expr(Right, VarMap, SRight),
    scala_op(StdOp, SOp),
    format(string(Condition), '~w ~w ~w', [SLeft, SOp, SRight]).

%% scala_output_goals(+Goals, +VarMap, -Code)
scala_output_goals([], _VarMap, '"error"') :- !.
scala_output_goals([Goal], VarMap, Code) :-
    !, scala_output_goal_last(Goal, VarMap, Code).
scala_output_goals([_Goal|Rest], VarMap, Code) :-
    scala_output_goals(Rest, VarMap, Code).

%% scala_output_goal_last — produce the return expression
scala_output_goal_last(_Module:Goal, VarMap, Code) :-
    !, scala_output_goal_last(Goal, VarMap, Code).
scala_output_goal_last(Goal, VarMap, Code) :-
    if_then_else_goal(Goal, IfGoal, ThenGoal, ElseGoal),
    !,
    scala_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap, Code).
scala_output_goal_last(=(Var, Expr), VarMap, Code) :-
    var(Var), !,
    scala_expr(Expr, VarMap, Code).
scala_output_goal_last(is(Var, Expr), VarMap, Code) :-
    var(Var), !,
    scala_expr(Expr, VarMap, Code).

%% scala_if_then_else_output — generate if/else expressions
scala_if_then_else_output(IfGoal, ThenGoal, ElseGoal, VarMap, Code) :-
    flatten_scala_if_branches(IfGoal, ThenGoal, ElseGoal, Branches, DefaultGoal),
    scala_branches_to_if_expr(Branches, DefaultGoal, VarMap, Code).

flatten_scala_if_branches(If, Then, Else, [branch(If, Then)|RestBranches], Default) :-
    if_then_else_goal(Else, If2, Then2, Else2),
    !,
    flatten_scala_if_branches(If2, Then2, Else2, RestBranches, Default).
flatten_scala_if_branches(If, Then, Else, [branch(If, Then)], Else).

scala_branches_to_if_expr([branch(If, Then)], DefaultGoal, VarMap, Code) :-
    !,
    scala_guard_condition(VarMap, If, IfCond),
    scala_branch_value(Then, VarMap, ThenVal),
    scala_branch_value(DefaultGoal, VarMap, ElseVal),
    format(string(Code), 'if (~w) ~w else ~w', [IfCond, ThenVal, ElseVal]).
scala_branches_to_if_expr([branch(If, Then)|Rest], DefaultGoal, VarMap, Code) :-
    scala_guard_condition(VarMap, If, IfCond),
    scala_branch_value(Then, VarMap, ThenVal),
    scala_branches_to_if_expr(Rest, DefaultGoal, VarMap, ElseCode),
    format(string(Code), 'if (~w) ~w else ~w', [IfCond, ThenVal, ElseCode]).

%% scala_branch_value — extract result value from a branch
scala_branch_value(_Module:Goal, VarMap, Value) :-
    !, scala_branch_value(Goal, VarMap, Value).
scala_branch_value(Goal, VarMap, Value) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    scala_guard_condition(VarMap, If, Cond),
    scala_branch_value(Then, VarMap, ThenVal),
    scala_branch_value(Else, VarMap, ElseVal),
    format(string(Value), 'if (~w) ~w else ~w', [Cond, ThenVal, ElseVal]).
scala_branch_value((A, B), VarMap, Value) :-
    !,
    normalize_goals((A, B), Goals),
    last(Goals, LastGoal),
    scala_branch_value(LastGoal, VarMap, Value).
scala_branch_value(=(_, Expr), VarMap, Value) :-
    !, scala_expr(Expr, VarMap, Value).
scala_branch_value(is(_, Expr), VarMap, Value) :-
    !, scala_expr(Expr, VarMap, Value).
scala_branch_value(Goal, VarMap, Value) :-
    scala_expr(Goal, VarMap, Value).

% ============================================================================
% MULTIFILE HOOKS — Register Scala renderers for shared compile_expression
% ============================================================================

clause_body_analysis:render_output_goal(scala, =(Var, Expr), VarMap0, Line, VarName, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    scala_expr(Expr, VarMap0, ExprStr),
    format(string(Line), '    val ~w = ~w', [VarName, ExprStr]).
clause_body_analysis:render_output_goal(scala, is(Var, Expr), VarMap0, Line, VarName, VarMapOut) :-
    var(Var), !,
    ensure_var(VarMap0, Var, VarName, VarMapOut),
    scala_expr(Expr, VarMap0, ExprStr),
    format(string(Line), '    val ~w = ~w', [VarName, ExprStr]).

clause_body_analysis:render_guard_condition(scala, Goal, VarMap, CondStr) :-
    scala_guard_condition(VarMap, Goal, CondStr).

clause_body_analysis:render_branch_value(scala, Branch, VarMap, ExprStr) :-
    scala_branch_value(Branch, VarMap, ExprStr).

clause_body_analysis:render_ite_block(scala, Cond, ThenLines, ElseLines, Indent, _ReturnVars, Lines) :-
    format(string(IfLine), '~wif (~w) {', [Indent, Cond]),
    scala_indent_lines(ThenLines, Indent, IndentedThen),
    format(string(CloseThen), '~w}', [Indent]),
    (   ElseLines \= []
    ->  format(string(ElseLine), '~w} else {', [Indent]),
        scala_indent_lines(ElseLines, Indent, IndentedElse),
        format(string(CloseElse), '~w}', [Indent]),
        append([IfLine|IndentedThen], [ElseLine|IndentedElse], PreClose),
        append(PreClose, [CloseElse], Lines)
    ;   append([IfLine|IndentedThen], [CloseThen], Lines)
    ).

scala_indent_lines([], _, []).
scala_indent_lines([Line|Rest], Indent, [Indented|RestIndented]) :-
    format(string(Indented), '~w    ~w', [Indent, Line]),
    scala_indent_lines(Rest, Indent, RestIndented).

%% scala_expr — convert Prolog expression to Scala syntax
scala_expr(Var, VarMap, SExpr) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  atom_string(Name, SExpr)
    ;   SExpr = "0"
    ).
scala_expr(Expr, VarMap, SExpr) :-
    compound(Expr),
    Expr =.. [Op, Left, Right],
    expr_op(Op, StdOp),
    !,
    scala_expr(Left, VarMap, SLeft),
    scala_expr(Right, VarMap, SRight),
    scala_op(StdOp, SOp),
    format(string(SExpr), '(~w ~w ~w)', [SLeft, SOp, SRight]).
scala_expr(-Expr, VarMap, SExpr) :-
    !,
    scala_expr(Expr, VarMap, Inner),
    format(string(SExpr), '(-~w)', [Inner]).
scala_expr(abs(Expr), VarMap, SExpr) :-
    !,
    scala_expr(Expr, VarMap, Inner),
    format(string(SExpr), 'Math.abs(~w)', [Inner]).
scala_expr(Atom, _VarMap, SExpr) :-
    atom(Atom), !,
    scala_literal(Atom, SExpr).
scala_expr(Number, _VarMap, SExpr) :-
    number(Number), !,
    format(string(SExpr), '~w', [Number]).

%% scala_literal — convert Prolog value to Scala literal
scala_literal(Value, "\"\"") :- var(Value), !.
scala_literal(Value, SLit) :-
    number(Value), !,
    format(string(SLit), '~w', [Value]).
scala_literal(Value, SLit) :-
    atom(Value), !,
    format(string(SLit), '"~w"', [Value]).
scala_literal(Value, SLit) :-
    format(string(SLit), '"~w"', [Value]).

%% scala_resolve_value — resolve head arg to Scala expression
scala_resolve_value(VarMap, Var, Value) :-
    var(Var), !,
    (   lookup_var(Var, VarMap, Name)
    ->  atom_string(Name, Value)
    ;   Value = "\"\""
    ).
scala_resolve_value(_VarMap, Atom, Value) :-
    atom(Atom), !,
    format(string(Value), '"~w"', [Atom]).
scala_resolve_value(_VarMap, Number, Value) :-
    number(Number), !,
    format(string(Value), '~w.toString', [Number]).
scala_resolve_value(_VarMap, _, "\"\"").

%% scala_op — map comparison/arithmetic operator to Scala
scala_op('>', '>').
scala_op('<', '<').
scala_op('>=', '>=').
scala_op('<=', '<=').
scala_op('==', '==').
scala_op('!=', '!=').
scala_op('+', '+').
scala_op('-', '-').
scala_op('*', '*').
scala_op('/', '/').
scala_op('%', '%').

%% combine_scala_conditions(+Conditions, -Combined)
combine_scala_conditions([], "true") :- !.
combine_scala_conditions([C], C) :- !.
combine_scala_conditions([C|Rest], Combined) :-
    combine_scala_conditions(Rest, RestCombined),
    format(string(Combined), '~w && ~w', [C, RestCombined]).

%% branches_to_scala_if_chain(+Branches, +PredSpec, -Code)
branches_to_scala_if_chain(Branches, PredSpec, Code) :-
    scala_if_chain_lines(Branches, PredSpec, true, Lines),
    atomic_list_concat(Lines, '\n', Code).

scala_if_chain_lines([branch(Cond, ClauseCode)], PredSpec, IsFirst, Lines) :-
    !,
    (   Cond == "true"
    ->  (   IsFirst == true
        ->  format(string(Line), '    ~w', [ClauseCode]),
            Lines = [Line]
        ;   format(string(Line), '    else ~w', [ClauseCode]),
            Lines = [Line]
        )
    ;   (   IsFirst == true
        ->  format(string(L1), '    if (~w) ~w', [Cond, ClauseCode]),
            format(string(L2), '    else throw new RuntimeException("No matching clause for ~w")', [PredSpec]),
            Lines = [L1, L2]
        ;   format(string(L1), '    else if (~w) ~w', [Cond, ClauseCode]),
            format(string(L2), '    else throw new RuntimeException("No matching clause for ~w")', [PredSpec]),
            Lines = [L1, L2]
        )
    ).
scala_if_chain_lines([branch(Cond, ClauseCode)|Rest], PredSpec, IsFirst, [Line|RestLines]) :-
    (   IsFirst == true
    ->  format(string(Line), '    if (~w) ~w', [Cond, ClauseCode])
    ;   format(string(Line), '    else if (~w) ~w', [Cond, ClauseCode])
    ),
    scala_if_chain_lines(Rest, PredSpec, false, RestLines).
