:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% vbnet_target.pl - VB.NET Code Generation Target
% Compiles Prolog predicates to VB.NET programs for stream processing.

:- module(vbnet_target, [
    compile_predicate_to_vbnet/3,          % +PredIndicator, +Options, -VBCode
    compile_facts_to_vbnet/3,              % +Pred, +Arity, -VBCode  
    compile_tail_recursion_vbnet/3,        % +Pred/Arity, +Options, -VBCode
    compile_linear_recursion_vbnet/3,      % +Pred/Arity, +Options, -VBCode
    compile_mutual_recursion_vbnet/3,      % +Predicates, +Options, -VBCode
    write_vbnet_program/2,                 % +Code, +Filename
    init_vbnet_target/0                    % Initialize target
]).

:- use_module(library(lists)).
:- use_module('../bindings/vbnet_bindings', [init_vbnet_bindings/0]).

% Shared clause body analysis for native lowering
:- use_module('../core/clause_body_analysis').
:- use_module('../core/advanced/pattern_matchers', [is_per_path_visited_pattern/4]).

%% init_vbnet_target
init_vbnet_target :-
    init_vbnet_bindings.

%% compile_predicate_to_vbnet(+PredIndicator, +Options, -Code)
compile_predicate_to_vbnet(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'VB.NET target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_vbnet(Pred, Arity, Clauses, Options, Code)
    ).

%% compile_clauses_to_vbnet(+Pred, +Arity, +Clauses, +Options, -Code)
compile_clauses_to_vbnet(Pred, Arity, Clauses, _Options, Code) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredUp),
    atom_string(PredUp, PredUpStr),
    
    (   forall(member(_-Body, Clauses), Body == true)
    ->  compile_facts_vbnet(PredStr, PredUpStr, Arity, Clauses, Code)
    ;   compile_rule_vbnet(PredStr, PredUpStr, Arity, Clauses, Code)
    ).

%% compile_facts_vbnet(+PredStr, +PredUpStr, +Arity, +Clauses, -Code)
compile_facts_vbnet(PredStr, PredUpStr, Arity, Clauses, Code) :-
    generate_vbnet_fields(Arity, FieldDefs),
    generate_vbnet_ctor_params(Arity, CtorParams),
    generate_vbnet_ctor_body(Arity, CtorBody),
    findall(Entry, (
        member(Head-true, Clauses),
        Head =.. [_|Args],
        generate_vbnet_fact_entry(Args, PredUpStr, Entry)
    ), Entries),
    atomic_list_concat(Entries, ',\n            ', EntriesCode),
    generate_vbnet_print(Arity, PrintCode),
    
    format(string(Code),
'Imports System
Imports System.Collections.Generic

'' Generated by UnifyWeaver VB.NET Target - Fact Export
'' Predicate: ~w/~w

Public Class ~w
~w
    
    Public Sub New(~w)
~w
    End Sub
End Class

Module Facts
    Public Function GetAll~w() As List(Of ~w)
        Return New List(Of ~w) From {
            ~w
        }
    End Function
    
    Public Function Stream~w() As IEnumerable(Of ~w)
        Return GetAll~w()
    End Function
    
    Public Function Contains(target As ~w) As Boolean
        Return GetAll~w().Exists(Function(f) f.Equals(target))
    End Function
End Module

Module Program
    Sub Main()
        For Each fact In GetAll~w()
            Console.WriteLine(~w)
        Next
    End Sub
End Module
', [PredStr, Arity, PredUpStr, FieldDefs, CtorParams, CtorBody,
    PredUpStr, PredUpStr, PredUpStr, EntriesCode,
    PredUpStr, PredUpStr, PredUpStr,
    PredUpStr, PredUpStr, PredUpStr, PrintCode]).

%% compile_rule_vbnet(+PredStr, +PredUpStr, +Arity, +Clauses, -Code)

% Try native clause body lowering first
compile_rule_vbnet(PredStr, _PredUpStr, Arity, Clauses, Code) :-
    \+ (member(_-Body, Clauses), Body == true),
    native_vbnet_clause_body(PredStr/Arity, Clauses, FuncBody),
    !,
    Arity1 is Arity - 1,
    build_vbnet_arg_list(Arity1, ArgList),
    format(string(Code),
'Imports System

'' Generated by UnifyWeaver VB.NET Target - Native Clause Lowering
'' Predicate: ~w/~w

Module Program
    Function ~w(~w) As String
~w
    End Function

    Sub Main(args As String())
        If args.Length > 0 Then
            Console.WriteLine(~w(CLng(args(0))))
        End If
    End Sub
End Module
', [PredStr, Arity, PredStr, ArgList, FuncBody, PredStr]).

% Fallback stub
compile_rule_vbnet(PredStr, _PredUpStr, Arity, _Clauses, Code) :-
    format(string(Code),
'Imports System
Imports System.IO

'' Generated by UnifyWeaver VB.NET Target - Rule Compilation
'' Predicate: ~w/~w

Module Program
    Sub Main()
        Dim reader = New StreamReader(Console.OpenStandardInput())
        Dim line As String

        line = reader.ReadLine()
        While line IsNot Nothing
            Dim parts = line.Split(":"c)
            If parts.Length >= ~w Then
                Console.WriteLine(line)
            End If
            line = reader.ReadLine()
        End While
    End Sub
End Module
', [PredStr, Arity, Arity]).

%% ============================================
%% TAIL RECURSION (Do While loop)
%% ============================================

compile_tail_recursion_vbnet(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredUp),
    atom_string(PredUp, PredUpStr),
    
    format(string(Code),
'Imports System

'' Generated by UnifyWeaver VB.NET Target - Tail Recursion
'' Predicate: ~w/~w
'' Optimized to O(1) stack space using Do While loop

Module ~wModule
    '' Tail-recursive function compiled to iterative loop
    Public Function ~w(n As Integer, acc As Integer) As Integer
        Dim current = n
        Dim accumulator = acc
        
        Do While current > 0
            accumulator += current
            current -= 1
        Loop
        
        Return accumulator
    End Function
    
    '' Entry point
    Public Function ~w(n As Integer) As Integer
        Return ~w(n, 0)
    End Function
End Module

Module Program
    Sub Main(args As String())
        If args.Length >= 1 Then
            Dim n = Integer.Parse(args(0))
            Console.WriteLine(~wModule.~w(n))
        End If
    End Sub
End Module
', [PredStr, Arity, PredUpStr, PredStr, PredStr, PredStr, PredUpStr, PredStr]).

%% ============================================
%% LINEAR RECURSION (Dictionary memo)
%% ============================================

compile_linear_recursion_vbnet(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    upcase_atom(Pred, PredUp),
    atom_string(PredUp, PredUpStr),
    
    format(string(Code),
'Imports System
Imports System.Collections.Generic

'' Generated by UnifyWeaver VB.NET Target - Linear Recursion
'' Predicate: ~w/~w
'' Uses Dictionary-based memoization for O(n) performance

Module ~wModule
    Private ReadOnly _memo As New Dictionary(Of Integer, Integer)
    
    Public Function ~w(n As Integer) As Integer
        '' Check memo
        If _memo.ContainsKey(n) Then
            Return _memo(n)
        End If
        
        '' Base cases
        If n <= 0 Then Return 0
        If n = 1 Then Return 1
        
        '' Recursive case with memoization
        Dim result = ~w(n - 1) + n
        _memo(n) = result
        Return result
    End Function
    
    Public Sub ClearMemo()
        _memo.Clear()
    End Sub
End Module

Module Program
    Sub Main(args As String())
        If args.Length >= 1 Then
            Dim n = Integer.Parse(args(0))
            Console.WriteLine(~wModule.~w(n))
        End If
    End Sub
End Module
', [PredStr, Arity, PredUpStr, PredStr, PredStr, PredUpStr, PredStr]).

%% ============================================
%% MUTUAL RECURSION (Shared Dictionary)
%% ============================================

compile_mutual_recursion_vbnet(Predicates, _Options, Code) :-
    findall(PredStr, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr)
    ), PredStrs),
    atomic_list_concat(PredStrs, '_', GroupName),
    upcase_atom(GroupName, GroupUp),
    atom_string(GroupUp, GroupUpStr),
    
    % Generate functions for each predicate
    findall(FuncCode, (
        member(Pred/Arity, Predicates),
        generate_vbnet_mutual_function(Pred, Arity, Predicates, FuncCode)
    ), FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),
    
    format(string(Code),
'Imports System
Imports System.Collections.Generic

'' Generated by UnifyWeaver VB.NET Target - Mutual Recursion
'' Group: ~w

Module ~wModule
    Private ReadOnly _memo As New Dictionary(Of String, Boolean)
    
~w
    
    Public Sub ClearMemo()
        _memo.Clear()
    End Sub
End Module

Module Program
    Sub Main(args As String())
        If args.Length >= 2 Then
            Dim func = args(0)
            Dim n = Integer.Parse(args(1))
            Select Case func
                Case "is_even"
                    Console.WriteLine(~wModule.is_even(n))
                Case "is_odd"
                    Console.WriteLine(~wModule.is_odd(n))
            End Select
        End If
    End Sub
End Module
', [GroupName, GroupUpStr, FunctionsCode, GroupUpStr, GroupUpStr]).

%% generate_vbnet_mutual_function(+Pred, +Arity, +AllPredicates, -Code)
generate_vbnet_mutual_function(Pred, _Arity, AllPredicates, Code) :-
    atom_string(Pred, PredStr),
    
    % Find the other predicate to call
    member(OtherPred/_OtherArity, AllPredicates),
    OtherPred \= Pred,
    atom_string(OtherPred, OtherPredStr),
    
    format(string(Code),
'    Public Function ~w(n As Integer) As Boolean
        Dim key = "~w:" & n.ToString()
        If _memo.ContainsKey(key) Then
            Return _memo(key)
        End If
        
        '' Base case
        If n = 0 Then
            _memo(key) = ("~w" = "is_even")
            Return ("~w" = "is_even")
        End If
        
        '' Recursive case - call other predicate
        If n > 0 Then
            Dim result = ~w(n - 1)
            _memo(key) = result
            Return result
        End If
        
        Return False
    End Function', [PredStr, PredStr, PredStr, PredStr, OtherPredStr]).

%% compile_facts_to_vbnet(+Pred, +Arity, -Code)
compile_facts_to_vbnet(Pred, Arity, Code) :-
    compile_predicate_to_vbnet(Pred/Arity, [], Code).

%% write_vbnet_program(+Code, +Filename)
write_vbnet_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('VB.NET program written to: ~w~n', [Filename]).

%% Helper predicates
generate_vbnet_fields(Arity, Fields) :-
    findall(Field, (
        between(1, Arity, N),
        format(string(Field), '    Public Property Arg~w As String', [N])
    ), FieldList),
    atomic_list_concat(FieldList, '\n', Fields).

generate_vbnet_ctor_params(Arity, Result) :-
    findall(Param, (
        between(1, Arity, N),
        format(string(Param), 'arg~w As String', [N])
    ), Params),
    atomic_list_concat(Params, ', ', Result).

generate_vbnet_ctor_body(Arity, Result) :-
    findall(Assign, (
        between(1, Arity, N),
        format(string(Assign), '        Me.Arg~w = arg~w', [N, N])
    ), Assigns),
    atomic_list_concat(Assigns, '\n', Result).

generate_vbnet_fact_entry(Args, StructName, Entry) :-
    findall(ArgStr, (
        member(Arg, Args),
        format(string(ArgStr), '"~w"', [Arg])
    ), ArgStrs),
    atomic_list_concat(ArgStrs, ', ', ArgsJoined),
    format(string(Entry), 'New ~w(~w)', [StructName, ArgsJoined]).

generate_vbnet_print(Arity, Code) :-
    findall(Field, (
        between(1, Arity, N),
        format(string(Field), 'fact.Arg~w', [N])
    ), Fields),
    atomic_list_concat(Fields, ' & ":" & ', Code).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% build_vbnet_arg_list(+N, -ArgList)
%  Generates "arg1 As Long, arg2 As Long, ..." for N input arguments.
build_vbnet_arg_list(0, "") :- !.
build_vbnet_arg_list(N, ArgList) :-
    findall(Param, (
        between(1, N, I),
        format(string(Param), 'arg~w As Long', [I])
    ), Params),
    atomic_list_concat(Params, ', ', ArgList).

%% native_vbnet_clause_body(+PredIndicator, +Clauses, -FuncBody)
%  Compiles clause list to VB.NET If/ElseIf/Else body.
native_vbnet_clause_body(PredStr/Arity, Clauses, FuncBody) :-
    Arity1 is Arity - 1,
    findall(branch(Cond, Value), (
        member(Head-Body, Clauses),
        Body \== true,
        native_vbnet_clause(Head, Body, Arity1, Cond, Value)
    ), Branches),
    Branches \= [],
    branches_to_vbnet_if_chain(Branches, PredStr, Arity, FuncBody).

%% native_vbnet_clause(+Head, +Body, +InputArity, -Cond, -Value)
native_vbnet_clause(Head, Body, _InputArity, Cond, Value) :-
    Head =.. [_|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputArgs, [OutputHeadArg], HeadArgs)
    ;   OutputHeadArg = _
    ),
    normalize_goals(Body, Goals),
    (   Goals = [SingleGoal],
        if_then_else_goal(SingleGoal, If, Then, Else)
    ->  vbnet_if_then_else_output(If, Then, Else, VarMap, Value),
        Cond = "True"
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  % Output is a constant in the head (e.g. classify(X, small))
            clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
            vbnet_head_conditions(Guards, VarMap, Cond),
            vbnet_literal(OutputHeadArg, Value)
        ;   native_vbnet_goal_sequence(Goals, VarMap, Cond, Value)
        )
    ).

%% vbnet_head_conditions(+Guards, +VarMap, -Cond)
vbnet_head_conditions([], _VarMap, "True") :- !.
vbnet_head_conditions(Guards, VarMap, Cond) :-
    findall(C, (
        member(G, Guards),
        vbnet_guard_condition(G, VarMap, C)
    ), Conds),
    (   Conds = []
    ->  Cond = "True"
    ;   combine_vbnet_conditions(Conds, Cond)
    ).

%% vbnet_guard_condition(+Goal, +VarMap, -Cond)
vbnet_guard_condition(Goal, VarMap, Cond) :-
    Goal =.. [Op, Left, Right],
    vbnet_op(Op, VBOp),
    vbnet_resolve_value(Left, VarMap, LStr),
    vbnet_resolve_value(Right, VarMap, RStr),
    format(string(Cond), '~w ~w ~w', [LStr, VBOp, RStr]).

%% vbnet_op(+PrologOp, -VBOp)
vbnet_op(>, ">").
vbnet_op(<, "<").
vbnet_op(>=, ">=").
vbnet_op(=<, "<=").
vbnet_op(=:=, "=").
vbnet_op(=\=, "<>").
vbnet_op(==, "=").
vbnet_op(\==, "<>").

%% vbnet_output_goals(+Outputs, +VarMap, -Value)
vbnet_output_goals(Outputs, VarMap, Value) :-
    last(Outputs, LastGoal),
    (   goal_output_var(LastGoal, _)
    ->  vbnet_expr(LastGoal, VarMap, Value)
    ;   vbnet_resolve_value(LastGoal, VarMap, Value)
    ).

%% native_vbnet_goal_sequence(+Goals, +VarMap, -Cond, -Value)
%  Uses classify_goal_sequence for advanced pattern detection.
%  Falls back to clause_guard_output_split if classification fails.
native_vbnet_goal_sequence(Goals, VarMap, Cond, Value) :-
    classify_goal_sequence(Goals, VarMap, ClassifiedGoals),
    ClassifiedGoals \= [],
    vbnet_render_classified_goals(ClassifiedGoals, VarMap, Conditions, Lines),
    Lines \= [],
    (   Conditions = []
    ->  Cond = "True"
    ;   combine_vbnet_conditions(Conditions, Cond)
    ),
    atomic_list_concat(Lines, '\n', Value),
    !.
native_vbnet_goal_sequence(Goals, VarMap, Cond, Value) :-
    clause_guard_output_split(Goals, VarMap, Guards, Outputs),
    vbnet_head_conditions(Guards, VarMap, Cond),
    vbnet_output_goals(Outputs, VarMap, Value).

%% vbnet_render_classified_goals(+ClassifiedGoals, +VarMap, -Conditions, -Lines)
vbnet_render_classified_goals([], _VarMap, [], []).
vbnet_render_classified_goals([Classified], VarMap, Conds, Lines) :-
    !,
    vbnet_render_classified_last(Classified, VarMap, Conds, Lines).
%% Guarded tail: output followed by guard(s)
vbnet_render_classified_goals([output(Goal, _, _)|Rest], VarMap, [], Lines) :-
    Rest = [guard(_, _)|_],
    !,
    vbnet_classified_output_goal(Goal, VarMap, AssignLine, VarMap1),
    vbnet_collect_trailing_guards(Rest, VarMap1, GuardGoals, _Remaining),
    maplist(vbnet_guard_condition_flip(VarMap1), GuardGoals, GuardConds),
    combine_vbnet_conditions(GuardConds, GuardExpr),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMap1, OutName)
    ->  true
    ;   OutName = "_"
    ),
    format(string(IfLine), '        If ~w Then', [GuardExpr]),
    format(string(RetLine), '            Return ~w', [OutName]),
    EndLine = '        End If',
    Lines = [AssignLine, IfLine, RetLine, EndLine].
vbnet_render_classified_goals([Classified|Rest], VarMap, Conds, Lines) :-
    vbnet_render_classified_mid(Classified, VarMap, MidConds, MidLines, VarMap1),
    vbnet_render_classified_goals(Rest, VarMap1, RestConds, RestLines),
    append(MidConds, RestConds, Conds),
    append(MidLines, RestLines, Lines).

%% vbnet_guard_condition_flip(+VarMap, +Goal, -Cond)
%%  Wrapper with swapped arg order for maplist compatibility.
vbnet_guard_condition_flip(VarMap, Goal, Cond) :-
    vbnet_guard_condition(Goal, VarMap, Cond).

%% vbnet_render_classified_mid(+Classified, +VarMap, -Conds, -Lines, -VarMapOut)
vbnet_render_classified_mid(guard(Goal, _), VarMap, [Cond], [], VarMap) :-
    vbnet_guard_condition(Goal, VarMap, Cond).
vbnet_render_classified_mid(output(Goal, _, _), VarMap0, [], [Line], VarMapOut) :-
    vbnet_classified_output_goal(Goal, VarMap0, Line, VarMapOut).
vbnet_render_classified_mid(output_ite(If, Then, Else, _SharedVars), VarMap0, [], Lines, VarMap0) :-
    vbnet_guard_condition(If, VarMap0, Cond),
    vbnet_classified_branch_value(Then, VarMap0, ThenExpr),
    vbnet_classified_branch_value(Else, VarMap0, ElseExpr),
    format(string(IfLine), '        If ~w Then', [Cond]),
    format(string(ThenLine), '            Return ~w', [ThenExpr]),
    ElseLine = '        Else',
    format(string(ElseRetLine), '            Return ~w', [ElseExpr]),
    EndLine = '        End If',
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine, EndLine].
vbnet_render_classified_mid(passthrough(Goal), VarMap0, [], [Line], VarMapOut) :-
    vbnet_classified_output_goal(Goal, VarMap0, Line, VarMapOut).
vbnet_render_classified_mid(_, VarMap, [], [], VarMap).

%% vbnet_render_classified_last(+Classified, +VarMap, -Conds, -Lines)
vbnet_render_classified_last(guard(Goal, _), VarMap, [Cond], []) :-
    vbnet_guard_condition(Goal, VarMap, Cond).
vbnet_render_classified_last(output(Goal, _, _), VarMap, [], Lines) :-
    vbnet_classified_output_last(Goal, VarMap, Lines).
vbnet_render_classified_last(output_ite(If, Then, Else, _), VarMap, [], Lines) :-
    vbnet_guard_condition(If, VarMap, Cond),
    vbnet_classified_branch_value(Then, VarMap, ThenExpr),
    vbnet_classified_branch_value(Else, VarMap, ElseExpr),
    format(string(IfLine), '        If ~w Then', [Cond]),
    format(string(ThenLine), '            Return ~w', [ThenExpr]),
    ElseLine = '        Else',
    format(string(ElseRetLine), '            Return ~w', [ElseExpr]),
    EndLine = '        End If',
    Lines = [IfLine, ThenLine, ElseLine, ElseRetLine, EndLine].
vbnet_render_classified_last(output_disj(Alternatives, _SharedVars), VarMap, [], Lines) :-
    vbnet_disj_if_chain(Alternatives, VarMap, Lines).
vbnet_render_classified_last(passthrough(Goal), VarMap, [], Lines) :-
    vbnet_classified_output_last(Goal, VarMap, Lines).
vbnet_render_classified_last(_, _, [], []).

%% vbnet_classified_output_goal(+Goal, +VarMap0, -Line, -VarMapOut)
%%  Inline singular output goal handler for VB.NET (no standalone vbnet_output_goal).
vbnet_classified_output_goal(Goal, VarMap0, Line, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap0, Var, VarName, VarMapOut),
        vbnet_resolve_value(Expr, VarMap0, ExprStr),
        format(string(Line), '        Dim ~w = ~w', [VarName, ExprStr])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap0, Var, VarName, VarMapOut),
        vbnet_arith_expr(ArithExpr, VarMap0, ExprStr),
        format(string(Line), '        Dim ~w = ~w', [VarName, ExprStr])
    ;   VarName = "_", VarMapOut = VarMap0,
        Line = "        ' unsupported output goal"
    ).

%% vbnet_classified_branch_value(+Branch, +VarMap, -ExprStr)
%%  Inline branch value extractor for VB.NET.
vbnet_classified_branch_value(Goal, VarMap, Value) :-
    if_then_else_goal(Goal, If, Then, Else),
    !,
    vbnet_guard_condition(VarMap, If, Cond),
    vbnet_classified_branch_value(Then, VarMap, ThenVal),
    vbnet_classified_branch_value(Else, VarMap, ElseVal),
    format(string(Value), 'If(~w, ~w, ~w)', [Cond, ThenVal, ElseVal]).
vbnet_classified_branch_value(Branch, VarMap, ExprStr) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   goal_output_var(LastGoal, _)
    ->  vbnet_expr(LastGoal, VarMap, ExprStr)
    ;   vbnet_resolve_value(LastGoal, VarMap, ExprStr)
    ).

%% vbnet_classified_output_last(+Goal, +VarMap, -Lines)
%%  Wrap a single output goal as lines for classified rendering (last position).
vbnet_classified_output_last(Goal, VarMap, [Line]) :-
    vbnet_classified_output_goal(Goal, VarMap, AssignLine, VarMapOut),
    (   goal_output_var(Goal, OutVar), lookup_var(OutVar, VarMapOut, OutName)
    ->  format(string(Line), '~w\n        Return ~w', [AssignLine, OutName])
    ;   Line = AssignLine
    ).
vbnet_classified_output_last(Goal, VarMap, [Line]) :-
    vbnet_classified_branch_value(Goal, VarMap, Expr),
    format(string(Line), '        Return ~w', [Expr]).

%% vbnet_collect_trailing_guards(+ClassifiedGoals, +VarMap, -GuardGoals, -Remaining)
vbnet_collect_trailing_guards([guard(Goal, _)|Rest], VarMap, [Goal|Guards], Remaining) :-
    !, vbnet_collect_trailing_guards(Rest, VarMap, Guards, Remaining).
vbnet_collect_trailing_guards(Remaining, _, [], Remaining).

%% vbnet_disj_if_chain(+Alternatives, +VarMap, -Lines)
vbnet_disj_if_chain([], _, []).
vbnet_disj_if_chain([Alt], VarMap, [ElseLine, RetLine, EndLine]) :-
    !,
    vbnet_classified_branch_value(Alt, VarMap, ValExpr),
    ElseLine = '        Else',
    format(string(RetLine), '            Return ~w', [ValExpr]),
    EndLine = '        End If'.
vbnet_disj_if_chain([Alt|Rest], VarMap, Lines) :-
    normalize_goals(Alt, Goals),
    clause_guard_output_split(Goals, VarMap, Guards, _Outputs),
    (   Guards \= []
    ->  findall(C, (member(G, Guards), vbnet_guard_condition(G, VarMap, C)), CondStrs),
        combine_vbnet_conditions(CondStrs, CondExpr)
    ;   CondExpr = "True"
    ),
    vbnet_classified_branch_value(Alt, VarMap, ValExpr),
    (   Rest = []
    ->  format(string(ThisLine), '        If ~w Then\n            Return ~w\n        End If', [CondExpr, ValExpr]),
        Lines = [ThisLine]
    ;   format(string(IfLine), '        If ~w Then', [CondExpr]),
        format(string(RetLine), '            Return ~w', [ValExpr]),
        vbnet_disj_if_chain(Rest, VarMap, ChainLines),
        (   ChainLines = ['        Else'|_]
        ->  Lines = [IfLine, RetLine|ChainLines]
        ;   (   ChainLines = ['        ElseIf'|_]
            ->  Lines = [IfLine, RetLine|ChainLines]
            ;   EndLine = '        End If',
                append([IfLine, RetLine, EndLine], ChainLines, Lines)
            )
        )
    ).

% ============================================================================
% MULTIFILE HOOKS — Register VB.NET renderers for shared compile_expression
% ============================================================================

clause_body_analysis:render_output_goal(vbnet, Goal, VarMap, Line, VarName, VarMapOut) :-
    (   Goal = (Var = Expr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        vbnet_resolve_value(Expr, VarMap, ExprStr),
        format(string(Line), '        Dim ~w = ~w', [VarName, ExprStr])
    ;   Goal = (Var is ArithExpr), var(Var)
    ->  ensure_var(VarMap, Var, VarName, VarMapOut),
        vbnet_arith_expr(ArithExpr, VarMap, ExprStr),
        format(string(Line), '        Dim ~w = ~w', [VarName, ExprStr])
    ;   VarName = "_", VarMapOut = VarMap,
        Line = "        ' unsupported output goal"
    ).

clause_body_analysis:render_guard_condition(vbnet, Goal, VarMap, CondStr) :-
    vbnet_guard_condition(Goal, VarMap, CondStr).

clause_body_analysis:render_branch_value(vbnet, Branch, VarMap, ExprStr) :-
    normalize_goals(Branch, Goals),
    last(Goals, LastGoal),
    (   goal_output_var(LastGoal, _)
    ->  vbnet_expr(LastGoal, VarMap, ExprStr)
    ;   vbnet_resolve_value(LastGoal, VarMap, ExprStr)
    ).

clause_body_analysis:render_ite_block(vbnet, Cond, ThenLines, ElseLines, Indent, _ReturnVars, Lines) :-
    format(string(IfLine), '~wIf ~w Then', [Indent, Cond]),
    vbnet_indent_lines(ThenLines, Indent, IndentedThen),
    (   ElseLines \= []
    ->  format(string(ElseLine), '~wElse', [Indent]),
        vbnet_indent_lines(ElseLines, Indent, IndentedElse),
        format(string(EndLine), '~wEnd If', [Indent]),
        append([IfLine|IndentedThen], [ElseLine|IndentedElse], Pre),
        append(Pre, [EndLine], Lines)
    ;   format(string(EndLine), '~wEnd If', [Indent]),
        append([IfLine|IndentedThen], [EndLine], Lines)
    ).

vbnet_indent_lines([], _, []).
vbnet_indent_lines([Line|Rest], Indent, [Indented|RestIndented]) :-
    format(string(Indented), '~w    ~w', [Indent, Line]),
    vbnet_indent_lines(Rest, Indent, RestIndented).

%% vbnet_expr(+Goal, +VarMap, -Expr)
vbnet_expr(Goal, VarMap, Expr) :-
    Goal = (_Var = RHS),
    !,
    vbnet_resolve_value(RHS, VarMap, Expr).
vbnet_expr(Goal, VarMap, Expr) :-
    Goal = (_Var is ArithExpr),
    !,
    vbnet_arith_expr(ArithExpr, VarMap, Expr).
vbnet_expr(Goal, VarMap, Expr) :-
    vbnet_resolve_value(Goal, VarMap, Expr).

%% vbnet_arith_expr(+Expr, +VarMap, -Code)
vbnet_arith_expr(Expr, VarMap, Code) :-
    var(Expr),
    !,
    lookup_var(Expr, VarMap, Code).
vbnet_arith_expr(Expr, _VarMap, Code) :-
    number(Expr),
    !,
    format(string(Code), '~w', [Expr]).
vbnet_arith_expr(Expr, VarMap, Code) :-
    Expr =.. [Op, Left, Right],
    expr_op(Op, _),
    !,
    vbnet_arith_expr(Left, VarMap, LCode),
    vbnet_arith_expr(Right, VarMap, RCode),
    (   Op = (//)
    ->  format(string(Code), '(~w \\ ~w)', [LCode, RCode])
    ;   Op = (/)
    ->  format(string(Code), '(~w \\ ~w)', [LCode, RCode])
    ;   format(string(Code), '(~w ~w ~w)', [LCode, Op, RCode])
    ).
vbnet_arith_expr(-Expr, VarMap, Code) :-
    !,
    vbnet_arith_expr(Expr, VarMap, Inner),
    format(string(Code), '(-~w)', [Inner]).
vbnet_arith_expr(abs(Expr), VarMap, Code) :-
    !,
    vbnet_arith_expr(Expr, VarMap, Inner),
    format(string(Code), 'Math.Abs(~w)', [Inner]).
vbnet_arith_expr(Expr, VarMap, Code) :-
    vbnet_resolve_value(Expr, VarMap, Code).

%% vbnet_resolve_value(+Term, +VarMap, -Str)
vbnet_resolve_value(Var, VarMap, Name) :-
    var(Var),
    !,
    lookup_var(Var, VarMap, Name).
vbnet_resolve_value(Term, _VarMap, Str) :-
    number(Term),
    !,
    format(string(Str), '~w', [Term]).
vbnet_resolve_value(Term, VarMap, Name) :-
    lookup_var(Term, VarMap, Name),
    !.
vbnet_resolve_value(Term, _VarMap, Str) :-
    atom(Term),
    !,
    vbnet_literal(Term, Str).
vbnet_resolve_value(Term, VarMap, Str) :-
    compound(Term),
    vbnet_arith_expr(Term, VarMap, Str).

%% vbnet_literal(+Atom, -Str)
vbnet_literal(Atom, Str) :-
    format(string(Str), '"~w"', [Atom]).

%% combine_vbnet_conditions(+Conds, -Combined)
combine_vbnet_conditions([C], C) :- !.
combine_vbnet_conditions(Conds, Combined) :-
    atomic_list_concat(Conds, ' AndAlso ', Combined).

%% branches_to_vbnet_if_chain(+Branches, +PredStr, +Arity, -Code)
branches_to_vbnet_if_chain(Branches, PredStr, Arity, Code) :-
    (   Branches = [branch("True", Value)]
    ->  % Single clause with if-then-else (already handled inline)
        format(string(Code), '~w', [Value])
    ;   vbnet_if_chain_lines(Branches, first, Lines),
        format(string(Fallback),
               '        Throw New Exception("No matching clause for ~w/~w")',
               [PredStr, Arity]),
        atomic_list_concat([Lines, Fallback], '\n', Code)
    ).

%% vbnet_if_chain_lines(+Branches, +Position, -Lines)
vbnet_if_chain_lines([], _, "") :- !.
vbnet_if_chain_lines([branch(Cond, Value)], Position, Lines) :-
    !,
    (   Cond = "True"
    ->  format(string(Lines), '        Else\n            Return ~w\n        End If', [Value])
    ;   (   Position = first
        ->  format(string(Lines),
                   '        If ~w Then\n            Return ~w\n        End If',
                   [Cond, Value])
        ;   format(string(Lines),
                   '        ElseIf ~w Then\n            Return ~w\n        End If',
                   [Cond, Value])
        )
    ).
vbnet_if_chain_lines([branch(Cond, Value)|Rest], Position, Lines) :-
    (   Position = first
    ->  format(string(ThisLine), '        If ~w Then\n            Return ~w',
               [Cond, Value])
    ;   format(string(ThisLine), '        ElseIf ~w Then\n            Return ~w',
               [Cond, Value])
    ),
    vbnet_if_chain_lines(Rest, not_first, RestLines),
    atomic_list_concat([ThisLine, RestLines], '\n', Lines).

%% vbnet_if_then_else_output(+If, +Then, +Else, +VarMap, -Value)
%  Compiles if-then-else to VB.NET If/ElseIf/Else block.
vbnet_if_then_else_output(If, Then, Else, VarMap, Value) :-
    vbnet_guard_condition(If, VarMap, CondStr),
    vbnet_ite_value(Then, VarMap, ThenVal),
    vbnet_ite_else(Else, VarMap, ElseCode),
    format(string(Value),
           '        If ~w Then\n            Return ~w\n~w',
           [CondStr, ThenVal, ElseCode]).

%% vbnet_ite_value(+Goal, +VarMap, -Value)
vbnet_ite_value(Goal, VarMap, Value) :-
    (   Goal = (_Var = RHS)
    ->  vbnet_resolve_value(RHS, VarMap, Value)
    ;   Goal = (_Var is ArithExpr)
    ->  vbnet_arith_expr(ArithExpr, VarMap, Value)
    ;   vbnet_resolve_value(Goal, VarMap, Value)
    ).

%% vbnet_ite_else(+Else, +VarMap, -Code)
vbnet_ite_else(Else, VarMap, Code) :-
    (   if_then_else_goal(Else, If2, Then2, Else2)
    ->  vbnet_guard_condition(If2, VarMap, CondStr2),
        vbnet_ite_value(Then2, VarMap, ThenVal2),
        vbnet_ite_else(Else2, VarMap, ElseCode2),
        format(string(Code),
               '        ElseIf ~w Then\n            Return ~w\n~w',
               [CondStr2, ThenVal2, ElseCode2])
    ;   vbnet_ite_value(Else, VarMap, ElseVal),
        format(string(Code),
               '        Else\n            Return ~w\n        End If',
               [ElseVal])
    ).

%% ============================================================
%% Multifile recursion pattern hooks for VB.NET
%% ============================================================

:- multifile tail_recursion:compile_tail_pattern/9.
:- multifile linear_recursion:compile_linear_pattern/8.
:- multifile tree_recursion:compile_tree_pattern/6.
:- multifile mutual_recursion:compile_mutual_pattern/5.
:- multifile advanced_recursive_compiler:compile_general_recursive_pattern/6.

%% --- Pattern 1: Tail recursion ---

tail_recursion:compile_tail_pattern(vbnet, PredStr, Arity, _BaseClauses, _RecClauses, _AccPos, StepOp, _ExitAfterResult, Code) :-
    step_op_to_vbnet(StepOp, VBStep),
    (   Arity =:= 3 ->
        % Arity 3: fold over list items
        format(string(Code),
'Imports System

Module PrologGenerated
    Function ~w(items() As Long) As Long
        Dim acc As Long = 0
        For Each item As Long In items
            ~w
        Next
        Return acc
    End Function

    Sub Main(args() As String)
        If args.Length >= 1 Then
            Dim parts() As String = args(0).Split(","c)
            Dim items(parts.Length - 1) As Long
            For i As Integer = 0 To parts.Length - 1
                items(i) = CLng(parts(i))
            Next
            Console.WriteLine(~w(items))
        End If
    End Sub
End Module
', [PredStr, VBStep, PredStr])
    ;   Arity =:= 2 ->
        % Arity 2: numeric accumulator
        format(string(Code),
'Imports System

Module PrologGenerated
    Function ~w(n As Long) As Long
        Dim acc As Long = 1
        While n > 0
            ~w
            n -= 1
        End While
        Return acc
    End Function

    Sub Main(args() As String)
        If args.Length >= 1 Then
            Console.WriteLine(~w(CLng(args(0))))
        End If
    End Sub
End Module
', [PredStr, VBStep, PredStr])
    ;   format(string(Code), ''' Unsupported arity ~d for tail recursion~n', [Arity])
    ).

step_op_to_vbnet(add_element, 'acc += item').
step_op_to_vbnet(add_1, 'acc += 1').
step_op_to_vbnet(mult_element, 'acc *= item').
step_op_to_vbnet(sub_element, 'acc -= item').
step_op_to_vbnet(mult, 'acc = acc * n').
step_op_to_vbnet(add, 'acc = acc + n').
step_op_to_vbnet(Op, VBCode) :-
    atom(Op),
    format(string(VBCode), 'acc = acc ~w n', [Op]).

%% --- Pattern 2: Linear recursion ---

linear_recursion:compile_linear_pattern(vbnet, PredStr, Arity, BaseClauses, _RecClauses, _MemoEnabled, _MemoStrategy, Code) :-
    (   Arity =:= 2 ->
        linear_fold_vbnet(PredStr, BaseClauses, Code)
    ;   format(string(Code), ''' Unsupported arity ~d for linear recursion~n', [Arity])
    ).

linear_fold_vbnet(PredStr, BaseClauses, Code) :-
    %% Extract base case info
    linear_recursion:extract_base_case_info(BaseClauses, BaseInput, BaseOutput),
    (   integer(BaseInput) -> format(string(BaseCheck), 'n = ~w', [BaseInput])
    ;   BaseCheck = "n <= 0"
    ),
    (   integer(BaseOutput) -> format(string(BaseValStr), '~w', [BaseOutput])
    ;   BaseValStr = "0"
    ),
    format(string(Code),
'Imports System

Module PrologGenerated
    Function ~w(n As Long) As Long
        If ~w Then
            Return ~w
        End If
        Return n + ~w(n - 1)
    End Function

    Sub Main(args() As String)
        If args.Length >= 1 Then
            Console.WriteLine(~w(CLng(args(0))))
        End If
    End Sub
End Module
', [PredStr, BaseCheck, BaseValStr, PredStr, PredStr]).

%% --- Pattern 3: Tree recursion ---

tree_recursion:compile_tree_pattern(vbnet, PredStr, _Arity, _BaseClauses, _RecClauses, Code) :-
    format(string(Code),
'Imports System
Imports System.Collections.Generic

Module PrologGenerated
    Private memo As New Dictionary(Of Long, Long)

    Function ~w(n As Long) As Long
        If n <= 1 Then
            Return n
        End If
        If memo.ContainsKey(n) Then
            Return memo(n)
        End If
        Dim result As Long = ~w(n - 1) + ~w(n - 2)
        memo(n) = result
        Return result
    End Function

    Sub Main(args() As String)
        If args.Length >= 1 Then
            Console.WriteLine(~w(CLng(args(0))))
        End If
    End Sub
End Module
', [PredStr, PredStr, PredStr, PredStr]).

%% --- Pattern 4: Mutual recursion ---

mutual_recursion:compile_mutual_pattern(vbnet, Predicates, _MemoEnabled, _MemoStrategy, Code) :-
    vbnet_mutual_methods(Predicates, Predicates, MethodCodes),
    atomic_list_concat(MethodCodes, '\n\n', MethodSection),
    Predicates = [FirstPred/_|_],
    atom_string(FirstPred, FirstStr),
    format(string(Code),
'Imports System

Module PrologGenerated
~w

    Sub Main(args() As String)
        If args.Length >= 1 Then
            Console.WriteLine(~w(CLng(args(0))))
        End If
    End Sub
End Module
', [MethodSection, FirstStr]).

vbnet_mutual_methods([], _, []).
vbnet_mutual_methods([Pred/Arity|Rest], AllPreds, [MethodCode|RestCodes]) :-
    atom_string(Pred, PredStr),
    functor(Head, Pred, Arity),
    findall(clause(Head, Body), user:clause(Head, Body), Clauses),
    partition(mutual_recursion:is_mutual_recursive_clause(AllPreds), Clauses, RecClauses, BaseClauses),
    %% Extract base value
    (   BaseClauses = [clause(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs],
        last(BaseArgs, BaseResult),
        integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    %% Extract base input
    (   BaseClauses = [clause(BaseHead2, _)|_],
        BaseHead2 =.. [_|BaseArgs2],
        BaseArgs2 = [BaseInput|_],
        integer(BaseInput)
    ->  BaseIn = BaseInput
    ;   BaseIn = 0
    ),
    %% Find the other predicate being called (mutual step)
    (   RecClauses = [clause(_, RecBody)|_],
        mutual_recursion:extract_mutual_call(RecBody, AllPreds, Pred, CalledPred, _)
    ->  atom_string(CalledPred, CalledStr)
    ;   CalledStr = PredStr
    ),
    %% Build VB.NET method
    (   Arity =:= 1 ->
        %% Boolean: is_even/is_odd pattern
        (   BaseVal =:= 1 -> BoolStr = "True" ; BoolStr = "False" ),
        format(string(MethodCode),
'    Function ~w(n As Long) As Boolean
        If n = ~w Then
            Return ~w
        End If
        Return ~w(n - 1)
    End Function',
            [PredStr, BaseIn, BoolStr, CalledStr])
    ;   %% Value-returning: arity 2+
        format(string(MethodCode),
'    Function ~w(n As Long) As Long
        If n = ~w Then
            Return ~w
        End If
        Return ~w(n - 1) + 1
    End Function',
            [PredStr, BaseIn, BaseVal, CalledStr])
    ),
    vbnet_mutual_methods(Rest, AllPreds, RestCodes).

%% --- Pattern 5: General recursion ---

%% No-visited-pattern — plain recursive VB.NET without HashSet
advanced_recursive_compiler:compile_general_recursive_pattern(vbnet, PredStr, Arity, BaseClauses, RecClauses, Code) :-
    atom_string(Pred, PredStr),
    append(BaseClauses, RecClauses, AllClauses),
    \+ is_per_path_visited_pattern(Pred, Arity, AllClauses, _),
    !,
    (   BaseClauses = [(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs], last(BaseArgs, BaseResult), integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    format(string(Code),
"' General recursive: ~w (plain, no visited pattern)\n\c
\n\c
Function ~w(arg1 As String) As Long\n\c
    ' Base case + recursive call (no visited set)\n\c
    Return ~w\n\c
End Function\n",
    [PredStr, PredStr, BaseVal]).

advanced_recursive_compiler:compile_general_recursive_pattern(vbnet, PredStr, _Arity, BaseClauses, _RecClauses, Code) :-
    %% Extract base value
    (   BaseClauses = [(BaseHead, _)|_],
        BaseHead =.. [_|BaseArgs],
        last(BaseArgs, BaseResult),
        integer(BaseResult)
    ->  BaseVal = BaseResult
    ;   BaseVal = 0
    ),
    %% Extract base input
    (   BaseClauses = [(BaseHead2, _)|_],
        BaseHead2 =.. [_|BaseArgs2],
        BaseArgs2 = [BaseInput|_],
        integer(BaseInput)
    ->  BaseIn = BaseInput
    ;   BaseIn = 0
    ),
    format(string(Code),
'Imports System
Imports System.Collections.Generic

Module PrologGenerated
    Function ~w(start As String) As Long
        Dim visited As New HashSet(Of String)
        Return ~w_worker(start, visited)
    End Function

    Function ~w_worker(current As String, visited As HashSet(Of String)) As Long
        If visited.Contains(current) Then
            Return ~w
        End If
        visited.Add(current)
        '' Base case
        If current = "~w" Then
            Return ~w
        End If
        '' Recursive case — would be expanded from clause body
        Return ~w
    End Function

    Sub Main(args() As String)
        If args.Length >= 1 Then
            Console.WriteLine(~w(args(0)))
        End If
    End Sub
End Module
', [PredStr, PredStr, PredStr, BaseVal, BaseIn, BaseVal, BaseVal, PredStr]).
