:- encoding(utf8).
% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (@s243a)
%
% wat_target.pl - WebAssembly Text Format Code Generation Target
% Compiles Prolog predicates directly to WAT (WebAssembly Text Format).
% Uses structured control flow (if/else/end) rather than flat basic blocks.
% Falls back to LLVM IR compilation for unsupported patterns.

:- module(wat_target, [
    compile_predicate_to_wat/3,          % +PredIndicator, +Options, -WATCode
    compile_facts_to_wat/3,              % +Pred, +Arity, -WATCode
    compile_tail_recursion_wat/3,        % +Pred/Arity, +Options, -WATCode
    compile_linear_recursion_wat/3,      % +Pred/Arity, +Options, -WATCode
    compile_tree_recursion_wat/3,        % +Pred/Arity, +Options, -WATCode
    compile_mutual_recursion_wat/3,      % +Predicates, +Options, -WATCode
    compile_transitive_closure_wat/3,    % +Pred/Arity, +Options, -WATCode
    write_wat_program/2,                 % +Code, +Filename
    init_wat_target/0                    % Initialize target
]).

:- use_module(library(lists)).
:- use_module('../bindings/wat_bindings', [init_wat_bindings/0]).

% Shared clause body analysis for native lowering
:- use_module('../core/clause_body_analysis').

% LLVM target for WASM fallback (loaded lazily to avoid circular deps)
:- use_module('../targets/llvm_target', [compile_wasm_module/3]).

%% init_wat_target
init_wat_target :-
    init_wat_bindings.

%% compile_predicate_to_wat(+PredIndicator, +Options, -Code)
compile_predicate_to_wat(Pred/Arity, Options, Code) :-
    functor(Head, Pred, Arity),
    findall(Head-Body, user:clause(Head, Body), Clauses),
    (   Clauses = []
    ->  format(user_error, 'WAT target: no clauses for ~w/~w~n', [Pred, Arity]),
        fail
    ;   compile_clauses_to_wat(Pred, Arity, Clauses, Options, Code)
    ).

%% compile_clauses_to_wat(+Pred, +Arity, +Clauses, +Options, -Code)
compile_clauses_to_wat(Pred, Arity, Clauses, _Options, Code) :-
    atom_string(Pred, PredStr),
    (   forall(member(_-Body, Clauses), Body == true)
    ->  compile_facts_wat(PredStr, Arity, Clauses, Code)
    ;   compile_rule_wat(PredStr, Arity, Clauses, Code)
    ).

%% compile_facts_wat(+PredStr, +Arity, +Clauses, -Code)
compile_facts_wat(PredStr, Arity, Clauses, Code) :-
    length(Clauses, Count),
    findall(DataEntry, (
        nth1(Idx, Clauses, Head-true),
        Head =.. [_|Args],
        generate_wat_data_entry(Args, Idx, DataEntry)
    ), DataEntries),
    atomic_list_concat(DataEntries, '\n', DataCode),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Fact Export
  ;; Predicate: ~w/~w

  (memory (export "memory") 1)

~w

  (func $get_~w_count (export "get_~w_count") (result i64)
    (i64.const ~w)
  )
)
', [PredStr, Arity, DataCode, PredStr, PredStr, Count]).

%% compile_rule_wat(+PredStr, +Arity, +Clauses, -Code)

% Try native clause body lowering first
compile_rule_wat(PredStr, Arity, Clauses, Code) :-
    \+ (member(_-Body, Clauses), Body == true),
    native_wat_clause_body(PredStr/Arity, Clauses, FuncBody),
    !,
    Arity1 is Arity - 1,
    build_wat_params(Arity1, Params),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Native Clause Lowering
  ;; Predicate: ~w/~w

  (func $~w (export "~w") ~w(result i64)
~w
  )
)
', [PredStr, Arity, PredStr, PredStr, Params, FuncBody]).

% Fallback: try LLVM WASM compilation path
compile_rule_wat(PredStr, Arity, _Clauses, Code) :-
    catch(
        (   atom_string(PredAtom, PredStr),
            llvm_target:compile_wasm_module(
                [func(PredAtom, Arity, linear_recursion)],
                [module_name(PredStr)],
                LLVMCode
            )
        ),
        _Error,
        fail
    ),
    !,
    format(string(Code),
';; Generated by UnifyWeaver WAT Target - LLVM WASM Fallback
;; Predicate: ~w/~w
;; Native WAT lowering unavailable; LLVM IR for wasm32 below.
;; Compile with: llc -march=wasm32 -filetype=obj <file>.ll && wasm-ld --no-entry --export-all -o <file>.wasm <file>.o

~w
', [PredStr, Arity, LLVMCode]).

% Final fallback stub when LLVM is also unavailable
compile_rule_wat(PredStr, Arity, _Clauses, Code) :-
    Arity1 is Arity - 1,
    build_wat_params(Arity1, Params),
    (   Arity1 > 0
    ->  BodyCode = "(local.get $arg1)"
    ;   BodyCode = "(i64.const 0)"
    ),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Stub
  ;; Predicate: ~w/~w
  ;; Native lowering and LLVM fallback unavailable

  (func $~w (export "~w") ~w(result i64)
    ~w
  )
)
', [PredStr, Arity, PredStr, PredStr, Params, BodyCode]).

%% ============================================
%% TAIL RECURSION (loop + br)
%% ============================================

compile_tail_recursion_wat(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Tail Recursion
  ;; Predicate: ~w/~w
  ;; Optimized to O(1) stack space using loop/br

  (func $~w (export "~w") (param $n i64) (param $acc i64) (result i64)
    (loop $continue
      (if (result i64) (i64.gt_s (local.get $n) (i64.const 0))
        (then
          (local.set $acc (i64.add (local.get $acc) (local.get $n)))
          (local.set $n (i64.sub (local.get $n) (i64.const 1)))
          (br $continue)
        )
        (else
          (local.get $acc)
        )
      )
    )
  )

  (func $~w_entry (export "~w_entry") (param $n i64) (result i64)
    (call $~w (local.get $n) (i64.const 0))
  )
)
', [PredStr, Arity, PredStr, PredStr, PredStr, PredStr, PredStr]).

%% ============================================
%% LINEAR RECURSION (table-based memoization)
%% ============================================

compile_linear_recursion_wat(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Linear Recursion
  ;; Predicate: ~w/~w
  ;; Uses linear memory for memoization

  (memory (export "memory") 1)

  ;; Memo table: offset 0 = values (i64 each), offset 8192 = valid flags (i32 each)

  (func $~w (export "~w") (param $n i64) (result i64)
    (local $offset i32)
    (local $flag_offset i32)
    (local $result i64)

    ;; Base cases
    (if (result i64) (i64.le_s (local.get $n) (i64.const 0))
      (then (i64.const 0))
      (else
        (if (result i64) (i64.eq (local.get $n) (i64.const 1))
          (then (i64.const 1))
          (else
            ;; Check memo
            (local.set $offset (i32.mul (i32.wrap_i64 (local.get $n)) (i32.const 8)))
            (local.set $flag_offset (i32.add (i32.const 8192) (i32.mul (i32.wrap_i64 (local.get $n)) (i32.const 4))))
            (if (result i64) (i32.load (local.get $flag_offset))
              (then (i64.load (local.get $offset)))
              (else
                ;; Compute and memoize
                (local.set $result
                  (i64.add
                    (call $~w (i64.sub (local.get $n) (i64.const 1)))
                    (local.get $n)
                  )
                )
                (i64.store (local.get $offset) (local.get $result))
                (i32.store (local.get $flag_offset) (i32.const 1))
                (local.get $result)
              )
            )
          )
        )
      )
    )
  )
)
', [PredStr, Arity, PredStr, PredStr, PredStr]).

%% ============================================
%% MUTUAL RECURSION
%% ============================================

compile_mutual_recursion_wat(Predicates, _Options, Code) :-
    findall(PredStr, (
        member(Pred/_Arity, Predicates),
        atom_string(Pred, PredStr)
    ), PredStrs),
    atomic_list_concat(PredStrs, '_', GroupName),

    findall(FuncCode, (
        member(Pred/Arity, Predicates),
        generate_wat_mutual_function(Pred, Arity, Predicates, FuncCode)
    ), FuncCodes),
    atomic_list_concat(FuncCodes, '\n\n', FunctionsCode),

    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Mutual Recursion
  ;; Group: ~w

~w
)
', [GroupName, FunctionsCode]).

%% generate_wat_mutual_function(+Pred, +Arity, +AllPredicates, -Code)
generate_wat_mutual_function(Pred, _Arity, AllPredicates, Code) :-
    atom_string(Pred, PredStr),
    member(OtherPred/_OtherArity, AllPredicates),
    OtherPred \= Pred,
    atom_string(OtherPred, OtherPredStr),

    % is_even(0) = 1, is_odd(0) = 0
    (   PredStr = "is_even"
    ->  BaseVal = 1
    ;   BaseVal = 0
    ),

    format(string(Code),
'  (func $~w (export "~w") (param $n i64) (result i64)
    (if (result i64) (i64.eq (local.get $n) (i64.const 0))
      (then (i64.const ~w))
      (else
        (if (result i64) (i64.gt_s (local.get $n) (i64.const 0))
          (then (call $~w (i64.sub (local.get $n) (i64.const 1))))
          (else (i64.const 0))
        )
      )
    )
  )', [PredStr, PredStr, BaseVal, OtherPredStr]).

%% ============================================
%% TREE RECURSION (two recursive calls + memoization)
%% ============================================

compile_tree_recursion_wat(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Tree Recursion
  ;; Predicate: ~w/~w
  ;; Memoized tree recursion using linear memory

  (memory (export "memory") 1)

  ;; Memo layout: offset 0 = values (i64, 8 bytes each)
  ;; Offset 8192 = valid flags (i32, 4 bytes each)

  (func $~w (export "~w") (param $n i64) (result i64)
    (local $offset i32)
    (local $flag_offset i32)
    (local $result i64)

    ;; Base cases
    (if (result i64) (i64.le_s (local.get $n) (i64.const 0))
      (then (i64.const 0))
      (else
        (if (result i64) (i64.eq (local.get $n) (i64.const 1))
          (then (i64.const 1))
          (else
            ;; Check memo table
            (local.set $offset (i32.mul (i32.wrap_i64 (local.get $n)) (i32.const 8)))
            (local.set $flag_offset
              (i32.add (i32.const 8192)
                (i32.mul (i32.wrap_i64 (local.get $n)) (i32.const 4))))
            (if (result i64) (i32.load (local.get $flag_offset))
              (then (i64.load (local.get $offset)))
              (else
                ;; Two recursive calls (tree pattern)
                (local.set $result
                  (i64.add
                    (call $~w (i64.sub (local.get $n) (i64.const 1)))
                    (call $~w (i64.sub (local.get $n) (i64.const 2)))
                  )
                )
                ;; Store in memo
                (i64.store (local.get $offset) (local.get $result))
                (i32.store (local.get $flag_offset) (i32.const 1))
                (local.get $result)
              )
            )
          )
        )
      )
    )
  )
)
', [PredStr, Arity, PredStr, PredStr, PredStr, PredStr]).

%% ============================================
%% TRANSITIVE CLOSURE (BFS with linear memory)
%% ============================================

compile_transitive_closure_wat(Pred/Arity, _Options, Code) :-
    atom_string(Pred, PredStr),
    format(string(Code),
'(module
  ;; Generated by UnifyWeaver WAT Target - Transitive Closure
  ;; Predicate: ~w/~w
  ;; BFS reachability using linear memory
  ;; Memory layout:
  ;;   0-4095: adjacency list (pairs of i64 node IDs)
  ;;   4096-8191: visited bitmap
  ;;   8192-12287: BFS queue

  (memory (export "memory") 1)

  ;; Edge count and node count
  (global $edge_count (mut i32) (i32.const 0))
  (global $node_count (mut i32) (i32.const 0))

  ;; Add an edge: add_edge(from, to)
  (func $add_edge (export "add_edge") (param $from i64) (param $to i64) (result i64)
    (local $offset i32)
    (local.set $offset (i32.mul (global.get $edge_count) (i32.const 16)))
    (i64.store (local.get $offset) (local.get $from))
    (i64.store (i32.add (local.get $offset) (i32.const 8)) (local.get $to))
    (global.set $edge_count (i32.add (global.get $edge_count) (i32.const 1)))
    (i64.const 1)
  )

  ;; Check if visited
  (func $is_visited (param $node i64) (result i32)
    (i32.load
      (i32.add (i32.const 4096)
        (i32.mul (i32.wrap_i64 (local.get $node)) (i32.const 4))))
  )

  ;; Mark as visited
  (func $mark_visited (param $node i64)
    (i32.store
      (i32.add (i32.const 4096)
        (i32.mul (i32.wrap_i64 (local.get $node)) (i32.const 4)))
      (i32.const 1))
  )

  ;; BFS reachability: ~w(source, target) → 1 if reachable, 0 otherwise
  (func $~w (export "~w") (param $source i64) (param $target i64) (result i64)
    (local $queue_head i32)
    (local $queue_tail i32)
    (local $current i64)
    (local $i i32)
    (local $edge_from i64)
    (local $edge_to i64)

    ;; Initialize: clear visited, enqueue source
    (local.set $queue_head (i32.const 0))
    (local.set $queue_tail (i32.const 0))

    ;; Enqueue source
    (i64.store
      (i32.add (i32.const 8192)
        (i32.mul (local.get $queue_tail) (i32.const 8)))
      (local.get $source))
    (local.set $queue_tail (i32.add (local.get $queue_tail) (i32.const 1)))
    (call $mark_visited (local.get $source))

    ;; BFS loop
    (block $done
      (loop $bfs
        ;; If queue empty, not reachable
        (br_if $done (i32.ge_u (local.get $queue_head) (local.get $queue_tail)))

        ;; Dequeue
        (local.set $current
          (i64.load
            (i32.add (i32.const 8192)
              (i32.mul (local.get $queue_head) (i32.const 8)))))
        (local.set $queue_head (i32.add (local.get $queue_head) (i32.const 1)))

        ;; Check if target found
        (if (i64.eq (local.get $current) (local.get $target))
          (then (return (i64.const 1)))
        )

        ;; Scan edges for neighbors
        (local.set $i (i32.const 0))
        (block $edge_done
          (loop $edge_scan
            (br_if $edge_done (i32.ge_u (local.get $i) (global.get $edge_count)))
            (local.set $edge_from
              (i64.load (i32.mul (local.get $i) (i32.const 16))))
            (local.set $edge_to
              (i64.load (i32.add (i32.mul (local.get $i) (i32.const 16)) (i32.const 8))))

            ;; If edge starts at current node and target not visited
            (if (i32.and
                  (i64.eq (local.get $edge_from) (local.get $current))
                  (i32.eqz (call $is_visited (local.get $edge_to))))
              (then
                (call $mark_visited (local.get $edge_to))
                (i64.store
                  (i32.add (i32.const 8192)
                    (i32.mul (local.get $queue_tail) (i32.const 8)))
                  (local.get $edge_to))
                (local.set $queue_tail (i32.add (local.get $queue_tail) (i32.const 1)))
              )
            )

            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $edge_scan)
          )
        )
        (br $bfs)
      )
    )
    (i64.const 0)
  )
)
', [PredStr, Arity, PredStr, PredStr, PredStr]).

%% compile_facts_to_wat(+Pred, +Arity, -Code)
compile_facts_to_wat(Pred, Arity, Code) :-
    compile_predicate_to_wat(Pred/Arity, [], Code).

%% write_wat_program(+Code, +Filename)
write_wat_program(Code, Filename) :-
    open(Filename, write, Stream),
    write(Stream, Code),
    close(Stream),
    format('WAT program written to: ~w~n', [Filename]).

%% ============================================
%% Helper predicates
%% ============================================

generate_wat_data_entry(Args, Idx, Entry) :-
    findall(ArgStr, (
        member(Arg, Args),
        format(string(ArgStr), '~w', [Arg])
    ), ArgStrs),
    atomic_list_concat(ArgStrs, ':', Joined),
    Offset is (Idx - 1) * 256,
    format(string(Entry),
           '  (data (i32.const ~w) "~w")', [Offset, Joined]).

%% build_wat_params(+N, -Params)
%  Generates "(param $arg1 i64) (param $arg2 i64) " for N input arguments.
build_wat_params(0, "") :- !.
build_wat_params(N, Params) :-
    findall(Param, (
        between(1, N, I),
        format(string(Param), '(param $arg~w i64) ', [I])
    ), ParamList),
    atomic_list_concat(ParamList, '', Params).

%% ============================================
%% NATIVE CLAUSE BODY LOWERING
%% ============================================

%% native_wat_clause_body(+PredIndicator, +Clauses, -FuncBody)
native_wat_clause_body(PredStr/Arity, Clauses, FuncBody) :-
    findall(branch(Cond, Value), (
        member(Head-Body, Clauses),
        Body \== true,
        native_wat_clause(Head, Body, Cond, Value)
    ), Branches),
    Branches \= [],
    branches_to_wat_if_chain(Branches, PredStr, Arity, FuncBody).

%% native_wat_clause(+Head, +Body, -Cond, -Value)
native_wat_clause(Head, Body, Cond, Value) :-
    Head =.. [_|HeadArgs],
    length(HeadArgs, Arity),
    build_head_varmap(HeadArgs, 1, VarMap),
    (   Arity > 1
    ->  append(_InputArgs, [OutputHeadArg], HeadArgs)
    ;   OutputHeadArg = _
    ),
    normalize_goals(Body, Goals),
    (   Goals = [SingleGoal],
        if_then_else_goal(SingleGoal, If, Then, Else)
    ->  wat_if_then_else_output(If, Then, Else, VarMap, Value),
        Cond = none
    ;   (   Arity > 1, nonvar(OutputHeadArg)
        ->  once(clause_guard_output_split(Goals, VarMap, Guards, _Outputs)),
            wat_head_conditions(Guards, VarMap, Cond),
            wat_literal(OutputHeadArg, Value)
        ;   once(clause_guard_output_split(Goals, VarMap, Guards, Outputs)),
            wat_head_conditions(Guards, VarMap, Cond),
            wat_output_goals(Outputs, VarMap, Value)
        )
    ).

%% wat_head_conditions(+Guards, +VarMap, -Cond)
wat_head_conditions([], _VarMap, none) :- !.
wat_head_conditions(Guards, VarMap, Cond) :-
    findall(C, (
        member(G, Guards),
        wat_guard_condition(G, VarMap, C)
    ), Conds),
    (   Conds = []
    ->  Cond = none
    ;   combine_wat_conditions(Conds, Cond)
    ).

%% wat_guard_condition(+Goal, +VarMap, -Cond)
wat_guard_condition(Goal, VarMap, Cond) :-
    Goal =.. [Op, Left, Right],
    wat_cmp_op(Op, WATOp),
    wat_resolve_value(Left, VarMap, LStr),
    wat_resolve_value(Right, VarMap, RStr),
    format(string(Cond), '(~w ~w ~w)', [WATOp, LStr, RStr]).

%% wat_cmp_op(+PrologOp, -WATOp)
wat_cmp_op(>, "i64.gt_s").
wat_cmp_op(<, "i64.lt_s").
wat_cmp_op(>=, "i64.ge_s").
wat_cmp_op(=<, "i64.le_s").
wat_cmp_op(=:=, "i64.eq").
wat_cmp_op(=\=, "i64.ne").
wat_cmp_op(==, "i64.eq").
wat_cmp_op(\==, "i64.ne").

%% wat_output_goals(+Outputs, +VarMap, -Value)
wat_output_goals(Outputs, VarMap, Value) :-
    last(Outputs, LastGoal),
    (   goal_output_var(LastGoal, _)
    ->  wat_expr(LastGoal, VarMap, Value)
    ;   wat_resolve_value(LastGoal, VarMap, Value)
    ).

%% wat_expr(+Goal, +VarMap, -Expr)
wat_expr(Goal, VarMap, Expr) :-
    Goal = (_Var = RHS),
    !,
    wat_resolve_value(RHS, VarMap, Expr).
wat_expr(Goal, VarMap, Expr) :-
    Goal = (_Var is ArithExpr),
    !,
    wat_arith_expr(ArithExpr, VarMap, Expr).
wat_expr(Goal, VarMap, Expr) :-
    wat_resolve_value(Goal, VarMap, Expr).

%% wat_arith_expr(+Expr, +VarMap, -Code)
wat_arith_expr(Expr, VarMap, Code) :-
    var(Expr),
    !,
    lookup_var(Expr, VarMap, Name),
    format(string(Code), '(local.get $~w)', [Name]).
wat_arith_expr(Expr, _VarMap, Code) :-
    number(Expr),
    !,
    format(string(Code), '(i64.const ~w)', [Expr]).
wat_arith_expr(Expr, VarMap, Code) :-
    Expr =.. [Op, Left, Right],
    expr_op(Op, _),
    !,
    wat_arith_expr(Left, VarMap, LCode),
    wat_arith_expr(Right, VarMap, RCode),
    wat_arith_op(Op, WATOp),
    format(string(Code), '(~w ~w ~w)', [WATOp, LCode, RCode]).
wat_arith_expr(-Expr, VarMap, Code) :-
    !,
    wat_arith_expr(Expr, VarMap, Inner),
    format(string(Code), '(i64.sub (i64.const 0) ~w)', [Inner]).
wat_arith_expr(abs(Expr), VarMap, Code) :-
    !,
    wat_arith_expr(Expr, VarMap, Inner),
    % abs(x) = if x >= 0 then x else -x
    format(string(Code),
           '(if (result i64) (i64.ge_s ~w (i64.const 0)) (then ~w) (else (i64.sub (i64.const 0) ~w)))',
           [Inner, Inner, Inner]).
wat_arith_expr(Expr, VarMap, Code) :-
    wat_resolve_value(Expr, VarMap, Code).

%% wat_arith_op(+PrologOp, -WATOp)
wat_arith_op(+, "i64.add").
wat_arith_op(-, "i64.sub").
wat_arith_op(*, "i64.mul").
wat_arith_op(/, "i64.div_s").
wat_arith_op(//, "i64.div_s").
wat_arith_op(mod, "i64.rem_s").

%% wat_resolve_value(+Term, +VarMap, -Str)
wat_resolve_value(Var, VarMap, Str) :-
    var(Var),
    !,
    lookup_var(Var, VarMap, Name),
    format(string(Str), '(local.get $~w)', [Name]).
wat_resolve_value(Term, _VarMap, Str) :-
    number(Term),
    !,
    format(string(Str), '(i64.const ~w)', [Term]).
wat_resolve_value(Term, VarMap, Str) :-
    lookup_var(Term, VarMap, Name),
    !,
    format(string(Str), '(local.get $~w)', [Name]).
wat_resolve_value(Term, _VarMap, Str) :-
    atom(Term),
    !,
    wat_literal(Term, Str).
wat_resolve_value(Term, VarMap, Str) :-
    compound(Term),
    wat_arith_expr(Term, VarMap, Str).

%% wat_literal(+Atom, -Str)
%  Atoms are encoded as their hash for i64 representation.
wat_literal(Atom, Str) :-
    atom_codes(Atom, Codes),
    wat_hash_codes(Codes, 0, Hash),
    format(string(Str), '(i64.const ~w)', [Hash]).

%% wat_hash_codes(+Codes, +Acc, -Hash)
%  Simple deterministic hash for encoding atoms as i64 values.
wat_hash_codes([], Acc, Acc).
wat_hash_codes([C|Cs], Acc, Hash) :-
    Acc1 is (Acc * 31 + C) mod 2147483647,
    wat_hash_codes(Cs, Acc1, Hash).

%% combine_wat_conditions(+Conds, -Combined)
combine_wat_conditions([C], C) :- !.
combine_wat_conditions([C|Cs], Combined) :-
    combine_wat_conditions(Cs, Rest),
    format(string(Combined), '(i32.and ~w ~w)', [C, Rest]).

%% branches_to_wat_if_chain(+Branches, +PredStr, +Arity, -Code)
branches_to_wat_if_chain(Branches, _PredStr, _Arity, Code) :-
    (   Branches = [branch(none, Value)]
    ->  % Single clause with if-then-else (already handled inline)
        format(string(Code), '~w', [Value])
    ;   wat_if_chain_nested(Branches, Code)
    ).

%% wat_if_chain_nested(+Branches, -Code)
%  Generates nested (if (result i64) ...) chains.
wat_if_chain_nested([], "    (unreachable)") :- !.
wat_if_chain_nested([branch(none, Value)], Code) :-
    !,
    format(string(Code), '    ~w', [Value]).
wat_if_chain_nested([branch(Cond, Value)], Code) :-
    !,
    format(string(Code),
'    (if (result i64) ~w
      (then ~w)
      (else (unreachable))
    )', [Cond, Value]).
wat_if_chain_nested([branch(Cond, Value)|Rest], Code) :-
    wat_if_chain_nested(Rest, ElseCode),
    format(string(Code),
'    (if (result i64) ~w
      (then ~w)
      (else
~w
      )
    )', [Cond, Value, ElseCode]).

%% wat_if_then_else_output(+If, +Then, +Else, +VarMap, -Value)
%  Compiles if-then-else to WAT structured if/else.
wat_if_then_else_output(If, Then, Else, VarMap, Value) :-
    wat_guard_condition(If, VarMap, CondStr),
    wat_ite_value(Then, VarMap, ThenVal),
    wat_ite_else(Else, VarMap, ElseCode),
    format(string(Value),
'    (if (result i64) ~w
      (then ~w)
      (else
~w
      )
    )', [CondStr, ThenVal, ElseCode]).

%% wat_ite_value(+Goal, +VarMap, -Value)
wat_ite_value(Goal, VarMap, Value) :-
    (   Goal = (_Var = RHS)
    ->  wat_resolve_value(RHS, VarMap, Value)
    ;   Goal = (_Var is ArithExpr)
    ->  wat_arith_expr(ArithExpr, VarMap, Value)
    ;   wat_resolve_value(Goal, VarMap, Value)
    ).

%% wat_ite_else(+Else, +VarMap, -Code)
wat_ite_else(Else, VarMap, Code) :-
    (   if_then_else_goal(Else, If2, Then2, Else2)
    ->  wat_guard_condition(If2, VarMap, CondStr2),
        wat_ite_value(Then2, VarMap, ThenVal2),
        wat_ite_else(Else2, VarMap, ElseCode2),
        format(string(Code),
'        (if (result i64) ~w
          (then ~w)
          (else
~w
          )
        )', [CondStr2, ThenVal2, ElseCode2])
    ;   wat_ite_value(Else, VarMap, ElseVal),
        format(string(Code), '        ~w', [ElseVal])
    ).
