% SPDX-License-Identifier: MIT OR Apache-2.0
% Copyright (c) 2025 John William Creighton (s243a)
%
% This file is part of UnifyWeaver.
% Licensed under either MIT or Apache-2.0 at your option.

:- encoding(utf8).
% custom_chart.pl - Custom Chart.js Component Type for TypeScript
%
% Allows defining Chart.js visualizations from Prolog.
% The component generates TypeScript code that creates Chart.js charts.
%
% Example:
%   declare_component(source, my_chart, custom_chart, [
%       chart_type(line),
%       title("My Curve"),
%       x_axis(label("X"), min(-10), max(10)),
%       y_axis(label("Y"), min(-5), max(5)),
%       datasets([
%           dataset(label("sin(x)"), color("#00d4ff")),
%           dataset(label("cos(x)"), color("#7c3aed"))
%       ])
%   ]).

:- module(custom_chart, [
    type_info/1,
    validate_config/1,
    init_component/2,
    invoke_component/4,
    compile_component/4
]).

:- use_module('../../core/component_registry').

%% type_info(-Info)
type_info(info(
    name('Custom Chart.js Component'),
    version('1.0.0'),
    description('Generates Chart.js visualizations from Prolog configuration')
)).

%% validate_config(+Config)
validate_config(Config) :-
    (   member(chart_type(Type), Config),
        member(Type, [line, bar, scatter, bubble, pie, doughnut, radar, polarArea])
    ->  true
    ;   throw(error(missing_or_invalid_chart_type))
    ).

%% init_component(+Name, +Config)
init_component(_Name, _Config).

%% invoke_component(+Name, +Config, +Input, -Output)
invoke_component(_Name, _Config, _Input, _Output) :-
    throw(error(runtime_invocation_not_supported(custom_chart))).

%% compile_component(+Name, +Config, +Options, -Code)
compile_component(Name, Config, _Options, Code) :-
    member(chart_type(ChartType), Config),

    % Get title
    (   member(title(Title), Config)
    ->  true
    ;   Title = ""
    ),

    % Get axis configurations
    (   member(x_axis(XAxisConfig), Config)
    ->  compile_axis_config(XAxisConfig, XAxisCode)
    ;   XAxisCode = "{}"
    ),
    (   member(y_axis(YAxisConfig), Config)
    ->  compile_axis_config(YAxisConfig, YAxisCode)
    ;   YAxisCode = "{}"
    ),

    % Get datasets configuration
    (   member(datasets(Datasets), Config)
    ->  compile_datasets(Datasets, DatasetsCode)
    ;   DatasetsCode = "[]"
    ),

    % Get responsive setting
    (   member(responsive(Responsive), Config)
    ->  (Responsive == true -> ResponsiveStr = "true" ; ResponsiveStr = "false")
    ;   ResponsiveStr = "true"
    ),

    atom_string(Name, NameStr),
    atom_string(ChartType, ChartTypeStr),
    format(string(Code),
"// Custom Chart Component: ~w
// Generated by UnifyWeaver custom_chart component

import { Chart, ChartConfiguration } from 'chart.js';

/**
 * Chart component: ~w
 * Type: ~w
 */
export function create~wChart(
  ctx: CanvasRenderingContext2D | HTMLCanvasElement,
  data: { labels: (string | number)[]; datasets: any[] }
): Chart {
  const config: ChartConfiguration = {
    type: '~w',
    data: data,
    options: {
      responsive: ~w,
      plugins: {
        title: {
          display: ~w,
          text: '~w'
        }
      },
      scales: {
        x: ~w,
        y: ~w
      }
    }
  };

  return new Chart(ctx, config);
}

/**
 * Default dataset configuration for ~w
 */
export const ~wDatasetDefaults = ~w;

/**
 * Update chart with new data points
 */
export function update~wChart(
  chart: Chart,
  points: [number, number][]
): void {
  chart.data.labels = points.map(p => p[0]);
  if (chart.data.datasets.length > 0) {
    chart.data.datasets[0].data = points.map(p => p[1]);
  }
  chart.update();
}
", [NameStr, NameStr, ChartTypeStr, NameStr, ChartTypeStr, ResponsiveStr,
    (Title \= "" -> "true" ; "false"), Title, XAxisCode, YAxisCode,
    NameStr, NameStr, DatasetsCode, NameStr]).

%% compile_axis_config(+Config, -Code)
compile_axis_config(Config, Code) :-
    (   member(label(Label), Config)
    ->  format(string(TitleCode), "title: { display: true, text: '~w' }", [Label])
    ;   TitleCode = ""
    ),
    (   member(min(Min), Config)
    ->  format(string(MinCode), "min: ~w", [Min])
    ;   MinCode = ""
    ),
    (   member(max(Max), Config)
    ->  format(string(MaxCode), "max: ~w", [Max])
    ;   MaxCode = ""
    ),
    (   member(type(Type), Config)
    ->  format(string(TypeCode), "type: '~w'", [Type])
    ;   TypeCode = "type: 'linear'"
    ),

    findall(Part, (
        member(Part, [TypeCode, TitleCode, MinCode, MaxCode]),
        Part \= ""
    ), Parts),
    atomic_list_concat(Parts, ', ', PartsStr),
    format(string(Code), "{ ~w }", [PartsStr]).

%% compile_datasets(+Datasets, -Code)
compile_datasets(Datasets, Code) :-
    findall(DatasetCode, (
        member(dataset(DatasetConfig), Datasets),
        compile_single_dataset(DatasetConfig, DatasetCode)
    ), DatasetCodes),
    atomic_list_concat(DatasetCodes, ',\n    ', DatasetsStr),
    format(string(Code), "[\n    ~w\n  ]", [DatasetsStr]).

compile_datasets([], "[]").

%% compile_single_dataset(+Config, -Code)
compile_single_dataset(Config, Code) :-
    (   member(label(Label), Config)
    ->  format(string(LabelCode), "label: '~w'", [Label])
    ;   LabelCode = "label: 'Data'"
    ),
    (   member(color(Color), Config)
    ->  format(string(ColorCode), "borderColor: '~w', backgroundColor: '~w'", [Color, Color])
    ;   ColorCode = "borderColor: '#00d4ff', backgroundColor: '#00d4ff'"
    ),
    (   member(fill(Fill), Config)
    ->  (Fill == true -> FillCode = "fill: true" ; FillCode = "fill: false")
    ;   FillCode = "fill: false"
    ),
    (   member(tension(Tension), Config)
    ->  format(string(TensionCode), "tension: ~w", [Tension])
    ;   TensionCode = ""
    ),
    (   member(point_radius(Radius), Config)
    ->  format(string(RadiusCode), "pointRadius: ~w", [Radius])
    ;   RadiusCode = "pointRadius: 0"
    ),

    findall(Part, (
        member(Part, [LabelCode, ColorCode, FillCode, TensionCode, RadiusCode]),
        Part \= ""
    ), Parts),
    atomic_list_concat(Parts, ', ', PartsStr),
    format(string(Code), "{ ~w }", [PartsStr]).

% ============================================================================
% REGISTRATION
% ============================================================================

:- initialization((
    register_component_type(source, custom_chart, custom_chart, [
        description("Custom Chart.js Visualization")
    ])
), now).
